voogasalad_VOOGirlsGeneration: authoring_environment.ShapeGrid Class Reference
authoring_environment.ShapeGrid Class Reference abstract
Public Member Functions
abstract SandyTile findTile (MouseEvent event)
void removePieces (Piece unit)
void removePatches (Patch terrain)
String getID ()
Protected Member Functions
ShapeGrid (int cols, int rows, int tileSize, PieceInstanceData pieceData, PatchInstanceData patchData, String myID)
abstract Point2D getCenter (int row, int col, double height)
abstract Shape makeShape (Point2D center, int row, int col, double height)
void setCheckeredColor (int row, int col, Shape shape)
void addUnit (SandyTile tile, Piece unit)
void addTerrain (SandyTile tile, Patch terrain)
void removeUnit (SandyTile tile, Piece unit)
void removeTerrain (SandyTile tile, Patch terrain)
void editUnit (SandyTile tile, Piece unit)
void editTerrain (SandyTile tile, Patch terrain)
Protected Attributes
int myRows
int myCols
int myTileSize
String myID
List< List< SandyTile > > myGrid
Private Member Functions
void initGridTiles ()
Private Attributes
PieceInstanceData myPieceData
PatchInstanceData myPatchData
Detailed Description
Definition at line 17 of file ShapeGrid.java.
Constructor & Destructor Documentation
authoring_environment.ShapeGrid.ShapeGrid (int cols, int rows, int tileSize, PieceInstanceData pieceData, PatchInstanceData patchData, String myID) protected
Definition at line 28 of file ShapeGrid.java.
References authoring_environment.ShapeGrid.initGridTiles().
Member Function Documentation
void authoring_environment.ShapeGrid.addTerrain (SandyTile tile, Patch terrain) protected
Definition at line 83 of file ShapeGrid.java.
References authoring.data.PatchInstanceData.add(), gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.SandyTile.getLocation(), authoring_environment.SandyTile.myPatchImage, authoring.data.PatchInstanceData.removePatchAtLoc(), and gamedata.gamecomponents.GridComponent.setLoc().
void authoring_environment.ShapeGrid.addUnit (SandyTile tile, Piece unit) protected
Definition at line 75 of file ShapeGrid.java.
References authoring.data.PieceInstanceData.add(), gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.SandyTile.getLocation(), authoring_environment.SandyTile.myPieceImage, and gamedata.gamecomponents.GridComponent.setLoc().
void authoring_environment.ShapeGrid.editTerrain (SandyTile tile, Patch terrain) protected
Definition at line 105 of file ShapeGrid.java.
void authoring_environment.ShapeGrid.editUnit (SandyTile tile, Piece unit) protected
Definition at line 101 of file ShapeGrid.java.
abstract SandyTile authoring_environment.ShapeGrid.findTile (MouseEvent event) abstract
abstract Point2D authoring_environment.ShapeGrid.getCenter (int row, int col, double height) abstract protected
Referenced by authoring_environment.ShapeGrid.initGridTiles().
String authoring_environment.ShapeGrid.getID ()
Definition at line 131 of file ShapeGrid.java.
References authoring_environment.ShapeGrid.myID.
void authoring_environment.ShapeGrid.initGridTiles () private
Definition at line 41 of file ShapeGrid.java.
References authoring_environment.ShapeGrid.getCenter(), authoring_environment.ShapeGrid.makeShape(), authoring_environment.ShapeGrid.myCols, and authoring_environment.ShapeGrid.myRows.
Referenced by authoring_environment.ShapeGrid.ShapeGrid().
abstract Shape authoring_environment.ShapeGrid.makeShape (Point2D center, int row, int col, double height) abstract protected
Referenced by authoring_environment.ShapeGrid.initGridTiles().
void authoring_environment.ShapeGrid.removePatches (Patch terrain)
Definition at line 120 of file ShapeGrid.java.
References authoring_environment.ShapeGrid.myCols, authoring_environment.SandyTile.myPatchImage, authoring_environment.ShapeGrid.myRows, and authoring.data.PatchInstanceData.terrainAtLoc().
void authoring_environment.ShapeGrid.removePieces (Piece unit)
Definition at line 109 of file ShapeGrid.java.
References authoring_environment.ShapeGrid.myCols, authoring_environment.SandyTile.myPieceImage, authoring_environment.ShapeGrid.myRows, and authoring.data.PieceInstanceData.unitAtLoc().
void authoring_environment.ShapeGrid.removeTerrain (SandyTile tile, Patch terrain) protected
Definition at line 96 of file ShapeGrid.java.
References authoring_environment.SandyTile.myPatchImage, and authoring.data.PatchInstanceData.remove().
void authoring_environment.ShapeGrid.removeUnit (SandyTile tile, Piece unit) protected
Definition at line 91 of file ShapeGrid.java.
References authoring_environment.SandyTile.myPieceImage, and authoring.data.PieceInstanceData.remove().
void authoring_environment.ShapeGrid.setCheckeredColor (int row, int col, Shape shape) protected
Definition at line 62 of file ShapeGrid.java.
Referenced by authoring_environment.SandyGrid.makeShape(), and authoring_environment.JennieGrid.makeShape().
Member Data Documentation
int authoring_environment.ShapeGrid.myCols protected
Definition at line 19 of file ShapeGrid.java.
Referenced by authoring_environment.SandyGrid.findTile(), authoring_environment.JennieGrid.findTile(), authoring_environment.ShapeGrid.initGridTiles(), authoring_environment.ShapeGrid.removePatches(), and authoring_environment.ShapeGrid.removePieces().
List<List<SandyTile> > authoring_environment.ShapeGrid.myGrid protected
Definition at line 26 of file ShapeGrid.java.
Referenced by authoring_environment.JennieGrid.findTile().
String authoring_environment.ShapeGrid.myID protected
Definition at line 24 of file ShapeGrid.java.
Referenced by authoring_environment.ShapeGrid.getID().
PatchInstanceData authoring_environment.ShapeGrid.myPatchData private
Definition at line 23 of file ShapeGrid.java.
PieceInstanceData authoring_environment.ShapeGrid.myPieceData private
Definition at line 22 of file ShapeGrid.java.
int authoring_environment.ShapeGrid.myRows protected
Definition at line 18 of file ShapeGrid.java.
Referenced by authoring_environment.JennieGrid.findTile(), authoring_environment.ShapeGrid.initGridTiles(), authoring_environment.ShapeGrid.removePatches(), and authoring_environment.ShapeGrid.removePieces().
int authoring_environment.ShapeGrid.myTileSize protected
Definition at line 20 of file ShapeGrid.java.
Referenced by authoring_environment.JennieGrid.findTile().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/ShapeGrid.java