voogasalad_VOOGirlsGeneration: authoring_environment.SuperGrid Class Reference
authoring_environment.SuperGrid Class Reference
Public Member Functions
SuperGrid ()
SuperGrid (int cols, int rows, double tileHeight, String shape)
int getNumRows ()
int getNumCols ()
double getTileHeight ()
void displayPane (ScrollPane parent)
Point2D.Double findClickedCoordinate (double xLoc, double yLoc)
SuperTile findClickedTile (double xLoc, double yLoc)
SuperTile findTile (Point2D coor)
Protected Member Functions
void clearGridImages ()
void initGridTiles (String shape)
Protected Attributes
int myNumRows
int myNumCols
double myTileHeight
String myShape
transient Pane myPane
transient List< List< SuperTile > > myGrid
Private Member Functions
SuperTile makeShapeTile (String shape, double tileSize, Point2D.Double location)
Static Private Attributes
static final String CIRCLE_GRID = "Circle Grid"
static final String HEXAGON_GRID = "Hexagon Grid"
static final String SQUARE_GRID = "Square Grid"
Detailed Description
Superclass of grids with different behavior. Can use tiles of different shapes.
Author
Meng'en Huang
Definition at line 17 of file SuperGrid.java.
Constructor & Destructor Documentation
authoring_environment.SuperGrid.SuperGrid ()
Definition at line 29 of file SuperGrid.java.
References authoring_environment.SuperGrid.SQUARE_GRID.
authoring_environment.SuperGrid.SuperGrid (int cols, int rows, double tileHeight, String shape)
Definition at line 33 of file SuperGrid.java.
References authoring_environment.SuperGrid.initGridTiles().
Member Function Documentation
void authoring_environment.SuperGrid.clearGridImages () protected
Definition at line 42 of file SuperGrid.java.
void authoring_environment.SuperGrid.displayPane (ScrollPane parent)
Sets the given ScrollPane as the parent to myPane containing the grid SuperTiles
Parameters
parent - ScrollPane parent of mypane
Definition at line 108 of file SuperGrid.java.
Referenced by authoring_environment.GridView.GridView(), fxml_main.LevelController.initEntryDelBtn(), gamePlayer.ViewController.initializeGrid(), authoring_environment.RangeGridView.RangeGridView(), fxml_main.LevelController.setAndDisplayGrid(), and authoring_environment.RangeGridView.update().
Point2D.Double authoring_environment.SuperGrid.findClickedCoordinate (double xLoc, double yLoc)
Get the grid coordinate of the mouse click event for x and y pixel locations
Parameters
xLoc - x pixel location
yLoc - y pixel location
Returns
Point2D containing the grid coordinations of the mouse click as (col, row) or (x, y)
Definition at line 121 of file SuperGrid.java.
References authoring_environment.SuperGrid.findClickedTile(), and authoring_environment.SuperTile.getCoordinates().
Referenced by gamePlayer.ViewController.findPosition(), fxml_main.PatchController.initGlobalDelBtn(), fxml_main.PieceController.initGlobalDelBtn(), fxml_main.PatchController.initGlobalEditBtn(), fxml_main.PieceController.initGlobalEditBtn(), fxml_main.PatchController.makeEntryBox(), and fxml_main.PieceController.makeEntryBox().
SuperTile authoring_environment.SuperGrid.findClickedTile (double xLoc, double yLoc)
Uses PIXEL mouse location to find a SuperTile that was clicked on
Parameters
xLoc - x pixel location of click
yLoc - y pixel location of click
Returns
SuperTile that was clicked, null if none found
Definition at line 134 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.findClickedCoordinate(), gamePlayer.ApplyState.handleMouseMove(), and gamePlayer.GameGridEffect.isHoveringOverActionHighlight().
SuperTile authoring_environment.SuperGrid.findTile (Point2D coor)
Use GRID COORDINATE LOCATION to find a SuperTile
Parameters
coor - Point2D storing the coordinate location as (col, row) or (X,Y)
Returns
SuperTile at that coordinate
Definition at line 152 of file SuperGrid.java.
Referenced by gamePlayer.GameGridEffect.clearAllActionHighlights(), gamePlayer.GameGridEffect.clearAllEffectHighlights(), gamePlayer.GameGridEffect.clearAllPieceHighlights(), gamePlayer.GameGridEffect.greyOutPiece(), authoring_environment.LibraryView.handleAction(), gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.GameGridEffect.highlightCurrent(), gamePlayer.GameGridEffect.highlightEffectRange(), authoring_environment.GUIGrid.removePatch(), authoring_environment.GUIGrid.removePiece(), gamePlayer.KeyboardMovement.setMovementKeyControl(), and gamePlayer.ViewController.toggleKeyboardControl().
int authoring_environment.SuperGrid.getNumCols ()
Returns the int number of columns in the grid (Note: Col = X dimension)
Definition at line 91 of file SuperGrid.java.
References authoring_environment.SuperGrid.myNumCols.
Referenced by tests.TestGameCreator.createNewGrid(), authoring.data.AuthoringLevel.getNumCols(), gamePlayer.GameGridEffect.highlightActionRange(), fxml_main.LevelEditor.LevelEditor(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
int authoring_environment.SuperGrid.getNumRows ()
Returns the int number of rows in the grid (Note: Row = Y dimension)
Definition at line 83 of file SuperGrid.java.
References authoring_environment.SuperGrid.myNumRows.
Referenced by tests.TestGameCreator.createNewGrid(), authoring.data.AuthoringLevel.getNumRows(), gamePlayer.GameGridEffect.highlightActionRange(), fxml_main.LevelEditor.LevelEditor(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
double authoring_environment.SuperGrid.getTileHeight ()
Return the height of the SuperTiles
Returns
double height of the SuperTiles
Definition at line 99 of file SuperGrid.java.
References authoring_environment.SuperGrid.myTileHeight.
Referenced by fxml_main.LevelEditor.LevelEditor().
void authoring_environment.SuperGrid.initGridTiles (String shape) protected
Definition at line 51 of file SuperGrid.java.
References authoring_environment.SuperGrid.makeShapeTile(), authoring_environment.SuperGrid.myNumCols, and authoring_environment.SuperGrid.myNumRows.
Referenced by authoring_environment.RangeGrid.RangeGrid(), authoring_environment.GUIGrid.repopulateGrid(), and authoring_environment.SuperGrid.SuperGrid().
SuperTile authoring_environment.SuperGrid.makeShapeTile (String shape, double tileSize, Point2D.Double location) private
Definition at line 66 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.initGridTiles().
Member Data Documentation
final String authoring_environment.SuperGrid.CIRCLE_GRID = "Circle Grid" static private
Definition at line 18 of file SuperGrid.java.
final String authoring_environment.SuperGrid.HEXAGON_GRID = "Hexagon Grid" static private
Definition at line 19 of file SuperGrid.java.
transient List<List<SuperTile> > authoring_environment.SuperGrid.myGrid protected
Definition at line 27 of file SuperGrid.java.
Referenced by authoring_environment.GUIGrid.addPatchAtLoc(), authoring_environment.GUIGrid.addPatchToTile(), authoring_environment.GUIGrid.addPieceAtLoc(), and authoring_environment.GUIGrid.addPieceToTile().
int authoring_environment.SuperGrid.myNumCols protected
Definition at line 22 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.getNumCols(), and authoring_environment.SuperGrid.initGridTiles().
int authoring_environment.SuperGrid.myNumRows protected
Definition at line 21 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.getNumRows(), and authoring_environment.SuperGrid.initGridTiles().
transient Pane authoring_environment.SuperGrid.myPane protected
Definition at line 26 of file SuperGrid.java.
Referenced by authoring_environment.GUIGrid.paneSetOnMouseDragged(), and authoring_environment.GUIGrid.paneSetOnMousePressed().
String authoring_environment.SuperGrid.myShape protected
Definition at line 24 of file SuperGrid.java.
Referenced by authoring_environment.GUIGrid.repopulateGrid().
double authoring_environment.SuperGrid.myTileHeight protected
Definition at line 23 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.getTileHeight().
final String authoring_environment.SuperGrid.SQUARE_GRID = "Square Grid" static private
Definition at line 20 of file SuperGrid.java.
Referenced by authoring_environment.SuperGrid.SuperGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/SuperGrid.java