voogasalad_VOOGirlsGeneration: tests.GlobalActionTester Class Reference
tests.GlobalActionTester Class Reference
Public Member Functions
GlobalActionTester ()
void TestCreatePiece ()
void TestDeletePiece ()
void TestEndTurn ()
void TestLevelChange ()
Private Attributes
TestGameCreator myBob = new TestGameCreator()
Game myGame
MakePieceAtLocation myCreatePiece
DeletePieceAtLocation myDeletePiece
EndTurn myEndTurn
LevelChange myLevelChange
Piece pieceToCreate
Static Private Attributes
static final String DEFAULT_LEVEL_JUMP = "Level 1"
static final int DEFAULT_TURN_CHANGE = 12345
static final Point2D.Double DEFAULT_PIECE_LOCATION = new Point2D.Double(3,3)
Detailed Description
Definition at line 13 of file GlobalActionTester.java.
Constructor & Destructor Documentation
tests.GlobalActionTester.GlobalActionTester ()
Definition at line 26 of file GlobalActionTester.java.
References tests.TestGameCreator.createNewGame(), tests.TestGameCreator.createNewPiece(), tests.GlobalActionTester.DEFAULT_PIECE_LOCATION, gamedata.gamecomponents.Game.getCurrentLevel(), and gamedata.gamecomponents.Level.getGrid().
Member Function Documentation
void tests.GlobalActionTester.TestCreatePiece ()
Definition at line 36 of file GlobalActionTester.java.
References tests.GlobalActionTester.DEFAULT_PIECE_LOCATION, gamedata.events.globalaction.MakePieceAtLocation.doBehavior(), gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), authoring_environment.GUIGrid.getPiece(), and tests.GlobalActionTester.pieceToCreate.
void tests.GlobalActionTester.TestDeletePiece ()
Definition at line 42 of file GlobalActionTester.java.
References tests.GlobalActionTester.DEFAULT_PIECE_LOCATION, gamedata.events.globalaction.DeletePieceAtLocation.doBehavior(), gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), and authoring_environment.GUIGrid.getPiece().
void tests.GlobalActionTester.TestEndTurn ()
Definition at line 48 of file GlobalActionTester.java.
References gamedata.events.globalaction.EndTurn.doBehavior(), gamedata.gamecomponents.Game.getCurrentPlayer(), and gameengine.player.Player.getID().
void tests.GlobalActionTester.TestLevelChange ()
Definition at line 54 of file GlobalActionTester.java.
References gamedata.events.globalaction.LevelChange.doBehavior(), gamedata.gamecomponents.Game.getCurrentLevel(), and gamedata.gamecomponents.Level.getId().
Member Data Documentation
final String tests.GlobalActionTester.DEFAULT_LEVEL_JUMP = "Level 1" static private
Definition at line 22 of file GlobalActionTester.java.
final Point2D.Double tests.GlobalActionTester.DEFAULT_PIECE_LOCATION = new Point2D.Double(3,3) static private
Definition at line 24 of file GlobalActionTester.java.
Referenced by tests.GlobalActionTester.GlobalActionTester(), tests.GlobalActionTester.TestCreatePiece(), and tests.GlobalActionTester.TestDeletePiece().
final int tests.GlobalActionTester.DEFAULT_TURN_CHANGE = 12345 static private
Definition at line 23 of file GlobalActionTester.java.
TestGameCreator tests.GlobalActionTester.myBob = new TestGameCreator() private
Definition at line 14 of file GlobalActionTester.java.
MakePieceAtLocation tests.GlobalActionTester.myCreatePiece private
Definition at line 16 of file GlobalActionTester.java.
DeletePieceAtLocation tests.GlobalActionTester.myDeletePiece private
Definition at line 17 of file GlobalActionTester.java.
EndTurn tests.GlobalActionTester.myEndTurn private
Definition at line 18 of file GlobalActionTester.java.
Game tests.GlobalActionTester.myGame private
Definition at line 15 of file GlobalActionTester.java.
LevelChange tests.GlobalActionTester.myLevelChange private
Definition at line 19 of file GlobalActionTester.java.
Piece tests.GlobalActionTester.pieceToCreate private
Definition at line 21 of file GlobalActionTester.java.
Referenced by tests.GlobalActionTester.TestCreatePiece().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/tests/GlobalActionTester.java