voogasalad_VOOGirlsGeneration: authoring.concretefeatures.StatsTotalEditor Class Reference
authoring.concretefeatures.StatsTotalEditor Class Reference
Public Member Functions
StatsTotalEditor ()
StatsTotalEditor (Stats stats)
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Member Functions
void initStatsEditorBox (VBox statsVBox)
void initStatsCreatorBoxes (VBox statsVBox)
Button makeAddButton (VBox statsVBox)
void addStatHBox (VBox statsVBox, StatsCreatorBox scb)
Button makeDeleteButton (VBox statsVBox, HBox statsHBox, StatsCreatorBox scb)
Button makeDoneButton (VBox statsVbox)
Private Attributes
Stats myStats
List< StatsCreatorBox > myBoxes
Static Private Attributes
static final int WINDOW_HEIGHT = 400
static final int WINDOW_WIDTH = 420
static final String WINDOW_TITLE = "Stats Editor"
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Popup window for editing the stats for a type of piece. Allows for full editing of the names and default values for a type of piece.
Author
Jennie Ju
Definition at line 27 of file StatsTotalEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.StatsTotalEditor.StatsTotalEditor ()
Definition at line 36 of file StatsTotalEditor.java.
authoring.concretefeatures.StatsTotalEditor.StatsTotalEditor (Stats stats)
Creates an editor popup for creating stats and editing default stat values
Parameters
stats - Stats of the piece whose stats are being edited
Definition at line 47 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.initialize().
Member Function Documentation
void authoring.concretefeatures.StatsTotalEditor.addStatHBox (VBox statsVBox, StatsCreatorBox scb) private
Definition at line 103 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.makeDeleteButton().
Referenced by authoring.concretefeatures.StatsTotalEditor.initStatsCreatorBoxes(), and authoring.concretefeatures.StatsTotalEditor.makeAddButton().
void authoring.concretefeatures.StatsTotalEditor.initialize () protected
Definition at line 58 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.initStatsEditorBox(), authoring.concretefeatures.StatsTotalEditor.makeAddButton(), and authoring.concretefeatures.StatsTotalEditor.makeDoneButton().
Referenced by authoring.concretefeatures.StatsTotalEditor.StatsTotalEditor().
void authoring.concretefeatures.StatsTotalEditor.initStatsCreatorBoxes (VBox statsVBox) private
Definition at line 80 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.addStatHBox(), gamedata.stats.Stats.getStatNames(), and gamedata.stats.Stats.getValue().
Referenced by authoring.concretefeatures.StatsTotalEditor.initStatsEditorBox().
void authoring.concretefeatures.StatsTotalEditor.initStatsEditorBox (VBox statsVBox) private
Definition at line 76 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.initStatsCreatorBoxes().
Referenced by authoring.concretefeatures.StatsTotalEditor.initialize().
Button authoring.concretefeatures.StatsTotalEditor.makeAddButton (VBox statsVBox) private
Definition at line 90 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsTotalEditor.addStatHBox().
Referenced by authoring.concretefeatures.StatsTotalEditor.initialize().
Button authoring.concretefeatures.StatsTotalEditor.makeDeleteButton (VBox statsVBox, HBox statsHBox, StatsCreatorBox scb) private
Definition at line 111 of file StatsTotalEditor.java.
References authoring.concretefeatures.StatsCreatorBox.getStatName(), and gamedata.stats.Stats.remove().
Referenced by authoring.concretefeatures.StatsTotalEditor.addStatHBox().
Button authoring.concretefeatures.StatsTotalEditor.makeDoneButton (VBox statsVbox) private
Definition at line 125 of file StatsTotalEditor.java.
References gamedata.stats.Stats.add().
Referenced by authoring.concretefeatures.StatsTotalEditor.initialize().
Member Data Documentation
List<StatsCreatorBox> authoring.concretefeatures.StatsTotalEditor.myBoxes private
Definition at line 34 of file StatsTotalEditor.java.
Stats authoring.concretefeatures.StatsTotalEditor.myStats private
Definition at line 33 of file StatsTotalEditor.java.
final String authoring.concretefeatures.StatsTotalEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 31 of file StatsTotalEditor.java.
final int authoring.concretefeatures.StatsTotalEditor.WINDOW_HEIGHT = 400 static private
Definition at line 28 of file StatsTotalEditor.java.
final String authoring.concretefeatures.StatsTotalEditor.WINDOW_TITLE = "Stats Editor" static private
Definition at line 30 of file StatsTotalEditor.java.
final int authoring.concretefeatures.StatsTotalEditor.WINDOW_WIDTH = 420 static private
Definition at line 29 of file StatsTotalEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/StatsTotalEditor.java