voogasalad_VOOGirlsGeneration: authoring_environment.SuperTile Class Reference
authoring_environment.SuperTile Class Reference abstract
Public Member Functions
SuperTile (double size, Point2D.Double loc)
boolean selectTile (String color)
boolean deselectTile ()
boolean isSelected ()
void setPieceImage (ImageView imageView)
void setPatchImage (ImageView imageView)
void removePieceImage ()
void removePatchImage ()
Point2D.Double getCoordinates ()
Point2D.Double getLocation ()
Shape getPieceImage ()
Protected Member Functions
void makeShapeTile (double size, Point2D.Double loc)
abstract Shape makeShape (double size, Point2D.Double coordinates)
abstract Point2D.Double calculatePixelLocation (double size, Point2D.Double loc)
abstract Point2D.Double calculateImageLocation (double size, Point2D.Double loc)
abstract double calculateImageSize (double size)
Protected Attributes
Shape myShape
transient Shape myPieceImage
transient Shape myPatchImage
Private Member Functions
void makeHighlight (double size)
void setCheckeredColor (int row, int col, Shape shape)
ImageView initImageView (double size)
void alignNodes (Point2D.Double coord, Node...nodes)
Private Attributes
double myImageSize
Point2D.Double myLocation
Point2D.Double myImageLocation
Point2D.Double myCoordinates
transient Shape myHighlight
Static Private Attributes
static final Color DEFAULT_HIGHLIGHT_COLOR = Color.web("#0000FF", 0.3)
Detailed Description
Super class of tile of different shapes. Contains all the methods related to operation on the tile.
Author
Mengen Huang, Jennie Ju
Definition at line 17 of file SuperTile.java.
Constructor & Destructor Documentation
authoring_environment.SuperTile.SuperTile (double size, Point2D.Double loc)
Define the tile of shape and group all the elements in the tile.
Parameters
size The side length/height of the shape.
loc Grid location of the tile.
Definition at line 36 of file SuperTile.java.
References authoring_environment.SuperTile.makeShapeTile(), and authoring_environment.SuperTile.myCoordinates.
Member Function Documentation
void authoring_environment.SuperTile.alignNodes (Point2D.Double coord, Node... nodes) private
Align the passed in node at the same pixel location.
Parameters
coord The pixel location of the nodes.
nodes The node to be aligned.
Definition at line 225 of file SuperTile.java.
abstract Point2D.Double authoring_environment.SuperTile.calculateImageLocation (double size, Point2D.Double loc) abstract protected
Calculate the location of the image inside the tile that the image takes the place of the biggest square inside the tile.
Parameters
size The height or side length of the shape.
loc The grid location of the tile with the top left as (0,0).
Returns
The pixel location of the image.
Referenced by authoring_environment.SuperTile.makeShapeTile().
abstract double authoring_environment.SuperTile.calculateImageSize (double size) abstract protected
Parameters
size The height or side length of the tile.
Returns
The side length of the biggest square in the tile.
Referenced by authoring_environment.SuperTile.makeShapeTile().
abstract Point2D.Double authoring_environment.SuperTile.calculatePixelLocation (double size, Point2D.Double loc) abstract protected
Calculate the pixel location of the tile.
Parameters
size The height or side length of the shape.
loc The grid location of the tile with the top left as (0,0).
Returns
The pixel location of the tile.
Referenced by authoring_environment.SuperTile.makeShapeTile().
boolean authoring_environment.SuperTile.deselectTile ()
De-highlight the tile.
Returns
TODO
Definition at line 102 of file SuperTile.java.
Referenced by authoring_environment.RangeGrid.processHighlight(), gamePlayer.KeyboardMovement.setMovementKeyControl(), authoring_environment.RangeGrid.switchHighlight(), and gamePlayer.ViewController.toggleKeyboardControl().
Point2D.Double authoring_environment.SuperTile.getCoordinates ()
Get the grid location of the tile.
Returns
The grid location of the tile.
Definition at line 237 of file SuperTile.java.
References authoring_environment.SuperTile.myCoordinates.
Referenced by authoring_environment.SuperGrid.findClickedCoordinate(), and gamePlayer.GameGridEffect.isHoveringOverActionHighlight().
Point2D.Double authoring_environment.SuperTile.getLocation ()
Get the pixel location of the tile.
Returns
The pixel location of the tile.
Definition at line 246 of file SuperTile.java.
References authoring_environment.SuperTile.myLocation.
Shape authoring_environment.SuperTile.getPieceImage ()
Get the imageView of the piece.
Returns
The imageView of the piece.
Definition at line 254 of file SuperTile.java.
References authoring_environment.SuperTile.myPieceImage.
ImageView authoring_environment.SuperTile.initImageView (double size) private
Initiate ImageView as a square and visible at default.
Parameters
size The side length of the biggest square inside the tile.
Returns
The square imageView of the size passed in.
Definition at line 212 of file SuperTile.java.
boolean authoring_environment.SuperTile.isSelected ()
Return a boolean value indicating if the tile is highlighted.
Returns
If the tile is highlighted.
Definition at line 111 of file SuperTile.java.
Referenced by authoring_environment.RangeGrid.selectedRangeList(), and authoring_environment.RangeGrid.switchHighlight().
void authoring_environment.SuperTile.makeHighlight (double size) private
Creates the highlight shape the same as the tile and define the default settings for this tile.
Parameters
size The side length or height of the shape.
Definition at line 80 of file SuperTile.java.
References authoring_environment.SuperTile.makeShape(), and authoring_environment.SuperTile.myLocation.
Referenced by authoring_environment.SuperTile.makeShapeTile().
abstract Shape authoring_environment.SuperTile.makeShape (double size, Point2D.Double coordinates) abstract protected
Make the tile of a specific shape.
Parameters
size The side length/height of the shape.
coordinates The pixel coordinate of the tile.
Returns
The tile of a shape with its location and its size defined.
Referenced by authoring_environment.SuperTile.makeHighlight(), and authoring_environment.SuperTile.makeShapeTile().
void authoring_environment.SuperTile.makeShapeTile (double size, Point2D.Double loc) protected
Make the tile of the specific shape and align the shape, the patch, the piece, and the highlight shape on it. Set the color of background shape color and highlight color. The patch is a shape so that patch image will fill in the shape. The piece only takes the space of the biggeset square inside the tile.
Parameters
size The side length or height of the shape.
loc Grid location of the tile.
Definition at line 54 of file SuperTile.java.
References authoring_environment.SuperTile.calculateImageLocation(), authoring_environment.SuperTile.calculateImageSize(), authoring_environment.SuperTile.calculatePixelLocation(), authoring_environment.SuperTile.makeHighlight(), authoring_environment.SuperTile.makeShape(), authoring_environment.SuperTile.myImageLocation, authoring_environment.SuperTile.myLocation, authoring_environment.SuperTile.myShape, and authoring_environment.SuperTile.setCheckeredColor().
Referenced by authoring_environment.SuperTile.SuperTile().
void authoring_environment.SuperTile.removePatchImage ()
Remove the patch image on the tile by setting the patch a transparent shape.
Definition at line 151 of file SuperTile.java.
Referenced by authoring_environment.GUIGrid.removePatch(), and authoring_environment.GUIGrid.removePatchType().
void authoring_environment.SuperTile.removePieceImage ()
Remove the piece image on the tile by setting it invisible.
Definition at line 143 of file SuperTile.java.
Referenced by authoring_environment.GUIGrid.removePiece(), and authoring_environment.GUIGrid.removePieceType().
boolean authoring_environment.SuperTile.selectTile (String color)
Highlight the tile and pass in a hex color of the highlight.
Parameters
color The color of the highlight.
Returns
TODO
Definition at line 92 of file SuperTile.java.
Referenced by gamePlayer.GameGridEffect.greyOutPiece(), gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.GameGridEffect.highlightCurrent(), gamePlayer.GameGridEffect.highlightEffectRange(), authoring_environment.RangeGrid.highlightRange(), authoring_environment.RangeGrid.processHighlight(), gamePlayer.KeyboardMovement.setMovementKeyControl(), and authoring_environment.RangeGrid.switchHighlight().
void authoring_environment.SuperTile.setCheckeredColor (int row, int col, Shape shape) private
Set the background shape color as white or whitesmoke and the edge of the tile as gray.
Parameters
row The row the tile is on. (The y grid location of the tile).
col The column the tile is on. (The x grid location of the tile).
shape The shape of the tile.
Definition at line 196 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.makeShapeTile().
void authoring_environment.SuperTile.setPatchImage (ImageView imageView)
Set the Image of the Patch on the tile.
Parameters
imageView The imageView which contains the image to fill the tile as a patch.
Definition at line 135 of file SuperTile.java.
Referenced by authoring_environment.RangeGrid.addCenterImage(), authoring_environment.GUIGrid.addPatchAtLoc(), authoring_environment.GUIGrid.addPatchToTile(), and authoring_environment.GUIGrid.replacePatchType().
void authoring_environment.SuperTile.setPieceImage (ImageView imageView)
Show an image inside the tile which takes the place of the biggest square inside the shape.
Parameters
imageView The imageView which contains the image to put on the tile as a piece.
Definition at line 122 of file SuperTile.java.
Referenced by authoring_environment.GUIGrid.addPieceAtLoc(), authoring_environment.GUIGrid.addPieceToTile(), and authoring_environment.GUIGrid.replacePieceType().
Member Data Documentation
final Color authoring_environment.SuperTile.DEFAULT_HIGHLIGHT_COLOR = Color.web("#0000FF", 0.3) static private
Definition at line 18 of file SuperTile.java.
Point2D.Double authoring_environment.SuperTile.myCoordinates private
Definition at line 24 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.getCoordinates(), and authoring_environment.SuperTile.SuperTile().
transient Shape authoring_environment.SuperTile.myHighlight private
Definition at line 28 of file SuperTile.java.
Point2D.Double authoring_environment.SuperTile.myImageLocation private
Definition at line 23 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.makeShapeTile().
double authoring_environment.SuperTile.myImageSize private
Definition at line 21 of file SuperTile.java.
Point2D.Double authoring_environment.SuperTile.myLocation private
Definition at line 22 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.getLocation(), authoring_environment.SuperTile.makeHighlight(), and authoring_environment.SuperTile.makeShapeTile().
transient Shape authoring_environment.SuperTile.myPatchImage protected
Definition at line 27 of file SuperTile.java.
transient Shape authoring_environment.SuperTile.myPieceImage protected
Definition at line 26 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.getPieceImage().
Shape authoring_environment.SuperTile.myShape protected
Definition at line 19 of file SuperTile.java.
Referenced by authoring_environment.SuperTile.makeShapeTile().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/SuperTile.java