voogasalad_VOOGirlsGeneration: authoring.createedit.ActionCreator Class Reference
authoring.createedit.ActionCreator Class Reference
Public Member Functions
ActionCreator ()
ActionCreator (ActionData actionData)
Static Public Attributes
static final int HEIGHT = 400
static final int WIDTH = 350
static final String NAME = "Action Creator"
Protected Member Functions
void initialize ()
void setAttackRange (List< Point2D > attackRange)
void setEffectRange (List< Point2D > effectRange)
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Member Functions
void initConclusionsBox (VBox conclusionVBox)
List< String > trimClassList (List< String > conclusionsList)
String trimClassPaths (String s)
List< StatsTotalLogic > getStatsLogics (ChoiceBox< String > targetChoice, TextField moddedStat)
List< StatsSingleMultiplier > getSingleMultipliers (List< SingleMultiplierBox > smbList)
void initNameField (VBox nameBox, TextField nameField)
void initSetRangeButton (VBox rangeBox, String label, List< Point2D > range)
Private Attributes
List< SingleMultiplierBox > operationsList
ActionData myActionData
String myName
List< Point2D > myAttackRange
List< Point2D > myEffectRange
List< StatsTotalLogic > myStatsLogics
ActionConclusion myConclusion
List< Class > conclusionsList
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/actioncreator_layout.css"
static final Insets MARGINS = new Insets(20, WIDTH / 8, 20, WIDTH / 8 - 10)
static final String LABEL_CSS = "-fx-font-size: 12pt;"
static final String DEFAULT_IMAGE = "/resources/images/default_image.png"
static final String CONCLUSION_LABEL = "Choose action conclusion"
Detailed Description
Opens a dialog for creating new Actions in the authoring environment
Author
Mike Zhu, Rica Zhang, Jennie Ju, annamiyajima
Definition at line 44 of file ActionCreator.java.
Constructor & Destructor Documentation
authoring.createedit.ActionCreator.ActionCreator ()
Definition at line 67 of file ActionCreator.java.
authoring.createedit.ActionCreator.ActionCreator (ActionData actionData)
Constructor for an ActionCreator popup window
Parameters
actionData
class where user-created Actions are stored
Definition at line 77 of file ActionCreator.java.
References authoring.createedit.ActionCreator.initialize().
Member Function Documentation
List<StatsSingleMultiplier> authoring.createedit.ActionCreator.getSingleMultipliers (List< SingleMultiplierBox > smbList) private
Definition at line 213 of file ActionCreator.java.
Referenced by authoring.createedit.ActionCreator.getStatsLogics().
List<StatsTotalLogic> authoring.createedit.ActionCreator.getStatsLogics (ChoiceBox< String > targetChoice, TextField moddedStat) private
Definition at line 202 of file ActionCreator.java.
References authoring.createedit.ActionCreator.getSingleMultipliers().
Referenced by authoring.createedit.ActionCreator.initialize().
void authoring.createedit.ActionCreator.initConclusionsBox (VBox conclusionVBox) private
Definition at line 149 of file ActionCreator.java.
References utilities.ClassGrabber.getClasses(), and authoring.createedit.ActionCreator.trimClassList().
Referenced by authoring.createedit.ActionCreator.initialize().
void authoring.createedit.ActionCreator.initialize () protected
Definition at line 93 of file ActionCreator.java.
References authoring.data.ActionData.add(), authoring.data.ActionData.getActionNames(), authoring.createedit.ActionCreator.getStatsLogics(), authoring.createedit.ActionCreator.initConclusionsBox(), authoring.createedit.ActionCreator.initNameField(), and authoring.createedit.ActionCreator.initSetRangeButton().
Referenced by authoring.createedit.ActionCreator.ActionCreator().
void authoring.createedit.ActionCreator.initNameField (VBox nameBox, TextField nameField) private
Definition at line 221 of file ActionCreator.java.
Referenced by authoring.createedit.ActionCreator.initialize().
void authoring.createedit.ActionCreator.initSetRangeButton (VBox rangeBox, String label, List< Point2D > range) private
Definition at line 227 of file ActionCreator.java.
Referenced by authoring.createedit.ActionCreator.initialize().
void authoring.createedit.ActionCreator.setAttackRange (List< Point2D > attackRange) protected
Definition at line 240 of file ActionCreator.java.
void authoring.createedit.ActionCreator.setEffectRange (List< Point2D > effectRange) protected
Definition at line 244 of file ActionCreator.java.
List<String> authoring.createedit.ActionCreator.trimClassList (List< String > conclusionsList) private
Definition at line 175 of file ActionCreator.java.
References authoring.createedit.ActionCreator.trimClassPaths().
Referenced by authoring.createedit.ActionCreator.initConclusionsBox().
String authoring.createedit.ActionCreator.trimClassPaths (String s) private
Removes the classpath prefixes for each Condition name
Parameters
s
Definition at line 189 of file ActionCreator.java.
Referenced by authoring.createedit.ActionCreator.trimClassList().
Member Data Documentation
final String authoring.createedit.ActionCreator.CONCLUSION_LABEL = "Choose action conclusion" static private
Definition at line 57 of file ActionCreator.java.
List<Class> authoring.createedit.ActionCreator.conclusionsList private
Definition at line 65 of file ActionCreator.java.
final String authoring.createedit.ActionCreator.DEFAULT_IMAGE = "/resources/images/default_image.png" static private
Definition at line 56 of file ActionCreator.java.
final int authoring.createedit.ActionCreator.HEIGHT = 400 static
Definition at line 46 of file ActionCreator.java.
final String authoring.createedit.ActionCreator.LABEL_CSS = "-fx-font-size: 12pt;" static private
Definition at line 55 of file ActionCreator.java.
final Insets authoring.createedit.ActionCreator.MARGINS = new Insets(20, WIDTH / 8, 20, WIDTH / 8 - 10) static private
Definition at line 54 of file ActionCreator.java.
ActionData authoring.createedit.ActionCreator.myActionData private
Definition at line 52 of file ActionCreator.java.
List<Point2D> authoring.createedit.ActionCreator.myAttackRange private
Definition at line 60 of file ActionCreator.java.
ActionConclusion authoring.createedit.ActionCreator.myConclusion private
Definition at line 63 of file ActionCreator.java.
List<Point2D> authoring.createedit.ActionCreator.myEffectRange private
Definition at line 61 of file ActionCreator.java.
String authoring.createedit.ActionCreator.myName private
Definition at line 59 of file ActionCreator.java.
List<StatsTotalLogic> authoring.createedit.ActionCreator.myStatsLogics private
Definition at line 62 of file ActionCreator.java.
final String authoring.createedit.ActionCreator.NAME = "Action Creator" static
Definition at line 48 of file ActionCreator.java.
List<SingleMultiplierBox> authoring.createedit.ActionCreator.operationsList private
Definition at line 51 of file ActionCreator.java.
final String authoring.createedit.ActionCreator.STYLESHEET = "/resources/stylesheets/actioncreator_layout.css" static private
Definition at line 49 of file ActionCreator.java.
final int authoring.createedit.ActionCreator.WIDTH = 350 static
Definition at line 47 of file ActionCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/createedit/ActionCreator.java