voogasalad_VOOGirlsGeneration: tests.TestGameCreator Class Reference
tests.TestGameCreator Class Reference
Public Member Functions
TestGameCreator ()
GUIGrid createGUIGrid ()
SuperGrid createSuperGrid ()
Game createNewGame ()
GUIGrid createNewGrid ()
Piece createNewPiece (GUIGrid g, Point2D.Double p, int type)
Patch createNewPatch (Point2D.Double p)
Movement createNewMovement ()
Action createNewAction (List< Point2D.Double > pl1, List< Point2D.Double > pl2)
StatsSingleMultiplier createStatsSingleMultiplier ()
StatsTotalLogic createNewStatsTotalLogic ()
Event createNewEvent ()
Static Private Attributes
static String DEFAULT_DUVALL = "/resources/images/rcd.png"
static String DEFAULT_BUNNY = "/resources/images/bbybunny.jpeg"
static String DEFAULT_RICA = "/resources/images/Rica.png"
static String DEFAULT_LAND = "/resources/images/Land.jpeg"
static int RANDOMIZE = 0
static int DUVALL = 1
static int BUNNY = 2
static int RICA = 3
Detailed Description
Creates a test game and various game components
Author
Rica
Definition at line 39 of file TestGameCreator.java.
Constructor & Destructor Documentation
tests.TestGameCreator.TestGameCreator ()
Definition at line 50 of file TestGameCreator.java.
Member Function Documentation
GUIGrid tests.TestGameCreator.createGUIGrid ()
Definition at line 55 of file TestGameCreator.java.
Action tests.TestGameCreator.createNewAction (List< Point2D.Double > pl1, List< Point2D.Double > pl2)
Definition at line 234 of file TestGameCreator.java.
References tests.TestGameCreator.createNewStatsTotalLogic().
Referenced by tests.TestGameCreator.createNewPiece().
Event tests.TestGameCreator.createNewEvent ()
Definition at line 260 of file TestGameCreator.java.
References gamedata.events.Event.getConditions(), and gamedata.events.Event.getGlobalActions().
Game tests.TestGameCreator.createNewGame ()
Create a new game to test
Returns
a new default game
Definition at line 71 of file TestGameCreator.java.
References gamedata.gamecomponents.Game.addPlayers(), and tests.TestGameCreator.createNewGrid().
Referenced by tests.GlobalActionTester.GlobalActionTester(), authoring.concretefeatures.menus.FileX.handleSave(), gamePlayer.ViewController.testGame(), and tests.JSONTesterMain.testJSONwrite().
GUIGrid tests.TestGameCreator.createNewGrid ()
Definition at line 105 of file TestGameCreator.java.
References authoring_environment.GUIGrid.addPatchAtLoc(), authoring_environment.GUIGrid.addPieceAtLoc(), tests.TestGameCreator.createNewPatch(), tests.TestGameCreator.createNewPiece(), authoring_environment.SuperGrid.getNumCols(), authoring_environment.SuperGrid.getNumRows(), and gamedata.gamecomponents.Piece.setPlayerID().
Referenced by tests.TestGameCreator.createNewGame().
Movement tests.TestGameCreator.createNewMovement ()
Definition at line 214 of file TestGameCreator.java.
Patch tests.TestGameCreator.createNewPatch (Point2D.Double p)
Definition at line 209 of file TestGameCreator.java.
Referenced by tests.TestGameCreator.createNewGrid().
Piece tests.TestGameCreator.createNewPiece (GUIGrid g, Point2D.Double p, int type)
Definition at line 136 of file TestGameCreator.java.
References gamedata.stats.Stats.add(), and tests.TestGameCreator.createNewAction().
Referenced by tests.TestGameCreator.createNewGrid(), and tests.GlobalActionTester.GlobalActionTester().
StatsTotalLogic tests.TestGameCreator.createNewStatsTotalLogic ()
Definition at line 246 of file TestGameCreator.java.
Referenced by tests.TestGameCreator.createNewAction().
StatsSingleMultiplier tests.TestGameCreator.createStatsSingleMultiplier ()
Definition at line 242 of file TestGameCreator.java.
SuperGrid tests.TestGameCreator.createSuperGrid ()
Definition at line 61 of file TestGameCreator.java.
Member Data Documentation
int tests.TestGameCreator.BUNNY = 2 static private
Definition at line 47 of file TestGameCreator.java.
String tests.TestGameCreator.DEFAULT_BUNNY = "/resources/images/bbybunny.jpeg" static private
Definition at line 42 of file TestGameCreator.java.
String tests.TestGameCreator.DEFAULT_DUVALL = "/resources/images/rcd.png" static private
Definition at line 41 of file TestGameCreator.java.
String tests.TestGameCreator.DEFAULT_LAND = "/resources/images/Land.jpeg" static private
Definition at line 44 of file TestGameCreator.java.
String tests.TestGameCreator.DEFAULT_RICA = "/resources/images/Rica.png" static private
Definition at line 43 of file TestGameCreator.java.
int tests.TestGameCreator.DUVALL = 1 static private
Definition at line 46 of file TestGameCreator.java.
int tests.TestGameCreator.RANDOMIZE = 0 static private
Definition at line 45 of file TestGameCreator.java.
int tests.TestGameCreator.RICA = 3 static private
Definition at line 48 of file TestGameCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/tests/TestGameCreator.java