voogasalad_VOOGirlsGeneration: authoring.data.GameAuthoringData Class Reference
authoring.data.GameAuthoringData Class Reference
Public Member Functions
GameAuthoringData (LevelData levelData, PieceTypeData pieceTypeData, PatchTypeData patchTypeData, ActionData actionData, GamePropertiesData gamePropertiesData, PlayerStatData playerStatData)
Game createGame ()
Private Attributes
LevelData myLevelData
PieceTypeData myPieceTypeData
PatchTypeData myPatchTypeData
ActionData myActionData
GamePropertiesData myGamePropertiesData
PlayerStatData myPlayerStatData
Detailed Description
Stores all the data use in the Authoring environment and needed for the game player/json
Definition at line 13 of file GameAuthoringData.java.
Constructor & Destructor Documentation
authoring.data.GameAuthoringData.GameAuthoringData (LevelData levelData, PieceTypeData pieceTypeData, PatchTypeData patchTypeData, ActionData actionData, GamePropertiesData gamePropertiesData, PlayerStatData playerStatData)
Definition at line 21 of file GameAuthoringData.java.
Member Function Documentation
Game authoring.data.GameAuthoringData.createGame ()
Creates a Game from the stored num players and level data
Returns
Game made from authoring environment data
Definition at line 37 of file GameAuthoringData.java.
References gamedata.gamecomponents.Game.addPlayers(), authoring.data.LevelData.createGame(), authoring.data.GamePropertiesData.getNumPlayers(), and authoring.data.PlayerStatData.makePlayers().
Referenced by fxml_main.AuthoringController.saveAsGame(), and fxml_main.AuthoringController.saveGame().
Member Data Documentation
ActionData authoring.data.GameAuthoringData.myActionData private
Definition at line 17 of file GameAuthoringData.java.
GamePropertiesData authoring.data.GameAuthoringData.myGamePropertiesData private
Definition at line 18 of file GameAuthoringData.java.
LevelData authoring.data.GameAuthoringData.myLevelData private
Definition at line 14 of file GameAuthoringData.java.
PatchTypeData authoring.data.GameAuthoringData.myPatchTypeData private
Definition at line 16 of file GameAuthoringData.java.
PieceTypeData authoring.data.GameAuthoringData.myPieceTypeData private
Definition at line 15 of file GameAuthoringData.java.
PlayerStatData authoring.data.GameAuthoringData.myPlayerStatData private
Definition at line 19 of file GameAuthoringData.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/GameAuthoringData.java