voogasalad_VOOGirlsGeneration: gameengine.player.HumanPlayer Class Reference
gameengine.player.HumanPlayer Class Reference
Public Member Functions
HumanPlayer (int id)
HumanPlayer (int id, Stats stats, String scoreStat)
HumanPlayer (Player player)
void startTurn (Level l)
Map< KeyCode, Action > getActionKeyMap ()
Map< KeyCode, Point2D.Double > getMovementKeyMap ()
void setActionKeyMap (Map< KeyCode, Action > myActionKeyMap)
void setMovementKeyMap (Map< KeyCode, Point2D.Double > myMovementKeyMap2)
void play ()
String getType ()
Public Member Functions inherited from gameengine.player.Player
Player ()
Player (int id)
Player (Player player)
Stats getStats ()
double getScore ()
Point2D getLoc ()
void changeStat (String statName, double value)
abstract void startTurn (Level l)
void resetMovesPlayed ()
int getID ()
abstract void play ()
void playTurn ()
int getNumMovesPlayed ()
String printString ()
String toString ()
abstract String getType ()
Private Attributes
Map< KeyCode, Action > myActionKeyMap
Map< KeyCode, Point2D.Double > myMovementKeyMap
Additional Inherited Members
Protected Member Functions inherited from gameengine.player.Player
Player (int id, Stats stats, String scoreStat)
Protected Attributes inherited from gameengine.player.Player
int myNumMovesPlayed
int myID
Stats myStats
String myScoreStat
Detailed Description
Defines a Human Player
Author
Jesse, Sandy, Rica
Definition at line 19 of file HumanPlayer.java.
Constructor & Destructor Documentation
gameengine.player.HumanPlayer.HumanPlayer (int id)
Constructor
Parameters
id int representing the ID of the player
Definition at line 37 of file HumanPlayer.java.
References gameengine.player.HumanPlayer.myMovementKeyMap, gameengine.player.HumanPlayer.setActionKeyMap(), and gameengine.player.HumanPlayer.setMovementKeyMap().
gameengine.player.HumanPlayer.HumanPlayer (int id, Stats stats, String scoreStat)
Definition at line 43 of file HumanPlayer.java.
References gameengine.player.HumanPlayer.myMovementKeyMap, gameengine.player.HumanPlayer.setActionKeyMap(), and gameengine.player.HumanPlayer.setMovementKeyMap().
gameengine.player.HumanPlayer.HumanPlayer (Player player)
Definition at line 49 of file HumanPlayer.java.
References gameengine.player.HumanPlayer.myMovementKeyMap, gameengine.player.HumanPlayer.setActionKeyMap(), and gameengine.player.HumanPlayer.setMovementKeyMap().
Member Function Documentation
Map<KeyCode, Action> gameengine.player.HumanPlayer.getActionKeyMap ()
used by game player (GUI) so that it knows what action to perform when certain keycodes are pressed/used.
Returns
myKeyMap which maps actions to pre-defined keycodes
Definition at line 68 of file HumanPlayer.java.
References gameengine.player.HumanPlayer.myActionKeyMap.
Map<KeyCode, Point2D.Double> gameengine.player.HumanPlayer.getMovementKeyMap ()
Returns the Key Mapping for the Player
Returns
Definition at line 77 of file HumanPlayer.java.
References gameengine.player.HumanPlayer.myMovementKeyMap.
String gameengine.player.HumanPlayer.getType ()
Definition at line 105 of file HumanPlayer.java.
void gameengine.player.HumanPlayer.play ()
Definition at line 100 of file HumanPlayer.java.
void gameengine.player.HumanPlayer.setActionKeyMap (Map< KeyCode, Action > myActionKeyMap)
needs to get info from the authoring environment to set up the map..
Parameters
myKeyMap
Definition at line 86 of file HumanPlayer.java.
Referenced by gameengine.player.HumanPlayer.HumanPlayer().
void gameengine.player.HumanPlayer.setMovementKeyMap (Map< KeyCode, Point2D.Double > myMovementKeyMap2)
Sets the Key Mapping for the Player
Parameters
myMovementKeyMap2
Definition at line 95 of file HumanPlayer.java.
Referenced by gameengine.player.HumanPlayer.HumanPlayer().
void gameengine.player.HumanPlayer.startTurn (Level l)
Definition at line 56 of file HumanPlayer.java.
References gameengine.player.Player.resetMovesPlayed().
Member Data Documentation
Map<KeyCode, Action> gameengine.player.HumanPlayer.myActionKeyMap private
Maps Action Keys
Definition at line 24 of file HumanPlayer.java.
Referenced by gameengine.player.HumanPlayer.getActionKeyMap().
Map<KeyCode, Point2D.Double> gameengine.player.HumanPlayer.myMovementKeyMap private
Maps Movement Keys
Definition at line 29 of file HumanPlayer.java.
Referenced by gameengine.player.HumanPlayer.getMovementKeyMap(), and gameengine.player.HumanPlayer.HumanPlayer().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gameengine/player/HumanPlayer.java