voogasalad_VOOGirlsGeneration: authoring.concretefeatures.RangeEditor.selectRangeHandler Class Reference
authoring.concretefeatures.RangeEditor.selectRangeHandler Class Reference
Public Member Functions
selectRangeHandler (ChoiceBox< String > tc, TextField sd, Button b)
void handle (ActionEvent event)
Package Attributes
ChoiceBox< String > targetChoice
TextField specifiedData
Button button
Detailed Description
Definition at line 181 of file RangeEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.RangeEditor.selectRangeHandler.selectRangeHandler (ChoiceBox< String > tc, TextField sd, Button b)
Definition at line 186 of file RangeEditor.java.
Member Function Documentation
void authoring.concretefeatures.RangeEditor.selectRangeHandler.handle (ActionEvent event)
Definition at line 193 of file RangeEditor.java.
References authoring_environment.RangeGridView.getGrid(), authoring_environment.RangeGrid.rangeAll(), authoring_environment.RangeGrid.rangeColumn(), authoring_environment.RangeGrid.rangeRadius(), and authoring_environment.RangeGrid.rangeRow().
Member Data Documentation
Button authoring.concretefeatures.RangeEditor.selectRangeHandler.button package
Definition at line 184 of file RangeEditor.java.
TextField authoring.concretefeatures.RangeEditor.selectRangeHandler.specifiedData package
Definition at line 183 of file RangeEditor.java.
ChoiceBox<String> authoring.concretefeatures.RangeEditor.selectRangeHandler.targetChoice package
Definition at line 182 of file RangeEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/RangeEditor.java