voogasalad_VOOGirlsGeneration: gamedata.action.Action Interface Reference
gamedata.action.Action Interface Reference
Public Member Functions
String toString ()
String getName ()
List< Point2D.Double > getAbsoluteActionRange (Point2D pieceLocation)
List< Point2D.Double > getAbsoluteEffectRange (Point2D pieceLocation)
List< Point2D.Double > getActionRange ()
List< Point2D.Double > getEffectRange ()
void doBehavior (GUIGrid grid, Piece actor, Piece...receivers)
Detailed Description
Interface of a game component that performs an action on another component in the game. Pieces will contain a list of actions.
Author
Jennie Ju
Definition at line 16 of file Action.java.
Member Function Documentation
void gamedata.action.Action.doBehavior (GUIGrid grid, Piece actor, Piece... receivers)
Executes an action on a component of the game (i.e. a piece, patch, or other module)
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by gamePlayer.ApplyState.onClick(), and gameengine.player.SimpleAIPlayer.play().
List<Point2D.Double> gamedata.action.Action.getAbsoluteActionRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the action range
Returns
list of absolute locations in Point2D
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.ApplyState.onClick(), and gameengine.player.SimpleAIPlayer.play().
List<Point2D.Double> gamedata.action.Action.getAbsoluteEffectRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the effect range
Returns
list of absolute locations in Point2D
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by gamePlayer.GameGridEffect.highlightEffectRange().
List<Point2D.Double> gamedata.action.Action.getActionRange ()
Gives back a list of Point2D of relative locations for the action range
Returns
list of absolute locations in Point2D
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by fxml_main.ActionViewer.ActionViewer().
List<Point2D.Double> gamedata.action.Action.getEffectRange ()
Gives back a list of Point2D of relative locations for the effect range of the action (splashzone)
Returns
list of relative locations in Point2D
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by fxml_main.ActionViewer.ActionViewer().
String gamedata.action.Action.getName ()
Returns the name of the Action for display
Returns
name of Action
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by gamePlayer.KeyboardAction.markAction(), and gamePlayer.ApplyState.onClick().
String gamedata.action.Action.toString ()
Returns the information about the Action for display
Returns
name of Action
Implemented in gameengine.movement.Movement, and gamedata.action.ConcreteAction.
Referenced by fxml_main.ActionViewer.ActionViewer(), tests.ViewControllerTest.bindActionTest(), and authoring.data.ActionData.canAdd().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/Action.java