voogasalad_VOOGirlsGeneration: fxml_main.PieceTypeEditor Class Reference
fxml_main.PieceTypeEditor Class Reference
Public Member Functions
PieceTypeEditor (Consumer< Piece > okLambda, PieceTypeData pieceTypes, ActionData actions, String gridShape)
PieceTypeEditor (Consumer< Piece > okLambda, Piece piece, ActionData actions, String gridShape)
void constructor (Consumer< Piece > okLambda)
void initialize ()
Protected Member Functions
List< Action > addSelectedActions (List< String > selected)
Private Member Functions
void initStatButton (Button createStatButton)
void showStatEditorWindow ()
ModulesList initModList ()
void initImageLoader (HBox images)
void initRangeEditorButton (Button rangeEditorButton)
ImageView setImageView ()
void initGoBtn (Button goButton, TextField unitID, TextField unitName, ModulesList modList, CheckBox cbInventory, CheckBox cbItem)
Private Attributes
String myEditorTitle
Consumer< Piece > myOkLambda
String myID
String myName
String myImageLocation
Piece myPiece
String myGridShape
ActionData myAvailableActions
Set< String > myIDSet
int myPlayerID
Stats myStats
Movement myMovement
List< Action > myActions
Inventory myInventory
boolean myHasInventory
boolean myIsItem
Static Private Attributes
static final int HEIGHT = 150
static final int WIDTH = 150
static final String CREATOR_TITLE = "Piece Creator"
static final String EDITOR_TITLE = "Piece Editor"
static final String ID_LABEL = "Unique ID"
static final String NAME_LABEL = "Name"
static final String LOADIMAGE_LABEL = "Load Piece Image"
static final String TEMPLATE_LABEL = "OK"
static final String ID_PROMPT = "Enter piece ID..."
static final String NAME_PROMPT = "Enter piece name..."
static final String STAT_CREATE_LABEL = "Add stat"
static final String MOVE_RANGE_LABEL = "Set Movement Range..."
static final Insets MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10)
static final String LABEL_CSS = "-fx-font-size: 14pt;"
static final String DEFAULT_IMAGE_LOC = "/resources/images/default_image.png"
static final String IMAGE_LOC = "/resources/images"
static final Point2D.Double DEFAULT_LOC = new Point2D.Double(0, 0)
Detailed Description
Author
Mike Zhu, Jennie Ju, Martin Tamayo
Definition at line 47 of file PieceTypeEditor.java.
Constructor & Destructor Documentation
fxml_main.PieceTypeEditor.PieceTypeEditor (Consumer< Piece > okLambda, PieceTypeData pieceTypes, ActionData actions, String gridShape)
Called when creating a new Piece
Parameters
pieceController
Definition at line 92 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.constructor(), fxml_main.PieceTypeEditor.CREATOR_TITLE, fxml_main.PieceTypeEditor.DEFAULT_IMAGE_LOC, and authoring.data.PieceTypeData.getIdSet().
fxml_main.PieceTypeEditor.PieceTypeEditor (Consumer< Piece > okLambda, Piece piece, ActionData actions, String gridShape)
Definition at line 111 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.constructor(), fxml_main.PieceTypeEditor.EDITOR_TITLE, gamedata.gamecomponents.GridComponent.getID(), gamedata.gamecomponents.GridComponent.getImageLocation(), gamedata.gamecomponents.Piece.getInventory(), gamedata.gamecomponents.Piece.getMovement(), gamedata.gamecomponents.GridComponent.getName(), gamedata.gamecomponents.Piece.getOriginalActions(), gamedata.gamecomponents.Piece.getPlayerID(), gamedata.gamecomponents.Piece.getStats(), gamedata.gamecomponents.Piece.hasInventory(), and gamedata.gamecomponents.Piece.isItem().
Member Function Documentation
List<Action> fxml_main.PieceTypeEditor.addSelectedActions (List< String > selected) protected
Definition at line 318 of file PieceTypeEditor.java.
References authoring.data.ActionData.getAction().
Referenced by fxml_main.PieceTypeEditor.initGoBtn().
void fxml_main.PieceTypeEditor.constructor (Consumer< Piece > okLambda)
Definition at line 130 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.initialize().
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor().
void fxml_main.PieceTypeEditor.initGoBtn (Button goButton, TextField unitID, TextField unitName, ModulesList modList, CheckBox cbInventory, CheckBox cbItem) private
Definition at line 289 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.addSelectedActions(), fxml_main.PieceTypeEditor.DEFAULT_LOC, authoring.createedit.ModulesList.getSelectedActions(), and gameengine.movement.Movement.toString().
Referenced by fxml_main.PieceTypeEditor.initialize().
void fxml_main.PieceTypeEditor.initialize ()
Definition at line 137 of file PieceTypeEditor.java.
References authoring_environment.UIspecs.allPadding, fxml_main.PieceTypeEditor.initGoBtn(), fxml_main.PieceTypeEditor.initImageLoader(), fxml_main.PieceTypeEditor.initModList(), fxml_main.PieceTypeEditor.initRangeEditorButton(), fxml_main.PieceTypeEditor.initStatButton(), and authoring_environment.UIspecs.topRightPadding.
Referenced by fxml_main.PieceTypeEditor.constructor().
void fxml_main.PieceTypeEditor.initImageLoader (HBox images) private
Definition at line 237 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.setImageView().
Referenced by fxml_main.PieceTypeEditor.initialize().
ModulesList fxml_main.PieceTypeEditor.initModList () private
Definition at line 227 of file PieceTypeEditor.java.
References authoring.data.ActionData.getActionNames().
Referenced by fxml_main.PieceTypeEditor.initialize().
void fxml_main.PieceTypeEditor.initRangeEditorButton (Button rangeEditorButton) private
Definition at line 263 of file PieceTypeEditor.java.
References gameengine.movement.Movement.getRelativeMoves().
Referenced by fxml_main.PieceTypeEditor.initialize().
void fxml_main.PieceTypeEditor.initStatButton (Button createStatButton) private
Definition at line 213 of file PieceTypeEditor.java.
References fxml_main.PieceTypeEditor.showStatEditorWindow().
Referenced by fxml_main.PieceTypeEditor.initialize().
ImageView fxml_main.PieceTypeEditor.setImageView () private
Definition at line 279 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.initImageLoader().
void fxml_main.PieceTypeEditor.showStatEditorWindow () private
Definition at line 222 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.initStatButton().
Member Data Documentation
final String fxml_main.PieceTypeEditor.CREATOR_TITLE = "Piece Creator" static private
Definition at line 50 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor().
final String fxml_main.PieceTypeEditor.DEFAULT_IMAGE_LOC = "/resources/images/default_image.png" static private
Definition at line 63 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor().
final Point2D.Double fxml_main.PieceTypeEditor.DEFAULT_LOC = new Point2D.Double(0, 0) static private
Definition at line 65 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.initGoBtn().
final String fxml_main.PieceTypeEditor.EDITOR_TITLE = "Piece Editor" static private
Definition at line 51 of file PieceTypeEditor.java.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor().
final int fxml_main.PieceTypeEditor.HEIGHT = 150 static private
Definition at line 48 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.ID_LABEL = "Unique ID" static private
Definition at line 52 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.ID_PROMPT = "Enter piece ID..." static private
Definition at line 56 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.IMAGE_LOC = "/resources/images" static private
Definition at line 64 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 61 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.LOADIMAGE_LABEL = "Load Piece Image" static private
Definition at line 54 of file PieceTypeEditor.java.
final Insets fxml_main.PieceTypeEditor.MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10) static private
Definition at line 60 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.MOVE_RANGE_LABEL = "Set Movement Range..." static private
Definition at line 59 of file PieceTypeEditor.java.
List<Action> fxml_main.PieceTypeEditor.myActions private
Definition at line 82 of file PieceTypeEditor.java.
ActionData fxml_main.PieceTypeEditor.myAvailableActions private
Definition at line 76 of file PieceTypeEditor.java.
String fxml_main.PieceTypeEditor.myEditorTitle private
Definition at line 67 of file PieceTypeEditor.java.
String fxml_main.PieceTypeEditor.myGridShape private
Definition at line 75 of file PieceTypeEditor.java.
boolean fxml_main.PieceTypeEditor.myHasInventory private
Definition at line 84 of file PieceTypeEditor.java.
String fxml_main.PieceTypeEditor.myID private
Definition at line 70 of file PieceTypeEditor.java.
Set<String> fxml_main.PieceTypeEditor.myIDSet private
Definition at line 77 of file PieceTypeEditor.java.
String fxml_main.PieceTypeEditor.myImageLocation private
Definition at line 72 of file PieceTypeEditor.java.
Inventory fxml_main.PieceTypeEditor.myInventory private
Definition at line 83 of file PieceTypeEditor.java.
boolean fxml_main.PieceTypeEditor.myIsItem private
Definition at line 85 of file PieceTypeEditor.java.
Movement fxml_main.PieceTypeEditor.myMovement private
Definition at line 81 of file PieceTypeEditor.java.
String fxml_main.PieceTypeEditor.myName private
Definition at line 71 of file PieceTypeEditor.java.
Consumer<Piece> fxml_main.PieceTypeEditor.myOkLambda private
Definition at line 68 of file PieceTypeEditor.java.
Piece fxml_main.PieceTypeEditor.myPiece private
Definition at line 73 of file PieceTypeEditor.java.
int fxml_main.PieceTypeEditor.myPlayerID private
Definition at line 79 of file PieceTypeEditor.java.
Stats fxml_main.PieceTypeEditor.myStats private
Definition at line 80 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.NAME_LABEL = "Name" static private
Definition at line 53 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.NAME_PROMPT = "Enter piece name..." static private
Definition at line 57 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.STAT_CREATE_LABEL = "Add stat" static private
Definition at line 58 of file PieceTypeEditor.java.
final String fxml_main.PieceTypeEditor.TEMPLATE_LABEL = "OK" static private
Definition at line 55 of file PieceTypeEditor.java.
final int fxml_main.PieceTypeEditor.WIDTH = 150 static private
Definition at line 49 of file PieceTypeEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PieceTypeEditor.java