voogasalad_VOOGirlsGeneration: fxml_main.PatchTypeEditor Class Reference
fxml_main.PatchTypeEditor Class Reference
Public Member Functions
PatchTypeEditor (Consumer< Patch > okLambda, PatchTypeData patchTypes)
PatchTypeEditor (Consumer< Patch > okLambda, Patch patch)
void constructor (Consumer< Patch > okLambda)
Protected Member Functions
void initialize ()
Private Member Functions
void initImageLoader (HBox images)
ImageView setImageView ()
void initGoBtn (Button goButton, TextField terrainID, TextField terrainName)
Private Attributes
String myEditorTitle
Consumer< Patch > myOkLambda
Set< String > myIDSet
String myID
String myName
String myImageLocation
Patch myPatch
Static Private Attributes
static final int HEIGHT = 150
static final int WIDTH = 150
static final String CREATOR_TITLE = "Patch Creator"
static final String EDITOR_TITLE = "Patch Editor"
static final String ID_LABEL = "Unique ID"
static final String NAME_LABEL = "Name"
static final String LOADIMAGE_LABEL = "Load Patch Image"
static final String TEMPLATE_LABEL = "OK"
static final String ID_PROMPT = "Enter patch ID..."
static final String NAME_PROMPT = "Enter patch name..."
static final Insets MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10)
static final String LABEL_CSS = "-fx-font-size: 14pt;"
static final String DEFAULT_IMAGE_LOC = "/resources/images/default_image.png"
static final Point2D.Double DEFAULT_LOC = new Point2D.Double(0, 0)
Detailed Description
GUI element used to create new Patch objects and add them to the library. Allows users to specify the name and image of the patch.
Author
Sandy Lee
Definition at line 32 of file PatchTypeEditor.java.
Constructor & Destructor Documentation
fxml_main.PatchTypeEditor.PatchTypeEditor (Consumer< Patch > okLambda, PatchTypeData patchTypes)
Constructor that sets the dimensions of the TerrainCreator GUI component and initializes it. this is for patch CREATOR
Definition at line 66 of file PatchTypeEditor.java.
References fxml_main.PatchTypeEditor.constructor(), fxml_main.PatchTypeEditor.CREATOR_TITLE, fxml_main.PatchTypeEditor.DEFAULT_IMAGE_LOC, and authoring.data.PatchTypeData.getIdSet().
fxml_main.PatchTypeEditor.PatchTypeEditor (Consumer< Patch > okLambda, Patch patch)
Constructor that sets the dimensions of the TerrainCreator GUI component and initializes it. this is for patch EDITOR
Definition at line 80 of file PatchTypeEditor.java.
References fxml_main.PatchTypeEditor.constructor(), fxml_main.PatchTypeEditor.EDITOR_TITLE, gamedata.gamecomponents.GridComponent.getID(), gamedata.gamecomponents.GridComponent.getImageLocation(), and gamedata.gamecomponents.GridComponent.getName().
Member Function Documentation
void fxml_main.PatchTypeEditor.constructor (Consumer< Patch > okLambda)
Definition at line 90 of file PatchTypeEditor.java.
References fxml_main.PatchTypeEditor.initialize().
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor().
void fxml_main.PatchTypeEditor.initGoBtn (Button goButton, TextField terrainID, TextField terrainName) private
initializes the go button
Parameters
goButton
terrainName
Definition at line 189 of file PatchTypeEditor.java.
References fxml_main.PatchTypeEditor.DEFAULT_LOC.
Referenced by fxml_main.PatchTypeEditor.initialize().
void fxml_main.PatchTypeEditor.initialize () protected
Definition at line 97 of file PatchTypeEditor.java.
References authoring_environment.UIspecs.allPadding, fxml_main.PatchTypeEditor.initGoBtn(), fxml_main.PatchTypeEditor.initImageLoader(), and authoring_environment.UIspecs.topRightPadding.
Referenced by fxml_main.PatchTypeEditor.constructor().
void fxml_main.PatchTypeEditor.initImageLoader (HBox images) private
initializes necessary contents for the user to load an img
Parameters
images - HBox
Definition at line 151 of file PatchTypeEditor.java.
References fxml_main.PatchTypeEditor.setImageView().
Referenced by fxml_main.PatchTypeEditor.initialize().
ImageView fxml_main.PatchTypeEditor.setImageView () private
Definition at line 174 of file PatchTypeEditor.java.
Referenced by fxml_main.PatchTypeEditor.initImageLoader().
Member Data Documentation
final String fxml_main.PatchTypeEditor.CREATOR_TITLE = "Patch Creator" static private
Definition at line 36 of file PatchTypeEditor.java.
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor().
final String fxml_main.PatchTypeEditor.DEFAULT_IMAGE_LOC = "/resources/images/default_image.png" static private
Definition at line 47 of file PatchTypeEditor.java.
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor().
final Point2D.Double fxml_main.PatchTypeEditor.DEFAULT_LOC = new Point2D.Double(0, 0) static private
Definition at line 48 of file PatchTypeEditor.java.
Referenced by fxml_main.PatchTypeEditor.initGoBtn().
final String fxml_main.PatchTypeEditor.EDITOR_TITLE = "Patch Editor" static private
Definition at line 37 of file PatchTypeEditor.java.
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor().
final int fxml_main.PatchTypeEditor.HEIGHT = 150 static private
Definition at line 34 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.ID_LABEL = "Unique ID" static private
Definition at line 38 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.ID_PROMPT = "Enter patch ID..." static private
Definition at line 42 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 45 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.LOADIMAGE_LABEL = "Load Patch Image" static private
Definition at line 40 of file PatchTypeEditor.java.
final Insets fxml_main.PatchTypeEditor.MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10) static private
Definition at line 44 of file PatchTypeEditor.java.
String fxml_main.PatchTypeEditor.myEditorTitle private
Definition at line 50 of file PatchTypeEditor.java.
String fxml_main.PatchTypeEditor.myID private
Definition at line 55 of file PatchTypeEditor.java.
Set<String> fxml_main.PatchTypeEditor.myIDSet private
Definition at line 53 of file PatchTypeEditor.java.
String fxml_main.PatchTypeEditor.myImageLocation private
Definition at line 57 of file PatchTypeEditor.java.
String fxml_main.PatchTypeEditor.myName private
Definition at line 56 of file PatchTypeEditor.java.
Consumer<Patch> fxml_main.PatchTypeEditor.myOkLambda private
Definition at line 51 of file PatchTypeEditor.java.
Patch fxml_main.PatchTypeEditor.myPatch private
Definition at line 58 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.NAME_LABEL = "Name" static private
Definition at line 39 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.NAME_PROMPT = "Enter patch name..." static private
Definition at line 43 of file PatchTypeEditor.java.
final String fxml_main.PatchTypeEditor.TEMPLATE_LABEL = "OK" static private
Definition at line 41 of file PatchTypeEditor.java.
final int fxml_main.PatchTypeEditor.WIDTH = 150 static private
Definition at line 35 of file PatchTypeEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PatchTypeEditor.java