voogasalad_VOOGirlsGeneration: authoring.data.PieceTypeData Class Reference
authoring.data.PieceTypeData Class Reference
Public Member Functions
PieceTypeData ()
void add (Piece p)
boolean canAdd (Piece element)
void remove (Piece p)
void replace (Piece origEl, Piece newEl)
List< Piece > getData ()
Set< String > getIdSet ()
boolean containsName (String name)
Public Member Functions inherited from authoring.data.AuthoringData< Piece >
void add (T element)
boolean canAdd (T element)
void remove (T element)
void replace (T origEl, T newEl)
List< T > getData ()
Private Attributes
List< Piece > myPieces
Detailed Description
Definition at line 11 of file PieceTypeData.java.
Constructor & Destructor Documentation
authoring.data.PieceTypeData.PieceTypeData ()
Definition at line 15 of file PieceTypeData.java.
Member Function Documentation
void authoring.data.PieceTypeData.add (Piece p)
Definition at line 20 of file PieceTypeData.java.
Referenced by authoring_environment.LibraryView.addPiece(), fxml_main.PieceController.initGlobalNewBtn(), and authoring.data.PieceTypeData.replace().
boolean authoring.data.PieceTypeData.canAdd (Piece element)
Definition at line 25 of file PieceTypeData.java.
References gamedata.gamecomponents.GridComponent.getID().
boolean authoring.data.PieceTypeData.containsName (String name)
Definition at line 62 of file PieceTypeData.java.
List<Piece> authoring.data.PieceTypeData.getData ()
Definition at line 50 of file PieceTypeData.java.
References authoring.data.PieceTypeData.myPieces.
Referenced by fxml_main.LevelController.globalNewBtnOnClickAction(), and fxml_main.LevelController.initEntryEditBtn().
Set<String> authoring.data.PieceTypeData.getIdSet ()
Definition at line 54 of file PieceTypeData.java.
Referenced by authoring.actionslogic.ActionLogicController.getData(), fxml_main.PieceTypeEditor.PieceTypeEditor(), and authoring_environment.GUIGrid.removePieceType().
void authoring.data.PieceTypeData.remove (Piece p)
Definition at line 35 of file PieceTypeData.java.
Referenced by fxml_main.PieceController.initEntryDelBtn(), and authoring_environment.LibraryView.removePiece().
void authoring.data.PieceTypeData.replace (Piece origEl, Piece newEl)
Definition at line 42 of file PieceTypeData.java.
References authoring.data.PieceTypeData.add().
Referenced by fxml_main.PieceController.initEntryEditBtn().
Member Data Documentation
List<Piece> authoring.data.PieceTypeData.myPieces private
Definition at line 13 of file PieceTypeData.java.
Referenced by authoring.data.PieceTypeData.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/PieceTypeData.java