voogasalad_VOOGirlsGeneration: authoring.data.PatchTypeData Class Reference
authoring.data.PatchTypeData Class Reference
Public Member Functions
PatchTypeData ()
void add (Patch p)
boolean canAdd (Patch element)
void remove (Patch p)
void replace (Patch origEl, Patch newEl)
List< Patch > getData ()
Set< String > getIdSet ()
boolean containsName (String name)
Public Member Functions inherited from authoring.data.AuthoringData< Patch >
void add (T element)
boolean canAdd (T element)
void remove (T element)
void replace (T origEl, T newEl)
List< T > getData ()
Private Attributes
List< Patch > myPatches
Detailed Description
Definition at line 11 of file PatchTypeData.java.
Constructor & Destructor Documentation
authoring.data.PatchTypeData.PatchTypeData ()
Definition at line 15 of file PatchTypeData.java.
Member Function Documentation
void authoring.data.PatchTypeData.add (Patch p)
Definition at line 20 of file PatchTypeData.java.
Referenced by authoring_environment.LibraryView.addPatch(), fxml_main.PatchController.initGlobalNewBtn(), and authoring.data.PatchTypeData.replace().
boolean authoring.data.PatchTypeData.canAdd (Patch element)
Definition at line 25 of file PatchTypeData.java.
References gamedata.gamecomponents.GridComponent.getID().
boolean authoring.data.PatchTypeData.containsName (String name)
Definition at line 62 of file PatchTypeData.java.
List<Patch> authoring.data.PatchTypeData.getData ()
Definition at line 50 of file PatchTypeData.java.
References authoring.data.PatchTypeData.myPatches.
Referenced by fxml_main.LevelController.globalNewBtnOnClickAction(), and fxml_main.LevelController.initEntryEditBtn().
Set<String> authoring.data.PatchTypeData.getIdSet ()
Definition at line 54 of file PatchTypeData.java.
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor(), and authoring_environment.GUIGrid.removePatchType().
void authoring.data.PatchTypeData.remove (Patch p)
Definition at line 35 of file PatchTypeData.java.
Referenced by fxml_main.PatchController.initEntryDelBtn(), and authoring_environment.LibraryView.removePatch().
void authoring.data.PatchTypeData.replace (Patch origEl, Patch newEl)
Definition at line 42 of file PatchTypeData.java.
References authoring.data.PatchTypeData.add().
Referenced by fxml_main.PatchController.initEntryEditBtn().
Member Data Documentation
List<Patch> authoring.data.PatchTypeData.myPatches private
Definition at line 13 of file PatchTypeData.java.
Referenced by authoring.data.PatchTypeData.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/PatchTypeData.java