voogasalad_VOOGirlsGeneration: fxml_main.PatchViewer Class Reference
fxml_main.PatchViewer Class Reference
Public Member Functions
PatchViewer (Patch patch)
Protected Member Functions
void initialize ()
Private Member Functions
void initImageDisplay (HBox images)
ImageView setImageView ()
Private Attributes
String myID
String myName
String myImageLocation
Static Private Attributes
static final int HEIGHT = 150
static final int WIDTH = 150
static final String VIEWER_TITLE = "Patch Viewer"
static final String ID_LABEL = "Unique ID: "
static final String NAME_LABEL = "Name: "
static final Insets MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10)
static final String LABEL_CSS = "-fx-font-size: 14pt;"
Detailed Description
Author
Martin Tamayo
Definition at line 17 of file PatchViewer.java.
Constructor & Destructor Documentation
fxml_main.PatchViewer.PatchViewer (Patch patch)
Definition at line 31 of file PatchViewer.java.
References gamedata.gamecomponents.GridComponent.getID(), gamedata.gamecomponents.GridComponent.getImageLocation(), gamedata.gamecomponents.GridComponent.getName(), and fxml_main.PatchViewer.initialize().
Member Function Documentation
void fxml_main.PatchViewer.initialize () protected
Definition at line 40 of file PatchViewer.java.
References authoring_environment.UIspecs.allPadding, fxml_main.PatchViewer.initImageDisplay(), and authoring_environment.UIspecs.topRightPadding.
Referenced by fxml_main.PatchViewer.PatchViewer().
void fxml_main.PatchViewer.initImageDisplay (HBox images) private
Definition at line 78 of file PatchViewer.java.
References fxml_main.PatchViewer.setImageView().
Referenced by fxml_main.PatchViewer.initialize().
ImageView fxml_main.PatchViewer.setImageView () private
Definition at line 85 of file PatchViewer.java.
Referenced by fxml_main.PatchViewer.initImageDisplay().
Member Data Documentation
final int fxml_main.PatchViewer.HEIGHT = 150 static private
Definition at line 19 of file PatchViewer.java.
final String fxml_main.PatchViewer.ID_LABEL = "Unique ID: " static private
Definition at line 22 of file PatchViewer.java.
final String fxml_main.PatchViewer.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 25 of file PatchViewer.java.
final Insets fxml_main.PatchViewer.MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10) static private
Definition at line 24 of file PatchViewer.java.
String fxml_main.PatchViewer.myID private
Definition at line 27 of file PatchViewer.java.
String fxml_main.PatchViewer.myImageLocation private
Definition at line 29 of file PatchViewer.java.
String fxml_main.PatchViewer.myName private
Definition at line 28 of file PatchViewer.java.
final String fxml_main.PatchViewer.NAME_LABEL = "Name: " static private
Definition at line 23 of file PatchViewer.java.
final String fxml_main.PatchViewer.VIEWER_TITLE = "Patch Viewer" static private
Definition at line 21 of file PatchViewer.java.
final int fxml_main.PatchViewer.WIDTH = 150 static private
Definition at line 20 of file PatchViewer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PatchViewer.java