voogasalad_VOOGirlsGeneration: tests.ViewControllerTest Class Reference
tests.ViewControllerTest Class Reference
Public Member Functions
void updateStatsTest ()
void findPositionTest ()
void updateActionsTest ()
void bindActionTest ()
Detailed Description
Definition at line 25 of file ViewControllerTest.java.
Member Function Documentation
void tests.ViewControllerTest.bindActionTest ()
Definition at line 72 of file ViewControllerTest.java.
References gamePlayer.ViewController.bindAction(), gamePlayer.ViewController.getActiveAction(), and gamedata.action.Action.toString().
void tests.ViewControllerTest.findPositionTest ()
Definition at line 41 of file ViewControllerTest.java.
References gamePlayer.ViewController.findPosition().
void tests.ViewControllerTest.updateActionsTest ()
Definition at line 57 of file ViewControllerTest.java.
References gamePlayer.ViewController.controlPane, and gamePlayer.ViewController.updateActions().
void tests.ViewControllerTest.updateStatsTest ()
Definition at line 29 of file ViewControllerTest.java.
References gamePlayer.ViewController.statsPane, and gamePlayer.ViewController.updateStats().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/tests/ViewControllerTest.java