voogasalad_VOOGirlsGeneration: gamedata.action.StatsModifier Class Reference
gamedata.action.StatsModifier Class Reference abstract
Public Member Functions
String getStatName ()
String getStatRef ()
Protected Member Functions
StatsModifier (String target, String stat)
boolean checkTarget (String targetToCheck)
Protected Attributes
String myStatRef
String myStat
Detailed Description
Super class for stats modifying logic. Removes duplicated methods from StatsSingleMultiplier and StatsTotalLogic.
Author
Jennie Ju
Definition at line 11 of file StatsModifier.java.
Constructor & Destructor Documentation
gamedata.action.StatsModifier.StatsModifier (String target, String stat) protected
Definition at line 15 of file StatsModifier.java.
Member Function Documentation
boolean gamedata.action.StatsModifier.checkTarget (String targetToCheck) protected
Checks whether the target is that named by the parameter
Parameters
targetToCheck - String to check if the target is the actor or the receiver
Returns
boolean of target checking
Definition at line 26 of file StatsModifier.java.
String gamedata.action.StatsModifier.getStatName ()
Returns the name of the stat to be modified
made public so GlobalStatLogicBox can access it
Definition at line 35 of file StatsModifier.java.
References gamedata.action.StatsModifier.myStat.
Referenced by gamedata.action.TotalLogicBox.initStatsModifier(), and gamedata.action.SingleMultiplierBox.setSingleMultiplier().
String gamedata.action.StatsModifier.getStatRef ()
Returns the name of the reference whose stat will be modified (actor or receiver)
Definition at line 43 of file StatsModifier.java.
References gamedata.action.StatsModifier.myStatRef.
Referenced by gamedata.action.TotalLogicBox.initStatsModifier(), and gamedata.action.SingleMultiplierBox.setSingleMultiplier().
Member Data Documentation
String gamedata.action.StatsModifier.myStat protected
Definition at line 13 of file StatsModifier.java.
Referenced by gamedata.action.StatsModifier.getStatName(), gamedata.action.StatsTotalLogic.toString(), and gamedata.action.StatsSingleMultiplier.toString().
String gamedata.action.StatsModifier.myStatRef protected
Definition at line 12 of file StatsModifier.java.
Referenced by gamedata.action.StatsModifier.getStatRef(), gamedata.action.StatsTotalLogic.toString(), and gamedata.action.StatsSingleMultiplier.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/StatsModifier.java