voogasalad_VOOGirlsGeneration: fxml_main.PieceEditor Class Reference
fxml_main.PieceEditor Class Reference
Public Member Functions
PieceEditor (Piece piece, int numPlayers)
void initialize ()
Private Member Functions
void initPlayerChoice (HBox player)
void initStatButton (Button createStatButton)
void showStatEditorWindow ()
ListView< String > initPseudoModList ()
void initImageDisplay (HBox images)
ImageView setImageView ()
Private Attributes
String myID
String myName
String myImageLocation
Piece myPiece
Stats myStats
int myNumPlayers
Static Private Attributes
static final int HEIGHT = 150
static final int WIDTH = 150
static final String EDITOR_TITLE = "Individual Unit Editor"
static final String ACTIONS_LIST = "Actions"
static final String ID_LABEL = "Unique ID: "
static final String NAME_LABEL = "Name: "
static final String PLAYER_LABEL = "Player ID: "
static final String PLAYER_BUTTON = "Set Player"
static final String STAT_CREATE_LABEL = "Add stat"
static final Insets MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10)
static final String LABEL_CSS = "-fx-font-size: 14pt;"
Detailed Description
Author
Martin Tamayo
Definition at line 25 of file PieceEditor.java.
Constructor & Destructor Documentation
fxml_main.PieceEditor.PieceEditor (Piece piece, int numPlayers)
Definition at line 45 of file PieceEditor.java.
References gamedata.gamecomponents.GridComponent.getID(), gamedata.gamecomponents.GridComponent.getImageLocation(), gamedata.gamecomponents.GridComponent.getName(), gamedata.gamecomponents.Piece.getStats(), and fxml_main.PieceEditor.initialize().
Member Function Documentation
void fxml_main.PieceEditor.initialize ()
Definition at line 57 of file PieceEditor.java.
References authoring_environment.UIspecs.allPadding, fxml_main.PieceEditor.initImageDisplay(), fxml_main.PieceEditor.initPlayerChoice(), fxml_main.PieceEditor.initPseudoModList(), fxml_main.PieceEditor.initStatButton(), and authoring_environment.UIspecs.topRightPadding.
Referenced by fxml_main.PieceEditor.PieceEditor().
void fxml_main.PieceEditor.initImageDisplay (HBox images) private
Definition at line 159 of file PieceEditor.java.
References fxml_main.PieceEditor.setImageView().
Referenced by fxml_main.PieceEditor.initialize().
void fxml_main.PieceEditor.initPlayerChoice (HBox player) private
Definition at line 118 of file PieceEditor.java.
References gamedata.gamecomponents.Piece.getPlayerID(), fxml_main.PieceEditor.myNumPlayers, gamedata.gamecomponents.Piece.setPlayerID(), and authoring_environment.UIspecs.topRightPadding.
Referenced by fxml_main.PieceEditor.initialize().
ListView<String> fxml_main.PieceEditor.initPseudoModList () private
Definition at line 151 of file PieceEditor.java.
Referenced by fxml_main.PieceEditor.initialize().
void fxml_main.PieceEditor.initStatButton (Button createStatButton) private
Definition at line 137 of file PieceEditor.java.
References fxml_main.PieceEditor.showStatEditorWindow().
Referenced by fxml_main.PieceEditor.initialize().
ImageView fxml_main.PieceEditor.setImageView () private
Definition at line 166 of file PieceEditor.java.
Referenced by fxml_main.PieceEditor.initImageDisplay().
void fxml_main.PieceEditor.showStatEditorWindow () private
Definition at line 146 of file PieceEditor.java.
Referenced by fxml_main.PieceEditor.initStatButton().
Member Data Documentation
final String fxml_main.PieceEditor.ACTIONS_LIST = "Actions" static private
Definition at line 29 of file PieceEditor.java.
final String fxml_main.PieceEditor.EDITOR_TITLE = "Individual Unit Editor" static private
Definition at line 28 of file PieceEditor.java.
final int fxml_main.PieceEditor.HEIGHT = 150 static private
Definition at line 26 of file PieceEditor.java.
final String fxml_main.PieceEditor.ID_LABEL = "Unique ID: " static private
Definition at line 30 of file PieceEditor.java.
final String fxml_main.PieceEditor.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 36 of file PieceEditor.java.
final Insets fxml_main.PieceEditor.MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10) static private
Definition at line 35 of file PieceEditor.java.
String fxml_main.PieceEditor.myID private
Definition at line 38 of file PieceEditor.java.
String fxml_main.PieceEditor.myImageLocation private
Definition at line 40 of file PieceEditor.java.
String fxml_main.PieceEditor.myName private
Definition at line 39 of file PieceEditor.java.
int fxml_main.PieceEditor.myNumPlayers private
Definition at line 43 of file PieceEditor.java.
Referenced by fxml_main.PieceEditor.initPlayerChoice().
Piece fxml_main.PieceEditor.myPiece private
Definition at line 41 of file PieceEditor.java.
Stats fxml_main.PieceEditor.myStats private
Definition at line 42 of file PieceEditor.java.
final String fxml_main.PieceEditor.NAME_LABEL = "Name: " static private
Definition at line 31 of file PieceEditor.java.
final String fxml_main.PieceEditor.PLAYER_BUTTON = "Set Player" static private
Definition at line 33 of file PieceEditor.java.
final String fxml_main.PieceEditor.PLAYER_LABEL = "Player ID: " static private
Definition at line 32 of file PieceEditor.java.
final String fxml_main.PieceEditor.STAT_CREATE_LABEL = "Add stat" static private
Definition at line 34 of file PieceEditor.java.
final int fxml_main.PieceEditor.WIDTH = 150 static private
Definition at line 27 of file PieceEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PieceEditor.java