voogasalad_VOOGirlsGeneration: fxml_main.ActionEditor Class Reference
fxml_main.ActionEditor Class Reference
Public Member Functions
ActionEditor (Consumer< ConcreteAction > okLambda, String gridShape)
ActionEditor (Consumer< ConcreteAction > okLambda, ConcreteAction action, String gridShape)
Protected Member Functions
void initEditor (Consumer< ConcreteAction > okLambda, String gridShape)
Private Member Functions
void initNameField (VBox nameBox, TextField nameField)
void initSetRangeButton (VBox rangeBox, String label, List< Point2D.Double > range)
void initConclusionsBox (VBox conclusionVBox, ChoiceBox< ActionConclusion > choiceBox)
List< String > trimClassList (List< String > conclusionNames)
Private Attributes
String mySceneTitle
String myName
List< Point2D.Double > myAttackRange
List< Point2D.Double > myEffectRange
List< StatsTotalLogic > myStatsLogics
ActionConclusion myConclusion
Consumer< ConcreteAction > myOkLambda
String myGridShape
Static Private Attributes
static final int HEIGHT = 100
static final int WIDTH = 100
static final String STYLESHEET = "/resources/stylesheets/actioncreator_layout.css"
static final Insets MARGINS = new Insets(20, WIDTH / 8, 20, WIDTH / 8 - 10)
static final String LABEL_CSS = "-fx-font-size: 12pt;"
static final String CONCLUSION_LABEL = "Choose action conclusion"
Detailed Description
Author
seungwonlee, Jennie Ju
Definition at line 42 of file ActionEditor.java.
Constructor & Destructor Documentation
fxml_main.ActionEditor.ActionEditor (Consumer< ConcreteAction > okLambda, String gridShape)
Definition at line 63 of file ActionEditor.java.
References fxml_main.ActionEditor.initEditor(), fxml_main.ActionEditor.myAttackRange, and fxml_main.ActionEditor.myEffectRange.
fxml_main.ActionEditor.ActionEditor (Consumer< ConcreteAction > okLambda, ConcreteAction action, String gridShape)
Constructor for an ActionCreator popup window
Parameters
actionData
class where user-created Actions are stored
Definition at line 80 of file ActionEditor.java.
References gamedata.action.ConcreteAction.getActionRange(), gamedata.action.ConcreteAction.getConclusion(), gamedata.action.ConcreteAction.getEffectRange(), gamedata.action.ConcreteAction.getName(), gamedata.action.ConcreteAction.getStatsLogics(), fxml_main.ActionEditor.initEditor(), fxml_main.ActionEditor.myAttackRange, and fxml_main.ActionEditor.myEffectRange.
Member Function Documentation
void fxml_main.ActionEditor.initConclusionsBox (VBox conclusionVBox, ChoiceBox< ActionConclusion > choiceBox) private
Definition at line 181 of file ActionEditor.java.
References utilities.Reflection.createInstance(), utilities.ClassGrabber.getClassNames(), gamedata.action.ActionConclusion.toString(), and fxml_main.ActionEditor.trimClassList().
Referenced by fxml_main.ActionEditor.initEditor().
void fxml_main.ActionEditor.initEditor (Consumer< ConcreteAction > okLambda, String gridShape) protected
Definition at line 90 of file ActionEditor.java.
References gamedata.action.ActionStatsEditor.getStatsTotalLogics(), fxml_main.ActionEditor.initConclusionsBox(), fxml_main.ActionEditor.initNameField(), fxml_main.ActionEditor.initSetRangeButton(), fxml_main.ActionEditor.myAttackRange, and fxml_main.ActionEditor.myEffectRange.
Referenced by fxml_main.ActionEditor.ActionEditor().
void fxml_main.ActionEditor.initNameField (VBox nameBox, TextField nameField) private
Definition at line 153 of file ActionEditor.java.
Referenced by fxml_main.ActionEditor.initEditor().
void fxml_main.ActionEditor.initSetRangeButton (VBox rangeBox, String label, List< Point2D.Double > range) private
Definition at line 160 of file ActionEditor.java.
Referenced by fxml_main.ActionEditor.initEditor().
List<String> fxml_main.ActionEditor.trimClassList (List< String > conclusionNames) private
Definition at line 203 of file ActionEditor.java.
Referenced by fxml_main.ActionEditor.initConclusionsBox().
Member Data Documentation
final String fxml_main.ActionEditor.CONCLUSION_LABEL = "Choose action conclusion" static private
Definition at line 50 of file ActionEditor.java.
final int fxml_main.ActionEditor.HEIGHT = 100 static private
Definition at line 44 of file ActionEditor.java.
final String fxml_main.ActionEditor.LABEL_CSS = "-fx-font-size: 12pt;" static private
Definition at line 49 of file ActionEditor.java.
final Insets fxml_main.ActionEditor.MARGINS = new Insets(20, WIDTH / 8, 20, WIDTH / 8 - 10) static private
Definition at line 48 of file ActionEditor.java.
List<Point2D.Double> fxml_main.ActionEditor.myAttackRange private
Definition at line 55 of file ActionEditor.java.
Referenced by fxml_main.ActionEditor.ActionEditor(), and fxml_main.ActionEditor.initEditor().
ActionConclusion fxml_main.ActionEditor.myConclusion private
Definition at line 58 of file ActionEditor.java.
List<Point2D.Double> fxml_main.ActionEditor.myEffectRange private
Definition at line 56 of file ActionEditor.java.
Referenced by fxml_main.ActionEditor.ActionEditor(), and fxml_main.ActionEditor.initEditor().
String fxml_main.ActionEditor.myGridShape private
Definition at line 61 of file ActionEditor.java.
String fxml_main.ActionEditor.myName private
Definition at line 54 of file ActionEditor.java.
Consumer<ConcreteAction> fxml_main.ActionEditor.myOkLambda private
Definition at line 60 of file ActionEditor.java.
String fxml_main.ActionEditor.mySceneTitle private
Definition at line 52 of file ActionEditor.java.
List<StatsTotalLogic> fxml_main.ActionEditor.myStatsLogics private
Definition at line 57 of file ActionEditor.java.
final String fxml_main.ActionEditor.STYLESHEET = "/resources/stylesheets/actioncreator_layout.css" static private
Definition at line 47 of file ActionEditor.java.
final int fxml_main.ActionEditor.WIDTH = 100 static private
Definition at line 45 of file ActionEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/ActionEditor.java