voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.Piece Class Reference
gamedata.gamecomponents.Piece Class Reference
Public Member Functions
Piece (String id, String name, String imageLoc, Movement movement, List< Action > actions, Stats stats, Point2D.Double loc, int playerID, boolean hasInventory, boolean isItem)
Piece (Piece clone, Point2D.Double placeHere)
int getPlayerID ()
Stats getStats ()
Movement getMovement ()
void addAction (Action a)
void removeAction (Action a)
List< Action > getActions ()
List< String > getActionNames ()
void markForRemoval ()
boolean shouldRemove ()
boolean addToInventory (Piece item)
void removeFromInventory (Piece item)
Inventory getInventory ()
Object getUniqueID ()
void setPlayerID (int id)
boolean hasInventory ()
boolean isItem ()
List< Action > getOriginalActions ()
String printString ()
Public Member Functions inherited from gamedata.gamecomponents.GridComponent
GridComponent (String id, String name, String imageLocation, Point2D.Double point)
GridComponent (GridComponent clone, Point2D.Double placeHere)
String getID ()
void setName (String name)
Point2D.Double getLoc ()
void setLoc (Point2D.Double loc)
String getImageLocation ()
String getName ()
void setImageLocation (String imageLocation)
ImageView getImageView ()
String toString ()
Private Member Functions
boolean inventoryValid (Piece item)
Private Attributes
Movement myMovement
List< Action > myActions
Stats myStats
int myPlayerID
boolean myShouldRemove
Inventory myInventory
boolean myHasInventory
boolean myIsItem
Additional Inherited Members
Protected Attributes inherited from gamedata.gamecomponents.GridComponent
String myID
String myName
Point2D.Double myLoc
String myImageLocation
transient ImageView myImageView
Detailed Description
Class for pieces. Pieces are the primary unit for game play. They have movement and can carry out various actions during the game.
Authors
Sandy Lee, Jesse Ling, Jennie Ju, Martin Tamayo
Definition at line 18 of file Piece.java.
Constructor & Destructor Documentation
gamedata.gamecomponents.Piece.Piece (String id, String name, String imageLoc, Movement movement, List< Action > actions, Stats stats, Point2D.Double loc, int playerID, boolean hasInventory, boolean isItem)
Piece constructor
Parameters
id
Unique string ID for the piece or patch.
imageLoc
url of the piece's image location
movement
List of Movement defining how/where the piece moves relative to its current position
actions
List of Actions defining what actions are available for each piece to perform
stats
the Piece's stats, already defined
loc
Point2D containing the piece's current coordinates
playerID
Piece's player ID, serves as a reference to which player this piece belongs to
hasInventory TODO
isItem TODO
tid
Piece's type ID, serves as a reference to this type of piece
uid
Piece's unique ID, serves as a reference to this specific instance of piece
Definition at line 90 of file Piece.java.
References gamedata.gamecomponents.Piece.hasInventory(), and gamedata.gamecomponents.Piece.isItem().
gamedata.gamecomponents.Piece.Piece (Piece clone, Point2D.Double placeHere)
Cloning constructor for deep cloning of a piece
Parameters
clone
Piece instance to be cloned
Definition at line 109 of file Piece.java.
References gamedata.gamecomponents.Piece.myActions, gamedata.gamecomponents.Piece.myHasInventory, gamedata.gamecomponents.Piece.myInventory, gamedata.gamecomponents.Piece.myIsItem, gamedata.gamecomponents.Piece.myMovement, gamedata.gamecomponents.Piece.myPlayerID, and gamedata.gamecomponents.Piece.myStats.
Member Function Documentation
void gamedata.gamecomponents.Piece.addAction (Action a)
Adds an Action to the piece's list of Actions
Definition at line 145 of file Piece.java.
Referenced by authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor().
boolean gamedata.gamecomponents.Piece.addToInventory (Piece item)
Adds an item to the inventory as long as there is an inventory and the item added is not the piece holding the inventory.
Parameters
item
piece to be added to inventory
Returns
boolean stating whether item was added
Definition at line 211 of file Piece.java.
References gamedata.gamecomponents.Inventory.addItem(), and gamedata.gamecomponents.Piece.inventoryValid().
Referenced by gamedata.action.conclusions.ReceiverToInventoryConclusion.runConclusion().
List<String> gamedata.gamecomponents.Piece.getActionNames ()
Returns a list of Strings containing the name of the Actions contained in the piece for display purposes in the Game Player
Returns
List<String> of Action Names
Definition at line 178 of file Piece.java.
List<Action> gamedata.gamecomponents.Piece.getActions ()
Returns the list of the piece's available actions. Takes into account inventory if relevant
Returns
List of available actions
Definition at line 164 of file Piece.java.
References gamedata.gamecomponents.Inventory.getItemActions(), and gamedata.gamecomponents.Piece.myActions.
Referenced by authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor(), gamePlayer.KeyboardAction.setActionKeyControl(), tests.JSONTesterMain.testJSONwrite(), and gamePlayer.ViewController.updateActions().
Inventory gamedata.gamecomponents.Piece.getInventory ()
Returns the inventory that the piece contains
Returns
Inventory of the Piece
Definition at line 243 of file Piece.java.
References gamedata.gamecomponents.Piece.myInventory.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor(), tests.JSONTesterMain.testJSONwrite(), and gamePlayer.ViewController.updateInventory().
Movement gamedata.gamecomponents.Piece.getMovement ()
Getter method for unit's Movement
Definition at line 138 of file Piece.java.
References gamedata.gamecomponents.Piece.myMovement.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor(), and tests.JSONTesterMain.testJSONwrite().
List<Action> gamedata.gamecomponents.Piece.getOriginalActions ()
Returns the original actions contained in the piece (without
Returns
Definition at line 287 of file Piece.java.
References gamedata.gamecomponents.Piece.myActions.
Referenced by fxml_main.PieceTypeEditor.PieceTypeEditor().
int gamedata.gamecomponents.Piece.getPlayerID ()
Returns the int ID for the player controlling this piece
Definition at line 124 of file Piece.java.
References gamedata.gamecomponents.Piece.myPlayerID.
Referenced by gamedata.rules.CanAttackRule.conditionsMet(), fxml_main.PieceEditor.initPlayerChoice(), gamePlayer.SelectState.onClick(), and fxml_main.PieceTypeEditor.PieceTypeEditor().
Stats gamedata.gamecomponents.Piece.getStats ()
Returns the piece's stats
Implements gamedata.gamecomponents.IHasStats.
Definition at line 131 of file Piece.java.
References gamedata.gamecomponents.Piece.myStats.
Referenced by authoring.concretefeatures.IndividualUnitEditor.initialize(), authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor(), fxml_main.PieceEditor.PieceEditor(), fxml_main.PieceTypeEditor.PieceTypeEditor(), tests.JSONTesterMain.testJSONwrite(), and gamePlayer.ViewController.updateStats().
Object gamedata.gamecomponents.Piece.getUniqueID ()
returns a uniqueID identifier
Returns
Definition at line 252 of file Piece.java.
References gamedata.gamecomponents.GridComponent.myName.
boolean gamedata.gamecomponents.Piece.hasInventory ()
Returns whether the piece is able to use an inventory
Returns
boolean stating if the piece has an inventory
Definition at line 270 of file Piece.java.
References gamedata.gamecomponents.Piece.myHasInventory.
Referenced by gamedata.gamecomponents.Piece.Piece(), and fxml_main.PieceTypeEditor.PieceTypeEditor().
boolean gamedata.gamecomponents.Piece.inventoryValid (Piece item) private
Definition at line 234 of file Piece.java.
References gamedata.gamecomponents.Piece.isItem().
Referenced by gamedata.gamecomponents.Piece.addToInventory(), and gamedata.gamecomponents.Piece.removeFromInventory().
boolean gamedata.gamecomponents.Piece.isItem ()
Returns whether the piece is an item (can be added to inventory)
Returns
boolean stating if the piece is an item
Definition at line 278 of file Piece.java.
References gamedata.gamecomponents.Piece.myIsItem.
Referenced by gamedata.gamecomponents.Piece.inventoryValid(), gamedata.gamecomponents.Piece.Piece(), and fxml_main.PieceTypeEditor.PieceTypeEditor().
void gamedata.gamecomponents.Piece.markForRemoval ()
Marks the myShouldRemove boolean to true to flag for piece removal from board
Definition at line 190 of file Piece.java.
Referenced by gamedata.action.conclusions.ActorRemovalConclusion.runConclusion().
String gamedata.gamecomponents.Piece.printString ()
Definition at line 291 of file Piece.java.
References gamedata.gamecomponents.GridComponent.myID, gamedata.gamecomponents.GridComponent.myImageLocation, gamedata.gamecomponents.GridComponent.myLoc, gamedata.gamecomponents.GridComponent.myName, and gameengine.movement.Movement.toString().
void gamedata.gamecomponents.Piece.removeAction (Action a)
Removes an Action from the piece's list of Actions
Definition at line 154 of file Piece.java.
void gamedata.gamecomponents.Piece.removeFromInventory (Piece item)
Removes an item from the inventory as long as there is an inventory and the item added is not the piece holding the inventory.
Parameters
item
piece to be removed from the inventory
Definition at line 228 of file Piece.java.
References gamedata.gamecomponents.Piece.inventoryValid(), and gamedata.gamecomponents.Inventory.removeItem().
void gamedata.gamecomponents.Piece.setPlayerID (int id)
Setter to set the player ID who owns the piece
Parameters
id int representing player ID
Definition at line 262 of file Piece.java.
Referenced by tests.TestGameCreator.createNewGrid(), gamedata.events.globalaction.MakePieceAtLocation.doBehavior(), and fxml_main.PieceEditor.initPlayerChoice().
boolean gamedata.gamecomponents.Piece.shouldRemove ()
Checks if the piece should be removed
Returns
boolean for whether or not the piece should be removed
Definition at line 199 of file Piece.java.
References gamedata.gamecomponents.Piece.myShouldRemove.
Member Data Documentation
List<Action> gamedata.gamecomponents.Piece.myActions private
List containing the Actions a piece can execute
Definition at line 28 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.getActions(), gamedata.gamecomponents.Piece.getOriginalActions(), and gamedata.gamecomponents.Piece.Piece().
boolean gamedata.gamecomponents.Piece.myHasInventory private
Boolean stating whether the piece has an inventory
Definition at line 53 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.hasInventory(), and gamedata.gamecomponents.Piece.Piece().
Inventory gamedata.gamecomponents.Piece.myInventory private
Inventory of item pieces that add extra actions to a piece
Definition at line 48 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.getInventory(), and gamedata.gamecomponents.Piece.Piece().
boolean gamedata.gamecomponents.Piece.myIsItem private
Boolean stating whether the piece is an item (can be added into an inventory)
Definition at line 59 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.isItem(), and gamedata.gamecomponents.Piece.Piece().
Movement gamedata.gamecomponents.Piece.myMovement private
The unit's movement range.
Definition at line 23 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.getMovement(), and gamedata.gamecomponents.Piece.Piece().
int gamedata.gamecomponents.Piece.myPlayerID private
ID of the player whom owns the piece
Definition at line 38 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.getPlayerID(), and gamedata.gamecomponents.Piece.Piece().
boolean gamedata.gamecomponents.Piece.myShouldRemove private
Tag for garbage collection to remove the piece
Definition at line 43 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.shouldRemove().
Stats gamedata.gamecomponents.Piece.myStats private
Contains the stats for a piece
Definition at line 33 of file Piece.java.
Referenced by gamedata.gamecomponents.Piece.getStats(), and gamedata.gamecomponents.Piece.Piece().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/Piece.java