voogasalad_VOOGirlsGeneration: authoring.concretefeatures.LibraryUnitEditor Class Reference
authoring.concretefeatures.LibraryUnitEditor Class Reference
Public Member Functions
LibraryUnitEditor (Piece unit, ActionData availableActions)
Protected Member Functions
List< Action > addSelectedActions (List< String > selected)
Private Attributes
final String NAME = "Unit Editor"
final String UNIT_NAME_LABEL = "Name"
final String IMAGE_LABEL = "Unit image"
final String LOAD_IMAGE_LABEL = "Load image"
final String TEMPLATE_LABEL = "Update unit"
final String DELETE = "Delete"
final String EDIT = "Edit"
Piece myUnit
Stats myStats
List< Action > myActions
ActionData myAvailableActions
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Author
Martin Tamayo, Jennie Ju
GUI component for editing the stats of a given unit. This can be accessed by clicking on the hyperlink of the unit's name in the LibraryView of the game authoring environment.
Definition at line 28 of file LibraryUnitEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor (Piece unit, ActionData availableActions)
Constructor that sets the dimensions of the UnitEditor GUI component and initializes it.
Parameters
unit : Piece class of the unit to edit.
myAvailableActions
Definition at line 53 of file LibraryUnitEditor.java.
References gamedata.gamecomponents.Piece.addAction(), authoring.concretefeatures.LibraryUnitEditor.addSelectedActions(), authoring.data.ActionData.getActionNames(), gamedata.gamecomponents.Piece.getActions(), authoring.createedit.ModulesList.getSelectedActions(), and gamedata.gamecomponents.Piece.getStats().
Member Function Documentation
List<Action> authoring.concretefeatures.LibraryUnitEditor.addSelectedActions (List< String > selected) protected
Definition at line 102 of file LibraryUnitEditor.java.
References authoring.data.ActionData.getAction().
Referenced by authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor().
Member Data Documentation
final String authoring.concretefeatures.LibraryUnitEditor.DELETE = "Delete" private
Definition at line 36 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.EDIT = "Edit" private
Definition at line 37 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.IMAGE_LABEL = "Unit image" private
Definition at line 33 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.LOAD_IMAGE_LABEL = "Load image" private
Definition at line 34 of file LibraryUnitEditor.java.
List<Action> authoring.concretefeatures.LibraryUnitEditor.myActions private
Definition at line 42 of file LibraryUnitEditor.java.
ActionData authoring.concretefeatures.LibraryUnitEditor.myAvailableActions private
Definition at line 44 of file LibraryUnitEditor.java.
Stats authoring.concretefeatures.LibraryUnitEditor.myStats private
Definition at line 41 of file LibraryUnitEditor.java.
Piece authoring.concretefeatures.LibraryUnitEditor.myUnit private
Definition at line 39 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.NAME = "Unit Editor" private
Definition at line 31 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 30 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.TEMPLATE_LABEL = "Update unit" private
Definition at line 35 of file LibraryUnitEditor.java.
final String authoring.concretefeatures.LibraryUnitEditor.UNIT_NAME_LABEL = "Name" private
Definition at line 32 of file LibraryUnitEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/LibraryUnitEditor.java