voogasalad_VOOGirlsGeneration: authoring.data.PatchInstanceData Class Reference
authoring.data.PatchInstanceData Class Reference
Public Member Functions
PatchInstanceData ()
PatchInstanceData (List< Patch > patches)
void add (Patch p)
boolean canAdd (Patch element)
void remove (Patch p)
void replace (Patch origEl, Patch newEl)
List< Patch > getData ()
List< Point2D.Double > replace (Patch patchType)
List< Point2D.Double > removeUnknown (Set< String > idSet)
void removePatchAtLoc (Point2D.Double location)
boolean terrainAtLoc (Patch terrain, int x, int y)
Public Member Functions inherited from authoring.data.AuthoringData< Patch >
void add (T element)
boolean canAdd (T element)
void remove (T element)
void replace (T origEl, T newEl)
List< T > getData ()
Private Attributes
List< Patch > myPatches
Detailed Description
Class for storing the patches created by the user Stored in the authoring environment
Author
Sandy Lee
Definition at line 17 of file PatchInstanceData.java.
Constructor & Destructor Documentation
authoring.data.PatchInstanceData.PatchInstanceData ()
Constructor for new PatchData, initializes empty list of Patch
Definition at line 25 of file PatchInstanceData.java.
authoring.data.PatchInstanceData.PatchInstanceData (List< Patch > patches)
Constructor for patch from game data, aka with already existent data
Parameters
patches
Definition at line 33 of file PatchInstanceData.java.
Member Function Documentation
void authoring.data.PatchInstanceData.add (Patch p)
Definition at line 38 of file PatchInstanceData.java.
References gamedata.gamecomponents.GridComponent.getLoc(), and authoring.data.PatchInstanceData.removePatchAtLoc().
Referenced by authoring_environment.GUIGrid.addPatchAtLoc(), and authoring_environment.ShapeGrid.addTerrain().
boolean authoring.data.PatchInstanceData.canAdd (Patch element)
Definition at line 44 of file PatchInstanceData.java.
References gamedata.gamecomponents.GridComponent.getID(), and gamedata.gamecomponents.GridComponent.getLoc().
List<Patch> authoring.data.PatchInstanceData.getData ()
Definition at line 69 of file PatchInstanceData.java.
References authoring.data.PatchInstanceData.myPatches.
Referenced by authoring_environment.GUIGrid.getPatch(), authoring_environment.GUIGrid.isPatchOccupied(), authoring_environment.GUIGrid.removeRunOffData(), authoring_environment.GUIGrid.repopulate(), authoring_environment.GUIGrid.repopulateGrid(), authoring_environment.GUIGrid.runEvents(), and authoring_environment.GUIGrid.toString().
void authoring.data.PatchInstanceData.remove (Patch p)
Definition at line 58 of file PatchInstanceData.java.
Referenced by authoring_environment.GUIGrid.removePatch(), and authoring_environment.ShapeGrid.removeTerrain().
void authoring.data.PatchInstanceData.removePatchAtLoc (Point2D.Double location)
Definition at line 98 of file PatchInstanceData.java.
Referenced by authoring.data.PatchInstanceData.add(), and authoring_environment.ShapeGrid.addTerrain().
List<Point2D.Double> authoring.data.PatchInstanceData.removeUnknown (Set< String > idSet)
Definition at line 84 of file PatchInstanceData.java.
Referenced by authoring_environment.GUIGrid.removePatchType().
void authoring.data.PatchInstanceData.replace (Patch origEl, Patch newEl)
Definition at line 63 of file PatchInstanceData.java.
References gamedata.gamecomponents.GridComponent.getImageLocation(), gamedata.gamecomponents.GridComponent.setImageLocation(), gamedata.gamecomponents.GridComponent.setName(), and gamedata.gamecomponents.Patch.toString().
Referenced by authoring.data.PatchInstanceData.replace(), and authoring_environment.GUIGrid.replacePatchType().
List<Point2D.Double> authoring.data.PatchInstanceData.replace (Patch patchType)
Definition at line 73 of file PatchInstanceData.java.
References gamedata.gamecomponents.GridComponent.getID(), and authoring.data.PatchInstanceData.replace().
boolean authoring.data.PatchInstanceData.terrainAtLoc (Patch terrain, int x, int y)
Definition at line 108 of file PatchInstanceData.java.
References gamedata.gamecomponents.Patch.toString().
Referenced by authoring_environment.ShapeGrid.removePatches().
Member Data Documentation
List<Patch> authoring.data.PatchInstanceData.myPatches private
Definition at line 19 of file PatchInstanceData.java.
Referenced by authoring.data.PatchInstanceData.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/PatchInstanceData.java