voogasalad_VOOGirlsGeneration: authoring.data.PieceInstanceData Class Reference
authoring.data.PieceInstanceData Class Reference
Public Member Functions
PieceInstanceData ()
PieceInstanceData (List< Piece > pieces)
void add (Piece p)
boolean canAdd (Piece element)
void remove (Piece p)
void replace (Piece origEl, Piece newEl)
List< Piece > getData ()
List< Point2D.Double > replace (Piece pieceType)
List< Point2D.Double > removeUnknown (Set< String > idSet)
void removePieceAtLoc (Point2D.Double location)
boolean unitAtLoc (Piece unit, int x, int y)
Public Member Functions inherited from authoring.data.AuthoringData< Piece >
void add (T element)
boolean canAdd (T element)
void remove (T element)
void replace (T origEl, T newEl)
List< T > getData ()
Private Attributes
List< Piece > myPieces
Detailed Description
Class for storing the each type of piece created by the user. Stored in the game authoring environment.
Author
Martin Tamayo
Definition at line 17 of file PieceInstanceData.java.
Constructor & Destructor Documentation
authoring.data.PieceInstanceData.PieceInstanceData ()
Constructor for new PieceData, initializes empty list of Pieces.
Definition at line 25 of file PieceInstanceData.java.
authoring.data.PieceInstanceData.PieceInstanceData (List< Piece > pieces)
Constructor for piece from already existent data, aka for game data
Parameters
pieces
Definition at line 33 of file PieceInstanceData.java.
Member Function Documentation
void authoring.data.PieceInstanceData.add (Piece p)
Definition at line 38 of file PieceInstanceData.java.
Referenced by authoring_environment.GUIGrid.addPieceAtLoc(), authoring_environment.ShapeGrid.addUnit(), authoring.data.PieceInstanceData.replace(), and tests.JSONTesterMain.testJSONwrite().
boolean authoring.data.PieceInstanceData.canAdd (Piece element)
Definition at line 44 of file PieceInstanceData.java.
References gamedata.gamecomponents.GridComponent.getID(), and gamedata.gamecomponents.GridComponent.getLoc().
List<Piece> authoring.data.PieceInstanceData.getData ()
Definition at line 69 of file PieceInstanceData.java.
References authoring.data.PieceInstanceData.myPieces.
Referenced by authoring_environment.GUIGrid.getPiece(), authoring_environment.GUIGrid.getPlayerPieces(), authoring_environment.GUIGrid.getRemovedPieces(), authoring_environment.GUIGrid.isPieceOccupied(), authoring_environment.GUIGrid.removeRunOffData(), authoring_environment.GUIGrid.repopulate(), authoring_environment.GUIGrid.repopulateGrid(), authoring_environment.GUIGrid.runEvents(), and authoring_environment.GUIGrid.toString().
void authoring.data.PieceInstanceData.remove (Piece p)
Definition at line 58 of file PieceInstanceData.java.
Referenced by authoring_environment.GUIGrid.removePiece(), and authoring_environment.ShapeGrid.removeUnit().
void authoring.data.PieceInstanceData.removePieceAtLoc (Point2D.Double location)
Definition at line 98 of file PieceInstanceData.java.
List<Point2D.Double> authoring.data.PieceInstanceData.removeUnknown (Set< String > idSet)
Definition at line 84 of file PieceInstanceData.java.
Referenced by authoring_environment.GUIGrid.removePieceType().
void authoring.data.PieceInstanceData.replace (Piece origEl, Piece newEl)
Definition at line 63 of file PieceInstanceData.java.
References authoring.data.PieceInstanceData.add(), and gamedata.gamecomponents.GridComponent.getLoc().
Referenced by authoring.data.PieceInstanceData.replace(), and authoring_environment.GUIGrid.replacePieceType().
List<Point2D.Double> authoring.data.PieceInstanceData.replace (Piece pieceType)
Definition at line 73 of file PieceInstanceData.java.
References gamedata.gamecomponents.GridComponent.getID(), and authoring.data.PieceInstanceData.replace().
boolean authoring.data.PieceInstanceData.unitAtLoc (Piece unit, int x, int y)
Definition at line 108 of file PieceInstanceData.java.
References gamedata.gamecomponents.GridComponent.toString().
Referenced by authoring_environment.ShapeGrid.removePieces().
Member Data Documentation
List<Piece> authoring.data.PieceInstanceData.myPieces private
Definition at line 19 of file PieceInstanceData.java.
Referenced by authoring.data.PieceInstanceData.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/PieceInstanceData.java