voogasalad_VOOGirlsGeneration: gamePlayer.ApplyState Class Reference
gamePlayer.ApplyState Class Reference
Public Member Functions
ApplyState (ViewController controller)
void onClick (Piece piece)
Private Member Functions
void handleMouseMove (MouseEvent event)
Private Attributes
ViewController myController
GameGridEffect myGameGridEffect
SuperTile activeTile
Detailed Description
Class representing the state of the grid when a particular action has been selected and is ready to be applied on the grid
Author
Eric, Yiran, Yoon, Rica, Jesse
Definition at line 19 of file ApplyState.java.
Constructor & Destructor Documentation
gamePlayer.ApplyState.ApplyState (ViewController controller)
Definition at line 25 of file ApplyState.java.
References gamePlayer.ViewController.getGameGridEffect(), gamePlayer.ViewController.getGridPane(), and gamePlayer.ApplyState.handleMouseMove().
Member Function Documentation
void gamePlayer.ApplyState.handleMouseMove (MouseEvent event) private
When the mouse of moved, it will find a new effect range to highlight relative to the current location
Parameters
event
Definition at line 38 of file ApplyState.java.
References authoring_environment.SuperGrid.findClickedTile(), gamePlayer.ViewController.getGrid(), and gamePlayer.GameGridEffect.isHoveringOverActionHighlight().
Referenced by gamePlayer.ApplyState.ApplyState().
void gamePlayer.ApplyState.onClick (Piece piece)
Implements gamePlayer.IGridState.
Definition at line 50 of file ApplyState.java.
References gamePlayer.ViewController.clearActions(), gamePlayer.GameGridEffect.clearAllActionHighlights(), gamePlayer.GameGridEffect.clearAllPieceHighlights(), gamedata.action.Action.doBehavior(), gamePlayer.ViewController.endAction(), gamedata.action.Action.getAbsoluteActionRange(), gamePlayer.ViewController.getActiveAction(), gamePlayer.ViewController.getActivePiece(), gamePlayer.ViewController.getCurrentClick(), gamePlayer.ViewController.getGrid(), gamedata.gamecomponents.GridComponent.getLoc(), gamedata.action.Action.getName(), gamePlayer.ViewController.setActiveAction(), gamePlayer.ViewController.setActivePiece(), gamePlayer.ViewController.setGridState(), and gamedata.gamecomponents.GridComponent.setLoc().
Member Data Documentation
SuperTile gamePlayer.ApplyState.activeTile private
Definition at line 23 of file ApplyState.java.
ViewController gamePlayer.ApplyState.myController private
Definition at line 21 of file ApplyState.java.
GameGridEffect gamePlayer.ApplyState.myGameGridEffect private
Definition at line 22 of file ApplyState.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/ApplyState.java