voogasalad_VOOGirlsGeneration: authoring.createedit.GamePropertiesEditor Class Reference
authoring.createedit.GamePropertiesEditor Class Reference
Public Member Functions
GamePropertiesEditor (Consumer< GamePropertiesData > c)
GamePropertiesEditor (GamePropertiesData gamePropertiesData)
int getNumPlayer ()
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Attributes
int myNumPlayers
String myGridShape
ResourceBundle gridShapeBundle
TextField myNumPlayerField
ChoiceBox< String > myShapeChoice
Button myCreateBtn
Static Private Attributes
static final int DEFAULT_NUMPLAYERS = 1
static final String DEFAULT_GRIDSHAPE = ""
static final String RESOURCES_PROPERTIES_GRID_SHAPE = "resources.properties/gridShape"
static final String STYLESHEET = "/resources/stylesheets/actioncreator_layout.css"
Detailed Description
Definition at line 19 of file GamePropertiesEditor.java.
Constructor & Destructor Documentation
authoring.createedit.GamePropertiesEditor.GamePropertiesEditor (Consumer< GamePropertiesData > c)
Definition at line 33 of file GamePropertiesEditor.java.
References authoring.createedit.GamePropertiesEditor.DEFAULT_GRIDSHAPE, authoring.createedit.GamePropertiesEditor.DEFAULT_NUMPLAYERS, and authoring.createedit.GamePropertiesEditor.initialize().
authoring.createedit.GamePropertiesEditor.GamePropertiesEditor (GamePropertiesData gamePropertiesData)
Definition at line 50 of file GamePropertiesEditor.java.
References authoring.data.GamePropertiesData.getGridShape(), authoring.data.GamePropertiesData.getNumPlayers(), and authoring.createedit.GamePropertiesEditor.initialize().
Member Function Documentation
int authoring.createedit.GamePropertiesEditor.getNumPlayer ()
Definition at line 123 of file GamePropertiesEditor.java.
References authoring.createedit.GamePropertiesEditor.myNumPlayers.
void authoring.createedit.GamePropertiesEditor.initialize () protected
Definition at line 61 of file GamePropertiesEditor.java.
Referenced by authoring.createedit.GamePropertiesEditor.GamePropertiesEditor().
Member Data Documentation
final String authoring.createedit.GamePropertiesEditor.DEFAULT_GRIDSHAPE = "" static private
Definition at line 21 of file GamePropertiesEditor.java.
Referenced by authoring.createedit.GamePropertiesEditor.GamePropertiesEditor().
final int authoring.createedit.GamePropertiesEditor.DEFAULT_NUMPLAYERS = 1 static private
Definition at line 20 of file GamePropertiesEditor.java.
Referenced by authoring.createedit.GamePropertiesEditor.GamePropertiesEditor().
ResourceBundle authoring.createedit.GamePropertiesEditor.gridShapeBundle private
Definition at line 27 of file GamePropertiesEditor.java.
Button authoring.createedit.GamePropertiesEditor.myCreateBtn private
Definition at line 31 of file GamePropertiesEditor.java.
String authoring.createedit.GamePropertiesEditor.myGridShape private
Definition at line 26 of file GamePropertiesEditor.java.
TextField authoring.createedit.GamePropertiesEditor.myNumPlayerField private
Definition at line 29 of file GamePropertiesEditor.java.
int authoring.createedit.GamePropertiesEditor.myNumPlayers private
Definition at line 25 of file GamePropertiesEditor.java.
Referenced by authoring.createedit.GamePropertiesEditor.getNumPlayer().
ChoiceBox<String> authoring.createedit.GamePropertiesEditor.myShapeChoice private
Definition at line 30 of file GamePropertiesEditor.java.
final String authoring.createedit.GamePropertiesEditor.RESOURCES_PROPERTIES_GRID_SHAPE = "resources.properties/gridShape" static private
Definition at line 22 of file GamePropertiesEditor.java.
final String authoring.createedit.GamePropertiesEditor.STYLESHEET = "/resources/stylesheets/actioncreator_layout.css" static private
Definition at line 23 of file GamePropertiesEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/createedit/GamePropertiesEditor.java