voogasalad_VOOGirlsGeneration: gamePlayer.KeyboardMovement Class Reference
gamePlayer.KeyboardMovement Class Reference
Public Member Functions
KeyboardMovement ()
void setMovementKeyControl (ViewController vc)
Point2D.Double getCurrentLocation ()
void useDefaultMap ()
Private Attributes
Point2D.Double myCurrentLocation
Map< KeyCode, Point2D.Double > myKeyMap
SuperTile currentTile
Static Private Attributes
static final String KEY_MOVEMENT_COLOR = "#AC58FA"
Detailed Description
Allows users to use keyboard to "move the cursor" around the game grid. KeyboardMovement is strictly used for moving and selecting objects on the game grid.
Author
Yoonhyung
Definition at line 20 of file KeyboardMovement.java.
Constructor & Destructor Documentation
gamePlayer.KeyboardMovement.KeyboardMovement ()
Definition at line 27 of file KeyboardMovement.java.
References gamePlayer.KeyboardMovement.myCurrentLocation, and gamePlayer.KeyboardMovement.myKeyMap.
Member Function Documentation
Point2D.Double gamePlayer.KeyboardMovement.getCurrentLocation ()
Returns the current location selected by keyboard movement.
Returns
current keyboard control location on the game grid
Definition at line 103 of file KeyboardMovement.java.
References gamePlayer.KeyboardMovement.myCurrentLocation.
void gamePlayer.KeyboardMovement.setMovementKeyControl (ViewController vc)
Movement map (which maps movements to keycodes) is passed by the game engine. This method creates key event handlers so that when such a keycode is pressed, its corresponding movement is implemented. Movement is "moving the cursor" with the keyboard.
Parameters
myKeyMap
gameScene
Definition at line 43 of file KeyboardMovement.java.
References authoring_environment.SuperTile.deselectTile(), authoring_environment.SuperGrid.findTile(), gamedata.gamecomponents.Game.getCurrentPlayer(), gamePlayer.ViewController.getGame(), gamePlayer.ViewController.getGrid(), gamePlayer.ViewController.getGridPane(), authoring_environment.SuperGrid.getNumCols(), authoring_environment.SuperGrid.getNumRows(), gameengine.player.Player.getType(), gamePlayer.KeyboardMovement.myCurrentLocation, gamePlayer.KeyboardMovement.myKeyMap, gamePlayer.ViewController.performAction(), authoring_environment.SuperTile.selectTile(), and gamePlayer.KeyboardMovement.useDefaultMap().
Referenced by gamePlayer.ViewController.bindAction(), gamePlayer.ViewController.performAction(), and gamePlayer.ViewController.toggleKeyboardControl().
void gamePlayer.KeyboardMovement.useDefaultMap ()
Uses the default keyboard movement map if it is not specified for the active human player.
Definition at line 110 of file KeyboardMovement.java.
References gamePlayer.KeyboardMovement.myKeyMap.
Referenced by gamePlayer.KeyboardMovement.setMovementKeyControl().
Member Data Documentation
SuperTile gamePlayer.KeyboardMovement.currentTile private
Definition at line 25 of file KeyboardMovement.java.
final String gamePlayer.KeyboardMovement.KEY_MOVEMENT_COLOR = "#AC58FA" static private
Definition at line 21 of file KeyboardMovement.java.
Point2D.Double gamePlayer.KeyboardMovement.myCurrentLocation private
Definition at line 23 of file KeyboardMovement.java.
Referenced by gamePlayer.KeyboardMovement.getCurrentLocation(), gamePlayer.KeyboardMovement.KeyboardMovement(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
Map<KeyCode, Point2D.Double> gamePlayer.KeyboardMovement.myKeyMap private
Definition at line 24 of file KeyboardMovement.java.
Referenced by gamePlayer.KeyboardMovement.KeyboardMovement(), gamePlayer.KeyboardMovement.setMovementKeyControl(), and gamePlayer.KeyboardMovement.useDefaultMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/KeyboardMovement.java