voogasalad_VOOGirlsGeneration: gamedata.stats.Stats Class Reference
gamedata.stats.Stats Class Reference
Public Member Functions
Stats ()
Stats (Map< String, Double > stats)
Stats (Stats clone)
void add (String name, double value)
void remove (String name)
double getValue (String name)
void setValue (String name, double value)
void clear ()
boolean contains (String statName)
List< String > getStatNames ()
Private Attributes
Map< String, Double > myStats
Detailed Description
Numerical stats class. Stats are contained in every piece. Stats map a stat name to a double value.
Author
Jennie Ju
Definition at line 16 of file Stats.java.
Constructor & Destructor Documentation
gamedata.stats.Stats.Stats ()
Stats constructor for initializing empty stats map
Definition at line 22 of file Stats.java.
gamedata.stats.Stats.Stats (Map< String, Double > stats)
Stats constructor for initializing with already created map of names to doubles
Parameters
stats - map of stat names to doubles
Definition at line 31 of file Stats.java.
gamedata.stats.Stats.Stats (Stats clone)
Cloning constructor for deep cloning of stats
Parameters
clone - Stats instance to be cloned
Definition at line 39 of file Stats.java.
References gamedata.stats.Stats.myStats.
Member Function Documentation
void gamedata.stats.Stats.add (String name, double value)
Adds a new stat to the stats map
Definition at line 46 of file Stats.java.
Referenced by authoring.concretefeatures.StatsIndividualEditor.createButton(), tests.TestGameCreator.createNewPiece(), and authoring.concretefeatures.StatsTotalEditor.makeDoneButton().
void gamedata.stats.Stats.clear ()
Clears the stats map
Definition at line 75 of file Stats.java.
boolean gamedata.stats.Stats.contains (String statName)
Checks if the stats contain the specified stat
Definition at line 82 of file Stats.java.
Referenced by fxml_main.PlayerStatEditor.initialize().
List<String> gamedata.stats.Stats.getStatNames ()
Returns a set of all the stat names
Definition at line 89 of file Stats.java.
Referenced by authoring.concretefeatures.StatsIndividualEditor.initialize(), authoring.concretefeatures.StatsTotalEditor.initStatsCreatorBoxes(), authoring.eventeditor.ConditionEditorPane.setupStatsBox(), and gamePlayer.ViewController.updateStats().
double gamedata.stats.Stats.getValue (String name)
Gets the value of the stat indicated by name
Definition at line 60 of file Stats.java.
Referenced by gameengine.player.Player.changeStat(), gamedata.events.conditions.StatGreaterThan.compare(), gamedata.events.conditions.StatLessThan.compare(), gamedata.events.conditions.StatEquals.compare(), gamedata.action.StatsDataModifier.evaluateMultiplierLogic(), gameengine.player.Player.getScore(), authoring.concretefeatures.StatsTotalEditor.initStatsCreatorBoxes(), authoring.concretefeatures.StatsIndividualEditor.initStatsEditorBox(), and gamePlayer.ViewController.updateStats().
void gamedata.stats.Stats.remove (String name)
Removes a stat from the stats map by name
Definition at line 53 of file Stats.java.
Referenced by authoring.concretefeatures.StatsTotalEditor.makeDeleteButton().
void gamedata.stats.Stats.setValue (String name, double value)
Sets the value of the stat with the indicated name to the value specified
Definition at line 68 of file Stats.java.
Referenced by gameengine.player.Player.changeStat(), and gamedata.action.StatsDataModifier.modifyStats().
Member Data Documentation
Map<String, Double> gamedata.stats.Stats.myStats private
Definition at line 17 of file Stats.java.
Referenced by gamedata.stats.Stats.Stats().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/stats/Stats.java