voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.Game Class Reference
gamedata.gamecomponents.Game Class Reference
Public Member Functions
Game ()
Game (int numPlayers, List< Level > levels)
Game (int numPlayers, List< Level > levels, Level currentLevel)
void startGame ()
void addPlayers (List< Player > p)
void changeTurn (int playerToChangeTo)
String toString ()
Level getCurrentLevel ()
Player getCurrentPlayer ()
List< Player > getPlayers ()
List< Level > getLevels ()
void setPlayer (Player p, int pos)
void nextPlayer ()
void setCurrentLevel (Level l)
void setCurrentPlayer (Player p)
void endGame (int gameStatus)
void changeLevel (String name)
void endTurn ()
void replacePlayer (int playerID, String playerType)
Private Member Functions
void resetPlayer ()
void restartLevel ()
Private Attributes
List< Player > myPlayers
List< Level > myLevels
Level myCurrentLevel
Player myCurrentPlayer
int myGameWon
int myNumPlayers
Static Private Attributes
static final String SIMPLE_AI_PLAYER = "Simple AI player"
static final String HUMAN_PLAYER = "Human Player"
Detailed Description
A game that contains a list of players and the levels that players can play
The play method in this class is called in every iteration of the game loop.
Author
Jesse, Jennie
Definition at line 20 of file Game.java.
Constructor & Destructor Documentation
gamedata.gamecomponents.Game.Game ()
Default Constructor
Definition at line 52 of file Game.java.
gamedata.gamecomponents.Game.Game (int numPlayers, List< Level > levels)
Instantiate a new Game given a list of players and levels that exist.
Parameters
numPlayers Number of Players
levels List of levels that compose the game
Definition at line 64 of file Game.java.
gamedata.gamecomponents.Game.Game (int numPlayers, List< Level > levels, Level currentLevel)
Instantiate a new Game given a list of players and levels that exist and a specific currentLevel
Parameters
numPlayers Number of Players
levels List of levels that compose the game
currentLevel Current Level that the game starts on
Definition at line 79 of file Game.java.
Member Function Documentation
void gamedata.gamecomponents.Game.addPlayers (List< Player > p)
Adds the list of players whom will by playing the game in order
Parameters
p List of Players
Definition at line 103 of file Game.java.
Referenced by authoring.data.GameAuthoringData.createGame(), tests.TestGameCreator.createNewGame(), gamedata.wrappers.GameData.getGameFromData(), and fxml_main.AuthoringController.saveAsGame().
void gamedata.gamecomponents.Game.changeLevel (String name)
Used by global action.
Parameters
name
Definition at line 246 of file Game.java.
Referenced by gamePlayer.ViewController.checkEndActions().
void gamedata.gamecomponents.Game.changeTurn (int playerToChangeTo)
Changes the player to the player with the int position in the list of players
Parameters
playerToChangeTo Integer to change the current player to
Definition at line 117 of file Game.java.
References gamedata.gamecomponents.Game.setCurrentPlayer().
void gamedata.gamecomponents.Game.endGame (int gameStatus)
Used by global action. Status set as 1 if game is won, set as -1 if game is lost. game continues to run if value is 0
Parameters
gameStatus
Definition at line 237 of file Game.java.
void gamedata.gamecomponents.Game.endTurn ()
Used by global action.
Definition at line 257 of file Game.java.
References gamedata.gamecomponents.Game.resetPlayer().
Level gamedata.gamecomponents.Game.getCurrentLevel ()
Getter for the Current Level
Returns
Returns the Current Level
Definition at line 153 of file Game.java.
References gamedata.gamecomponents.Game.myCurrentLevel.
Referenced by gamePlayer.ViewController.checkEndActions(), tests.GlobalActionTester.GlobalActionTester(), gamePlayer.ViewController.highlightSelected(), gamePlayer.ViewController.initializeGrid(), gamePlayer.ViewController.performAction(), tests.GlobalActionTester.TestCreatePiece(), tests.GlobalActionTester.TestDeletePiece(), tests.JSONTesterMain.testJSONwrite(), tests.GlobalActionTester.TestLevelChange(), gamePlayer.ViewController.testPlayGame(), gamePlayer.ViewController.testPlayGameInTab(), and gamePlayer.ViewController.testPlayGUIGame().
Player gamedata.gamecomponents.Game.getCurrentPlayer ()
Getter for the Current Player
Returns
Returns the Current Player
Definition at line 162 of file Game.java.
References gamedata.gamecomponents.Game.myCurrentPlayer.
Referenced by gamePlayer.ViewController.checkEndActions(), gamePlayer.SelectState.onClick(), gamePlayer.ViewController.setGridState(), gamePlayer.KeyboardMovement.setMovementKeyControl(), and tests.GlobalActionTester.TestEndTurn().
List<Level> gamedata.gamecomponents.Game.getLevels ()
Getter for the list of levels
Returns
Returns the list of levels
Definition at line 180 of file Game.java.
References gamedata.gamecomponents.Game.myLevels.
Referenced by tests.JSONTesterMain.testJSONwrite().
List<Player> gamedata.gamecomponents.Game.getPlayers ()
Getter for the list of players
Returns
Returns the list of players
Definition at line 171 of file Game.java.
References gamedata.gamecomponents.Game.myPlayers.
Referenced by gamePlayer.ViewController.checkEndActions(), gamePlayer.ViewController.editGUIPlayers(), gamePlayer.ViewController.editPlayers(), gamedata.wrappers.GameData.getGameFromData(), and gamePlayer.ViewController.loadScores().
void gamedata.gamecomponents.Game.nextPlayer ()
Iterates the current player to the next chronological player in the list of players
Definition at line 200 of file Game.java.
References gamedata.gamecomponents.Game.resetPlayer(), and gameengine.player.Player.startTurn().
Referenced by gamePlayer.ViewController.checkEndActions().
void gamedata.gamecomponents.Game.replacePlayer (int playerID, String playerType)
Game player initializes players to a specific type, needs to replace each player with the appropriate type
Parameters
playerID
newPlayer
Definition at line 272 of file Game.java.
Referenced by gamePlayer.ViewController.editSpecificPlayer().
void gamedata.gamecomponents.Game.resetPlayer () private
Resets the active player to be the first player who has played
Definition at line 128 of file Game.java.
References gameengine.player.Player.startTurn().
Referenced by gamedata.gamecomponents.Game.endTurn(), and gamedata.gamecomponents.Game.nextPlayer().
void gamedata.gamecomponents.Game.restartLevel () private
Restarts the level
Definition at line 136 of file Game.java.
References gamedata.gamecomponents.Level.restart().
void gamedata.gamecomponents.Game.setCurrentLevel (Level l)
Used by Global Actions. Set the current player to the player with a given ID
Parameters
levelID
Definition at line 216 of file Game.java.
void gamedata.gamecomponents.Game.setCurrentPlayer (Player p)
Sets the current player to a specific player p
Parameters
p Player p to set as the current player
Definition at line 226 of file Game.java.
References gameengine.player.Player.startTurn().
Referenced by gamedata.gamecomponents.Game.changeTurn(), gamedata.wrappers.GameData.getGameFromData(), and gamePlayer.ViewController.saveGame().
void gamedata.gamecomponents.Game.setPlayer (Player p, int pos)
Setter for the player to set a player to a specific position in the list
Parameters
p Player to set
pos Int Position to set the player in the list
Definition at line 192 of file Game.java.
void gamedata.gamecomponents.Game.startGame ()
Starts the game by calling on the current player to start the turn
Definition at line 93 of file Game.java.
References gameengine.player.Player.startTurn().
String gamedata.gamecomponents.Game.toString ()
Formats the information regarding a game to a string output
Definition at line 143 of file Game.java.
Referenced by gamePlayer.ViewController.loadScores().
Member Data Documentation
final String gamedata.gamecomponents.Game.HUMAN_PLAYER = "Human Player" static private
Definition at line 47 of file Game.java.
Level gamedata.gamecomponents.Game.myCurrentLevel private
Current Level being Player
Definition at line 33 of file Game.java.
Referenced by gamedata.gamecomponents.Game.getCurrentLevel().
Player gamedata.gamecomponents.Game.myCurrentPlayer private
Current Player Making Plays
Definition at line 37 of file Game.java.
Referenced by gamedata.gamecomponents.Game.getCurrentPlayer().
int gamedata.gamecomponents.Game.myGameWon private
Integer representing the win state of the game
Definition at line 41 of file Game.java.
List<Level> gamedata.gamecomponents.Game.myLevels private
Contains ordered list of levels that compose the game
Definition at line 29 of file Game.java.
Referenced by gamedata.gamecomponents.Game.getLevels().
int gamedata.gamecomponents.Game.myNumPlayers private
Number of players in the game
Definition at line 45 of file Game.java.
List<Player> gamedata.gamecomponents.Game.myPlayers private
Contains player in order of their turns
Definition at line 25 of file Game.java.
Referenced by gamedata.gamecomponents.Game.getPlayers().
final String gamedata.gamecomponents.Game.SIMPLE_AI_PLAYER = "Simple AI player" static private
Definition at line 46 of file Game.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/Game.java