voogasalad_VOOGirlsGeneration: gamePlayer.PlayerTypeSetter Class Reference
gamePlayer.PlayerTypeSetter Class Reference
Public Member Functions
PlayerTypeSetter (Game game, ViewController vc)
Scene startLoadPlayers ()
Static Public Attributes
static final String PLAYER_FXML = "playerEditorScene.fxml"
Private Member Functions
void editSpecificPlayer (int playerID)
void loadFXML (String url, Node n)
Private Attributes
BorderPane myPlayers
BorderPane editPlayerRoot
VBox playersList
TextField editPlayerName
ComboBox< String > playerTypeCombo
Button startGameButton
Button setPlayerButton
Scene myScene
Game myGame
ViewController myVC
Static Private Attributes
static final String SIMPLE_AI_PLAYER = "Simple AI player"
static final String HUMAN_PLAYER = "Human Player"
static final String PLAYER = "Player: "
Detailed Description
Definition at line 24 of file PlayerTypeSetter.java.
Constructor & Destructor Documentation
gamePlayer.PlayerTypeSetter.PlayerTypeSetter (Game game, ViewController vc)
Contains scene for users to choose their player of choice
Parameters
game
Definition at line 52 of file PlayerTypeSetter.java.
References gamePlayer.PlayerTypeSetter.loadFXML(), and gamePlayer.PlayerTypeSetter.startLoadPlayers().
Member Function Documentation
void gamePlayer.PlayerTypeSetter.editSpecificPlayer (int playerID) private
Allows user to edit the specific player to be a player of a specific type
Parameters
playerID
Definition at line 84 of file PlayerTypeSetter.java.
References gamedata.gamecomponents.Game.replacePlayer().
Referenced by gamePlayer.PlayerTypeSetter.startLoadPlayers().
void gamePlayer.PlayerTypeSetter.loadFXML (String url, Node n) private
Loads FXML for this View
Parameters
url
n
Definition at line 102 of file PlayerTypeSetter.java.
Referenced by gamePlayer.PlayerTypeSetter.PlayerTypeSetter().
Scene gamePlayer.PlayerTypeSetter.startLoadPlayers ()
Definition at line 60 of file PlayerTypeSetter.java.
References gamePlayer.PlayerTypeSetter.editSpecificPlayer(), gamedata.gamecomponents.Game.getPlayers(), and gamePlayer.PlayerTypeSetter.myScene.
Referenced by gamePlayer.ViewController.loadGame(), gamePlayer.PlayerTypeSetter.PlayerTypeSetter(), and gamePlayer.ViewController.testGame().
Member Data Documentation
TextField gamePlayer.PlayerTypeSetter.editPlayerName private
Definition at line 37 of file PlayerTypeSetter.java.
BorderPane gamePlayer.PlayerTypeSetter.editPlayerRoot private
Definition at line 33 of file PlayerTypeSetter.java.
final String gamePlayer.PlayerTypeSetter.HUMAN_PLAYER = "Human Player" static private
Definition at line 27 of file PlayerTypeSetter.java.
Game gamePlayer.PlayerTypeSetter.myGame private
Definition at line 45 of file PlayerTypeSetter.java.
BorderPane gamePlayer.PlayerTypeSetter.myPlayers private
Definition at line 31 of file PlayerTypeSetter.java.
Scene gamePlayer.PlayerTypeSetter.myScene private
Definition at line 44 of file PlayerTypeSetter.java.
Referenced by gamePlayer.PlayerTypeSetter.startLoadPlayers().
ViewController gamePlayer.PlayerTypeSetter.myVC private
Definition at line 46 of file PlayerTypeSetter.java.
final String gamePlayer.PlayerTypeSetter.PLAYER = "Player: " static private
Definition at line 28 of file PlayerTypeSetter.java.
final String gamePlayer.PlayerTypeSetter.PLAYER_FXML = "playerEditorScene.fxml" static
Definition at line 25 of file PlayerTypeSetter.java.
VBox gamePlayer.PlayerTypeSetter.playersList private
Definition at line 35 of file PlayerTypeSetter.java.
ComboBox<String> gamePlayer.PlayerTypeSetter.playerTypeCombo private
Definition at line 39 of file PlayerTypeSetter.java.
Button gamePlayer.PlayerTypeSetter.setPlayerButton private
Definition at line 43 of file PlayerTypeSetter.java.
final String gamePlayer.PlayerTypeSetter.SIMPLE_AI_PLAYER = "Simple AI player" static private
Definition at line 26 of file PlayerTypeSetter.java.
Button gamePlayer.PlayerTypeSetter.startGameButton private
Definition at line 41 of file PlayerTypeSetter.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/PlayerTypeSetter.java