voogasalad_VOOGirlsGeneration: fxml_main.GUIGridReference Class Reference
fxml_main.GUIGridReference Class Reference
Public Member Functions
GUIGridReference ()
void resetGrid ()
GUIGrid getGrid ()
void setGrid (GUIGrid grid)
Private Attributes
GUIGrid myGrid
Static Private Attributes
static final GUIGrid DEFAULT_GRID = new GUIGrid(0,0,0,"Square Grid")
Detailed Description
Works as a reference to the current GUIGrid so that the current GUIGrid can be replaced while the controller classes maintain the same pointer to the same GUIGridReference.
Needed because Java can only pass by value :(
Author
Jennie Ju
Definition at line 17 of file GUIGridReference.java.
Constructor & Destructor Documentation
fxml_main.GUIGridReference.GUIGridReference ()
Definition at line 21 of file GUIGridReference.java.
References fxml_main.GUIGridReference.resetGrid().
Member Function Documentation
GUIGrid fxml_main.GUIGridReference.getGrid ()
Definition at line 30 of file GUIGridReference.java.
References fxml_main.GUIGridReference.myGrid.
Referenced by fxml_main.LevelController.initEntryDelBtn(), fxml_main.PatchController.initGlobalDelBtn(), fxml_main.PieceController.initGlobalDelBtn(), fxml_main.PatchController.initGlobalEditBtn(), fxml_main.PieceController.initGlobalEditBtn(), fxml_main.PatchController.makeEntryBox(), fxml_main.PieceController.makeEntryBox(), and fxml_main.LevelController.setAndDisplayGrid().
void fxml_main.GUIGridReference.resetGrid ()
Definition at line 26 of file GUIGridReference.java.
References fxml_main.GUIGridReference.DEFAULT_GRID.
Referenced by fxml_main.GUIGridReference.GUIGridReference(), and fxml_main.LevelController.initEntryDelBtn().
void fxml_main.GUIGridReference.setGrid (GUIGrid grid)
Definition at line 34 of file GUIGridReference.java.
Referenced by fxml_main.LevelController.setAndDisplayGrid().
Member Data Documentation
final GUIGrid fxml_main.GUIGridReference.DEFAULT_GRID = new GUIGrid(0,0,0,"Square Grid") static private
Definition at line 18 of file GUIGridReference.java.
Referenced by fxml_main.GUIGridReference.resetGrid().
GUIGrid fxml_main.GUIGridReference.myGrid private
Definition at line 19 of file GUIGridReference.java.
Referenced by fxml_main.GUIGridReference.getGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/GUIGridReference.java