voogasalad_VOOGirlsGeneration: gamedata.action.StatsDataModifier Class Reference
gamedata.action.StatsDataModifier Class Reference
Public Member Functions
StatsDataModifier (List< StatsTotalLogic > statsLogics)
void modifyStats (IHasStats actor, IHasStats receiver)
Private Member Functions
double evaluateMultiplierLogic (Stats actorStats, Stats receiverStats, List< StatsSingleMultiplier > multiplierLogic)
Private Attributes
List< StatsTotalLogic > myStatsLogics
Detailed Description
Extracted from Concrete action to be applied in ChangePlayerStat global action
Author
annamiyajima
Definition at line 13 of file StatsDataModifier.java.
Constructor & Destructor Documentation
gamedata.action.StatsDataModifier.StatsDataModifier (List< StatsTotalLogic > statsLogics)
Definition at line 17 of file StatsDataModifier.java.
Member Function Documentation
double gamedata.action.StatsDataModifier.evaluateMultiplierLogic (Stats actorStats, Stats receiverStats, List< StatsSingleMultiplier > multiplierLogic) private
Definition at line 44 of file StatsDataModifier.java.
References gamedata.stats.Stats.getValue().
Referenced by gamedata.action.StatsDataModifier.modifyStats().
void gamedata.action.StatsDataModifier.modifyStats (IHasStats actor, IHasStats receiver)
Takes in two objects that impelment IHasStats(piece,patch,player) and changes receiver's stat based on actor's stat
Parameters
actor
receiver
Definition at line 27 of file StatsDataModifier.java.
References gamedata.action.StatsDataModifier.evaluateMultiplierLogic(), gamedata.gamecomponents.IHasStats.getStats(), and gamedata.stats.Stats.setValue().
Referenced by gamedata.action.ConcreteAction.modifyStats().
Member Data Documentation
List<StatsTotalLogic> gamedata.action.StatsDataModifier.myStatsLogics private
Definition at line 15 of file StatsDataModifier.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/StatsDataModifier.java