voogasalad_VOOGirlsGeneration: authoring_environment.RangeGrid Class Reference
authoring_environment.RangeGrid Class Reference
Public Member Functions
RangeGrid (int width, int height, double tileSize, String shape, List< Point2D.Double > range)
List< Point2D.Double > selectedRangeList ()
void processChoice (String chosen, int parameter, boolean toChoose)
Public Member Functions inherited from authoring_environment.SuperGrid
SuperGrid ()
SuperGrid (int cols, int rows, double tileHeight, String shape)
int getNumRows ()
int getNumCols ()
double getTileHeight ()
void displayPane (ScrollPane parent)
Point2D.Double findClickedCoordinate (double xLoc, double yLoc)
SuperTile findClickedTile (double xLoc, double yLoc)
SuperTile findTile (Point2D coor)
Private Member Functions
void addSelectAction ()
void switchHighlight (SuperTile tile)
void highlightRange (List< Point2D.Double > range)
SuperTile findTile (int row, int column)
void addCenterImage (int row, int column)
void rangeColumn (int column, boolean toChoose)
void rangeRow (int row, boolean toChoose)
void rangeRadius (int radius, boolean toChoose)
void rangeAll (int nullInt, boolean toChoose)
boolean processHighlight (boolean toChoose, int column, int row)
Private Attributes
List< List< SuperTile > > rangeGrid
int myWidth
int myHeight
int centerX
int centerY
List< Point2D.Double > myRange
Static Private Attributes
static final String ERROR_INFOMATION = "Ops!"
static final String RANGE = "range"
static final String DEFAULT_CENTRAL_IMAGE ="/resources/images/Patrick.jpeg"
static final String DEFAULT_HIGHLIGHT_COLOR = "#0000FF"
Additional Inherited Members
Protected Member Functions inherited from authoring_environment.SuperGrid
void clearGridImages ()
void initGridTiles (String shape)
Protected Attributes inherited from authoring_environment.SuperGrid
int myNumRows
int myNumCols
double myTileHeight
String myShape
transient Pane myPane
transient List< List< SuperTile > > myGrid
Detailed Description
The grid is made especially for selecting the range. It is shown inside the RangeGridView inside RangeEditor. This class deals with the logic of user's selection and gives back a list of point2D which represents the relative coordinates to the center tile of the grid.
Author
Mengen Huang
Definition at line 24 of file RangeGrid.java.
Constructor & Destructor Documentation
authoring_environment.RangeGrid.RangeGrid (int width, int height, double tileSize, String shape, List< Point2D.Double > range)
Definition at line 38 of file RangeGrid.java.
References authoring_environment.RangeGrid.addCenterImage(), authoring_environment.RangeGrid.addSelectAction(), authoring_environment.RangeGrid.highlightRange(), authoring_environment.SuperGrid.initGridTiles(), and authoring_environment.RangeGrid.myRange.
Member Function Documentation
void authoring_environment.RangeGrid.addCenterImage (int row, int column) private
Add the image "Patrick" at the center of the grid.
Parameters
row Number of rows in the grid.
column Number of columns in the grid.
Definition at line 115 of file RangeGrid.java.
References authoring_environment.RangeGrid.findTile(), and authoring_environment.SuperTile.setPatchImage().
Referenced by authoring_environment.RangeGrid.RangeGrid().
void authoring_environment.RangeGrid.addSelectAction () private
Apply the action to all the tiles in the grid that clicking on the tile will switch the highlight on or off.
Definition at line 62 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.RangeGrid().
SuperTile authoring_environment.RangeGrid.findTile (int row, int column) private
Get the tile by its grid location.
Parameters
row The y axis grid location.
column The x axis grid location.
Returns
The tile on the indicated grid location.
Definition at line 104 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.addCenterImage(), authoring_environment.RangeGrid.highlightRange(), authoring_environment.RangeGrid.processHighlight(), and authoring_environment.RangeGrid.selectedRangeList().
void authoring_environment.RangeGrid.highlightRange (List< Point2D.Double > range) private
Highlight all the tiles currently in the visible grid. The tiles are represented by grid location in range.
Parameters
range The list of tiles represented by relative grid location to the center tile.
Definition at line 85 of file RangeGrid.java.
References authoring_environment.RangeGrid.centerX, authoring_environment.RangeGrid.findTile(), and authoring_environment.SuperTile.selectTile().
Referenced by authoring_environment.RangeGrid.RangeGrid().
void authoring_environment.RangeGrid.processChoice (String chosen, int parameter, boolean toChoose)
Reflection method that get the correspondent method according to the String passed in.
Parameters
chosen The string passed in that represents column/row/radius/all.
parameter The integer passed in as the parameter of the method. It specifies which row/column or what is the radius of the select range. The parameter is set 0 when the user choose all.
toChoose To select or deselect the tile.
Definition at line 223 of file RangeGrid.java.
Referenced by authoring.concretefeatures.RangeEditor.selectRangeHandler.handle().
boolean authoring_environment.RangeGrid.processHighlight (boolean toChoose, int column, int row) private
Process if the tile at a certain location should be selected or deselected accroding to the information passed in.
Parameters
toChoose True as to select and false as deselect.
column The x coordinate of the tile.
row The y coordinate of the tile.
Returns
Definition at line 208 of file RangeGrid.java.
References authoring_environment.SuperTile.deselectTile(), authoring_environment.RangeGrid.findTile(), and authoring_environment.SuperTile.selectTile().
Referenced by authoring_environment.RangeGrid.rangeAll(), authoring_environment.RangeGrid.rangeColumn(), authoring_environment.RangeGrid.rangeRadius(), and authoring_environment.RangeGrid.rangeRow().
void authoring_environment.RangeGrid.rangeAll (int nullInt, boolean toChoose) private
Select or deselect all the tiles in the range.
Parameters
toChoose true to be select, false to be deselect.
Definition at line 191 of file RangeGrid.java.
References authoring_environment.RangeGrid.myHeight, authoring_environment.RangeGrid.myWidth, and authoring_environment.RangeGrid.processHighlight().
Referenced by authoring_environment.RangeGrid.rangeRadius().
void authoring_environment.RangeGrid.rangeColumn (int column, boolean toChoose) private
Select or deselect the Column of the specified one by highlighting the tile.
Parameters
column The number of the column.
toChoose true to be select, false to be deselect.
Definition at line 148 of file RangeGrid.java.
References authoring_environment.RangeGrid.myHeight, and authoring_environment.RangeGrid.processHighlight().
void authoring_environment.RangeGrid.rangeRadius (int radius, boolean toChoose) private
Select or deselect the tiles radius away from the center by highlighting the tile.
Parameters
column The radius of the highlighted tiles from the center.
toChoose true to be select, false to be deselect.
Definition at line 175 of file RangeGrid.java.
References authoring_environment.RangeGrid.processHighlight(), and authoring_environment.RangeGrid.rangeAll().
void authoring_environment.RangeGrid.rangeRow (int row, boolean toChoose) private
Select or deselect the row of the specified one by highlighting the tile.
Parameters
column The number of the row.
toChoose true to be select, false to be deselect.
Definition at line 162 of file RangeGrid.java.
References authoring_environment.RangeGrid.myWidth, and authoring_environment.RangeGrid.processHighlight().
List<Point2D.Double> authoring_environment.RangeGrid.selectedRangeList ()
Collect all the coordination of selected tiles relative to the center tile as Point2D in a list.
Returns
The list of relative coordination relative to the center tile.
Definition at line 128 of file RangeGrid.java.
References authoring_environment.RangeGrid.findTile(), authoring_environment.SuperTile.isSelected(), authoring_environment.RangeGrid.myHeight, authoring_environment.RangeGrid.myRange, and authoring_environment.RangeGrid.myWidth.
Referenced by authoring_environment.RangeGridView.returnSelectedList().
void authoring_environment.RangeGrid.switchHighlight (SuperTile tile) private
Switch the highlight on or off with a specified color.
Parameters
tile The tile to switch the highlight.
Definition at line 74 of file RangeGrid.java.
References authoring_environment.SuperTile.deselectTile(), authoring_environment.SuperTile.isSelected(), and authoring_environment.SuperTile.selectTile().
Member Data Documentation
int authoring_environment.RangeGrid.centerX private
Definition at line 34 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.highlightRange().
int authoring_environment.RangeGrid.centerY private
Definition at line 35 of file RangeGrid.java.
final String authoring_environment.RangeGrid.DEFAULT_CENTRAL_IMAGE ="/resources/images/Patrick.jpeg" static private
Definition at line 28 of file RangeGrid.java.
final String authoring_environment.RangeGrid.DEFAULT_HIGHLIGHT_COLOR = "#0000FF" static private
Definition at line 29 of file RangeGrid.java.
final String authoring_environment.RangeGrid.ERROR_INFOMATION = "Ops!" static private
Definition at line 26 of file RangeGrid.java.
int authoring_environment.RangeGrid.myHeight private
Definition at line 33 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.rangeAll(), authoring_environment.RangeGrid.rangeColumn(), and authoring_environment.RangeGrid.selectedRangeList().
List<Point2D.Double> authoring_environment.RangeGrid.myRange private
Definition at line 36 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.RangeGrid(), and authoring_environment.RangeGrid.selectedRangeList().
int authoring_environment.RangeGrid.myWidth private
Definition at line 32 of file RangeGrid.java.
Referenced by authoring_environment.RangeGrid.rangeAll(), authoring_environment.RangeGrid.rangeRow(), and authoring_environment.RangeGrid.selectedRangeList().
final String authoring_environment.RangeGrid.RANGE = "range" static private
Definition at line 27 of file RangeGrid.java.
List<List<SuperTile> > authoring_environment.RangeGrid.rangeGrid private
Definition at line 31 of file RangeGrid.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/RangeGrid.java