voogasalad_VOOGirlsGeneration: fxml_main.AuthoringController Class Reference
fxml_main.AuthoringController Class Reference
Public Member Functions
void initialize (URL fxmlFileLocation, ResourceBundle resources)
void initData (GamePropertiesData gamePropertiesData)
Private Member Functions
void showActionslogicChartWindow () throws IOException
void showGamePropertiesWindow ()
void showPlayerEditWindow ()
void saveGame ()
void saveAsGame ()
Private Attributes
ScrollPane myPropertiesSPane
VBox myLevelsVBox
VBox myPiecesVBox
VBox myPatchesVBox
VBox myActionsVBox
ScrollPane myGridSPane
MenuItem actonsLogicChart
MenuItem gameProperties
MenuItem playerEditor
MenuItem mySaveBtn
MenuItem mySaveAsBtn
GUIGridReference myGridReference
PieceController myPieceController
PatchController myPatchController
LevelController myLevelController
ActionController myActionController
GameAuthoringData myTotalData
ActionData myActionData
LevelData myLevelData
PieceTypeData myPieceTypes
PatchTypeData myPatchTypes
GamePropertiesData myGamePropertiesData
PlayerStatData myPlayerStatData
Detailed Description
Definition at line 40 of file AuthoringController.java.
Member Function Documentation
void fxml_main.AuthoringController.initData (GamePropertiesData gamePropertiesData)
Definition at line 179 of file AuthoringController.java.
References authoring.data.GamePropertiesData.getGridShape().
Referenced by fxml_main.GUIcontainerController.LoadNewAuthoring().
void fxml_main.AuthoringController.initialize (URL fxmlFileLocation, ResourceBundle resources)
Definition at line 95 of file AuthoringController.java.
void fxml_main.AuthoringController.saveAsGame () private
Definition at line 159 of file AuthoringController.java.
References gamedata.gamecomponents.Game.addPlayers(), authoring.data.GameAuthoringData.createGame(), and gamePlayer.ViewController.testPlayGame().
void fxml_main.AuthoringController.saveGame () private
Definition at line 138 of file AuthoringController.java.
References authoring.data.GameAuthoringData.createGame(), and gamedata.JSON.JSONManager.writeToJSON().
void fxml_main.AuthoringController.showActionslogicChartWindow () throws IOException private
Definition at line 108 of file AuthoringController.java.
References authoring.actionslogic.ActionLogicController.getData().
void fxml_main.AuthoringController.showGamePropertiesWindow () private
Definition at line 123 of file AuthoringController.java.
void fxml_main.AuthoringController.showPlayerEditWindow () private
Definition at line 128 of file AuthoringController.java.
Member Data Documentation
MenuItem fxml_main.AuthoringController.actonsLogicChart private
Definition at line 64 of file AuthoringController.java.
MenuItem fxml_main.AuthoringController.gameProperties private
Definition at line 67 of file AuthoringController.java.
ActionController fxml_main.AuthoringController.myActionController private
Definition at line 82 of file AuthoringController.java.
ActionData fxml_main.AuthoringController.myActionData private
Definition at line 86 of file AuthoringController.java.
VBox fxml_main.AuthoringController.myActionsVBox private
Definition at line 56 of file AuthoringController.java.
GamePropertiesData fxml_main.AuthoringController.myGamePropertiesData private
Definition at line 90 of file AuthoringController.java.
GUIGridReference fxml_main.AuthoringController.myGridReference private
Definition at line 78 of file AuthoringController.java.
ScrollPane fxml_main.AuthoringController.myGridSPane private
Definition at line 59 of file AuthoringController.java.
LevelController fxml_main.AuthoringController.myLevelController private
Definition at line 81 of file AuthoringController.java.
LevelData fxml_main.AuthoringController.myLevelData private
Definition at line 87 of file AuthoringController.java.
VBox fxml_main.AuthoringController.myLevelsVBox private
Definition at line 47 of file AuthoringController.java.
PatchController fxml_main.AuthoringController.myPatchController private
Definition at line 80 of file AuthoringController.java.
VBox fxml_main.AuthoringController.myPatchesVBox private
Definition at line 53 of file AuthoringController.java.
PatchTypeData fxml_main.AuthoringController.myPatchTypes private
Definition at line 89 of file AuthoringController.java.
PieceController fxml_main.AuthoringController.myPieceController private
Definition at line 79 of file AuthoringController.java.
VBox fxml_main.AuthoringController.myPiecesVBox private
Definition at line 50 of file AuthoringController.java.
PieceTypeData fxml_main.AuthoringController.myPieceTypes private
Definition at line 88 of file AuthoringController.java.
PlayerStatData fxml_main.AuthoringController.myPlayerStatData private
Definition at line 91 of file AuthoringController.java.
ScrollPane fxml_main.AuthoringController.myPropertiesSPane private
Definition at line 44 of file AuthoringController.java.
MenuItem fxml_main.AuthoringController.mySaveAsBtn private
Definition at line 76 of file AuthoringController.java.
MenuItem fxml_main.AuthoringController.mySaveBtn private
Definition at line 73 of file AuthoringController.java.
GameAuthoringData fxml_main.AuthoringController.myTotalData private
Definition at line 85 of file AuthoringController.java.
MenuItem fxml_main.AuthoringController.playerEditor private
Definition at line 70 of file AuthoringController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/AuthoringController.java