voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.GameState Class Reference
gamedata.gamecomponents.GameState Class Reference
Static Public Member Functions
static boolean getGameWon ()
static int getMoves ()
static void resetMoves ()
static boolean getGameLost ()
static boolean getTurnOver ()
static String getNextLevelID ()
static void setTurnFalse ()
static void winGame ()
static void loseGame ()
static void endTurn ()
static void changeLevel (String name)
static void printState ()
Static Public Attributes
static boolean gameWon
static boolean gameLost
static boolean turnOver
static String nextLevelID
static List< Player > playersList
static int movesMade =0
Detailed Description
Definition at line 7 of file GameState.java.
Member Function Documentation
static void gamedata.gamecomponents.GameState.changeLevel (String name) static
Definition at line 58 of file GameState.java.
Referenced by gamedata.events.globalaction.LevelChange.doBehavior().
static void gamedata.gamecomponents.GameState.endTurn () static
Definition at line 54 of file GameState.java.
Referenced by gamedata.events.globalaction.EndTurn.doBehavior().
static boolean gamedata.gamecomponents.GameState.getGameLost () static
Definition at line 27 of file GameState.java.
References gamedata.gamecomponents.GameState.gameLost.
Referenced by gamePlayer.ViewController.checkEndActions().
static boolean gamedata.gamecomponents.GameState.getGameWon () static
Definition at line 16 of file GameState.java.
References gamedata.gamecomponents.GameState.gameWon.
Referenced by gamePlayer.ViewController.checkEndActions().
static int gamedata.gamecomponents.GameState.getMoves () static
Definition at line 20 of file GameState.java.
References gamedata.gamecomponents.GameState.movesMade.
Referenced by gamedata.events.conditions.MovesReachedEquals.evaluate().
static String gamedata.gamecomponents.GameState.getNextLevelID () static
Definition at line 35 of file GameState.java.
References gamedata.gamecomponents.GameState.nextLevelID.
Referenced by gamePlayer.ViewController.checkEndActions().
static boolean gamedata.gamecomponents.GameState.getTurnOver () static
Definition at line 31 of file GameState.java.
References gamedata.gamecomponents.GameState.turnOver.
Referenced by gamePlayer.ViewController.checkEndActions().
static void gamedata.gamecomponents.GameState.loseGame () static
Definition at line 50 of file GameState.java.
Referenced by gamedata.events.globalaction.LoseGame.doBehavior().
static void gamedata.gamecomponents.GameState.printState () static
Definition at line 62 of file GameState.java.
static void gamedata.gamecomponents.GameState.resetMoves () static
Definition at line 24 of file GameState.java.
Referenced by gamedata.events.globalaction.EndTurn.doBehavior().
static void gamedata.gamecomponents.GameState.setTurnFalse () static
Definition at line 39 of file GameState.java.
Referenced by gamePlayer.ViewController.checkEndActions().
static void gamedata.gamecomponents.GameState.winGame () static
IChangeGameState interface methods
Definition at line 46 of file GameState.java.
Referenced by gamedata.events.globalaction.WinGame.doBehavior().
Member Data Documentation
boolean gamedata.gamecomponents.GameState.gameLost static
Definition at line 10 of file GameState.java.
Referenced by gamedata.gamecomponents.GameState.getGameLost().
boolean gamedata.gamecomponents.GameState.gameWon static
Definition at line 9 of file GameState.java.
Referenced by gamedata.gamecomponents.GameState.getGameWon().
int gamedata.gamecomponents.GameState.movesMade =0 static
Definition at line 14 of file GameState.java.
Referenced by gamePlayer.ViewController.checkEndActions(), and gamedata.gamecomponents.GameState.getMoves().
String gamedata.gamecomponents.GameState.nextLevelID static
Definition at line 12 of file GameState.java.
Referenced by gamedata.gamecomponents.GameState.getNextLevelID().
List<Player> gamedata.gamecomponents.GameState.playersList static
Definition at line 13 of file GameState.java.
Referenced by gamedata.events.globalaction.ChangePlayerStats.doBehavior().
boolean gamedata.gamecomponents.GameState.turnOver static
Definition at line 11 of file GameState.java.
Referenced by gamedata.gamecomponents.GameState.getTurnOver().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/GameState.java