voogasalad_VOOGirlsGeneration: gamePlayer.KeyboardAction Class Reference
gamePlayer.KeyboardAction Class Reference
Public Member Functions
KeyboardAction ()
void setActionKeyControl (ViewController vc)
void markAction (ViewController vc)
void useDefaultMap ()
Package Attributes
Player myCurrentPlayer
Point2D myCurrentLocation
GameGridEffect myGameGridEffect
List< Action > myActions
Action myCurrentAction
int myActionIndex
Map< KeyCode, Point2D.Double > myKeyMap
Static Private Attributes
static final double ACTION_LABEL_SHADOW_OFFSET = 6.0
Detailed Description
Allows users to use keyboard to "move the cursor" up and down the available actions in the Controls panel. KeyboardAction is strictly used for selecting actions in the Controls.
Author
Yoonhyung
Definition at line 25 of file KeyboardAction.java.
Constructor & Destructor Documentation
gamePlayer.KeyboardAction.KeyboardAction ()
Definition at line 35 of file KeyboardAction.java.
References gamePlayer.KeyboardAction.myKeyMap.
Member Function Documentation
void gamePlayer.KeyboardAction.markAction (ViewController vc)
Definition at line 84 of file KeyboardAction.java.
References gamedata.action.Action.getName().
Referenced by gamePlayer.KeyboardAction.setActionKeyControl().
void gamePlayer.KeyboardAction.setActionKeyControl (ViewController vc)
Definition at line 41 of file KeyboardAction.java.
References gamePlayer.ViewController.bindAction(), gamedata.gamecomponents.Piece.getActions(), gamePlayer.ViewController.getActivePiece(), gamePlayer.ViewController.getGridPane(), gamePlayer.KeyboardAction.markAction(), gamePlayer.KeyboardAction.myKeyMap, and gamePlayer.KeyboardAction.useDefaultMap().
Referenced by gamePlayer.ViewController.performAction().
void gamePlayer.KeyboardAction.useDefaultMap ()
Definition at line 98 of file KeyboardAction.java.
References gamePlayer.KeyboardAction.myKeyMap.
Referenced by gamePlayer.KeyboardAction.setActionKeyControl().
Member Data Documentation
final double gamePlayer.KeyboardAction.ACTION_LABEL_SHADOW_OFFSET = 6.0 static private
Definition at line 26 of file KeyboardAction.java.
int gamePlayer.KeyboardAction.myActionIndex package
Definition at line 32 of file KeyboardAction.java.
List<Action> gamePlayer.KeyboardAction.myActions package
Definition at line 30 of file KeyboardAction.java.
Action gamePlayer.KeyboardAction.myCurrentAction package
Definition at line 31 of file KeyboardAction.java.
Point2D gamePlayer.KeyboardAction.myCurrentLocation package
Definition at line 28 of file KeyboardAction.java.
Player gamePlayer.KeyboardAction.myCurrentPlayer package
Definition at line 27 of file KeyboardAction.java.
GameGridEffect gamePlayer.KeyboardAction.myGameGridEffect package
Definition at line 29 of file KeyboardAction.java.
Map<KeyCode, Point2D.Double> gamePlayer.KeyboardAction.myKeyMap package
Definition at line 33 of file KeyboardAction.java.
Referenced by gamePlayer.KeyboardAction.KeyboardAction(), gamePlayer.KeyboardAction.setActionKeyControl(), and gamePlayer.KeyboardAction.useDefaultMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/KeyboardAction.java