voogasalad_VOOGirlsGeneration: authoring.concretefeatures.StatsCreatorBox Class Reference
authoring.concretefeatures.StatsCreatorBox Class Reference
Public Member Functions
StatsCreatorBox ()
StatsCreatorBox (String name, double value)
String getStatName ()
double getStatValue ()
boolean isEmpty ()
Static Protected Attributes
static final String DEFAULT_STAT = ""
Private Member Functions
void initStatsCreatorBox ()
void initTextField (TextField tf, int width, String prompt)
Private Attributes
TextField myStatField
TextField myValueField
Static Private Attributes
static final int STAT_BOX_WIDTH = 150
static final int VALUE_BOX_WIDTH = 150
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
static final String STAT_PROMPT = "Enter stat name"
static final String VALUE_PROMPT = "Enter stat value (real number)"
static final double DEFAULT_VALUE = 0
static final String EQUALS_LABEL = "="
Detailed Description
Creates a new Hbox view that allows users to define and edit stats for different types of pieces
Author
Jennie Ju
Definition at line 14 of file StatsCreatorBox.java.
Constructor & Destructor Documentation
authoring.concretefeatures.StatsCreatorBox.StatsCreatorBox ()
Constructor for a new empty StatsCreatorBox
Definition at line 32 of file StatsCreatorBox.java.
References authoring.concretefeatures.StatsCreatorBox.initStatsCreatorBox().
authoring.concretefeatures.StatsCreatorBox.StatsCreatorBox (String name, double value)
Constructor for a StatsCreatorBox to display already defined Stats
Parameters
name - String name of the Stat
value - double value of the Stat
Definition at line 42 of file StatsCreatorBox.java.
References authoring.concretefeatures.StatsCreatorBox.initStatsCreatorBox().
Member Function Documentation
String authoring.concretefeatures.StatsCreatorBox.getStatName ()
Gets the string name of the Stat
Returns
string name of the Stat
Definition at line 52 of file StatsCreatorBox.java.
Referenced by authoring.concretefeatures.StatsTotalEditor.makeDeleteButton().
double authoring.concretefeatures.StatsCreatorBox.getStatValue ()
Gets the value of the Stat as a double
Returns
double value of the Stat
Definition at line 61 of file StatsCreatorBox.java.
References authoring.concretefeatures.StatsCreatorBox.DEFAULT_VALUE.
void authoring.concretefeatures.StatsCreatorBox.initStatsCreatorBox () private
Definition at line 73 of file StatsCreatorBox.java.
References authoring.concretefeatures.StatsCreatorBox.initTextField().
Referenced by authoring.concretefeatures.StatsCreatorBox.StatsCreatorBox().
void authoring.concretefeatures.StatsCreatorBox.initTextField (TextField tf, int width, String prompt) private
Definition at line 84 of file StatsCreatorBox.java.
Referenced by authoring.concretefeatures.StatsCreatorBox.initStatsCreatorBox().
boolean authoring.concretefeatures.StatsCreatorBox.isEmpty ()
Definition at line 69 of file StatsCreatorBox.java.
Member Data Documentation
final String authoring.concretefeatures.StatsCreatorBox.DEFAULT_STAT = "" static protected
Definition at line 21 of file StatsCreatorBox.java.
final double authoring.concretefeatures.StatsCreatorBox.DEFAULT_VALUE = 0 static private
Definition at line 22 of file StatsCreatorBox.java.
Referenced by authoring.concretefeatures.StatsCreatorBox.getStatValue().
final String authoring.concretefeatures.StatsCreatorBox.EQUALS_LABEL = "=" static private
Definition at line 24 of file StatsCreatorBox.java.
TextField authoring.concretefeatures.StatsCreatorBox.myStatField private
Definition at line 26 of file StatsCreatorBox.java.
TextField authoring.concretefeatures.StatsCreatorBox.myValueField private
Definition at line 27 of file StatsCreatorBox.java.
final int authoring.concretefeatures.StatsCreatorBox.STAT_BOX_WIDTH = 150 static private
Definition at line 15 of file StatsCreatorBox.java.
final String authoring.concretefeatures.StatsCreatorBox.STAT_PROMPT = "Enter stat name" static private
Definition at line 19 of file StatsCreatorBox.java.
final String authoring.concretefeatures.StatsCreatorBox.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 17 of file StatsCreatorBox.java.
final int authoring.concretefeatures.StatsCreatorBox.VALUE_BOX_WIDTH = 150 static private
Definition at line 16 of file StatsCreatorBox.java.
final String authoring.concretefeatures.StatsCreatorBox.VALUE_PROMPT = "Enter stat value (real number)" static private
Definition at line 20 of file StatsCreatorBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/StatsCreatorBox.java