voogasalad_VOOGirlsGeneration: gameengine.movement.Movement Class Reference
gameengine.movement.Movement Class Reference
Public Member Functions
Movement (List< Point2D.Double >...endPoints)
List< Point2D.Double > getPossibleLocs (int x, int y)
boolean isValidLocation (int x, int y)
List< Point2D.Double > getAbsoluteActionRange (Point2D pieceLocation)
List< Point2D.Double > getEffectRange ()
void doBehavior (GUIGrid grid, Piece actor, Piece...receivers)
String toString ()
List< Point2D.Double > getActionRange ()
List< Point2D.Double > getRelativeMoves ()
String getName ()
List< Double > getAbsoluteEffectRange (Point2D pieceLocation)
Private Member Functions
boolean checkPathCollision (GUIGrid myGrid, Point2D endPoint)
Private Attributes
List< Point2D.Double > myMoves
List< Point2D.Double > myAbsoluteMoves
List< List< Point2D.Double > > myPaths
transient GUIGrid myGrid
transient Orientator myOrientator
double myOrientation
String myName
Detailed Description
Defines the movement of a piece. Responsible for maintaining the behavior properties of a piece and executing allowed movements
Author
Jesse, Rica
Definition at line 32 of file Movement.java.
Constructor & Destructor Documentation
gameengine.movement.Movement.Movement (List< Point2D.Double >... endPoints)
Constructor
Parameters
g The GUIGrid that the piece containing this movement exists on
endPoints Point2Ds representing all possible relative locations of movement
Definition at line 79 of file Movement.java.
References gameengine.movement.Movement.myMoves, and gameengine.movement.Movement.myPaths.
Member Function Documentation
boolean gameengine.movement.Movement.checkPathCollision (GUIGrid myGrid, Point2D endPoint) private
Checks the collisions in the currently defined path. Checks with piece and patch collisions.
Returns
true or false depending on whether a collision is detected on a path
Definition at line 142 of file Movement.java.
void gameengine.movement.Movement.doBehavior (GUIGrid grid, Piece actor, Piece... receivers)
Contains the logic to execute the behavior of moving the piece
Implements gamedata.action.Action.
Definition at line 172 of file Movement.java.
References gamedata.gamecomponents.GridComponent.getLoc(), gameengine.movement.Movement.isValidLocation(), authoring_environment.GUIGrid.repopulateGrid(), and gamedata.gamecomponents.GridComponent.setLoc().
List<Point2D.Double> gameengine.movement.Movement.getAbsoluteActionRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the action range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 158 of file Movement.java.
References gameengine.movement.Movement.getPossibleLocs().
List<Double> gameengine.movement.Movement.getAbsoluteEffectRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the effect range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 250 of file Movement.java.
List<Point2D.Double> gameengine.movement.Movement.getActionRange ()
Gives back a list of Point2D of relative locations for the action range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 228 of file Movement.java.
List<Point2D.Double> gameengine.movement.Movement.getEffectRange ()
Gives back a list of Point2D of relative locations for the effect range of the action (splashzone)
Returns
list of relative locations in Point2D
Implements gamedata.action.Action.
Definition at line 164 of file Movement.java.
String gameengine.movement.Movement.getName ()
Returns the name of the Action for display
Returns
name of Action
Implements gamedata.action.Action.
Definition at line 245 of file Movement.java.
References gameengine.movement.Movement.myName.
List<Point2D.Double> gameengine.movement.Movement.getPossibleLocs (int x, int y)
Return absolute possible x,y coordinates of movement based on current location x,y
Parameters
x Current x coordinate
y Current y coordinate
Returns
List of Point2D corresponding to absolute locations of movement
Definition at line 107 of file Movement.java.
References gameengine.movement.Movement.myAbsoluteMoves, and gameengine.movement.Movement.myMoves.
Referenced by gameengine.movement.Movement.getAbsoluteActionRange().
List<Point2D.Double> gameengine.movement.Movement.getRelativeMoves ()
Getter method for the list of relative moves. This method is needed by the PieceTypeEditor, so do not delete it!
Returns
: List of locations a piece can move to relative to its current location.
Definition at line 240 of file Movement.java.
References gameengine.movement.Movement.myMoves.
Referenced by fxml_main.PieceTypeEditor.initRangeEditorButton().
boolean gameengine.movement.Movement.isValidLocation (int x, int y)
Checks to see if an absolute location (x,y) is a valid location for movement and that the destination is empty (no pieces overlapping)
Parameters
x Absolute coordinate x
y Absolute coordinate y
Returns
Definition at line 125 of file Movement.java.
References authoring_environment.GUIGrid.getPiece(), and gameengine.movement.Movement.myAbsoluteMoves.
Referenced by gameengine.movement.Movement.doBehavior().
String gameengine.movement.Movement.toString ()
Returns the information about the Action for display
Returns
name of Action
Implements gamedata.action.Action.
Definition at line 211 of file Movement.java.
References gameengine.movement.Movement.myMoves, and gameengine.movement.Movement.myPaths.
Referenced by fxml_main.PieceTypeEditor.initGoBtn(), and gamedata.gamecomponents.Piece.printString().
Member Data Documentation
List<Point2D.Double> gameengine.movement.Movement.myAbsoluteMoves private
Point2Ds referring to currently calculated absolute positions of movement
Definition at line 42 of file Movement.java.
Referenced by gameengine.movement.Movement.getPossibleLocs(), and gameengine.movement.Movement.isValidLocation().
transient GUIGrid gameengine.movement.Movement.myGrid private
Grid the Piece is on and movement will be execute on
Definition at line 52 of file Movement.java.
List<Point2D.Double> gameengine.movement.Movement.myMoves private
Point2Ds referring to relative positions of movement
Definition at line 37 of file Movement.java.
Referenced by gameengine.movement.Movement.getPossibleLocs(), gameengine.movement.Movement.getRelativeMoves(), gameengine.movement.Movement.Movement(), and gameengine.movement.Movement.toString().
String gameengine.movement.Movement.myName private
Name of the action for display in the Player
Definition at line 67 of file Movement.java.
Referenced by gameengine.movement.Movement.getName().
double gameengine.movement.Movement.myOrientation private
Orientation of the piece (depending on last movement made)
Definition at line 62 of file Movement.java.
transient Orientator gameengine.movement.Movement.myOrientator private
Orientator resonsible for calculating orientations
Definition at line 57 of file Movement.java.
List<List<Point2D.Double> > gameengine.movement.Movement.myPaths private
List of Point2Ds referring to relative paths of movement
Definition at line 47 of file Movement.java.
Referenced by gameengine.movement.Movement.Movement(), and gameengine.movement.Movement.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gameengine/movement/Movement.java