voogasalad_VOOGirlsGeneration: fxml_main.PieceController Class Reference
fxml_main.PieceController Class Reference
Public Member Functions
PieceController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, PieceTypeData pieceTypes, ActionData actions, GamePropertiesData gamePropertiesData)
Protected Member Functions
void initGlobalNewBtn (Button newBtn)
void initGlobalEditBtn (Button editBtn)
void initGlobalDelBtn (Button delBtn)
HBox makeEntryBox (Piece entry)
void initEntryEditBtn (Piece entry, Button editBtn)
void initEntryDelBtn (Piece entry, Button delBtn)
Protected Member Functions inherited from fxml_main.GridComponentAbstCtrl< Piece >
GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef)
abstract void initGlobalNewBtn (Button newBtn)
abstract void initGlobalEditBtn (Button editBtn)
abstract void initGlobalDelBtn (Button delBtn)
void addEntry (T entry)
HBox makeCompleteEntryBox (T entry)
HBox initEntryControls (T entry)
abstract HBox makeEntryBox (T entry)
abstract void initEntryEditBtn (T entry, Button editBtn)
abstract void initEntryDelBtn (T entry, Button delBtn)
Private Attributes
PieceTypeData myPieceTypes
ActionData myActionData
GamePropertiesData myGameProperties
Additional Inherited Members
Protected Attributes inherited from fxml_main.GridComponentAbstCtrl< Piece >
VBox myVBox
ScrollPane myPropertiesSPane
GUIGridReference myGridReference
Map< T, HBox > myEntryMap
Detailed Description
Author
Martin Tamayo
Definition at line 25 of file PieceController.java.
Constructor & Destructor Documentation
fxml_main.PieceController.PieceController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, PieceTypeData pieceTypes, ActionData actions, GamePropertiesData gamePropertiesData)
Definition at line 31 of file PieceController.java.
Member Function Documentation
void fxml_main.PieceController.initEntryDelBtn (Piece entry, Button delBtn) protected
Definition at line 150 of file PieceController.java.
References fxml_main.GridComponentAbstCtrl< Piece >.myEntryMap, fxml_main.GridComponentAbstCtrl< Piece >.myVBox, and authoring.data.PieceTypeData.remove().
void fxml_main.PieceController.initEntryEditBtn (Piece entry, Button editBtn) protected
Definition at line 128 of file PieceController.java.
References fxml_main.GridComponentAbstCtrl< Piece >.makeCompleteEntryBox(), fxml_main.GridComponentAbstCtrl< Piece >.myEntryMap, fxml_main.GridComponentAbstCtrl< Piece >.myPropertiesSPane, and authoring.data.PieceTypeData.replace().
void fxml_main.PieceController.initGlobalDelBtn (Button delBtn) protected
Definition at line 81 of file PieceController.java.
References authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), fxml_main.GridComponentAbstCtrl< Piece >.myGridReference, authoring_environment.GUIGrid.paneSetOnMouseDragged(), authoring_environment.GUIGrid.paneSetOnMousePressed(), and authoring_environment.GUIGrid.removePieceAtCoordinate().
void fxml_main.PieceController.initGlobalEditBtn (Button editBtn) protected
Definition at line 58 of file PieceController.java.
References authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), authoring_environment.GUIGrid.getPiece(), fxml_main.GridComponentAbstCtrl< Piece >.myGridReference, fxml_main.GridComponentAbstCtrl< Piece >.myPropertiesSPane, authoring_environment.GUIGrid.paneSetOnMouseDragged(), and authoring_environment.GUIGrid.paneSetOnMousePressed().
void fxml_main.PieceController.initGlobalNewBtn (Button newBtn) protected
Definition at line 41 of file PieceController.java.
References authoring.data.PieceTypeData.add(), fxml_main.GridComponentAbstCtrl< Piece >.addEntry(), and fxml_main.GridComponentAbstCtrl< Piece >.myPropertiesSPane.
HBox fxml_main.PieceController.makeEntryBox (Piece entry) protected
Definition at line 101 of file PieceController.java.
References authoring_environment.GUIGrid.addPieceAtLoc(), authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), gamedata.gamecomponents.GridComponent.getImageView(), gamedata.gamecomponents.GridComponent.getName(), fxml_main.GridComponentAbstCtrl< Piece >.myGridReference, authoring_environment.GUIGrid.paneSetOnMouseDragged(), and authoring_environment.GUIGrid.paneSetOnMousePressed().
Member Data Documentation
ActionData fxml_main.PieceController.myActionData private
Definition at line 28 of file PieceController.java.
GamePropertiesData fxml_main.PieceController.myGameProperties private
Definition at line 29 of file PieceController.java.
PieceTypeData fxml_main.PieceController.myPieceTypes private
Definition at line 27 of file PieceController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PieceController.java