voogasalad_VOOGirlsGeneration: authoring.concretefeatures.ActionCheck Class Reference
authoring.concretefeatures.ActionCheck Class Reference
Public Member Functions
ActionCheck ()
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Member Functions
void initReceiverChooser (VBox posReceiverVBox, ChoiceBox< String > posActors, ChoiceBox< String > actionTypes)
void initActorChooser (VBox posActorVBox, ChoiceBox< String > posActors)
void initActionChooser (VBox nameVBox, ChoiceBox< String > actionTypes)
Private Attributes
final int HEIGHT = 400
final int WIDTH = 400
final String NAME = "Available Actions for Units"
final String ACTION_TYPE = "Action Type"
final String ACTOR = "Actor"
final String RECEIVER = "Receiver"
List< Action > myActions
List< String > myPieces = new ArrayList<String>()
Map< String, Map > Conclusion
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/actioncreator_layout.css"
Detailed Description
GUI component that checks, for each type of actions, which pieces can perform this action and which other pieces can receive this action
Definition at line 30 of file ActionCheck.java.
Constructor & Destructor Documentation
authoring.concretefeatures.ActionCheck.ActionCheck ()
Constructor for ActionCheck popup window
Parameters
actionLst List of all the actions
pieceLst List of pieces
patchLst List of patches
Definition at line 69 of file ActionCheck.java.
References authoring.concretefeatures.ActionCheck.initialize().
Member Function Documentation
void authoring.concretefeatures.ActionCheck.initActionChooser (VBox nameVBox, ChoiceBox< String > actionTypes) private
Definition at line 142 of file ActionCheck.java.
Referenced by authoring.concretefeatures.ActionCheck.initialize().
void authoring.concretefeatures.ActionCheck.initActorChooser (VBox posActorVBox, ChoiceBox< String > posActors) private
Definition at line 131 of file ActionCheck.java.
Referenced by authoring.concretefeatures.ActionCheck.initialize().
void authoring.concretefeatures.ActionCheck.initialize () protected
Definition at line 79 of file ActionCheck.java.
References authoring.concretefeatures.ActionCheck.initActionChooser(), authoring.concretefeatures.ActionCheck.initActorChooser(), and authoring.concretefeatures.ActionCheck.initReceiverChooser().
Referenced by authoring.concretefeatures.ActionCheck.ActionCheck().
void authoring.concretefeatures.ActionCheck.initReceiverChooser (VBox posReceiverVBox, ChoiceBox< String > posActors, ChoiceBox< String > actionTypes) private
Definition at line 111 of file ActionCheck.java.
Referenced by authoring.concretefeatures.ActionCheck.initialize().
Member Data Documentation
final String authoring.concretefeatures.ActionCheck.ACTION_TYPE = "Action Type" private
Definition at line 35 of file ActionCheck.java.
final String authoring.concretefeatures.ActionCheck.ACTOR = "Actor" private
Definition at line 36 of file ActionCheck.java.
Map<String, Map> authoring.concretefeatures.ActionCheck.Conclusion private
Definition at line 43 of file ActionCheck.java.
final int authoring.concretefeatures.ActionCheck.HEIGHT = 400 private
Definition at line 32 of file ActionCheck.java.
List<Action> authoring.concretefeatures.ActionCheck.myActions private
Definition at line 39 of file ActionCheck.java.
List<String> authoring.concretefeatures.ActionCheck.myPieces = new ArrayList<String>() private
Definition at line 42 of file ActionCheck.java.
final String authoring.concretefeatures.ActionCheck.NAME = "Available Actions for Units" private
Definition at line 34 of file ActionCheck.java.
final String authoring.concretefeatures.ActionCheck.RECEIVER = "Receiver" private
Definition at line 37 of file ActionCheck.java.
final String authoring.concretefeatures.ActionCheck.STYLESHEET = "/resources/stylesheets/actioncreator_layout.css" static private
Definition at line 45 of file ActionCheck.java.
final int authoring.concretefeatures.ActionCheck.WIDTH = 400 private
Definition at line 33 of file ActionCheck.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/ActionCheck.java