voogasalad_VOOGirlsGeneration: gamePlayer.Languages Class Reference
gamePlayer.Languages Class Reference
Public Member Functions
Languages (AnchorPane ap, TabPane tp, MenuButton mb, Button b)
void findCurrentLanguage ()
void updateLabels ()
Static Public Attributes
static final String DEFAULT_LANGUAGE = "resources.languages.English"
Private Attributes
ResourceBundle messages
String currentLanguage
Button showScoreButton
MenuButton gameMenu
TabPane tabPane
AnchorPane languagesPane
Detailed Description
Controls the languages used in the game
Author
Yoonhyung
Definition at line 18 of file Languages.java.
Constructor & Destructor Documentation
gamePlayer.Languages.Languages (AnchorPane ap, TabPane tp, MenuButton mb, Button b)
Definition at line 30 of file Languages.java.
References gamePlayer.Languages.DEFAULT_LANGUAGE.
Member Function Documentation
void gamePlayer.Languages.findCurrentLanguage ()
Checks the currently selected language
Definition at line 41 of file Languages.java.
References gamePlayer.Languages.updateLabels().
Referenced by gamePlayer.ViewController.updateLanguage().
void gamePlayer.Languages.updateLabels ()
Updates the game labels according to the selected language in settings
Definition at line 53 of file Languages.java.
Referenced by gamePlayer.Languages.findCurrentLanguage().
Member Data Documentation
String gamePlayer.Languages.currentLanguage private
Definition at line 23 of file Languages.java.
final String gamePlayer.Languages.DEFAULT_LANGUAGE = "resources.languages.English" static
Definition at line 20 of file Languages.java.
Referenced by gamePlayer.Languages.Languages().
MenuButton gamePlayer.Languages.gameMenu private
Definition at line 25 of file Languages.java.
AnchorPane gamePlayer.Languages.languagesPane private
Definition at line 27 of file Languages.java.
ResourceBundle gamePlayer.Languages.messages private
Definition at line 22 of file Languages.java.
Button gamePlayer.Languages.showScoreButton private
Definition at line 24 of file Languages.java.
TabPane gamePlayer.Languages.tabPane private
Definition at line 26 of file Languages.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/Languages.java