voogasalad_VOOGirlsGeneration: gamePlayer.ViewController Class Reference
gamePlayer.ViewController Class Reference
Public Member Functions
ViewController (Stage s) throws UnsupportedAudioFileException, IOException, LineUnavailableException
ViewController (Tab tab) throws UnsupportedAudioFileException, IOException, LineUnavailableException
void updateLanguage ()
void clearActions ()
void updateActionList (ArrayList< Label > actions)
void performAction (Point2D.Double myCurrentLocation)
void highlightSelected (Piece p)
Point2D.Double findPosition (double x, double y)
void toggleClickSound ()
void toggleBackgroundMusic () throws UnsupportedAudioFileException, IOException, LineUnavailableException
void toggleKeyboardControl ()
Point2D.Double getCurrentClick ()
IGridState getGridState ()
void setGridState (IGridState state)
VBox getcontrolPane ()
void checkEndActions ()
void testPlayGUIGame (Game gameToLoad)
void testPlayGame (Game gameToLoad)
Static Public Attributes
static final String ADD_HIGH_SCORE_FXML = "newHighScore.fxml"
static final String GAMESPACE_FXML = "gameSpace.fxml"
static final String INITIALSCENE_FXML = "initialScene.fxml"
static final String SCOREBOARD_FXML = "scoreBoard.fxml"
static final String PLAYER_FXML = "playerEditorScene.fxml"
static final String INITIALSCENE_TITLE = "VOOGASALAD!"
static final String GAME_LOCATION = "/src/resources/json"
static final String POPUP_FXML = "popup.fxml"
static final String SETTINGS_FXML = "settings.fxml"
Protected Member Functions
void openInitialGUIMenu () throws UnsupportedAudioFileException, IOException, LineUnavailableException
void openInitialMenu () throws UnsupportedAudioFileException, IOException, LineUnavailableException
void loadGame ()
void openSettings ()
void restartGame ()
void exitGame ()
void saveGame ()
void showScore ()
void cancelPopup ()
void editGUIPlayers (Game myGame)
void editPlayers (Game myGame)
void updatePlayers ()
void newGame () throws UnsupportedAudioFileException, IOException, LineUnavailableException
void loadScores ()
void updateInventory (Piece piece)
void updateStats (Piece piece)
void updateActions (Piece piece)
void bindAction (Action action)
Action getActiveAction ()
Scene getScene ()
ScrollPane getGridPane ()
GUIGrid getGrid ()
Game getGame ()
Piece getActivePiece ()
void setActivePiece (Piece piece)
void setActiveAction (Action action)
GameGridEffect getGameGridEffect ()
void endAction ()
Protected Attributes
VBox statsPane
VBox inventoryPane
VBox controlPane
Package Functions
void setPlayerTurnDisplay ()
Private Member Functions
void loadGameInTab ()
void testPlayGameInTab (Game readFromJSONFile)
void testGame ()
void editSpecificPlayer (int playerID)
void removePreviousPlayer (int playerID)
void loadFXML (String url, Node n)
void initializeGrid ()
List< File > getResourceGames ()
void setOnClick ()
void enterHighScoreInfo (String highScorer, int highScore)
void addEntryToHallOfFame (Stage stage, String nickname, int score)
void handleClearHighScores ()
Private Attributes
Stage myStage
BorderPane myGameSpace
BorderPane myPopup
VBox mySettings
VBox myInitialScene
VBox myScoreBoard
BorderPane editPlayerRoot
Scene mySettingsScene
Scene scoreScene
Scene myPopupScene
Scene myPlayerScene
Scene myScene
Scene newHighScoreScene
Scene winLoseScene
Game myModel
GUIGrid myGrid
Stage mySplashStage
Player myCurrentPlayer
Boolean keyControlOn
Boolean clickSoundOn
Boolean backgroundMusicOn
Boolean actionActiveOn
KeyboardAction myKeyboardAction
KeyboardMovement myKeyboardMovement
Piece activePiece
Action activeAction
Audio myAudio
List< Player > myPlayerList
Tab myTab
MenuButton newGameMenu
Text gameName
Text highestScore
VBox scores
Label playerTurn
Button showScoreButton
MenuButton gameMenu
TabPane tabPane
AnchorPane languagesPane
Button clearHighScores
ChoiceBox players
ChoiceBox playerType
TextField playerName
GridPane newHighScoreRoot
TextField highScoreName
Label playerHighScore
Button highScoreOK
BorderPane myWinLoseScreen
Label winLose
VBox playersList
TextField editPlayerName
ComboBox< String > playerTypeCombo
Button startGameButton
Button setPlayerButton
ScrollPane myGridPane
Point2D.Double currentClick
IGridState gridState
JSONManager myJSONManager
GameGridEffect myGameGridEffect
SuperTile keySelectedTile
int tempMoveCount = 0
Languages myLanguages
Static Private Attributes
static final String INVENTORY_FONT_NAME = "Consolas"
static final int ACTIONNAME_FONT_SIZE = 16
static final int ITEMNAME_FONT_SIZE = 24
static final String SIMPLE_AI_PLAYER = "Simple AI player"
static final String HUMAN_PLAYER = "Human Player"
static final String HIGH_SCORE_FILE = "/resources/highscore/highscore.txt"
static final String WIN_SCREEN = "winLoseScreen.fxml"
static final String YOU_LOSE = "You Lose :("
Detailed Description
Definition at line 66 of file ViewController.java.
Constructor & Destructor Documentation
gamePlayer.ViewController.ViewController (Stage s) throws UnsupportedAudioFileException, IOException, LineUnavailableException
Definition at line 191 of file ViewController.java.
References gamePlayer.ViewController.newGame(), and gamePlayer.ViewController.openInitialMenu().
gamePlayer.ViewController.ViewController (Tab tab) throws UnsupportedAudioFileException, IOException, LineUnavailableException
Definition at line 210 of file ViewController.java.
References gamePlayer.ViewController.loadGameInTab(), and gamePlayer.ViewController.openInitialGUIMenu().
Member Function Documentation
void gamePlayer.ViewController.addEntryToHallOfFame (Stage stage, String nickname, int score) private
Adds new high score to the hall of fame
Parameters
stage
nickname
score
Definition at line 1085 of file ViewController.java.
Referenced by gamePlayer.ViewController.enterHighScoreInfo().
void gamePlayer.ViewController.bindAction (Action action) protected
Method called when user clicks an action button
Parameters
action
Definition at line 762 of file ViewController.java.
References gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.Audio.playSelection(), gamePlayer.ViewController.setActiveAction(), gamePlayer.ViewController.setGridState(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
Referenced by tests.ViewControllerTest.bindActionTest(), gamePlayer.KeyboardAction.setActionKeyControl(), and gamePlayer.ViewController.updateActions().
void gamePlayer.ViewController.cancelPopup () protected
Definition at line 457 of file ViewController.java.
void gamePlayer.ViewController.checkEndActions ()
Definition at line 1153 of file ViewController.java.
References gamedata.gamecomponents.Game.changeLevel(), gamePlayer.ViewController.enterHighScoreInfo(), gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Game.getCurrentPlayer(), gamedata.gamecomponents.GameState.getGameLost(), gamedata.gamecomponents.GameState.getGameWon(), gamedata.gamecomponents.GameState.getNextLevelID(), gamedata.gamecomponents.Game.getPlayers(), gamedata.gamecomponents.GameState.getTurnOver(), gamePlayer.ViewController.initializeGrid(), gamedata.gamecomponents.GameState.movesMade, gamedata.gamecomponents.Game.nextPlayer(), gameengine.player.Player.playTurn(), authoring_environment.GUIGrid.repopulateGrid(), gamedata.gamecomponents.Level.runGameEvents(), gamePlayer.ViewController.setPlayerTurnDisplay(), and gamedata.gamecomponents.GameState.setTurnFalse().
Referenced by gamePlayer.ViewController.endAction(), and gamePlayer.ViewController.performAction().
void gamePlayer.ViewController.clearActions ()
Clears control pane of actions after you've selected one to do
Definition at line 742 of file ViewController.java.
Referenced by gamePlayer.ApplyState.onClick().
void gamePlayer.ViewController.editGUIPlayers (Game myGame) protected
Starts screen to choose the type of players
Definition at line 464 of file ViewController.java.
References gamePlayer.ViewController.editSpecificPlayer(), and gamedata.gamecomponents.Game.getPlayers().
Referenced by gamePlayer.ViewController.loadGameInTab().
void gamePlayer.ViewController.editPlayers (Game myGame) protected
Definition at line 480 of file ViewController.java.
References gamePlayer.ViewController.editSpecificPlayer(), and gamedata.gamecomponents.Game.getPlayers().
Referenced by gamePlayer.ViewController.loadGame(), and gamePlayer.ViewController.testGame().
void gamePlayer.ViewController.editSpecificPlayer (int playerID) private
Definition at line 503 of file ViewController.java.
References gamedata.gamecomponents.Game.replacePlayer().
Referenced by gamePlayer.ViewController.editGUIPlayers(), and gamePlayer.ViewController.editPlayers().
void gamePlayer.ViewController.endAction () protected
Definition at line 1147 of file ViewController.java.
References gamePlayer.ViewController.checkEndActions().
Referenced by gamePlayer.ApplyState.onClick().
void gamePlayer.ViewController.enterHighScoreInfo (String highScorer, int highScore) private
Allows winning player to enter their information
Parameters
highScorer
highScore
Definition at line 1070 of file ViewController.java.
References gamePlayer.ViewController.addEntryToHallOfFame().
Referenced by gamePlayer.ViewController.checkEndActions().
void gamePlayer.ViewController.exitGame () protected
Definition at line 400 of file ViewController.java.
Point2D.Double gamePlayer.ViewController.findPosition (double x, double y)
Method to convert pixel coordinates into tile coordinates
Parameters
x
y
Returns
a Point2D.Double representing tile coordinates
Definition at line 851 of file ViewController.java.
References gamePlayer.ViewController.currentClick, and authoring_environment.SuperGrid.findClickedCoordinate().
Referenced by tests.ViewControllerTest.findPositionTest(), and gamePlayer.ViewController.setOnClick().
Action gamePlayer.ViewController.getActiveAction () protected
Getter for the Active Action
Returns
Definition at line 943 of file ViewController.java.
References gamePlayer.ViewController.activeAction.
Referenced by tests.ViewControllerTest.bindActionTest(), gamePlayer.GameGridEffect.GameGridEffect(), gamePlayer.GameGridEffect.highlightEffectRange(), gamePlayer.ApplyState.onClick(), and gamePlayer.GameGridEffect.updateActives().
Piece gamePlayer.ViewController.getActivePiece () protected
Getter to get the Active Piece
Returns
Definition at line 990 of file ViewController.java.
References gamePlayer.ViewController.activePiece.
Referenced by gamePlayer.GameGridEffect.GameGridEffect(), gamePlayer.ApplyState.onClick(), gamePlayer.KeyboardAction.setActionKeyControl(), and gamePlayer.GameGridEffect.updateActives().
VBox gamePlayer.ViewController.getcontrolPane ()
Definition at line 1143 of file ViewController.java.
References gamePlayer.ViewController.controlPane.
Referenced by gamePlayer.KeyboardAction.markAction().
Point2D.Double gamePlayer.ViewController.getCurrentClick ()
Returns a Point2D.Double representing the Location of a Click
Returns
Definition at line 925 of file ViewController.java.
References gamePlayer.ViewController.currentClick.
Referenced by gamePlayer.ApplyState.onClick().
Game gamePlayer.ViewController.getGame () protected
Getter to get the Game
Returns
Definition at line 981 of file ViewController.java.
References gamePlayer.ViewController.myModel.
Referenced by gamePlayer.SelectState.onClick(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
GameGridEffect gamePlayer.ViewController.getGameGridEffect () protected
returns the GameGridEffect
Returns
Definition at line 1139 of file ViewController.java.
References gamePlayer.ViewController.myGameGridEffect.
Referenced by gamePlayer.ApplyState.ApplyState().
GUIGrid gamePlayer.ViewController.getGrid () protected
Getter to get the GUIGrid
Returns
Definition at line 972 of file ViewController.java.
References gamePlayer.ViewController.myGrid.
Referenced by gamePlayer.GameGridEffect.GameGridEffect(), gamePlayer.ApplyState.handleMouseMove(), gamePlayer.GameGridEffect.isHoveringOverActionHighlight(), gamePlayer.ApplyState.onClick(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
ScrollPane gamePlayer.ViewController.getGridPane () protected
Getter to get the GameGrid
Returns
Definition at line 962 of file ViewController.java.
References gamePlayer.ViewController.myGridPane.
Referenced by gamePlayer.ApplyState.ApplyState(), gamePlayer.KeyboardAction.setActionKeyControl(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
IGridState gamePlayer.ViewController.getGridState ()
Getter to get the GridState
Returns
Definition at line 934 of file ViewController.java.
References gamePlayer.ViewController.gridState.
List<File> gamePlayer.ViewController.getResourceGames () private
The method to get all json files from the resources directory that stores all the games user has defined from the authoring environment
Definition at line 654 of file ViewController.java.
References gamePlayer.ViewController.GAME_LOCATION.
Referenced by gamePlayer.ViewController.newGame().
Scene gamePlayer.ViewController.getScene () protected
Getter to get the Scene
Returns
Definition at line 952 of file ViewController.java.
References gamePlayer.ViewController.myScene.
void gamePlayer.ViewController.handleClearHighScores () private
Definition at line 1207 of file ViewController.java.
Referenced by gamePlayer.ViewController.initializeGrid().
void gamePlayer.ViewController.highlightSelected (Piece p)
Select state tells VC to highlight the selected piece
Parameters
p
Definition at line 838 of file ViewController.java.
References gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), gamedata.gamecomponents.GridComponent.getLoc(), authoring_environment.GUIGrid.getPiece(), and gamePlayer.GameGridEffect.highlightCurrent().
Referenced by gamePlayer.SelectState.onClick().
void gamePlayer.ViewController.initializeGrid () private
Initializes grid and its effects manager (gamegrideffect)
Definition at line 610 of file ViewController.java.
References authoring_environment.SuperGrid.displayPane(), gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), gamePlayer.ViewController.handleClearHighScores(), gamePlayer.Audio.playSelection(), gamePlayer.ViewController.setGridState(), and gamePlayer.ViewController.setOnClick().
Referenced by gamePlayer.ViewController.checkEndActions(), gamePlayer.ViewController.restartGame(), gamePlayer.ViewController.testPlayGame(), gamePlayer.ViewController.testPlayGameInTab(), and gamePlayer.ViewController.testPlayGUIGame().
void gamePlayer.ViewController.loadFXML (String url, Node n) private
Loads an FXML file
Parameters
url
n
Definition at line 553 of file ViewController.java.
Referenced by gamePlayer.ViewController.openInitialGUIMenu(), and gamePlayer.ViewController.openInitialMenu().
void gamePlayer.ViewController.loadGame () protected
the method allows user to load the previously saved json representation of the game and uses JSON reader from Game Data to generate an instance of Game.
Definition at line 348 of file ViewController.java.
References gamePlayer.ViewController.editPlayers(), and gamedata.JSON.JSONManager.readFromJSONFile().
void gamePlayer.ViewController.loadGameInTab () private
Definition at line 217 of file ViewController.java.
References gamePlayer.ViewController.editGUIPlayers(), and gamedata.JSON.JSONManager.readFromJSONFile().
Referenced by gamePlayer.ViewController.ViewController().
void gamePlayer.ViewController.loadScores () protected
Loads the scores from the current game
Definition at line 635 of file ViewController.java.
References gamedata.gamecomponents.Game.getPlayers(), and gamedata.gamecomponents.Game.toString().
Referenced by gamePlayer.ViewController.showScore().
void gamePlayer.ViewController.newGame () throws UnsupportedAudioFileException, IOException, LineUnavailableException protected
Generates a drop down menu that allow user to choose a new Game to play. The Games are generated from the directory that stores all json files defined from authoring environment
Exceptions
LineUnavailableException
IOException
UnsupportedAudioFileException
Definition at line 576 of file ViewController.java.
References gamePlayer.ViewController.getResourceGames(), gamedata.JSON.JSONManager.readFromJSONFile(), and gamePlayer.ViewController.testPlayGame().
Referenced by gamePlayer.ViewController.ViewController().
void gamePlayer.ViewController.openInitialGUIMenu () throws UnsupportedAudioFileException, IOException, LineUnavailableException protected
Definition at line 256 of file ViewController.java.
References gamePlayer.ViewController.loadFXML(), and gamePlayer.Audio.playBackground().
Referenced by gamePlayer.ViewController.ViewController().
void gamePlayer.ViewController.openInitialMenu () throws UnsupportedAudioFileException, IOException, LineUnavailableException protected
Sets up and opens the initial scene
Exceptions
LineUnavailableException
IOException
UnsupportedAudioFileException
Definition at line 303 of file ViewController.java.
References gamePlayer.ViewController.loadFXML(), and gamePlayer.Audio.playBackground().
Referenced by gamePlayer.ViewController.ViewController().
void gamePlayer.ViewController.openSettings () protected
Definition at line 378 of file ViewController.java.
void gamePlayer.ViewController.performAction (Point2D.Double myCurrentLocation)
Perform the actions of a click at position (x,y) on game grid and highlights the piece that was clicked
Parameters
x
y
Definition at line 799 of file ViewController.java.
References gamePlayer.ViewController.checkEndActions(), gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), authoring_environment.GUIGrid.getPiece(), gameengine.player.Player.getType(), gamePlayer.IGridState.onClick(), gameengine.player.Player.play(), gamePlayer.Audio.playSelection(), gamePlayer.KeyboardAction.setActionKeyControl(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
Referenced by gamePlayer.KeyboardMovement.setMovementKeyControl(), and gamePlayer.ViewController.setOnClick().
void gamePlayer.ViewController.removePreviousPlayer (int playerID) private
Definition at line 535 of file ViewController.java.
Referenced by gamePlayer.ViewController.updatePlayers().
void gamePlayer.ViewController.restartGame () protected
the method to restart the game; it asks the user whether to save the current game
Definition at line 391 of file ViewController.java.
References gamePlayer.ViewController.initializeGrid().
void gamePlayer.ViewController.saveGame () protected
to save the current game (state and settings) to a json file which could be later loaded in
Definition at line 409 of file ViewController.java.
References gamedata.gamecomponents.Game.setCurrentPlayer(), and gamedata.JSON.JSONManager.writeToJSON().
void gamePlayer.ViewController.setActiveAction (Action action) protected
Setter to set the Active Action
Parameters
action
Definition at line 1008 of file ViewController.java.
Referenced by gamePlayer.ViewController.bindAction(), and gamePlayer.ApplyState.onClick().
void gamePlayer.ViewController.setActivePiece (Piece piece) protected
Setter to set the Active Piece
Parameters
piece
Definition at line 999 of file ViewController.java.
Referenced by gamePlayer.SelectState.onClick(), and gamePlayer.ApplyState.onClick().
void gamePlayer.ViewController.setGridState (IGridState state)
Method to switch the state of the game grid between select mode and apply mode Method to switch the state of the game grid between select mode and apply mode
Also checks if the game has been won to show high score
Parameters
state the current state of the Grid, select/ apply action Mode
Definition at line 1025 of file ViewController.java.
References gamedata.gamecomponents.Game.getCurrentPlayer(), and gamePlayer.ViewController.setPlayerTurnDisplay().
Referenced by gamePlayer.ViewController.bindAction(), gamePlayer.ViewController.initializeGrid(), and gamePlayer.ApplyState.onClick().
void gamePlayer.ViewController.setOnClick () private
Definition at line 785 of file ViewController.java.
References gamePlayer.ViewController.findPosition(), and gamePlayer.ViewController.performAction().
Referenced by gamePlayer.ViewController.initializeGrid().
void gamePlayer.ViewController.setPlayerTurnDisplay () package
Changes the player turn label to show current turn
Definition at line 1052 of file ViewController.java.
References gameengine.player.Player.getID().
Referenced by gamePlayer.ViewController.checkEndActions(), and gamePlayer.ViewController.setGridState().
void gamePlayer.ViewController.showScore () protected
loads the players and their scores of the current game; display the Highest score in the high score display at the bottom
Definition at line 448 of file ViewController.java.
References gamePlayer.ViewController.loadScores().
void gamePlayer.ViewController.testGame () private
Initiates a Button for a Test Game
Definition at line 427 of file ViewController.java.
References tests.TestGameCreator.createNewGame(), and gamePlayer.ViewController.editPlayers().
void gamePlayer.ViewController.testPlayGame (Game gameToLoad)
Loads a Game into gamePlayer GUI
Parameters
gameToLoad
Definition at line 1248 of file ViewController.java.
References gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), gamePlayer.ViewController.initializeGrid(), and authoring_environment.GUIGrid.repopulateGrid().
Referenced by gamePlayer.ViewController.newGame(), and fxml_main.AuthoringController.saveAsGame().
void gamePlayer.ViewController.testPlayGameInTab (Game readFromJSONFile) private
Definition at line 240 of file ViewController.java.
References gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), gamePlayer.ViewController.initializeGrid(), and authoring_environment.GUIGrid.repopulateGrid().
void gamePlayer.ViewController.testPlayGUIGame (Game gameToLoad)
Loads a Game into gamePlayer GUI
Parameters
gameToLoad
Definition at line 1229 of file ViewController.java.
References gamedata.gamecomponents.Game.getCurrentLevel(), gamedata.gamecomponents.Level.getGrid(), gamePlayer.ViewController.initializeGrid(), and authoring_environment.GUIGrid.repopulateGrid().
void gamePlayer.ViewController.toggleBackgroundMusic () throws UnsupportedAudioFileException, IOException, LineUnavailableException
Toggles background music sound
Exceptions
UnsupportedAudioFileException
IOException
LineUnavailableException
Definition at line 875 of file ViewController.java.
References gamePlayer.Audio.muteDefault(), and gamePlayer.Audio.playBackground().
void gamePlayer.ViewController.toggleClickSound ()
Toggles clicking sound
Definition at line 861 of file ViewController.java.
void gamePlayer.ViewController.toggleKeyboardControl ()
Toggles whether the Keyboard Controls are active or inactive
Definition at line 891 of file ViewController.java.
References gamePlayer.ViewController.currentClick, authoring_environment.SuperTile.deselectTile(), authoring_environment.SuperGrid.findTile(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
void gamePlayer.ViewController.updateActionList (ArrayList< Label > actions)
Updates the list of actions displayed
Parameters
actions
Definition at line 751 of file ViewController.java.
void gamePlayer.ViewController.updateActions (Piece piece) protected
Update the action panel with actions from the selected piece
Parameters
piece
Definition at line 725 of file ViewController.java.
References gamePlayer.ViewController.bindAction(), and gamedata.gamecomponents.Piece.getActions().
Referenced by gamePlayer.SelectState.onClick(), and tests.ViewControllerTest.updateActionsTest().
void gamePlayer.ViewController.updateInventory (Piece piece) protected
Definition at line 667 of file ViewController.java.
References gamedata.gamecomponents.Piece.getInventory(), and gamedata.gamecomponents.Inventory.getStringDisplay().
Referenced by gamePlayer.SelectState.onClick().
void gamePlayer.ViewController.updateLanguage ()
Updates the current language of the game.
Definition at line 439 of file ViewController.java.
References gamePlayer.Languages.findCurrentLanguage().
void gamePlayer.ViewController.updatePlayers () protected
Definition at line 516 of file ViewController.java.
References gamePlayer.ViewController.removePreviousPlayer().
void gamePlayer.ViewController.updateStats (Piece piece) protected
Update the stats panel with stats from the selected piece
Parameters
piece
Definition at line 703 of file ViewController.java.
References gamedata.stats.Stats.getStatNames(), gamedata.gamecomponents.Piece.getStats(), and gamedata.stats.Stats.getValue().
Referenced by gamePlayer.SelectState.onClick(), and tests.ViewControllerTest.updateStatsTest().
Member Data Documentation
Boolean gamePlayer.ViewController.actionActiveOn private
Definition at line 113 of file ViewController.java.
final int gamePlayer.ViewController.ACTIONNAME_FONT_SIZE = 16 static private
Definition at line 69 of file ViewController.java.
Action gamePlayer.ViewController.activeAction private
Definition at line 119 of file ViewController.java.
Referenced by gamePlayer.ViewController.getActiveAction().
Piece gamePlayer.ViewController.activePiece private
Definition at line 118 of file ViewController.java.
Referenced by gamePlayer.ViewController.getActivePiece().
final String gamePlayer.ViewController.ADD_HIGH_SCORE_FXML = "newHighScore.fxml" static
Definition at line 73 of file ViewController.java.
Boolean gamePlayer.ViewController.backgroundMusicOn private
Definition at line 112 of file ViewController.java.
Button gamePlayer.ViewController.clearHighScores private
Definition at line 151 of file ViewController.java.
Boolean gamePlayer.ViewController.clickSoundOn private
Definition at line 111 of file ViewController.java.
VBox gamePlayer.ViewController.controlPane protected
Definition at line 131 of file ViewController.java.
Referenced by gamePlayer.ViewController.getcontrolPane(), and tests.ViewControllerTest.updateActionsTest().
Point2D.Double gamePlayer.ViewController.currentClick private
Definition at line 182 of file ViewController.java.
Referenced by gamePlayer.ViewController.findPosition(), gamePlayer.ViewController.getCurrentClick(), and gamePlayer.ViewController.toggleKeyboardControl().
TextField gamePlayer.ViewController.editPlayerName private
Definition at line 173 of file ViewController.java.
BorderPane gamePlayer.ViewController.editPlayerRoot private
Definition at line 94 of file ViewController.java.
final String gamePlayer.ViewController.GAME_LOCATION = "/src/resources/json" static
Definition at line 79 of file ViewController.java.
Referenced by gamePlayer.ViewController.getResourceGames().
MenuButton gamePlayer.ViewController.gameMenu private
Definition at line 145 of file ViewController.java.
Text gamePlayer.ViewController.gameName private
Definition at line 135 of file ViewController.java.
final String gamePlayer.ViewController.GAMESPACE_FXML = "gameSpace.fxml" static
Definition at line 74 of file ViewController.java.
IGridState gamePlayer.ViewController.gridState private
Definition at line 183 of file ViewController.java.
Referenced by gamePlayer.ViewController.getGridState().
final String gamePlayer.ViewController.HIGH_SCORE_FILE = "/resources/highscore/highscore.txt" static private
Definition at line 82 of file ViewController.java.
Text gamePlayer.ViewController.highestScore private
Definition at line 137 of file ViewController.java.
TextField gamePlayer.ViewController.highScoreName private
Definition at line 161 of file ViewController.java.
Button gamePlayer.ViewController.highScoreOK private
Definition at line 165 of file ViewController.java.
final String gamePlayer.ViewController.HUMAN_PLAYER = "Human Player" static private
Definition at line 72 of file ViewController.java.
final String gamePlayer.ViewController.INITIALSCENE_FXML = "initialScene.fxml" static
Definition at line 75 of file ViewController.java.
final String gamePlayer.ViewController.INITIALSCENE_TITLE = "VOOGASALAD!" static
Definition at line 78 of file ViewController.java.
final String gamePlayer.ViewController.INVENTORY_FONT_NAME = "Consolas" static private
Definition at line 68 of file ViewController.java.
VBox gamePlayer.ViewController.inventoryPane protected
Definition at line 129 of file ViewController.java.
final int gamePlayer.ViewController.ITEMNAME_FONT_SIZE = 24 static private
Definition at line 70 of file ViewController.java.
Boolean gamePlayer.ViewController.keyControlOn private
Definition at line 110 of file ViewController.java.
SuperTile gamePlayer.ViewController.keySelectedTile private
Definition at line 186 of file ViewController.java.
AnchorPane gamePlayer.ViewController.languagesPane private
Definition at line 149 of file ViewController.java.
Audio gamePlayer.ViewController.myAudio private
Definition at line 121 of file ViewController.java.
Player gamePlayer.ViewController.myCurrentPlayer private
Definition at line 106 of file ViewController.java.
GameGridEffect gamePlayer.ViewController.myGameGridEffect private
Definition at line 185 of file ViewController.java.
Referenced by gamePlayer.ViewController.getGameGridEffect().
BorderPane gamePlayer.ViewController.myGameSpace private
Definition at line 88 of file ViewController.java.
GUIGrid gamePlayer.ViewController.myGrid private
Definition at line 103 of file ViewController.java.
Referenced by gamePlayer.ViewController.getGrid().
ScrollPane gamePlayer.ViewController.myGridPane private
Definition at line 181 of file ViewController.java.
Referenced by gamePlayer.ViewController.getGridPane().
VBox gamePlayer.ViewController.myInitialScene private
Definition at line 91 of file ViewController.java.
JSONManager gamePlayer.ViewController.myJSONManager private
Definition at line 184 of file ViewController.java.
KeyboardAction gamePlayer.ViewController.myKeyboardAction private
Definition at line 115 of file ViewController.java.
KeyboardMovement gamePlayer.ViewController.myKeyboardMovement private
Definition at line 116 of file ViewController.java.
Languages gamePlayer.ViewController.myLanguages private
Definition at line 189 of file ViewController.java.
Game gamePlayer.ViewController.myModel private
Definition at line 102 of file ViewController.java.
Referenced by gamePlayer.ViewController.getGame().
List<Player> gamePlayer.ViewController.myPlayerList private
Definition at line 123 of file ViewController.java.
Scene gamePlayer.ViewController.myPlayerScene private
Definition at line 98 of file ViewController.java.
BorderPane gamePlayer.ViewController.myPopup private
Definition at line 89 of file ViewController.java.
Scene gamePlayer.ViewController.myPopupScene private
Definition at line 97 of file ViewController.java.
Scene gamePlayer.ViewController.myScene private
Definition at line 99 of file ViewController.java.
Referenced by gamePlayer.ViewController.getScene().
VBox gamePlayer.ViewController.myScoreBoard private
Definition at line 92 of file ViewController.java.
VBox gamePlayer.ViewController.mySettings private
Definition at line 90 of file ViewController.java.
Scene gamePlayer.ViewController.mySettingsScene private
Definition at line 95 of file ViewController.java.
Stage gamePlayer.ViewController.mySplashStage private
Definition at line 104 of file ViewController.java.
Stage gamePlayer.ViewController.myStage private
Definition at line 86 of file ViewController.java.
Tab gamePlayer.ViewController.myTab private
Definition at line 124 of file ViewController.java.
BorderPane gamePlayer.ViewController.myWinLoseScreen private
Definition at line 167 of file ViewController.java.
MenuButton gamePlayer.ViewController.newGameMenu private
Definition at line 133 of file ViewController.java.
GridPane gamePlayer.ViewController.newHighScoreRoot private
Definition at line 159 of file ViewController.java.
Scene gamePlayer.ViewController.newHighScoreScene private
Definition at line 100 of file ViewController.java.
final String gamePlayer.ViewController.PLAYER_FXML = "playerEditorScene.fxml" static
Definition at line 77 of file ViewController.java.
Label gamePlayer.ViewController.playerHighScore private
Definition at line 163 of file ViewController.java.
TextField gamePlayer.ViewController.playerName private
Definition at line 157 of file ViewController.java.
ChoiceBox gamePlayer.ViewController.players private
Definition at line 153 of file ViewController.java.
VBox gamePlayer.ViewController.playersList private
Definition at line 171 of file ViewController.java.
Label gamePlayer.ViewController.playerTurn private
Definition at line 141 of file ViewController.java.
ChoiceBox gamePlayer.ViewController.playerType private
Definition at line 155 of file ViewController.java.
ComboBox<String> gamePlayer.ViewController.playerTypeCombo private
Definition at line 175 of file ViewController.java.
final String gamePlayer.ViewController.POPUP_FXML = "popup.fxml" static
Definition at line 80 of file ViewController.java.
final String gamePlayer.ViewController.SCOREBOARD_FXML = "scoreBoard.fxml" static
Definition at line 76 of file ViewController.java.
VBox gamePlayer.ViewController.scores private
Definition at line 139 of file ViewController.java.
Scene gamePlayer.ViewController.scoreScene private
Definition at line 96 of file ViewController.java.
Button gamePlayer.ViewController.setPlayerButton private
Definition at line 179 of file ViewController.java.
final String gamePlayer.ViewController.SETTINGS_FXML = "settings.fxml" static
Definition at line 81 of file ViewController.java.
Button gamePlayer.ViewController.showScoreButton private
Definition at line 143 of file ViewController.java.
final String gamePlayer.ViewController.SIMPLE_AI_PLAYER = "Simple AI player" static private
Definition at line 71 of file ViewController.java.
Button gamePlayer.ViewController.startGameButton private
Definition at line 177 of file ViewController.java.
VBox gamePlayer.ViewController.statsPane protected
Definition at line 127 of file ViewController.java.
Referenced by tests.ViewControllerTest.updateStatsTest().
TabPane gamePlayer.ViewController.tabPane private
Definition at line 147 of file ViewController.java.
int gamePlayer.ViewController.tempMoveCount = 0 private
Definition at line 188 of file ViewController.java.
final String gamePlayer.ViewController.WIN_SCREEN = "winLoseScreen.fxml" static private
Definition at line 83 of file ViewController.java.
Label gamePlayer.ViewController.winLose private
Definition at line 169 of file ViewController.java.
Scene gamePlayer.ViewController.winLoseScene private
Definition at line 101 of file ViewController.java.
final String gamePlayer.ViewController.YOU_LOSE = "You Lose :(" static private
Definition at line 84 of file ViewController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/ViewController.java