voogasalad_VOOGirlsGeneration: gameengine.player.Player Class Reference
gameengine.player.Player Class Reference abstract
Public Member Functions
Player ()
Player (int id)
Player (Player player)
Stats getStats ()
double getScore ()
Point2D getLoc ()
void changeStat (String statName, double value)
abstract void startTurn (Level l)
void resetMovesPlayed ()
int getID ()
abstract void play ()
void playTurn ()
int getNumMovesPlayed ()
String printString ()
String toString ()
abstract String getType ()
Protected Member Functions
Player (int id, Stats stats, String scoreStat)
Protected Attributes
int myNumMovesPlayed
int myID
Stats myStats
String myScoreStat
Detailed Description
A player object that contains the logic for playing each level. This object requires no parameters for initialization.
Jesse, Rica, Sandy
Definition at line 17 of file Player.java.
Constructor & Destructor Documentation
gameengine.player.Player.Player ()
Default constructor
Definition at line 38 of file Player.java.
gameengine.player.Player.Player (int id)
Constructs a player with a specific ID
Parameters
id int ID corresponding to the Player
Definition at line 48 of file Player.java.
gameengine.player.Player.Player (Player player)
Definition at line 53 of file Player.java.
References gameengine.player.Player.myID, gameengine.player.Player.myScoreStat, and gameengine.player.Player.myStats.
gameengine.player.Player.Player (int id, Stats stats, String scoreStat) protected
Definition at line 60 of file Player.java.
Member Function Documentation
void gameengine.player.Player.changeStat (String statName, double value)
Modify a stat of the player based on info from a global action
Parameters
statName
value
Definition at line 85 of file Player.java.
References gamedata.stats.Stats.getValue(), and gamedata.stats.Stats.setValue().
int gameengine.player.Player.getID ()
Getter to return the ID of the player
Returns
int ID of the player
Definition at line 109 of file Player.java.
References gameengine.player.Player.myID.
Referenced by gamePlayer.SelectState.onClick(), gamedata.goals.PlayerPiecesRemovedGoal.PlayerPiecesRemovedGoal(), gamePlayer.ViewController.setPlayerTurnDisplay(), and tests.GlobalActionTester.TestEndTurn().
Point2D gameengine.player.Player.getLoc ()
Implements gamedata.gamecomponents.IHasStats.
Definition at line 76 of file Player.java.
Referenced by gameengine.player.SimpleAIPlayer.play().
int gameengine.player.Player.getNumMovesPlayed ()
Getter for Number of Moves Played
Returns
Definition at line 131 of file Player.java.
References gameengine.player.Player.myNumMovesPlayed.
double gameengine.player.Player.getScore ()
Definition at line 72 of file Player.java.
References gamedata.stats.Stats.getValue().
Stats gameengine.player.Player.getStats ()
Implements gamedata.gamecomponents.IHasStats.
Definition at line 67 of file Player.java.
References gameengine.player.Player.myStats.
abstract String gameengine.player.Player.getType () abstract
Returns the type of the player
Returns
String representing the type of the player
Referenced by gamePlayer.ViewController.performAction(), and gamePlayer.KeyboardMovement.setMovementKeyControl().
abstract void gameengine.player.Player.play () abstract
Implements the play behavior of the player (allowing the user to become active and play)
Referenced by gamePlayer.ViewController.performAction().
void gameengine.player.Player.playTurn ()
Increments the number moves played during a turn
Definition at line 122 of file Player.java.
Referenced by gamePlayer.ViewController.checkEndActions().
String gameengine.player.Player.printString ()
ToString Method for Player Information. For debugging purposes.
Definition at line 139 of file Player.java.
References gameengine.player.Player.myNumMovesPlayed.
void gameengine.player.Player.resetMovesPlayed ()
Resets number of moves played for the player
Definition at line 100 of file Player.java.
Referenced by gameengine.player.SimpleAIPlayer.startTurn(), and gameengine.player.HumanPlayer.startTurn().
abstract void gameengine.player.Player.startTurn (Level l) abstract
Sets the player to start a turn on a level
Parameters
l
Referenced by gamedata.gamecomponents.Game.nextPlayer(), gamedata.gamecomponents.Game.resetPlayer(), gamedata.gamecomponents.Game.setCurrentPlayer(), and gamedata.gamecomponents.Game.startGame().
String gameengine.player.Player.toString ()
Implements gamedata.gamecomponents.IHasStats.
Definition at line 145 of file Player.java.
References gameengine.player.Player.myID.
Member Data Documentation
int gameengine.player.Player.myID protected
ID representing the player
Definition at line 26 of file Player.java.
Referenced by gameengine.player.Player.getID(), gameengine.player.SimpleAIPlayer.play(), gameengine.player.Player.Player(), and gameengine.player.Player.toString().
int gameengine.player.Player.myNumMovesPlayed protected
Number of moves a player has made in a given turn
Definition at line 22 of file Player.java.
Referenced by gameengine.player.Player.getNumMovesPlayed(), and gameengine.player.Player.printString().
String gameengine.player.Player.myScoreStat protected
Definition at line 33 of file Player.java.
Referenced by gameengine.player.Player.Player().
Stats gameengine.player.Player.myStats protected
Stats ranging from score to gold
Definition at line 31 of file Player.java.
Referenced by gameengine.player.Player.getStats(), and gameengine.player.Player.Player().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gameengine/player/Player.java