voogasalad_VOOGirlsGeneration: gamedata.events.globalaction.MakePieceAtLocation Class Reference
gamedata.events.globalaction.MakePieceAtLocation Class Reference
Public Member Functions
MakePieceAtLocation (Piece pieceToCreate, Point2D.Double loc, int PlayerID)
void doBehavior (GUIGrid grid)
Public Member Functions inherited from gamedata.events.globalaction.GlobalAction
abstract void doBehavior (GUIGrid grid)
String toString ()
Private Attributes
Piece myPieceType
Point2D.Double myLoc
int myPlayerID
Additional Inherited Members
Protected Member Functions inherited from gamedata.events.globalaction.GlobalAction
GlobalAction (String s)
Protected Attributes inherited from gamedata.events.globalaction.GlobalAction
final String myDescription
Detailed Description
Creates a piece on the grid in a level in a specified location
Author
Mike Zhu
Definition at line 14 of file MakePieceAtLocation.java.
Constructor & Destructor Documentation
gamedata.events.globalaction.MakePieceAtLocation.MakePieceAtLocation (Piece pieceToCreate, Point2D.Double loc, int PlayerID)
Create this global action with a piece that stores the location it should be placed in
Parameters
game
pieceToCreate
Definition at line 27 of file MakePieceAtLocation.java.
References gamedata.events.globalaction.MakePieceAtLocation.myLoc.
Member Function Documentation
void gamedata.events.globalaction.MakePieceAtLocation.doBehavior (GUIGrid grid)
Definition at line 35 of file MakePieceAtLocation.java.
References authoring_environment.GUIGrid.addPieceAtLoc(), authoring_environment.GUIGrid.getPiece(), gamedata.events.globalaction.MakePieceAtLocation.myLoc, and gamedata.gamecomponents.Piece.setPlayerID().
Referenced by tests.GlobalActionTester.TestCreatePiece().
Member Data Documentation
Point2D.Double gamedata.events.globalaction.MakePieceAtLocation.myLoc private
Definition at line 17 of file MakePieceAtLocation.java.
Referenced by gamedata.events.globalaction.MakePieceAtLocation.doBehavior(), and gamedata.events.globalaction.MakePieceAtLocation.MakePieceAtLocation().
Piece gamedata.events.globalaction.MakePieceAtLocation.myPieceType private
Definition at line 16 of file MakePieceAtLocation.java.
int gamedata.events.globalaction.MakePieceAtLocation.myPlayerID private
Definition at line 18 of file MakePieceAtLocation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/events/globalaction/MakePieceAtLocation.java