voogasalad_VOOGirlsGeneration: fxml_main.ActionController Class Reference
fxml_main.ActionController Class Reference
Protected Member Functions
ActionController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, ActionData actionData, String gridShape)
void initGlobalNewBtn (Button newBtn)
void initGlobalEditBtn (Button editBtn)
void initGlobalDelBtn (Button delBtn)
void initEntryEditBtn (ConcreteAction entry, Button editBtn)
HBox makeEntryBox (ConcreteAction entry)
void initEntryDelBtn (ConcreteAction entry, Button delBtn)
Protected Member Functions inherited from fxml_main.GridComponentAbstCtrl< ConcreteAction >
GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef)
abstract void initGlobalNewBtn (Button newBtn)
abstract void initGlobalEditBtn (Button editBtn)
abstract void initGlobalDelBtn (Button delBtn)
void addEntry (T entry)
HBox makeCompleteEntryBox (T entry)
HBox initEntryControls (T entry)
abstract HBox makeEntryBox (T entry)
abstract void initEntryEditBtn (T entry, Button editBtn)
abstract void initEntryDelBtn (T entry, Button delBtn)
Private Attributes
ActionData myActionData
String myGridShape
Additional Inherited Members
Protected Attributes inherited from fxml_main.GridComponentAbstCtrl< ConcreteAction >
VBox myVBox
ScrollPane myPropertiesSPane
GUIGridReference myGridReference
Map< T, HBox > myEntryMap
Detailed Description
Author
annamiyajima
Definition at line 21 of file ActionController.java.
Constructor & Destructor Documentation
fxml_main.ActionController.ActionController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, ActionData actionData, String gridShape) protected
Definition at line 25 of file ActionController.java.
Member Function Documentation
void fxml_main.ActionController.initEntryDelBtn (ConcreteAction entry, Button delBtn) protected
Definition at line 95 of file ActionController.java.
References fxml_main.GridComponentAbstCtrl< ConcreteAction >.myEntryMap, fxml_main.GridComponentAbstCtrl< ConcreteAction >.myVBox, and authoring.data.ActionData.remove().
void fxml_main.ActionController.initEntryEditBtn (ConcreteAction entry, Button editBtn) protected
Definition at line 60 of file ActionController.java.
References fxml_main.GridComponentAbstCtrl< ConcreteAction >.makeCompleteEntryBox(), fxml_main.GridComponentAbstCtrl< ConcreteAction >.myEntryMap, fxml_main.GridComponentAbstCtrl< ConcreteAction >.myPropertiesSPane, and authoring.data.ActionData.replace().
void fxml_main.ActionController.initGlobalDelBtn (Button delBtn) protected
Definition at line 54 of file ActionController.java.
void fxml_main.ActionController.initGlobalEditBtn (Button editBtn) protected
Definition at line 47 of file ActionController.java.
void fxml_main.ActionController.initGlobalNewBtn (Button newBtn) protected
Definition at line 33 of file ActionController.java.
References authoring.data.ActionData.add(), fxml_main.GridComponentAbstCtrl< ConcreteAction >.addEntry(), and fxml_main.GridComponentAbstCtrl< ConcreteAction >.myPropertiesSPane.
HBox fxml_main.ActionController.makeEntryBox (ConcreteAction entry) protected
Definition at line 79 of file ActionController.java.
References gamedata.action.ConcreteAction.getName(), and fxml_main.GridComponentAbstCtrl< ConcreteAction >.myPropertiesSPane.
Member Data Documentation
ActionData fxml_main.ActionController.myActionData private
Definition at line 22 of file ActionController.java.
String fxml_main.ActionController.myGridShape private
Definition at line 23 of file ActionController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/ActionController.java