voogasalad_VOOGirlsGeneration: gamedata.action.ConcreteAction Class Reference
gamedata.action.ConcreteAction Class Reference
Public Member Functions
ConcreteAction (String id, List< Point2D.Double > attackRange, List< Point2D.Double > effectRange, List< StatsTotalLogic > statsLogics, ActionConclusion conclusion)
List< Point2D.Double > getAbsoluteActionRange (Point2D pieceLoc)
List< Point2D.Double > getActionRange ()
List< Point2D.Double > getEffectRange ()
void doBehavior (GUIGrid grid, Piece actor, Piece...receivers)
List< StatsTotalLogic > getStatsLogics ()
String toString ()
String getName ()
ActionConclusion getConclusion ()
List< Point2D.Double > getAbsoluteEffectRange (Point2D pieceLoc)
Private Member Functions
void modifyStats (Piece actor, Piece[] receivers)
void runConclusion (GUIGrid grid, Piece actor, Piece[] receivers)
Private Attributes
String myName
List< Point2D.Double > myAttackRange
List< Point2D.Double > myEffectRange
List< StatsTotalLogic > myStatsLogics
ActionConclusion myConclusion
StatsDataModifier myDataModifier
Detailed Description
A concrete instance of an Action. All Actions defined by the user will be an instance of this class.
See Action interface for descriptions of public methods
Author
Jennie Ju, annamiyajima, Sandy Lee
Definition at line 22 of file ConcreteAction.java.
Constructor & Destructor Documentation
gamedata.action.ConcreteAction.ConcreteAction (String id, List< Point2D.Double > attackRange, List< Point2D.Double > effectRange, List< StatsTotalLogic > statsLogics, ActionConclusion conclusion)
ConcreteAction constructor Called when a new Action is made and its behavior is already defined
Definition at line 35 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myAttackRange, and gamedata.action.ConcreteAction.myEffectRange.
Member Function Documentation
void gamedata.action.ConcreteAction.doBehavior (GUIGrid grid, Piece actor, Piece... receivers)
Executes behavior of the action. Modifies the necessary stats and runs the conclusion
Implements gamedata.action.Action.
Definition at line 73 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.modifyStats(), and gamedata.action.ConcreteAction.runConclusion().
List<Point2D.Double> gamedata.action.ConcreteAction.getAbsoluteActionRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the action range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 47 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myAttackRange.
List<Point2D.Double> gamedata.action.ConcreteAction.getAbsoluteEffectRange (Point2D pieceLocation)
Gives back a list of Point2D of absolute locations for the effect range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 121 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myEffectRange.
List<Point2D.Double> gamedata.action.ConcreteAction.getActionRange ()
Gives back a list of Point2D of relative locations for the action range
Returns
list of absolute locations in Point2D
Implements gamedata.action.Action.
Definition at line 58 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myAttackRange.
Referenced by fxml_main.ActionEditor.ActionEditor().
ActionConclusion gamedata.action.ConcreteAction.getConclusion ()
Definition at line 116 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myConclusion.
Referenced by fxml_main.ActionEditor.ActionEditor().
List<Point2D.Double> gamedata.action.ConcreteAction.getEffectRange ()
Gives back a list of Point2D of relative locations for the effect range of the action (splashzone)
Returns
list of relative locations in Point2D
Implements gamedata.action.Action.
Definition at line 63 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myEffectRange.
Referenced by fxml_main.ActionEditor.ActionEditor().
String gamedata.action.ConcreteAction.getName ()
Returns the name of the Action for display
Returns
name of Action
Implements gamedata.action.Action.
Definition at line 112 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myName.
Referenced by fxml_main.ActionEditor.ActionEditor(), and fxml_main.ActionController.makeEntryBox().
List<StatsTotalLogic> gamedata.action.ConcreteAction.getStatsLogics ()
Returns the logic contained in the ConcreteAction for editing in the Authoring Environment
Returns
Definition at line 84 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myStatsLogics.
Referenced by fxml_main.ActionEditor.ActionEditor().
void gamedata.action.ConcreteAction.modifyStats (Piece actor, Piece[] receivers) private
Definition at line 88 of file ConcreteAction.java.
References gamedata.action.StatsDataModifier.modifyStats().
Referenced by gamedata.action.ConcreteAction.doBehavior().
void gamedata.action.ConcreteAction.runConclusion (GUIGrid grid, Piece actor, Piece[] receivers) private
Definition at line 99 of file ConcreteAction.java.
References gamedata.action.ActionConclusion.runConclusion().
Referenced by gamedata.action.ConcreteAction.doBehavior().
String gamedata.action.ConcreteAction.toString ()
Returns the information about the Action for display
Returns
name of Action
Implements gamedata.action.Action.
Definition at line 107 of file ConcreteAction.java.
References gamedata.action.ConcreteAction.myName.
Member Data Documentation
List<Point2D.Double> gamedata.action.ConcreteAction.myAttackRange private
Definition at line 24 of file ConcreteAction.java.
Referenced by gamedata.action.ConcreteAction.ConcreteAction(), gamedata.action.ConcreteAction.getAbsoluteActionRange(), and gamedata.action.ConcreteAction.getActionRange().
ActionConclusion gamedata.action.ConcreteAction.myConclusion private
Definition at line 27 of file ConcreteAction.java.
Referenced by gamedata.action.ConcreteAction.getConclusion().
StatsDataModifier gamedata.action.ConcreteAction.myDataModifier private
Definition at line 28 of file ConcreteAction.java.
List<Point2D.Double> gamedata.action.ConcreteAction.myEffectRange private
Definition at line 25 of file ConcreteAction.java.
Referenced by gamedata.action.ConcreteAction.ConcreteAction(), gamedata.action.ConcreteAction.getAbsoluteEffectRange(), and gamedata.action.ConcreteAction.getEffectRange().
String gamedata.action.ConcreteAction.myName private
Definition at line 23 of file ConcreteAction.java.
Referenced by gamedata.action.ConcreteAction.getName(), and gamedata.action.ConcreteAction.toString().
List<StatsTotalLogic> gamedata.action.ConcreteAction.myStatsLogics private
Definition at line 26 of file ConcreteAction.java.
Referenced by gamedata.action.ConcreteAction.getStatsLogics().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/ConcreteAction.java