voogasalad_VOOGirlsGeneration: fxml_main.LevelController Class Reference
fxml_main.LevelController Class Reference
Protected Member Functions
LevelController (VBox vbox, ScrollPane propertiesSPane, ScrollPane gridSPane, GUIGridReference gridRef, LevelData levels, PieceTypeData pieceTypes, PatchTypeData patchTypes, String gridShape)
void initGlobalNewBtn (Button newBtn)
void initGlobalEditBtn (Button editBtn)
void initGlobalDelBtn (Button delBtn)
HBox makeEntryBox (Level entry)
void initEntryEditBtn (Level entry, Button editBtn)
void initEntryDelBtn (Level entry, Button delBtn)
Protected Member Functions inherited from fxml_main.GridComponentAbstCtrl< Level >
GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef)
abstract void initGlobalNewBtn (Button newBtn)
abstract void initGlobalEditBtn (Button editBtn)
abstract void initGlobalDelBtn (Button delBtn)
void addEntry (T entry)
HBox makeCompleteEntryBox (T entry)
HBox initEntryControls (T entry)
abstract HBox makeEntryBox (T entry)
abstract void initEntryEditBtn (T entry, Button editBtn)
abstract void initEntryDelBtn (T entry, Button delBtn)
Private Member Functions
void globalNewBtnOnClickAction ()
void setAndDisplayGrid (Level level)
void addComponentObservingLevel (Level level)
Private Attributes
ScrollPane myGridSPane
LevelData myLevelData
PieceTypeData myPieceTypes
PatchTypeData myPatchTypes
String myGridShape
PlayerData myPlayerData
Additional Inherited Members
Protected Attributes inherited from fxml_main.GridComponentAbstCtrl< Level >
VBox myVBox
ScrollPane myPropertiesSPane
GUIGridReference myGridReference
Map< T, HBox > myEntryMap
Detailed Description
Author
Jennie Ju
Definition at line 30 of file LevelController.java.
Constructor & Destructor Documentation
fxml_main.LevelController.LevelController (VBox vbox, ScrollPane propertiesSPane, ScrollPane gridSPane, GUIGridReference gridRef, LevelData levels, PieceTypeData pieceTypes, PatchTypeData patchTypes, String gridShape) protected
Definition at line 38 of file LevelController.java.
Member Function Documentation
void fxml_main.LevelController.addComponentObservingLevel (Level level) private
Definition at line 166 of file LevelController.java.
References gamedata.gamecomponents.Level.getGrid().
Referenced by fxml_main.LevelController.globalNewBtnOnClickAction().
void fxml_main.LevelController.globalNewBtnOnClickAction () private
Definition at line 65 of file LevelController.java.
References authoring.data.LevelData.add(), fxml_main.LevelController.addComponentObservingLevel(), fxml_main.GridComponentAbstCtrl< Level >.addEntry(), authoring.data.PieceTypeData.getData(), authoring.data.PatchTypeData.getData(), fxml_main.GridComponentAbstCtrl< Level >.myPropertiesSPane, and fxml_main.LevelController.setAndDisplayGrid().
Referenced by fxml_main.LevelController.initGlobalNewBtn().
void fxml_main.LevelController.initEntryDelBtn (Level entry, Button delBtn) protected
Definition at line 146 of file LevelController.java.
References authoring_environment.SuperGrid.displayPane(), fxml_main.GUIGridReference.getGrid(), gamedata.gamecomponents.Level.getGrid(), fxml_main.GridComponentAbstCtrl< Level >.myEntryMap, fxml_main.GridComponentAbstCtrl< Level >.myGridReference, fxml_main.GridComponentAbstCtrl< Level >.myPropertiesSPane, fxml_main.GridComponentAbstCtrl< Level >.myVBox, authoring.data.LevelData.remove(), and fxml_main.GUIGridReference.resetGrid().
void fxml_main.LevelController.initEntryEditBtn (Level entry, Button editBtn) protected
Definition at line 116 of file LevelController.java.
References authoring.data.PieceTypeData.getData(), authoring.data.PatchTypeData.getData(), fxml_main.GridComponentAbstCtrl< Level >.makeCompleteEntryBox(), fxml_main.GridComponentAbstCtrl< Level >.myEntryMap, fxml_main.GridComponentAbstCtrl< Level >.myPropertiesSPane, authoring.data.LevelData.replace(), and fxml_main.LevelController.setAndDisplayGrid().
void fxml_main.LevelController.initGlobalDelBtn (Button delBtn) protected
Definition at line 96 of file LevelController.java.
void fxml_main.LevelController.initGlobalEditBtn (Button editBtn) protected
Definition at line 86 of file LevelController.java.
References authoring.data.LevelData.getData().
void fxml_main.LevelController.initGlobalNewBtn (Button newBtn) protected
Definition at line 51 of file LevelController.java.
References fxml_main.LevelController.globalNewBtnOnClickAction().
HBox fxml_main.LevelController.makeEntryBox (Level entry) protected
Definition at line 101 of file LevelController.java.
References gamedata.gamecomponents.Level.getId(), and fxml_main.LevelController.setAndDisplayGrid().
void fxml_main.LevelController.setAndDisplayGrid (Level level) private
Definition at line 161 of file LevelController.java.
References authoring_environment.SuperGrid.displayPane(), fxml_main.GUIGridReference.getGrid(), gamedata.gamecomponents.Level.getGrid(), fxml_main.GridComponentAbstCtrl< Level >.myGridReference, and fxml_main.GUIGridReference.setGrid().
Referenced by fxml_main.LevelController.globalNewBtnOnClickAction(), fxml_main.LevelController.initEntryEditBtn(), and fxml_main.LevelController.makeEntryBox().
Member Data Documentation
String fxml_main.LevelController.myGridShape private
Definition at line 35 of file LevelController.java.
ScrollPane fxml_main.LevelController.myGridSPane private
Definition at line 31 of file LevelController.java.
LevelData fxml_main.LevelController.myLevelData private
Definition at line 32 of file LevelController.java.
PatchTypeData fxml_main.LevelController.myPatchTypes private
Definition at line 34 of file LevelController.java.
PieceTypeData fxml_main.LevelController.myPieceTypes private
Definition at line 33 of file LevelController.java.
PlayerData fxml_main.LevelController.myPlayerData private
Definition at line 36 of file LevelController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/LevelController.java