voogasalad_VOOGirlsGeneration: authoring_environment.GUIGrid Class Reference
authoring_environment.GUIGrid Class Reference
Public Member Functions
GUIGrid ()
GUIGrid (int cols, int rows, double tileHeight, String shape)
GUIGrid (int cols, int rows, double tileHeight, String shape, PieceInstanceData pieceData, PatchInstanceData patchData)
GUIGrid (int cols, int rows, double tileHeight, String shape, GUIGrid copyGrid)
void addPieceAtLoc (Piece pieceType, Point2D.Double loc)
void addPatchAtLoc (Patch patchType, Point2D.Double loc)
boolean isPieceOccupied (Point2D.Double loc)
boolean isPatchOccupied (Point2D.Double loc)
void removePieceAtCoordinate (Point2D.Double coor)
void removePatchAtCoordinate (Point2D.Double coor)
Piece getPiece (Point2D.Double loc)
Patch getPatch (Point2D.Double loc)
void removePiece (Piece p)
void removePatch (Patch p)
List< Piece > getRemovedPieces ()
List< Piece > getPlayerPieces (int playerId)
void repopulateGrid ()
void repopulate ()
void removeRunOffData (int numCols, int numRows)
void update (Observable o, Object arg)
void paneSetOnMousePressed (EventHandler< MouseEvent > handler)
void paneSetOnMouseDragged (EventHandler< MouseEvent > handler)
void runEvents (BiConsumer< List< IHasStats >, GUIGrid > eventFunc)
PieceInstanceData getPieceData ()
PatchInstanceData getPatchData ()
String toString ()
Public Member Functions inherited from authoring_environment.SuperGrid
SuperGrid ()
SuperGrid (int cols, int rows, double tileHeight, String shape)
int getNumRows ()
int getNumCols ()
double getTileHeight ()
void displayPane (ScrollPane parent)
Point2D.Double findClickedCoordinate (double xLoc, double yLoc)
SuperTile findClickedTile (double xLoc, double yLoc)
SuperTile findTile (Point2D coor)
Private Member Functions
void replacePieceType (Piece pieceType)
void replacePatchType (Patch patchType)
void removePieceType (PieceTypeData typeData)
void removePatchType (PatchTypeData typeData)
void addPieceToTile (Piece pieceType, Point2D.Double loc)
void addPatchToTile (Patch patchType, Point2D.Double loc)
Private Attributes
PieceInstanceData myPieceData
PatchInstanceData myPatchData
Additional Inherited Members
Protected Member Functions inherited from authoring_environment.SuperGrid
void clearGridImages ()
void initGridTiles (String shape)
Protected Attributes inherited from authoring_environment.SuperGrid
int myNumRows
int myNumCols
double myTileHeight
String myShape
transient Pane myPane
transient List< List< SuperTile > > myGrid
Detailed Description
Authoring and player both use this grid
Author
VOOGirls Generation
Definition at line 28 of file GUIGrid.java.
Constructor & Destructor Documentation
authoring_environment.GUIGrid.GUIGrid ()
Default constructor for GUIGrid. Only for testing purposes.
Definition at line 36 of file GUIGrid.java.
authoring_environment.GUIGrid.GUIGrid (int cols, int rows, double tileHeight, String shape)
Constructor for a new GUIGrid
Parameters
cols - number of columns (NOTE: cols = X direction)
rows - number of rows (NOTE: rows = Y direction)
tileHeight - height of tiles in pixels
shape - shape of the grid given as string identifier in properties
Definition at line 48 of file GUIGrid.java.
authoring_environment.GUIGrid.GUIGrid (int cols, int rows, double tileHeight, String shape, PieceInstanceData pieceData, PatchInstanceData patchData)
Constructor for a new GUIGrid given saved PieceData and PatchData Specifically for JSON and game loading
Parameters
cols - number of columns (NOTE: cols = X direction)
rows - number of rows (NOTE: rows = Y direction)
tileHeight - height of tiles in pixels
shape - shape of the grid given as string identifier in properties
pieceData - saved pieceData
patchData - saved patchData
Definition at line 65 of file GUIGrid.java.
authoring_environment.GUIGrid.GUIGrid (int cols, int rows, double tileHeight, String shape, GUIGrid copyGrid)
Constructor for make a new GUIGrid after editing a GUIGrid's dimensions or size
Parameters
cols - number of columns (NOTE: cols = X direction)
rows - number of rows (NOTE: rows = Y direction)
tileHeight - height of tiles in pixels
shape - shape of the grid given as string identifier in properties
copyGrid - Grid whose data needs to be copied in
Definition at line 83 of file GUIGrid.java.
References authoring_environment.GUIGrid.myPatchData, authoring_environment.GUIGrid.myPieceData, authoring_environment.GUIGrid.removeRunOffData(), and authoring_environment.GUIGrid.repopulate().
Member Function Documentation
void authoring_environment.GUIGrid.addPatchAtLoc (Patch patchType, Point2D.Double loc)
Definition at line 102 of file GUIGrid.java.
References authoring.data.PatchInstanceData.add(), gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.GUIGrid.isPatchOccupied(), authoring_environment.SuperGrid.myGrid, authoring_environment.GUIGrid.removePatchAtCoordinate(), and authoring_environment.SuperTile.setPatchImage().
Referenced by tests.TestGameCreator.createNewGrid(), and fxml_main.PatchController.makeEntryBox().
void authoring_environment.GUIGrid.addPatchToTile (Patch patchType, Point2D.Double loc) private
Definition at line 340 of file GUIGrid.java.
References gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.SuperGrid.myGrid, and authoring_environment.SuperTile.setPatchImage().
Referenced by authoring_environment.GUIGrid.repopulate(), and authoring_environment.GUIGrid.repopulateGrid().
void authoring_environment.GUIGrid.addPieceAtLoc (Piece pieceType, Point2D.Double loc)
Definition at line 92 of file GUIGrid.java.
References authoring.data.PieceInstanceData.add(), gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.GUIGrid.isPieceOccupied(), authoring_environment.SuperGrid.myGrid, authoring_environment.GUIGrid.removePieceAtCoordinate(), and authoring_environment.SuperTile.setPieceImage().
Referenced by tests.TestGameCreator.createNewGrid(), gamedata.events.globalaction.MakePieceAtLocation.doBehavior(), and fxml_main.PieceController.makeEntryBox().
void authoring_environment.GUIGrid.addPieceToTile (Piece pieceType, Point2D.Double loc) private
Definition at line 334 of file GUIGrid.java.
References gamedata.gamecomponents.GridComponent.getImageView(), authoring_environment.SuperGrid.myGrid, and authoring_environment.SuperTile.setPieceImage().
Referenced by authoring_environment.GUIGrid.repopulate(), and authoring_environment.GUIGrid.repopulateGrid().
Patch authoring_environment.GUIGrid.getPatch (Point2D.Double loc)
Returns the patch at loc
Parameters
loc
Returns
Definition at line 215 of file GUIGrid.java.
References authoring.data.PatchInstanceData.getData().
Referenced by fxml_main.PatchController.initGlobalEditBtn(), and authoring_environment.GUIGrid.removePatchAtCoordinate().
PatchInstanceData authoring_environment.GUIGrid.getPatchData ()
Definition at line 366 of file GUIGrid.java.
References authoring_environment.GUIGrid.myPatchData.
Piece authoring_environment.GUIGrid.getPiece (Point2D.Double loc)
Returns the piece at loc
Parameters
loc
Returns
Definition at line 200 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData().
Referenced by gamedata.goals.PiecesRemovedGoal.checkGameState(), gamedata.events.globalaction.MakePieceAtLocation.doBehavior(), gamePlayer.ViewController.highlightSelected(), fxml_main.PieceController.initGlobalEditBtn(), gameengine.movement.Movement.isValidLocation(), gamePlayer.ViewController.performAction(), gameengine.player.SimpleAIPlayer.play(), authoring_environment.GUIGrid.removePieceAtCoordinate(), tests.GlobalActionTester.TestCreatePiece(), tests.GlobalActionTester.TestDeletePiece(), and tests.JSONTesterMain.testJSONwrite().
PieceInstanceData authoring_environment.GUIGrid.getPieceData ()
Definition at line 362 of file GUIGrid.java.
References authoring_environment.GUIGrid.myPieceData.
List<Piece> authoring_environment.GUIGrid.getPlayerPieces (int playerId)
Returns all pieces that belong to a given player
Parameters
playerId
ID of player
Returns
List of pieces belonging to the player
Definition at line 259 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData().
Referenced by gameengine.player.SimpleAIPlayer.play().
List<Piece> authoring_environment.GUIGrid.getRemovedPieces ()
Gets Pieces that have been tagged for removal
Returns
Definition at line 241 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData().
Referenced by gamedata.gamecomponents.Level.garbageCollectPieces().
boolean authoring_environment.GUIGrid.isPatchOccupied (Point2D.Double loc)
Definition at line 121 of file GUIGrid.java.
References authoring.data.PatchInstanceData.getData().
Referenced by authoring_environment.GUIGrid.addPatchAtLoc(), and authoring_environment.GUIGrid.removePatchAtCoordinate().
boolean authoring_environment.GUIGrid.isPieceOccupied (Point2D.Double loc)
Definition at line 112 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData().
Referenced by authoring_environment.GUIGrid.addPieceAtLoc(), and authoring_environment.GUIGrid.removePieceAtCoordinate().
void authoring_environment.GUIGrid.paneSetOnMouseDragged (EventHandler< MouseEvent > handler)
Definition at line 350 of file GUIGrid.java.
References authoring_environment.SuperGrid.myPane.
Referenced by fxml_main.PatchController.initGlobalDelBtn(), fxml_main.PieceController.initGlobalDelBtn(), fxml_main.PatchController.initGlobalEditBtn(), fxml_main.PieceController.initGlobalEditBtn(), fxml_main.PatchController.makeEntryBox(), and fxml_main.PieceController.makeEntryBox().
void authoring_environment.GUIGrid.paneSetOnMousePressed (EventHandler< MouseEvent > handler)
Definition at line 346 of file GUIGrid.java.
References authoring_environment.SuperGrid.myPane.
Referenced by fxml_main.PatchController.initGlobalDelBtn(), fxml_main.PieceController.initGlobalDelBtn(), fxml_main.PatchController.initGlobalEditBtn(), fxml_main.PieceController.initGlobalEditBtn(), fxml_main.PatchController.makeEntryBox(), and fxml_main.PieceController.makeEntryBox().
void authoring_environment.GUIGrid.removePatch (Patch p)
Definition at line 230 of file GUIGrid.java.
References authoring_environment.SuperGrid.findTile(), gamedata.gamecomponents.GridComponent.getLoc(), authoring.data.PatchInstanceData.remove(), and authoring_environment.SuperTile.removePatchImage().
Referenced by authoring_environment.GUIGrid.removePatchAtCoordinate().
void authoring_environment.GUIGrid.removePatchAtCoordinate (Point2D.Double coor)
Removes a piece at the given coordinates. NOTE: Point2D.Double coordinates given as X = column number, Y = row number
Parameters
coor - Point2D.Double containing coordinates of the piece to remove given as [Col, Row]
Definition at line 153 of file GUIGrid.java.
References authoring_environment.GUIGrid.getPatch(), authoring_environment.GUIGrid.isPatchOccupied(), and authoring_environment.GUIGrid.removePatch().
Referenced by authoring_environment.GUIGrid.addPatchAtLoc(), and fxml_main.PatchController.initGlobalDelBtn().
void authoring_environment.GUIGrid.removePatchType (PatchTypeData typeData) private
Definition at line 186 of file GUIGrid.java.
References authoring.data.PatchTypeData.getIdSet(), authoring_environment.SuperTile.removePatchImage(), and authoring.data.PatchInstanceData.removeUnknown().
Referenced by authoring_environment.GUIGrid.update().
void authoring_environment.GUIGrid.removePiece (Piece p)
Definition at line 224 of file GUIGrid.java.
References authoring_environment.SuperGrid.findTile(), gamedata.gamecomponents.GridComponent.getLoc(), authoring.data.PieceInstanceData.remove(), and authoring_environment.SuperTile.removePieceImage().
Referenced by gamedata.gamecomponents.Level.garbageCollectPieces(), and authoring_environment.GUIGrid.removePieceAtCoordinate().
void authoring_environment.GUIGrid.removePieceAtCoordinate (Point2D.Double coor)
Removes a piece at the given coordinates. NOTE: Point2D.Double coordinates given as X = column number, Y = row number
Parameters
coor - Point2D.Double containing coordinates of the piece to remove given as [Col, Row]
Definition at line 138 of file GUIGrid.java.
References authoring_environment.GUIGrid.getPiece(), authoring_environment.GUIGrid.isPieceOccupied(), and authoring_environment.GUIGrid.removePiece().
Referenced by authoring_environment.GUIGrid.addPieceAtLoc(), gamedata.events.globalaction.DeletePieceAtLocation.doBehavior(), and fxml_main.PieceController.initGlobalDelBtn().
void authoring_environment.GUIGrid.removePieceType (PieceTypeData typeData) private
Definition at line 178 of file GUIGrid.java.
References authoring.data.PieceTypeData.getIdSet(), authoring_environment.SuperTile.removePieceImage(), and authoring.data.PieceInstanceData.removeUnknown().
Referenced by authoring_environment.GUIGrid.update().
void authoring_environment.GUIGrid.removeRunOffData (int numCols, int numRows)
Definition at line 289 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData(), and authoring.data.PatchInstanceData.getData().
Referenced by authoring_environment.GUIGrid.GUIGrid().
void authoring_environment.GUIGrid.replacePatchType (Patch patchType) private
Definition at line 170 of file GUIGrid.java.
References gamedata.gamecomponents.GridComponent.getImageView(), authoring.data.PatchInstanceData.replace(), and authoring_environment.SuperTile.setPatchImage().
Referenced by authoring_environment.GUIGrid.update().
void authoring_environment.GUIGrid.replacePieceType (Piece pieceType) private
Definition at line 162 of file GUIGrid.java.
References gamedata.gamecomponents.GridComponent.getImageView(), authoring.data.PieceInstanceData.replace(), and authoring_environment.SuperTile.setPieceImage().
Referenced by authoring_environment.GUIGrid.update().
void authoring_environment.GUIGrid.repopulate ()
Definition at line 280 of file GUIGrid.java.
References authoring_environment.GUIGrid.addPatchToTile(), authoring_environment.GUIGrid.addPieceToTile(), authoring.data.PieceInstanceData.getData(), and authoring.data.PatchInstanceData.getData().
Referenced by authoring_environment.GUIGrid.GUIGrid().
void authoring_environment.GUIGrid.repopulateGrid ()
Definition at line 269 of file GUIGrid.java.
References authoring_environment.GUIGrid.addPatchToTile(), authoring_environment.GUIGrid.addPieceToTile(), authoring.data.PieceInstanceData.getData(), authoring.data.PatchInstanceData.getData(), authoring_environment.SuperGrid.initGridTiles(), and authoring_environment.SuperGrid.myShape.
Referenced by gamePlayer.ViewController.checkEndActions(), gameengine.movement.Movement.doBehavior(), gameengine.player.SimpleAIPlayer.play(), gamePlayer.ViewController.testPlayGame(), gamePlayer.ViewController.testPlayGameInTab(), and gamePlayer.ViewController.testPlayGUIGame().
void authoring_environment.GUIGrid.runEvents (BiConsumer< List< IHasStats >, GUIGrid > eventFunc)
Definition at line 354 of file GUIGrid.java.
References authoring.data.PieceInstanceData.getData(), and authoring.data.PatchInstanceData.getData().
Referenced by gamedata.gamecomponents.Level.runGameEvents().
String authoring_environment.GUIGrid.toString ()
Definition at line 371 of file GUIGrid.java.
References authoring.data.PatchInstanceData.getData(), and authoring.data.PieceInstanceData.getData().
Referenced by gamedata.gamecomponents.Level.toString().
void authoring_environment.GUIGrid.update (Observable o, Object arg)
Definition at line 311 of file GUIGrid.java.
References authoring_environment.GUIGrid.removePatchType(), authoring_environment.GUIGrid.removePieceType(), authoring_environment.GUIGrid.replacePatchType(), and authoring_environment.GUIGrid.replacePieceType().
Member Data Documentation
PatchInstanceData authoring_environment.GUIGrid.myPatchData private
Definition at line 31 of file GUIGrid.java.
Referenced by authoring_environment.GUIGrid.getPatchData(), and authoring_environment.GUIGrid.GUIGrid().
PieceInstanceData authoring_environment.GUIGrid.myPieceData private
Definition at line 30 of file GUIGrid.java.
Referenced by authoring_environment.GUIGrid.getPieceData(), and authoring_environment.GUIGrid.GUIGrid().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/GUIGrid.java