voogasalad_VOOGirlsGeneration: authoring.concretefeatures.menus.FileX Class Reference
authoring.concretefeatures.menus.FileX Class Reference
Classes
class ExitHandler
Public Member Functions
FileX (WorkspaceView wsView)
Static Public Attributes
static final String myLabel = "File"
static final String newLevelLabel = "Create New Level"
static final String openLabel = "Edit Existing Game"
static final String saveLabel = "Save Game"
static final String exitLabel = "Exit"
Private Member Functions
void handleNewLevel ()
void handleLoad ()
void handleSave ()
Private Attributes
WorkspaceView myWorkspaceView
Detailed Description
Basic menu options for the authoring environment
Author
Rica
Definition at line 27 of file FileX.java.
Constructor & Destructor Documentation
authoring.concretefeatures.menus.FileX.FileX (WorkspaceView wsView)
Definition at line 35 of file FileX.java.
References authoring.concretefeatures.menus.FileX.handleLoad(), authoring.concretefeatures.menus.FileX.handleNewLevel(), and authoring.concretefeatures.menus.FileX.handleSave().
Member Function Documentation
void authoring.concretefeatures.menus.FileX.handleLoad () private
Definition at line 56 of file FileX.java.
References gamedata.JSON.JSONManager.readFromJSONFile().
Referenced by authoring.concretefeatures.menus.FileX.FileX().
void authoring.concretefeatures.menus.FileX.handleNewLevel () private
Definition at line 52 of file FileX.java.
Referenced by authoring.concretefeatures.menus.FileX.FileX().
void authoring.concretefeatures.menus.FileX.handleSave () private
Creates a file chooser and uses that file path to save a JSON file to
Definition at line 76 of file FileX.java.
References tests.TestGameCreator.createNewGame(), and gamedata.JSON.JSONManager.writeToJSON().
Referenced by authoring.concretefeatures.menus.FileX.FileX().
Member Data Documentation
final String authoring.concretefeatures.menus.FileX.exitLabel = "Exit" static
Definition at line 32 of file FileX.java.
final String authoring.concretefeatures.menus.FileX.myLabel = "File" static
Definition at line 28 of file FileX.java.
WorkspaceView authoring.concretefeatures.menus.FileX.myWorkspaceView private
Definition at line 33 of file FileX.java.
final String authoring.concretefeatures.menus.FileX.newLevelLabel = "Create New Level" static
Definition at line 29 of file FileX.java.
final String authoring.concretefeatures.menus.FileX.openLabel = "Edit Existing Game" static
Definition at line 30 of file FileX.java.
final String authoring.concretefeatures.menus.FileX.saveLabel = "Save Game" static
Definition at line 31 of file FileX.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/menus/FileX.java