voogasalad_VOOGirlsGeneration: authoring_environment.SandyTile Class Reference
authoring_environment.SandyTile Class Reference
Public Member Functions
SandyTile (Shape bgShape, int size, Point2D coor, Point2D loc)
Point2D getLocation ()
Protected Attributes
ImageView myPieceImage
ImageView myPatchImage
Private Member Functions
ImageView initImageView ()
void alignNodes (Point2D center, Node...nodes)
Private Attributes
Shape myShape
int mySize
Point2D myCoordinates
Point2D myLocation
Detailed Description
SandyTiles are any shape tiles
Author
Jennie Ju
Definition at line 15 of file SandyTile.java.
Constructor & Destructor Documentation
authoring_environment.SandyTile.SandyTile (Shape bgShape, int size, Point2D coor, Point2D loc)
Parameters
bgShape Tile shape
size Tile size
coor Grid coordination
loc Layout coordination
Definition at line 30 of file SandyTile.java.
References authoring_environment.SandyTile.alignNodes(), and authoring_environment.SandyTile.initImageView().
Member Function Documentation
void authoring_environment.SandyTile.alignNodes (Point2D center, Node... nodes) private
Definition at line 56 of file SandyTile.java.
Referenced by authoring_environment.SandyTile.SandyTile().
Point2D authoring_environment.SandyTile.getLocation ()
Definition at line 44 of file SandyTile.java.
References authoring_environment.SandyTile.myCoordinates.
Referenced by authoring_environment.ShapeGrid.addTerrain(), and authoring_environment.ShapeGrid.addUnit().
ImageView authoring_environment.SandyTile.initImageView () private
Definition at line 48 of file SandyTile.java.
Referenced by authoring_environment.SandyTile.SandyTile().
Member Data Documentation
Point2D authoring_environment.SandyTile.myCoordinates private
Definition at line 18 of file SandyTile.java.
Referenced by authoring_environment.SandyTile.getLocation().
Point2D authoring_environment.SandyTile.myLocation private
Definition at line 19 of file SandyTile.java.
ImageView authoring_environment.SandyTile.myPatchImage protected
Definition at line 21 of file SandyTile.java.
Referenced by authoring_environment.ShapeGrid.addTerrain(), authoring_environment.ShapeGrid.removePatches(), and authoring_environment.ShapeGrid.removeTerrain().
ImageView authoring_environment.SandyTile.myPieceImage protected
Definition at line 20 of file SandyTile.java.
Referenced by authoring_environment.ShapeGrid.addUnit(), authoring_environment.ShapeGrid.removePieces(), and authoring_environment.ShapeGrid.removeUnit().
Shape authoring_environment.SandyTile.myShape private
Definition at line 16 of file SandyTile.java.
int authoring_environment.SandyTile.mySize private
Definition at line 17 of file SandyTile.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/SandyTile.java