voogasalad_VOOGirlsGeneration: authoring.eventeditor.ConditionEditorPane Class Reference
authoring.eventeditor.ConditionEditorPane Class Reference
Public Member Functions
ConditionEditorPane (Consumer< Condition > doneLambda, EventsDataWrapper data, Class<?> c)
Private Member Functions
void initDoneButton (Button doneButton)
void setUpComponents (ChoiceBox< String > typeBox, ChoiceBox< IHasStats > componentBox, ChoiceBox< String > statBox, TextField valueField)
void setupEditor (String oldType, String type, ChoiceBox< IHasStats > refName, ChoiceBox< String > statName, TextField value)
void setupStatsBox (IHasStats source, ChoiceBox< String > box)
void initialize ()
Private Attributes
ChoiceBox< String > myRefType = new ChoiceBox<>()
ChoiceBox< IHasStats > myRefName = new ChoiceBox<>()
ChoiceBox< String > myStat = new ChoiceBox<>()
TextField myVal = new TextField()
Consumer< Condition > myDoneLambda
Condition myCondition
EventsDataWrapper myData
Class<?> myClass
Static Private Attributes
static final int WIDTH_OFFSET = 30
static final String COMPONENTS_LABEL = "Expression"
static final String DONE_LABEL = "Done"
static final Insets MARGINS = new Insets(5, WIDTH_OFFSET, 10, WIDTH_OFFSET)
static final String LABEL_CSS = "-fx-font-size: 14pt;"
Detailed Description
Definition at line 27 of file ConditionEditorPane.java.
Constructor & Destructor Documentation
authoring.eventeditor.ConditionEditorPane.ConditionEditorPane (Consumer< Condition > doneLambda, EventsDataWrapper data, Class<?> c)
Definition at line 45 of file ConditionEditorPane.java.
References authoring.eventeditor.ConditionEditorPane.initialize().
Member Function Documentation
void authoring.eventeditor.ConditionEditorPane.initDoneButton (Button doneButton) private
References the specific values specified by the ChoiceBox and TextField. Then constructs a Condition object from those values.
Constructs the Condition using REFLECTION
Parameters
doneButton
Definition at line 59 of file ConditionEditorPane.java.
References utilities.reflection.Reflection.createInstance().
Referenced by authoring.eventeditor.ConditionEditorPane.initialize().
void authoring.eventeditor.ConditionEditorPane.initialize () private
Initialize all the GUI nonsense. Please ignore this for masterpiece.
Definition at line 140 of file ConditionEditorPane.java.
References authoring_environment.UIspecs.allPadding, authoring.eventeditor.ConditionEditorPane.initDoneButton(), and authoring.eventeditor.ConditionEditorPane.setUpComponents().
Referenced by authoring.eventeditor.ConditionEditorPane.ConditionEditorPane().
void authoring.eventeditor.ConditionEditorPane.setUpComponents (ChoiceBox< String > typeBox, ChoiceBox< IHasStats > componentBox, ChoiceBox< String > statBox, TextField valueField) private
Definition at line 88 of file ConditionEditorPane.java.
References authoring.eventeditor.ConditionEditorPane.setupEditor(), and authoring.eventeditor.ConditionEditorPane.setupStatsBox().
Referenced by authoring.eventeditor.ConditionEditorPane.initialize().
void authoring.eventeditor.ConditionEditorPane.setupEditor (String oldType, String type, ChoiceBox< IHasStats > refName, ChoiceBox< String > statName, TextField value) private
Parameters
oldType
type
refName
statName
value
Selects between the three types of input into this Condition
Definition at line 105 of file ConditionEditorPane.java.
References authoring.data.EventsDataWrapper.getPatchTypes(), authoring.data.EventsDataWrapper.getPieceTypes(), and authoring.data.EventsDataWrapper.getPlayers().
Referenced by authoring.eventeditor.ConditionEditorPane.setUpComponents().
void authoring.eventeditor.ConditionEditorPane.setupStatsBox (IHasStats source, ChoiceBox< String > box) private
Definition at line 132 of file ConditionEditorPane.java.
References gamedata.stats.Stats.getStatNames(), and gamedata.gamecomponents.IHasStats.getStats().
Referenced by authoring.eventeditor.ConditionEditorPane.setUpComponents().
Member Data Documentation
final String authoring.eventeditor.ConditionEditorPane.COMPONENTS_LABEL = "Expression" static private
Definition at line 30 of file ConditionEditorPane.java.
final String authoring.eventeditor.ConditionEditorPane.DONE_LABEL = "Done" static private
Definition at line 31 of file ConditionEditorPane.java.
final String authoring.eventeditor.ConditionEditorPane.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 33 of file ConditionEditorPane.java.
final Insets authoring.eventeditor.ConditionEditorPane.MARGINS = new Insets(5, WIDTH_OFFSET, 10, WIDTH_OFFSET) static private
Definition at line 32 of file ConditionEditorPane.java.
Class<?> authoring.eventeditor.ConditionEditorPane.myClass private
Definition at line 43 of file ConditionEditorPane.java.
Condition authoring.eventeditor.ConditionEditorPane.myCondition private
Definition at line 41 of file ConditionEditorPane.java.
EventsDataWrapper authoring.eventeditor.ConditionEditorPane.myData private
Definition at line 42 of file ConditionEditorPane.java.
Consumer<Condition> authoring.eventeditor.ConditionEditorPane.myDoneLambda private
Definition at line 40 of file ConditionEditorPane.java.
ChoiceBox<IHasStats> authoring.eventeditor.ConditionEditorPane.myRefName = new ChoiceBox<>() private
Definition at line 36 of file ConditionEditorPane.java.
ChoiceBox<String> authoring.eventeditor.ConditionEditorPane.myRefType = new ChoiceBox<>() private
Definition at line 35 of file ConditionEditorPane.java.
ChoiceBox<String> authoring.eventeditor.ConditionEditorPane.myStat = new ChoiceBox<>() private
Definition at line 37 of file ConditionEditorPane.java.
TextField authoring.eventeditor.ConditionEditorPane.myVal = new TextField() private
Definition at line 38 of file ConditionEditorPane.java.
final int authoring.eventeditor.ConditionEditorPane.WIDTH_OFFSET = 30 static private
Definition at line 29 of file ConditionEditorPane.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/eventeditor/ConditionEditorPane.java