voogasalad_VOOGirlsGeneration: authoring.concretefeatures.IndividualUnitEditor Class Reference
authoring.concretefeatures.IndividualUnitEditor Class Reference
Public Member Functions
IndividualUnitEditor (Piece piece)
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Member Functions
void initNameField (HBox names)
void initImage (HBox images)
void initPlayerID (HBox players, ChoiceBox< Integer > playersChoice)
void initRot (HBox imageRotation, TextField rotationAmt)
Private Attributes
final int WINDOW_HEIGHT = 400
final int WINDOW_WIDTH = 400
final String NAME = "Piece Editor"
final String NAME_LABEL = "Name: "
final String STAT_EDITOR_LABEL = "Stats Editor"
final String INVENTORY_EDITOR_LABEL = "Inventory Editor"
final String PLAYER_LABEL = "Player ID"
final String ROTATION_LABEL = "Image Rotation (degrees)"
Piece myPiece
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Creates a popup for editing individual units that are on the grid.
Author
Sandy Lee
Definition at line 26 of file IndividualUnitEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.IndividualUnitEditor.IndividualUnitEditor (Piece piece)
Constructor for the individual unit editor pop up
Definition at line 43 of file IndividualUnitEditor.java.
References authoring.concretefeatures.IndividualUnitEditor.initialize().
Member Function Documentation
void authoring.concretefeatures.IndividualUnitEditor.initialize () protected
Definition at line 54 of file IndividualUnitEditor.java.
References authoring_environment.UIspecs.allPadding, gamedata.gamecomponents.Piece.getStats(), authoring.concretefeatures.IndividualUnitEditor.initImage(), authoring.concretefeatures.IndividualUnitEditor.initNameField(), authoring.concretefeatures.IndividualUnitEditor.initPlayerID(), and authoring.concretefeatures.IndividualUnitEditor.initRot().
Referenced by authoring.concretefeatures.IndividualUnitEditor.IndividualUnitEditor().
void authoring.concretefeatures.IndividualUnitEditor.initImage (HBox images) private
This method is to display image of the piece
Parameters
images contains imageview
Definition at line 153 of file IndividualUnitEditor.java.
Referenced by authoring.concretefeatures.IndividualUnitEditor.initialize().
void authoring.concretefeatures.IndividualUnitEditor.initNameField (HBox names) private
This method is to display name of the piece in the editor
Parameters
names contain labels
Definition at line 139 of file IndividualUnitEditor.java.
References authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.concretefeatures.IndividualUnitEditor.initialize().
void authoring.concretefeatures.IndividualUnitEditor.initPlayerID (HBox players, ChoiceBox< Integer > playersChoice) private
This method is to allow users to choose player for individual units
Parameters
players is an hbox
playersChoice contain playerID choices
Definition at line 169 of file IndividualUnitEditor.java.
References authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.concretefeatures.IndividualUnitEditor.initialize().
void authoring.concretefeatures.IndividualUnitEditor.initRot (HBox imageRotation, TextField rotationAmt) private
This method is to allow users to rotate img of a unit
Parameters
imageRotation is an hbox displayed in the editor
rotationAmt where the user types in amt to be rototated
Definition at line 187 of file IndividualUnitEditor.java.
References authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.concretefeatures.IndividualUnitEditor.initialize().
Member Data Documentation
final String authoring.concretefeatures.IndividualUnitEditor.INVENTORY_EDITOR_LABEL = "Inventory Editor" private
Definition at line 33 of file IndividualUnitEditor.java.
Piece authoring.concretefeatures.IndividualUnitEditor.myPiece private
Definition at line 37 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.NAME = "Piece Editor" private
Definition at line 30 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.NAME_LABEL = "Name: " private
Definition at line 31 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.PLAYER_LABEL = "Player ID" private
Definition at line 34 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.ROTATION_LABEL = "Image Rotation (degrees)" private
Definition at line 35 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.STAT_EDITOR_LABEL = "Stats Editor" private
Definition at line 32 of file IndividualUnitEditor.java.
final String authoring.concretefeatures.IndividualUnitEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 36 of file IndividualUnitEditor.java.
final int authoring.concretefeatures.IndividualUnitEditor.WINDOW_HEIGHT = 400 private
Definition at line 28 of file IndividualUnitEditor.java.
final int authoring.concretefeatures.IndividualUnitEditor.WINDOW_WIDTH = 400 private
Definition at line 29 of file IndividualUnitEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/IndividualUnitEditor.java