voogasalad_VOOGirlsGeneration: authoring_environment.RangeGridView Class Reference
authoring_environment.RangeGridView Class Reference
Public Member Functions
RangeGridView (int viewWidth, int viewHeight, double tileSize, String shape, List< Point2D.Double > range)
void update (int width, int height, List< Point2D.Double > range)
List< Point2D.Double > returnSelectedList ()
RangeGrid getGrid ()
Private Member Functions
double getPrefTileSize (int col, int row, double minTileSize)
Point2D cacluateGridSize (List< Point2D.Double > range)
Private Attributes
int myViewWidth
int myViewHeight
double myTileSize
String myShape
RangeGrid myGrid
Static Private Attributes
static final int MIN_TILESIZE = 50
Detailed Description
The ScrollPane which contains any size of RangeGrid.
Author
Mengen Huang
Definition at line 14 of file RangeGridView.java.
Constructor & Destructor Documentation
authoring_environment.RangeGridView.RangeGridView (int viewWidth, int viewHeight, double tileSize, String shape, List< Point2D.Double > range)
The RangeGridView constructor.
Parameters
viewWidth The pixel width of the GridView
viewHeight The pixel height of the GridView
tileSize The size of the tile in the RangeGrid
shape The shape of the tile in the RnageGrid
range The previously set range or a new instantiated Point2D.Double List
Definition at line 30 of file RangeGridView.java.
References authoring_environment.RangeGridView.cacluateGridSize(), authoring_environment.SuperGrid.displayPane(), authoring_environment.RangeGridView.getPrefTileSize(), and authoring_environment.RangeGridView.myTileSize.
Member Function Documentation
Point2D authoring_environment.RangeGridView.cacluateGridSize (List< Point2D.Double > range) private
Get the largest number on x and y axis in range.
Parameters
range The range taken in to shown on the grid
Returns
The width and height of the grid shown.
Definition at line 90 of file RangeGridView.java.
Referenced by authoring_environment.RangeGridView.RangeGridView(), and authoring_environment.RangeGridView.update().
RangeGrid authoring_environment.RangeGridView.getGrid ()
Definition at line 111 of file RangeGridView.java.
References authoring_environment.RangeGridView.myGrid.
Referenced by authoring.concretefeatures.RangeEditor.selectRangeHandler.handle().
double authoring_environment.RangeGridView.getPrefTileSize (int col, int row, double minTileSize) private
Get the preference tile size by getting the larger size from the tile on horizontal or vertical line.
Parameters
col The grid width
row The grid height
minTileSize The minimum tile size set by default
Returns
Definition at line 77 of file RangeGridView.java.
Referenced by authoring_environment.RangeGridView.RangeGridView(), and authoring_environment.RangeGridView.update().
List<Point2D.Double> authoring_environment.RangeGridView.returnSelectedList ()
Definition at line 107 of file RangeGridView.java.
References authoring_environment.RangeGrid.selectedRangeList().
Referenced by authoring.concretefeatures.RangeEditor.SelectHandler.handle(), and authoring.concretefeatures.RangeEditor.initialize().
void authoring_environment.RangeGridView.update (int width, int height, List< Point2D.Double > range)
Update the grid shown on GridView.
Parameters
width The grid width
height The grid height
range The range passed in to shown on the grid.
Definition at line 56 of file RangeGridView.java.
References authoring_environment.RangeGridView.cacluateGridSize(), authoring_environment.SuperGrid.displayPane(), and authoring_environment.RangeGridView.getPrefTileSize().
Referenced by authoring.concretefeatures.RangeEditor.initialize().
Member Data Documentation
final int authoring_environment.RangeGridView.MIN_TILESIZE = 50 static private
Definition at line 15 of file RangeGridView.java.
RangeGrid authoring_environment.RangeGridView.myGrid private
Definition at line 20 of file RangeGridView.java.
Referenced by authoring_environment.RangeGridView.getGrid().
String authoring_environment.RangeGridView.myShape private
Definition at line 19 of file RangeGridView.java.
double authoring_environment.RangeGridView.myTileSize private
Definition at line 18 of file RangeGridView.java.
Referenced by authoring_environment.RangeGridView.RangeGridView().
int authoring_environment.RangeGridView.myViewHeight private
Definition at line 17 of file RangeGridView.java.
int authoring_environment.RangeGridView.myViewWidth private
Definition at line 16 of file RangeGridView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/RangeGridView.java