voogasalad_VOOGirlsGeneration: authoring.data.ActionData Class Reference
authoring.data.ActionData Class Reference
Public Member Functions
ActionData ()
ActionData (List< Action > actions)
ObservableList< String > getActionNames ()
Action getAction (String id)
void add (Action a)
boolean canAdd (Action element)
void remove (Action a)
void replace (Action origEl, Action newEl)
List< Action > getData ()
Public Member Functions inherited from authoring.data.AuthoringData< Action >
void add (T element)
boolean canAdd (T element)
void remove (T element)
void replace (T origEl, T newEl)
List< T > getData ()
Private Attributes
List< Action > myActions
Detailed Description
Class for storing the actions created by the user Stored in the authoring environment
Author
Jennie Ju
Definition at line 22 of file ActionData.java.
Constructor & Destructor Documentation
authoring.data.ActionData.ActionData ()
Constructor for new ActionData, initializes empty list of Actions
Definition at line 30 of file ActionData.java.
authoring.data.ActionData.ActionData (List< Action > actions)
Definition at line 34 of file ActionData.java.
Member Function Documentation
void authoring.data.ActionData.add (Action a)
Definition at line 58 of file ActionData.java.
Referenced by fxml_main.ActionController.initGlobalNewBtn(), authoring.createedit.ActionCreator.initialize(), and authoring.data.ActionData.replace().
boolean authoring.data.ActionData.canAdd (Action element)
Definition at line 63 of file ActionData.java.
References gamedata.action.Action.toString().
Action authoring.data.ActionData.getAction (String id)
Returns the Action with the given String id. Returns null if not found.
Definition at line 50 of file ActionData.java.
Referenced by authoring.concretefeatures.LibraryUnitEditor.addSelectedActions(), and fxml_main.PieceTypeEditor.addSelectedActions().
ObservableList<String> authoring.data.ActionData.getActionNames ()
Definition at line 38 of file ActionData.java.
Referenced by authoring.actionslogic.ActionLogicController.getData(), authoring.createedit.ActionCreator.initialize(), fxml_main.PieceTypeEditor.initModList(), and authoring.concretefeatures.LibraryUnitEditor.LibraryUnitEditor().
List<Action> authoring.data.ActionData.getData ()
Definition at line 82 of file ActionData.java.
References authoring.data.ActionData.myActions.
void authoring.data.ActionData.remove (Action a)
Definition at line 71 of file ActionData.java.
Referenced by fxml_main.ActionController.initEntryDelBtn().
void authoring.data.ActionData.replace (Action origEl, Action newEl)
Definition at line 76 of file ActionData.java.
References authoring.data.ActionData.add().
Referenced by fxml_main.ActionController.initEntryEditBtn().
Member Data Documentation
List<Action> authoring.data.ActionData.myActions private
Definition at line 24 of file ActionData.java.
Referenced by authoring.data.ActionData.getData().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/ActionData.java