voogasalad_VOOGirlsGeneration: utilities.leapMotion.LeapMotionListener Class Reference
utilities.leapMotion.LeapMotionListener Class Reference
Public Member Functions
void onConnect (Controller controller)
void onFrame (Controller controller)
Static Public Attributes
static final String PACKAGE_FILEPATH = "utilities.leapMotion."
static final String GESTURE_BUNDLE = "Untitled"
static final String MOUSE_MOVE_FLAG = "mouse"
Private Member Functions
void enableGestures (Controller controller)
void initializeRobot ()
void performAction (String gestureName)
Private Attributes
ResourceBundle myGestures
Robot myRobot
ILeapMouse myLeapMouse
Detailed Description
Definition at line 14 of file LeapMotionListener.java.
Member Function Documentation
void utilities.leapMotion.LeapMotionListener.enableGestures (Controller controller) private
Definition at line 31 of file LeapMotionListener.java.
Referenced by utilities.leapMotion.LeapMotionListener.onConnect().
void utilities.leapMotion.LeapMotionListener.initializeRobot () private
Definition at line 69 of file LeapMotionListener.java.
Referenced by utilities.leapMotion.LeapMotionListener.onConnect().
void utilities.leapMotion.LeapMotionListener.onConnect (Controller controller)
Definition at line 23 of file LeapMotionListener.java.
References utilities.leapMotion.LeapMotionListener.enableGestures(), and utilities.leapMotion.LeapMotionListener.initializeRobot().
void utilities.leapMotion.LeapMotionListener.onFrame (Controller controller)
Definition at line 76 of file LeapMotionListener.java.
References utilities.leapMotion.ILeapMouse.moveMouse(), and utilities.leapMotion.LeapMotionListener.performAction().
void utilities.leapMotion.LeapMotionListener.performAction (String gestureName) private
Definition at line 88 of file LeapMotionListener.java.
Referenced by utilities.leapMotion.LeapMotionListener.onFrame().
Member Data Documentation
final String utilities.leapMotion.LeapMotionListener.GESTURE_BUNDLE = "Untitled" static
Definition at line 19 of file LeapMotionListener.java.
final String utilities.leapMotion.LeapMotionListener.MOUSE_MOVE_FLAG = "mouse" static
Definition at line 20 of file LeapMotionListener.java.
ResourceBundle utilities.leapMotion.LeapMotionListener.myGestures private
Definition at line 15 of file LeapMotionListener.java.
ILeapMouse utilities.leapMotion.LeapMotionListener.myLeapMouse private
Definition at line 17 of file LeapMotionListener.java.
Robot utilities.leapMotion.LeapMotionListener.myRobot private
Definition at line 16 of file LeapMotionListener.java.
final String utilities.leapMotion.LeapMotionListener.PACKAGE_FILEPATH = "utilities.leapMotion." static
Definition at line 18 of file LeapMotionListener.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/utilities/leapMotion/LeapMotionListener.java