voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.Level Class Reference
gamedata.gamecomponents.Level Class Reference
Public Member Functions
Level ()
Level (GUIGrid gr, List< Event > events, String id, boolean isWinningLevel)
void runGameEvents ()
GUIGrid getGrid ()
List< Event > getEvents ()
String toString ()
void addObserverTo (Observer o)
void garbageCollectPieces ()
void restart ()
String getId ()
Private Member Functions
void initializeDefaultEvents ()
Private Attributes
GUIGrid myGrid
List< Event > myEvents
String myId
boolean isWinningLevel
Static Private Attributes
static final String DEFAULT_ID = "Default"
Detailed Description
Rules define how a player's turn ends Goals define whether or not the level has been won
Author
Jesse, Mike
Definition at line 23 of file Level.java.
Constructor & Destructor Documentation
gamedata.gamecomponents.Level.Level ()
Constructs a default level with a default ID and sets it as NOT the winning level
Definition at line 45 of file Level.java.
gamedata.gamecomponents.Level.Level (GUIGrid gr, List< Event > events, String id, boolean isWinningLevel)
Constructor to create a level
Parameters
gr GUIGrid Containing the Grid
events List of events to be applied to the level
id ID identifier for the Level
isWinningLevel Boolean indication whether winning the level triggers a win clause
Definition at line 62 of file Level.java.
References gamedata.gamecomponents.Level.initializeDefaultEvents(), and gamedata.gamecomponents.Level.isWinningLevel.
Member Function Documentation
void gamedata.gamecomponents.Level.addObserverTo (Observer o)
Adds an observer to the level
Parameters
o Observer to be added to the level
Definition at line 126 of file Level.java.
void gamedata.gamecomponents.Level.garbageCollectPieces ()
Removes all pieces marked for removal
Definition at line 133 of file Level.java.
References gamedata.gamecomponents.Inventory.getAllInventory(), authoring_environment.GUIGrid.getRemovedPieces(), gamedata.gamecomponents.Inventory.removeItem(), and authoring_environment.GUIGrid.removePiece().
Referenced by gamedata.gamecomponents.Level.runGameEvents().
List<Event> gamedata.gamecomponents.Level.getEvents ()
Returns the List of Events contained in this level.
Returns
Definition at line 105 of file Level.java.
References gamedata.gamecomponents.Level.myEvents.
Referenced by fxml_main.LevelEditor.LevelEditor(), and tests.JSONTesterMain.testJSONwrite().
GUIGrid gamedata.gamecomponents.Level.getGrid ()
Returns the grid contained in this level.
Returns
Definition at line 96 of file Level.java.
References gamedata.gamecomponents.Level.myGrid.
Referenced by fxml_main.LevelController.addComponentObservingLevel(), gamePlayer.ViewController.beginGame(), gamedata.goals.PlayerPiecesRemovedGoal.checkGameState(), gamedata.goals.PieceOnPatchGoal.checkGameState(), gamedata.goals.PiecesRemovedGoal.checkGameState(), tests.GlobalActionTester.GlobalActionTester(), gamePlayer.ViewController.highlightSelected(), fxml_main.LevelController.initEntryDelBtn(), gamePlayer.ViewController.initializeGrid(), fxml_main.LevelEditor.LevelEditor(), gamePlayer.ViewController.performAction(), gameengine.player.SimpleAIPlayer.play(), fxml_main.LevelController.setAndDisplayGrid(), tests.GlobalActionTester.TestCreatePiece(), tests.GlobalActionTester.TestDeletePiece(), tests.JSONTesterMain.testJSONwrite(), and gamePlayer.ViewController.testPlayGame().
String gamedata.gamecomponents.Level.getId ()
Getter to get the ID representing the level
Returns
String containing the ID of the level
Definition at line 170 of file Level.java.
References gamedata.gamecomponents.Level.myId.
Referenced by authoring.data.LevelData.canAdd(), fxml_main.LevelEditor.LevelEditor(), fxml_main.LevelController.makeEntryBox(), and tests.GlobalActionTester.TestLevelChange().
void gamedata.gamecomponents.Level.initializeDefaultEvents () private
Initiates a default event for testing purposes.
Definition at line 74 of file Level.java.
Referenced by gamedata.gamecomponents.Level.Level().
void gamedata.gamecomponents.Level.restart ()
Restarts the level
Definition at line 161 of file Level.java.
Referenced by gamedata.gamecomponents.Game.restartLevel().
void gamedata.gamecomponents.Level.runGameEvents ()
Runs events using the magic of laaaaaaaaaaambda
Definition at line 81 of file Level.java.
References gamedata.gamecomponents.Level.garbageCollectPieces(), and authoring_environment.GUIGrid.runEvents().
Referenced by gamePlayer.ViewController.checkEndActions().
String gamedata.gamecomponents.Level.toString ()
toString method used to test JSON read/write
Definition at line 112 of file Level.java.
References gamedata.gamecomponents.Level.isWinningLevel, and authoring_environment.GUIGrid.toString().
Member Data Documentation
final String gamedata.gamecomponents.Level.DEFAULT_ID = "Default" static private
Definition at line 24 of file Level.java.
boolean gamedata.gamecomponents.Level.isWinningLevel private
Definition at line 39 of file Level.java.
Referenced by gamedata.gamecomponents.Level.Level(), and gamedata.gamecomponents.Level.toString().
List<Event> gamedata.gamecomponents.Level.myEvents private
Goals defining how to win the level, how to react to changes
Definition at line 33 of file Level.java.
Referenced by gamedata.gamecomponents.Level.getEvents().
GUIGrid gamedata.gamecomponents.Level.myGrid private
GUIGrid containing the state of the level
Definition at line 29 of file Level.java.
Referenced by gamedata.gamecomponents.Level.getGrid().
String gamedata.gamecomponents.Level.myId private
ID Identifier for the Level
Definition at line 37 of file Level.java.
Referenced by gamedata.gamecomponents.Level.getId().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/Level.java