voogasalad_VOOGirlsGeneration: authoring.concretefeatures.GameCreator Class Reference
authoring.concretefeatures.GameCreator Class Reference
Public Member Functions
GameCreator (WorkspaceView wsView)
ComboBox< String > initChoiceBox (VBox box, ComboBox< String > choices)
TextField initLabel (VBox box, String labelName)
Protected Member Functions
void initializeVBoxContent ()
Private Member Functions
void handleCreate (String levelName, String gridType, int col, int row)
Private Attributes
List< String > gridTypes = new ArrayList<String>()
ComboBox< String > gridChoiceBox
WorkspaceView myWorkspaceView
VBox box = new VBox()
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
static final int HEIGHT = 600
static final int WIDTH = 400
static final Insets MARGINS = new Insets(20, WIDTH/4, 20, WIDTH/4 - 10)
static final String LABEL_CSS = "-fx-font-size: 25pt;"
static final String BUTTON_CSS = "-fx-padding: 10;"
static final String NAME = "Level Creator"
static final String DEFAULT_VALUES_BUTTON = "Load Default Values"
static final String GRID_HEIGHT_LABEL = "Number of Rows:"
static final String GRID_WIDTH_LABEL = "Number of Columns:"
static final String PLAYER_NUMBER_LABEL = "Number of Players:"
static final String NAME_LABEL = "Level name"
static final String TEMPLATE_LABEL = "Create"
static final String GRID_CHOICE_LABEL = "Grid Type: "
static final String SQUARE_GRID = "Square Grid"
static final String HEXAGON_GRID = "Hexagon Grid"
static final String CIRCLE_GRID = "Circle Grid"
static final String DEFAULT_LEVEL_NAME = "Level 1"
static final String DEFAULT_PLAYER_NUM = "3"
static final String DEFAULT_GRID_HEIGHT = "10"
static final String DEFAULT_GRID_WIDTH = "10"
Detailed Description
Creates a new game. The user can set elements for each game. (includes number of levels, grid size, grid type and number of players)
Author
Sandy Lee
Definition at line 31 of file GameCreator.java.
Constructor & Destructor Documentation
authoring.concretefeatures.GameCreator.GameCreator (WorkspaceView wsView)
Constructor that sets the dimensions of the TerrainCreator GUI component and initializes it.
Parameters
library : Library to which terrain will be added.
Definition at line 67 of file GameCreator.java.
References authoring.concretefeatures.GameCreator.initializeVBoxContent().
Member Function Documentation
void authoring.concretefeatures.GameCreator.handleCreate (String levelName, String gridType, int col, int row) private
When the user clicks the create button, a LevelEditor is created which creates the new Workspace tab. Also, I add the level editor to my list to keep track so when data needs to be pulled, you can get the level data from each of my level editors
Parameters
levelName
gridType
col
row
Definition at line 151 of file GameCreator.java.
Referenced by authoring.concretefeatures.GameCreator.initializeVBoxContent().
ComboBox<String> authoring.concretefeatures.GameCreator.initChoiceBox (VBox box, ComboBox< String > choices)
Definition at line 156 of file GameCreator.java.
References authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.concretefeatures.GameCreator.initializeVBoxContent().
void authoring.concretefeatures.GameCreator.initializeVBoxContent () protected
Definition at line 88 of file GameCreator.java.
References authoring.concretefeatures.GameCreator.handleCreate(), authoring.concretefeatures.GameCreator.initChoiceBox(), authoring.concretefeatures.GameCreator.initLabel(), and authoring_environment.UIspecs.topBottomPadding.
Referenced by authoring.concretefeatures.GameCreator.GameCreator().
TextField authoring.concretefeatures.GameCreator.initLabel (VBox box, String labelName)
Definition at line 165 of file GameCreator.java.
References authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.concretefeatures.GameCreator.initializeVBoxContent().
Member Data Documentation
VBox authoring.concretefeatures.GameCreator.box = new VBox() private
Definition at line 58 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.BUTTON_CSS = "-fx-padding: 10;" static private
Definition at line 37 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.CIRCLE_GRID = "Circle Grid" static private
Definition at line 49 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.DEFAULT_GRID_HEIGHT = "10" static private
Definition at line 52 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.DEFAULT_GRID_WIDTH = "10" static private
Definition at line 53 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.DEFAULT_LEVEL_NAME = "Level 1" static private
Definition at line 50 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.DEFAULT_PLAYER_NUM = "3" static private
Definition at line 51 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.DEFAULT_VALUES_BUTTON = "Load Default Values" static private
Definition at line 40 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.GRID_CHOICE_LABEL = "Grid Type: " static private
Definition at line 46 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.GRID_HEIGHT_LABEL = "Number of Rows:" static private
Definition at line 41 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.GRID_WIDTH_LABEL = "Number of Columns:" static private
Definition at line 42 of file GameCreator.java.
ComboBox<String> authoring.concretefeatures.GameCreator.gridChoiceBox private
Definition at line 56 of file GameCreator.java.
List<String> authoring.concretefeatures.GameCreator.gridTypes = new ArrayList<String>() private
Definition at line 55 of file GameCreator.java.
final int authoring.concretefeatures.GameCreator.HEIGHT = 600 static private
Definition at line 33 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.HEXAGON_GRID = "Hexagon Grid" static private
Definition at line 48 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.LABEL_CSS = "-fx-font-size: 25pt;" static private
Definition at line 36 of file GameCreator.java.
final Insets authoring.concretefeatures.GameCreator.MARGINS = new Insets(20, WIDTH/4, 20, WIDTH/4 - 10) static private
Definition at line 35 of file GameCreator.java.
WorkspaceView authoring.concretefeatures.GameCreator.myWorkspaceView private
Definition at line 57 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.NAME = "Level Creator" static private
Definition at line 39 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.NAME_LABEL = "Level name" static private
Definition at line 44 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.PLAYER_NUMBER_LABEL = "Number of Players:" static private
Definition at line 43 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.SQUARE_GRID = "Square Grid" static private
Definition at line 47 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 32 of file GameCreator.java.
final String authoring.concretefeatures.GameCreator.TEMPLATE_LABEL = "Create" static private
Definition at line 45 of file GameCreator.java.
final int authoring.concretefeatures.GameCreator.WIDTH = 400 static private
Definition at line 34 of file GameCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/GameCreator.java