voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.IHasStats Interface Reference
gamedata.gamecomponents.IHasStats Interface Reference
Public Member Functions
abstract Stats getStats ()
abstract Point2D getLoc ()
abstract String toString ()
Detailed Description
Marker Interface used to group together gamecomponents that have statistics (Player, Piece, Patch) stored in a Stats object, to enable abstraction when implementing Events.
Author
Mike Zhu
Definition at line 15 of file IHasStats.java.
Member Function Documentation
abstract Point2D gamedata.gamecomponents.IHasStats.getLoc () abstract
Implemented in gamedata.gamecomponents.GridComponent, gameengine.player.Player, and gamedata.gamecomponents.PlayerData.
abstract Stats gamedata.gamecomponents.IHasStats.getStats () abstract
Implemented in gamedata.gamecomponents.Piece, gameengine.player.Player, gamedata.gamecomponents.Patch, and gamedata.gamecomponents.PlayerData.
Referenced by gamedata.events.conditions.StatGreaterThan.compare(), gamedata.events.conditions.StatLessThan.compare(), gamedata.events.conditions.StatEquals.compare(), gamedata.action.StatsDataModifier.modifyStats(), and authoring.eventeditor.ConditionEditorPane.setupStatsBox().
abstract String gamedata.gamecomponents.IHasStats.toString () abstract
Implemented in gamedata.gamecomponents.GridComponent, gameengine.player.Player, and gamedata.gamecomponents.Patch.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/IHasStats.java