voogasalad_VOOGirlsGeneration: authoring.eventeditor.EventEditorController Class Reference
authoring.eventeditor.EventEditorController Class Reference
Public Member Functions
void initialize (URL fxmlFileLocation, ResourceBundle resources)
void loadEvents (List< Event > events)
void loadData (EventsDataWrapper data)
void loadGameState (IChangeGameState state)
void loadPlayerData (PlayerData playerData)
Private Member Functions
void handleNewCondition () throws IOException
void handleEditCondition () throws IOException
void handleDelCondition ()
void handleNewAction () throws IOException
void handleEditAction () throws IOException
void handleDelAction ()
void handleNewEvent ()
void handleSaveEvents ()
void handleDelEvent ()
void showEventInEditor (Event oldEvent, Event newEvent)
void showNewConditionWindow (Consumer< Condition > okLambda, Condition entry) throws IOException
void showNewActionWindow (Consumer< GlobalAction > okActionLambda, GlobalAction entry) throws IOException
Private Attributes
ListView< Event > eventsListView
ListView< Condition > conditionsListView
ListView< GlobalAction > actionsListView
Button newEvent
Button delEvent
Button saveEvents
Button newCondition
Button editCondition
Button delCondition
Button delAction
Button editAction
Button newAction
Stage newConditionStage
Stage newActionStage
List< Event > myEvents
ObservableList< Event > myObservableEventsList
List< Condition > myConditions
List< GlobalAction > myActions
EventsDataWrapper myData
PlayerData myPlayerData
Stage myStage
IChangeGameState myState
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
static final String NAME_PROMPT = "New Event name:"
Detailed Description
Definition at line 36 of file EventEditorController.java.
Member Function Documentation
void authoring.eventeditor.EventEditorController.handleDelAction () private
Definition at line 135 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleDelCondition () private
Definition at line 115 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleDelEvent () private
Definition at line 181 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleEditAction () throws IOException private
Definition at line 130 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleEditCondition () throws IOException private
Definition at line 105 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleNewAction () throws IOException private
Definition at line 121 of file EventEditorController.java.
References authoring.eventeditor.EventEditorController.showNewActionWindow().
void authoring.eventeditor.EventEditorController.handleNewCondition () throws IOException private
Definition at line 96 of file EventEditorController.java.
References authoring.eventeditor.EventEditorController.showNewConditionWindow().
void authoring.eventeditor.EventEditorController.handleNewEvent () private
Definition at line 141 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.handleSaveEvents () private
Definition at line 170 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.initialize (URL fxmlFileLocation, ResourceBundle resources)
Definition at line 84 of file EventEditorController.java.
References authoring.eventeditor.EventEditorController.showEventInEditor().
void authoring.eventeditor.EventEditorController.loadData (EventsDataWrapper data)
Definition at line 271 of file EventEditorController.java.
Referenced by fxml_main.LevelEditor.showEventsEditorWindow().
void authoring.eventeditor.EventEditorController.loadEvents (List< Event > events)
Loads a Level's Events into the editor. We pass the entire collection into this class because Editor must be able to add/remove from the list and modify individual Events
Parameters
myEvents - an ObservableList to interface with the ListView
Definition at line 265 of file EventEditorController.java.
Referenced by fxml_main.LevelEditor.showEventsEditorWindow().
void authoring.eventeditor.EventEditorController.loadGameState (IChangeGameState state)
Definition at line 275 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.loadPlayerData (PlayerData playerData)
Definition at line 279 of file EventEditorController.java.
void authoring.eventeditor.EventEditorController.showEventInEditor (Event oldEvent, Event newEvent) private
When user selects an Event from the left-hand list, it populates the Conditions and GlobalActions lists on the right-hand side. Also enables all Buttons allowing interaction with those objects.
Parameters
newEvent
To avoid null-pointer exceptions.
Definition at line 193 of file EventEditorController.java.
References gamedata.events.Event.getConditions(), and gamedata.events.Event.getGlobalActions().
Referenced by authoring.eventeditor.EventEditorController.initialize().
void authoring.eventeditor.EventEditorController.showNewActionWindow (Consumer< GlobalAction > okActionLambda, GlobalAction entry) throws IOException private
Definition at line 236 of file EventEditorController.java.
References authoring.eventeditor.NewActionController.loadData(), authoring.eventeditor.NewActionController.loadLambda(), and authoring.eventeditor.NewActionController.loadState().
Referenced by authoring.eventeditor.EventEditorController.handleNewAction().
void authoring.eventeditor.EventEditorController.showNewConditionWindow (Consumer< Condition > okLambda, Condition entry) throws IOException private
Definition at line 216 of file EventEditorController.java.
References authoring.eventeditor.NewConditionController.loadData(), and authoring.eventeditor.NewConditionController.loadLambda().
Referenced by authoring.eventeditor.EventEditorController.handleNewCondition().
Member Data Documentation
ListView<GlobalAction> authoring.eventeditor.EventEditorController.actionsListView private
Definition at line 47 of file EventEditorController.java.
ListView<Condition> authoring.eventeditor.EventEditorController.conditionsListView private
Definition at line 45 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.delAction private
Definition at line 63 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.delCondition private
Definition at line 61 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.delEvent private
Definition at line 53 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.editAction private
Definition at line 65 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.editCondition private
Definition at line 59 of file EventEditorController.java.
ListView<Event> authoring.eventeditor.EventEditorController.eventsListView private
Definition at line 43 of file EventEditorController.java.
List<GlobalAction> authoring.eventeditor.EventEditorController.myActions private
Definition at line 75 of file EventEditorController.java.
List<Condition> authoring.eventeditor.EventEditorController.myConditions private
Definition at line 74 of file EventEditorController.java.
EventsDataWrapper authoring.eventeditor.EventEditorController.myData private
Definition at line 76 of file EventEditorController.java.
List<Event> authoring.eventeditor.EventEditorController.myEvents private
Definition at line 72 of file EventEditorController.java.
ObservableList<Event> authoring.eventeditor.EventEditorController.myObservableEventsList private
Definition at line 73 of file EventEditorController.java.
PlayerData authoring.eventeditor.EventEditorController.myPlayerData private
Definition at line 77 of file EventEditorController.java.
Stage authoring.eventeditor.EventEditorController.myStage private
Definition at line 79 of file EventEditorController.java.
IChangeGameState authoring.eventeditor.EventEditorController.myState private
Definition at line 80 of file EventEditorController.java.
final String authoring.eventeditor.EventEditorController.NAME_PROMPT = "New Event name:" static private
Definition at line 39 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.newAction private
Definition at line 67 of file EventEditorController.java.
Stage authoring.eventeditor.EventEditorController.newActionStage private
Definition at line 70 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.newCondition private
Definition at line 57 of file EventEditorController.java.
Stage authoring.eventeditor.EventEditorController.newConditionStage private
Definition at line 69 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.newEvent private
Definition at line 51 of file EventEditorController.java.
Button authoring.eventeditor.EventEditorController.saveEvents private
Definition at line 55 of file EventEditorController.java.
final String authoring.eventeditor.EventEditorController.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 38 of file EventEditorController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/eventeditor/EventEditorController.java