voogasalad_VOOGirlsGeneration: gameengine.player.SimpleAIPlayer Class Reference
gameengine.player.SimpleAIPlayer Class Reference
Public Member Functions
SimpleAIPlayer (int id)
SimpleAIPlayer (int id, Stats stats, String scoreStat)
SimpleAIPlayer (Player player)
void startTurn (Level l)
void play ()
String getType ()
Public Member Functions inherited from gameengine.player.Player
Player ()
Player (int id)
Player (Player player)
Stats getStats ()
double getScore ()
Point2D getLoc ()
void changeStat (String statName, double value)
abstract void startTurn (Level l)
void resetMovesPlayed ()
int getID ()
abstract void play ()
void playTurn ()
int getNumMovesPlayed ()
String printString ()
String toString ()
abstract String getType ()
Private Attributes
Level myCurrentLevel
Additional Inherited Members
Protected Member Functions inherited from gameengine.player.Player
Player (int id, Stats stats, String scoreStat)
Protected Attributes inherited from gameengine.player.Player
int myNumMovesPlayed
int myID
Stats myStats
String myScoreStat
Detailed Description
Defines a simple AI for playing turn-based strategy games
Author
Jesse, Rica
Definition at line 19 of file SimpleAIPlayer.java.
Constructor & Destructor Documentation
gameengine.player.SimpleAIPlayer.SimpleAIPlayer (int id)
Constructor
Parameters
id
Definition at line 27 of file SimpleAIPlayer.java.
gameengine.player.SimpleAIPlayer.SimpleAIPlayer (int id, Stats stats, String scoreStat)
Definition at line 31 of file SimpleAIPlayer.java.
gameengine.player.SimpleAIPlayer.SimpleAIPlayer (Player player)
Definition at line 35 of file SimpleAIPlayer.java.
Member Function Documentation
String gameengine.player.SimpleAIPlayer.getType ()
Definition at line 92 of file SimpleAIPlayer.java.
void gameengine.player.SimpleAIPlayer.play ()
Definition at line 47 of file SimpleAIPlayer.java.
References gamedata.action.Action.doBehavior(), gamedata.action.Action.getAbsoluteActionRange(), gamedata.gamecomponents.Level.getGrid(), gameengine.player.Player.getLoc(), authoring_environment.GUIGrid.getPiece(), authoring_environment.GUIGrid.getPlayerPieces(), gameengine.player.Player.myID, and authoring_environment.GUIGrid.repopulateGrid().
Referenced by gameengine.player.SimpleAIPlayer.startTurn().
void gameengine.player.SimpleAIPlayer.startTurn (Level l)
Definition at line 40 of file SimpleAIPlayer.java.
References gameengine.player.SimpleAIPlayer.play(), and gameengine.player.Player.resetMovesPlayed().
Member Data Documentation
Level gameengine.player.SimpleAIPlayer.myCurrentLevel private
Definition at line 21 of file SimpleAIPlayer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gameengine/player/SimpleAIPlayer.java