voogasalad_VOOGirlsGeneration: gamedata.JSON.JSONManager Class Reference
gamedata.JSON.JSONManager Class Reference
Public Member Functions
JSONManager ()
void writeToJSON (Object thing, String fileName)
Game readFromJSONFile (String jsonFileLocation) throws FileNotFoundException
Object readSpecificFromJSONFile (Class<?> c, String jsonFileLocation) throws FileNotFoundException
void registerTypeAdapters (GsonBuilder builder)
Package Attributes
Gson myGson
Detailed Description
Creates JSON file from Authoring Environment data. Loads and parses JSON file to create a Game for Game Engine/Game Player.
Author
annamiyajima, Rica Zhang
Definition at line 31 of file JSONManager.java.
Constructor & Destructor Documentation
gamedata.JSON.JSONManager.JSONManager ()
Constructor
Definition at line 38 of file JSONManager.java.
References gamedata.JSON.JSONManager.registerTypeAdapters().
Member Function Documentation
Game gamedata.JSON.JSONManager.readFromJSONFile (String jsonFileLocation) throws FileNotFoundException
Given a filePath, read in a JSON file and construct a game with that data
Parameters
JSON file location
Exceptions
FileNotFoundException
Definition at line 73 of file JSONManager.java.
Referenced by authoring.concretefeatures.menus.FileX.handleLoad(), gamePlayer.ViewController.loadGame(), and tests.JSONTesterMain.testJSONload().
Object gamedata.JSON.JSONManager.readSpecificFromJSONFile (Class<?> c, String jsonFileLocation) throws FileNotFoundException
Pass in the class of the object you would like to read and it will return you that object you just need to cast it upon getting the return
Parameters
c
jsonFileLocation
Returns
Exceptions
FileNotFoundException
Definition at line 91 of file JSONManager.java.
void gamedata.JSON.JSONManager.registerTypeAdapters (GsonBuilder builder)
Definition at line 98 of file JSONManager.java.
Referenced by gamedata.JSON.JSONManager.JSONManager().
void gamedata.JSON.JSONManager.writeToJSON (Object thing, String fileName)
Write a game and its contents into a JSON file.
Parameters
piece
piece
Definition at line 51 of file JSONManager.java.
Referenced by authoring.concretefeatures.menus.FileX.handleSave(), fxml_main.AuthoringController.saveGame(), gamePlayer.ViewController.saveGame(), and tests.JSONTesterMain.testJSONwrite().
Member Data Documentation
Gson gamedata.JSON.JSONManager.myGson package
Definition at line 33 of file JSONManager.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/JSON/JSONManager.java