voogasalad_VOOGirlsGeneration: authoring.createedit.EventCreator Class Reference
authoring.createedit.EventCreator Class Reference
Public Member Functions
EventCreator (ObservableList< String > events)
Protected Member Functions
void initialize ()
Private Member Functions
void newEvent (String eventName)
Private Attributes
String EVENT_NAME_LABEL = "Event Name: "
ObservableList< String > myEvents
Static Private Attributes
static final int HEIGHT = 350
static final int WIDTH = 350
static final String NAME = "Event Creator"
static final String NEW_EVENT_BUTTON = "+ Event"
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
static final Insets MARGINS = new Insets(20, WIDTH/8, 20, WIDTH/8)
static final String LABEL_CSS = "-fx-font-size: 12pt;"
Detailed Description
Definition at line 13 of file EventCreator.java.
Constructor & Destructor Documentation
authoring.createedit.EventCreator.EventCreator (ObservableList< String > events)
Definition at line 26 of file EventCreator.java.
References authoring.createedit.EventCreator.initialize().
Member Function Documentation
void authoring.createedit.EventCreator.initialize () protected
Definition at line 34 of file EventCreator.java.
References authoring.createedit.EventCreator.newEvent(), and authoring_environment.UIspecs.topRightPadding.
Referenced by authoring.createedit.EventCreator.EventCreator().
void authoring.createedit.EventCreator.newEvent (String eventName) private
Definition at line 56 of file EventCreator.java.
Referenced by authoring.createedit.EventCreator.initialize().
Member Data Documentation
String authoring.createedit.EventCreator.EVENT_NAME_LABEL = "Event Name: " private
Definition at line 19 of file EventCreator.java.
final int authoring.createedit.EventCreator.HEIGHT = 350 static private
Definition at line 15 of file EventCreator.java.
final String authoring.createedit.EventCreator.LABEL_CSS = "-fx-font-size: 12pt;" static private
Definition at line 22 of file EventCreator.java.
final Insets authoring.createedit.EventCreator.MARGINS = new Insets(20, WIDTH/8, 20, WIDTH/8) static private
Definition at line 21 of file EventCreator.java.
ObservableList<String> authoring.createedit.EventCreator.myEvents private
Definition at line 24 of file EventCreator.java.
final String authoring.createedit.EventCreator.NAME = "Event Creator" static private
Definition at line 17 of file EventCreator.java.
final String authoring.createedit.EventCreator.NEW_EVENT_BUTTON = "+ Event" static private
Definition at line 18 of file EventCreator.java.
final String authoring.createedit.EventCreator.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 20 of file EventCreator.java.
final int authoring.createedit.EventCreator.WIDTH = 350 static private
Definition at line 16 of file EventCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/createedit/EventCreator.java