voogasalad_VOOGirlsGeneration: gamedata.action.TotalLogicBox Class Reference
gamedata.action.TotalLogicBox Class Reference
Public Member Functions
TotalLogicBox (StatsTotalLogic stl)
StatsTotalLogic getStatsLogic ()
Static Public Attributes
static final int MULTIPLIER_BOX_WIDTH = 75
static final int STATS_BOX_WIDTH = 120
Private Member Functions
List< StatsSingleMultiplier > getSingleMultipliers (List< SingleMultiplierBox > smbList)
void initStatsModifier (StatsTotalLogic stl)
void initSingleMultiplierVBox (List< StatsSingleMultiplier > ssmList)
void initNewButton (Button newBtn)
void addSingleMultiplierBox (StatsSingleMultiplier ssm)
Button makeDeleteButton (HBox deletableSsmHBox, SingleMultiplierBox ssmBox)
Private Attributes
ChoiceBox< String > myStatsRefChoice
TextField myStatName
VBox mySingleMultiplierVBox
List< SingleMultiplierBox > mySingleMultiplierList
Static Private Attributes
static final String STYLESHEET = "resources/stylesheets/singlemultiplierbox_layout.css"
Detailed Description
GUI element used in ActionEditor. This allows a user to specify a whole stat modifying operation. In a stats-modifying action, each operation adds to the target stat the value from a reference, scaled by a positive or negative number. This GUI element allows the user to which stat to edit and who the stat belongs to (actor or receiver).
Author
Mike Zhu, Jennie Ju
Definition at line 25 of file TotalLogicBox.java.
Constructor & Destructor Documentation
gamedata.action.TotalLogicBox.TotalLogicBox (StatsTotalLogic stl)
Definition at line 36 of file TotalLogicBox.java.
References gamedata.action.StatsTotalLogic.getMultiplierLogic(), gamedata.action.TotalLogicBox.initSingleMultiplierVBox(), and gamedata.action.TotalLogicBox.initStatsModifier().
Member Function Documentation
void gamedata.action.TotalLogicBox.addSingleMultiplierBox (StatsSingleMultiplier ssm) private
Definition at line 121 of file TotalLogicBox.java.
References gamedata.action.TotalLogicBox.makeDeleteButton().
Referenced by gamedata.action.TotalLogicBox.initNewButton(), and gamedata.action.TotalLogicBox.initSingleMultiplierVBox().
List<StatsSingleMultiplier> gamedata.action.TotalLogicBox.getSingleMultipliers (List< SingleMultiplierBox > smbList) private
Returns the List of StatsSingleMultipliers from the TotalLogicBox view
Parameters
smbList - List of SingleMultiplierBoxes representing the view of StatsSingleMultipliers
Returns
List of StatsSingleMultipliers for use with Actions
Definition at line 70 of file TotalLogicBox.java.
Referenced by gamedata.action.TotalLogicBox.getStatsLogic().
StatsTotalLogic gamedata.action.TotalLogicBox.getStatsLogic ()
Returns the StatsTotalLogic associated with this TotalLogicBox as shown in the view
Returns
StatsTotalLogic associated with this TotalLogicBox
Definition at line 57 of file TotalLogicBox.java.
References gamedata.action.TotalLogicBox.getSingleMultipliers().
void gamedata.action.TotalLogicBox.initNewButton (Button newBtn) private
Definition at line 110 of file TotalLogicBox.java.
References gamedata.action.TotalLogicBox.addSingleMultiplierBox().
Referenced by gamedata.action.TotalLogicBox.initSingleMultiplierVBox().
void gamedata.action.TotalLogicBox.initSingleMultiplierVBox (List< StatsSingleMultiplier > ssmList) private
Definition at line 97 of file TotalLogicBox.java.
References gamedata.action.TotalLogicBox.addSingleMultiplierBox(), and gamedata.action.TotalLogicBox.initNewButton().
Referenced by gamedata.action.TotalLogicBox.TotalLogicBox().
void gamedata.action.TotalLogicBox.initStatsModifier (StatsTotalLogic stl) private
Initializes the StatsTotalLogic associated with this TotalLogicBox
Parameters
stl
Definition at line 82 of file TotalLogicBox.java.
References gamedata.action.StatsModifier.getStatName(), and gamedata.action.StatsModifier.getStatRef().
Referenced by gamedata.action.TotalLogicBox.TotalLogicBox().
Button gamedata.action.TotalLogicBox.makeDeleteButton (HBox deletableSsmHBox, SingleMultiplierBox ssmBox) private
Definition at line 131 of file TotalLogicBox.java.
Referenced by gamedata.action.TotalLogicBox.addSingleMultiplierBox().
Member Data Documentation
final int gamedata.action.TotalLogicBox.MULTIPLIER_BOX_WIDTH = 75 static
Definition at line 27 of file TotalLogicBox.java.
List<SingleMultiplierBox> gamedata.action.TotalLogicBox.mySingleMultiplierList private
Definition at line 34 of file TotalLogicBox.java.
VBox gamedata.action.TotalLogicBox.mySingleMultiplierVBox private
Definition at line 33 of file TotalLogicBox.java.
TextField gamedata.action.TotalLogicBox.myStatName private
Definition at line 32 of file TotalLogicBox.java.
ChoiceBox<String> gamedata.action.TotalLogicBox.myStatsRefChoice private
Definition at line 31 of file TotalLogicBox.java.
final int gamedata.action.TotalLogicBox.STATS_BOX_WIDTH = 120 static
Definition at line 28 of file TotalLogicBox.java.
final String gamedata.action.TotalLogicBox.STYLESHEET = "resources/stylesheets/singlemultiplierbox_layout.css" static private
Definition at line 29 of file TotalLogicBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/TotalLogicBox.java