voogasalad_VOOGirlsGeneration: gamedata.action.SingleMultiplierBox Class Reference
gamedata.action.SingleMultiplierBox Class Reference
Public Member Functions
SingleMultiplierBox ()
SingleMultiplierBox (StatsSingleMultiplier ssm)
StatsSingleMultiplier getSingleMultipler ()
Static Public Attributes
static final int MULTIPLIER_BOX_WIDTH = 75
static final int STATS_BOX_WIDTH = 120
Private Member Functions
void initSingleMultiplierBox ()
void setSingleMultiplier (StatsSingleMultiplier ssm)
Private Attributes
ChoiceBox< String > myStatRef
TextField myMultiplier
TextField myStatName
Static Private Attributes
static final String STYLESHEET = "resources/stylesheets/singlemultiplierbox_layout.css"
Detailed Description
GUI element used in ActionEditor. This allows a user to specify a single "operation" on stats. In a stats-modifying action, each operation adds to the target stat the value from a reference, scaled by a positive or negative number. This GUI element allows the user to specify the scalar and reference stat (or constant).
Author
Mike Zhu, Jennie Ju
Definition at line 17 of file SingleMultiplierBox.java.
Constructor & Destructor Documentation
gamedata.action.SingleMultiplierBox.SingleMultiplierBox ()
Creates a new empty SingleMultiplierBox
Definition at line 30 of file SingleMultiplierBox.java.
References gamedata.action.SingleMultiplierBox.initSingleMultiplierBox().
gamedata.action.SingleMultiplierBox.SingleMultiplierBox (StatsSingleMultiplier ssm)
Creates a SingleMultiplierBox from an existing StatsSingleMultiplier
Definition at line 37 of file SingleMultiplierBox.java.
References gamedata.action.SingleMultiplierBox.initSingleMultiplierBox(), and gamedata.action.SingleMultiplierBox.setSingleMultiplier().
Member Function Documentation
StatsSingleMultiplier gamedata.action.SingleMultiplierBox.getSingleMultipler ()
Gets the StatsSingleMultiplier associated with this SingleMultiplierBox (connects this view to the data)
Returns
StatsSingleMultiplier - explains how to modify the stat
Definition at line 68 of file SingleMultiplierBox.java.
void gamedata.action.SingleMultiplierBox.initSingleMultiplierBox () private
Definition at line 42 of file SingleMultiplierBox.java.
Referenced by gamedata.action.SingleMultiplierBox.SingleMultiplierBox().
void gamedata.action.SingleMultiplierBox.setSingleMultiplier (StatsSingleMultiplier ssm) private
Takes in a StatsSingleMultipler and repopulates the textfields in view
Parameters
ssm - StatsSingleMultiplier to view
Definition at line 85 of file SingleMultiplierBox.java.
References gamedata.action.StatsSingleMultiplier.getModifier(), gamedata.action.StatsModifier.getStatName(), and gamedata.action.StatsModifier.getStatRef().
Referenced by gamedata.action.SingleMultiplierBox.SingleMultiplierBox().
Member Data Documentation
final int gamedata.action.SingleMultiplierBox.MULTIPLIER_BOX_WIDTH = 75 static
Definition at line 19 of file SingleMultiplierBox.java.
TextField gamedata.action.SingleMultiplierBox.myMultiplier private
Definition at line 24 of file SingleMultiplierBox.java.
TextField gamedata.action.SingleMultiplierBox.myStatName private
Definition at line 25 of file SingleMultiplierBox.java.
ChoiceBox<String> gamedata.action.SingleMultiplierBox.myStatRef private
Definition at line 23 of file SingleMultiplierBox.java.
final int gamedata.action.SingleMultiplierBox.STATS_BOX_WIDTH = 120 static
Definition at line 20 of file SingleMultiplierBox.java.
final String gamedata.action.SingleMultiplierBox.STYLESHEET = "resources/stylesheets/singlemultiplierbox_layout.css" static private
Definition at line 21 of file SingleMultiplierBox.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/SingleMultiplierBox.java