voogasalad_VOOGirlsGeneration: fxml_main.PatchController Class Reference
fxml_main.PatchController Class Reference
Public Member Functions
PatchController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, PatchTypeData patchTypes)
Protected Member Functions
void initGlobalNewBtn (Button newBtn)
void initGlobalEditBtn (Button editBtn)
void initGlobalDelBtn (Button delBtn)
HBox makeEntryBox (Patch entry)
void initEntryEditBtn (Patch entry, Button editBtn)
void initEntryDelBtn (Patch entry, Button delBtn)
Protected Member Functions inherited from fxml_main.GridComponentAbstCtrl< Patch >
GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef)
abstract void initGlobalNewBtn (Button newBtn)
abstract void initGlobalEditBtn (Button editBtn)
abstract void initGlobalDelBtn (Button delBtn)
void addEntry (T entry)
HBox makeCompleteEntryBox (T entry)
HBox initEntryControls (T entry)
abstract HBox makeEntryBox (T entry)
abstract void initEntryEditBtn (T entry, Button editBtn)
abstract void initEntryDelBtn (T entry, Button delBtn)
Private Attributes
PatchTypeData myPatchTypes
Additional Inherited Members
Protected Attributes inherited from fxml_main.GridComponentAbstCtrl< Patch >
VBox myVBox
ScrollPane myPropertiesSPane
GUIGridReference myGridReference
Map< T, HBox > myEntryMap
Detailed Description
Author
Sandy Lee
Definition at line 23 of file PatchController.java.
Constructor & Destructor Documentation
fxml_main.PatchController.PatchController (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef, PatchTypeData patchTypes)
Instantiates a PatchController with the PatchTypeData
Definition at line 30 of file PatchController.java.
Member Function Documentation
void fxml_main.PatchController.initEntryDelBtn (Patch entry, Button delBtn) protected
Definition at line 147 of file PatchController.java.
References fxml_main.GridComponentAbstCtrl< Patch >.myEntryMap, fxml_main.GridComponentAbstCtrl< Patch >.myVBox, and authoring.data.PatchTypeData.remove().
void fxml_main.PatchController.initEntryEditBtn (Patch entry, Button editBtn) protected
Definition at line 127 of file PatchController.java.
References fxml_main.GridComponentAbstCtrl< Patch >.makeCompleteEntryBox(), fxml_main.GridComponentAbstCtrl< Patch >.myEntryMap, fxml_main.GridComponentAbstCtrl< Patch >.myPropertiesSPane, and authoring.data.PatchTypeData.replace().
void fxml_main.PatchController.initGlobalDelBtn (Button delBtn) protected
Initalizes the global delete button to remove instances of patches from the current GUIGrid w/ mouse clicks
Definition at line 80 of file PatchController.java.
References authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), fxml_main.GridComponentAbstCtrl< Patch >.myGridReference, authoring_environment.GUIGrid.paneSetOnMouseDragged(), authoring_environment.GUIGrid.paneSetOnMousePressed(), and authoring_environment.GUIGrid.removePatchAtCoordinate().
void fxml_main.PatchController.initGlobalEditBtn (Button editBtn) protected
Definition at line 55 of file PatchController.java.
References authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), authoring_environment.GUIGrid.getPatch(), fxml_main.GridComponentAbstCtrl< Patch >.myGridReference, fxml_main.GridComponentAbstCtrl< Patch >.myPropertiesSPane, authoring_environment.GUIGrid.paneSetOnMouseDragged(), and authoring_environment.GUIGrid.paneSetOnMousePressed().
void fxml_main.PatchController.initGlobalNewBtn (Button newBtn) protected
Initializes the global New Button to add new patches
Definition at line 40 of file PatchController.java.
References authoring.data.PatchTypeData.add(), fxml_main.GridComponentAbstCtrl< Patch >.addEntry(), and fxml_main.GridComponentAbstCtrl< Patch >.myPropertiesSPane.
HBox fxml_main.PatchController.makeEntryBox (Patch entry) protected
Definition at line 100 of file PatchController.java.
References authoring_environment.GUIGrid.addPatchAtLoc(), authoring_environment.SuperGrid.findClickedCoordinate(), fxml_main.GUIGridReference.getGrid(), gamedata.gamecomponents.GridComponent.getImageView(), gamedata.gamecomponents.GridComponent.getName(), fxml_main.GridComponentAbstCtrl< Patch >.myGridReference, authoring_environment.GUIGrid.paneSetOnMouseDragged(), and authoring_environment.GUIGrid.paneSetOnMousePressed().
Member Data Documentation
PatchTypeData fxml_main.PatchController.myPatchTypes private
Definition at line 25 of file PatchController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PatchController.java