voogasalad_VOOGirlsGeneration: gamedata.action.ActionStatsEditor Class Reference
gamedata.action.ActionStatsEditor Class Reference
Public Member Functions
ActionStatsEditor (List< StatsTotalLogic > stlList)
List< StatsTotalLogic > getStatsTotalLogics ()
Private Member Functions
Button makeNewOpButton ()
void addTotalLogicBox (StatsTotalLogic stl)
Button makeDeleteButton (HBox deletableHBox, TotalLogicBox stlBox)
Private Attributes
List< TotalLogicBox > myTotalLogicList
Detailed Description
Definition at line 13 of file ActionStatsEditor.java.
Constructor & Destructor Documentation
gamedata.action.ActionStatsEditor.ActionStatsEditor (List< StatsTotalLogic > stlList)
Constructor for an ActionStatsEditor. Populates the editor based on an existing list of StatsTotalLogics
Parameters
stlList
Definition at line 22 of file ActionStatsEditor.java.
References gamedata.action.ActionStatsEditor.addTotalLogicBox(), and gamedata.action.ActionStatsEditor.makeNewOpButton().
Member Function Documentation
void gamedata.action.ActionStatsEditor.addTotalLogicBox (StatsTotalLogic stl) private
Definition at line 42 of file ActionStatsEditor.java.
References gamedata.action.ActionStatsEditor.makeDeleteButton().
Referenced by gamedata.action.ActionStatsEditor.ActionStatsEditor(), and gamedata.action.ActionStatsEditor.makeNewOpButton().
List<StatsTotalLogic> gamedata.action.ActionStatsEditor.getStatsTotalLogics ()
Returns all the StatsTotalLogics that are currently viewed as TotalLogicBoxes in thie ActionStatsEditor
Returns
List of StatsTotalLogic
Definition at line 68 of file ActionStatsEditor.java.
Referenced by fxml_main.ActionEditor.initEditor().
Button gamedata.action.ActionStatsEditor.makeDeleteButton (HBox deletableHBox, TotalLogicBox stlBox) private
Definition at line 51 of file ActionStatsEditor.java.
Referenced by gamedata.action.ActionStatsEditor.addTotalLogicBox().
Button gamedata.action.ActionStatsEditor.makeNewOpButton () private
Definition at line 31 of file ActionStatsEditor.java.
References gamedata.action.ActionStatsEditor.addTotalLogicBox().
Referenced by gamedata.action.ActionStatsEditor.ActionStatsEditor().
Member Data Documentation
List<TotalLogicBox> gamedata.action.ActionStatsEditor.myTotalLogicList private
Definition at line 14 of file ActionStatsEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/action/ActionStatsEditor.java