voogasalad_VOOGirlsGeneration: authoring.concretefeatures.LevelEditor Class Reference
authoring.concretefeatures.LevelEditor Class Reference
Public Member Functions
LevelEditor (WorkspaceView wsView, String gridType, String name, int row, int col)
Private Member Functions
void addWorkspaceTab (SuperGrid superGrid, String name, String shape)
int getPrefTileSize (int gridWidthNumber, int gridHeightNumber)
Private Attributes
WorkspaceView myWorkspaceView
String levelName
String myGridType
int myRows
int myCol
SuperGrid shapeGrid
int tileSize
PieceInstanceData pieceData = new PieceInstanceData()
PatchInstanceData patchData = new PatchInstanceData()
Static Private Attributes
static final int DEFAULT_TILE_SIZE = 100
static final int MIN_TILE_SIZE = 40
static final int GRID_VIEW_HEIGHT = 400
static final int GRID_VIEW_WIDTH = 800
Detailed Description
Author
Rica
Definition at line 21 of file LevelEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.LevelEditor.LevelEditor (WorkspaceView wsView, String gridType, String name, int row, int col)
Upon construction, makes a grid of the specified type and adds it to the Workspace Tab
Parameters
wsView
name
gridType
row
col
Definition at line 47 of file LevelEditor.java.
References authoring.concretefeatures.LevelEditor.addWorkspaceTab(), and authoring.concretefeatures.LevelEditor.getPrefTileSize().
Member Function Documentation
void authoring.concretefeatures.LevelEditor.addWorkspaceTab (SuperGrid superGrid, String name, String shape) private
Definition at line 59 of file LevelEditor.java.
References authoring_environment.WorkspaceView.addGrid(), and authoring_environment.WorkspaceView.addNextTab().
Referenced by authoring.concretefeatures.LevelEditor.LevelEditor().
int authoring.concretefeatures.LevelEditor.getPrefTileSize (int gridWidthNumber, int gridHeightNumber) private
Definition at line 75 of file LevelEditor.java.
References authoring.concretefeatures.LevelEditor.MIN_TILE_SIZE, and authoring.concretefeatures.LevelEditor.tileSize.
Referenced by authoring.concretefeatures.LevelEditor.LevelEditor().
Member Data Documentation
final int authoring.concretefeatures.LevelEditor.DEFAULT_TILE_SIZE = 100 static private
Definition at line 22 of file LevelEditor.java.
final int authoring.concretefeatures.LevelEditor.GRID_VIEW_HEIGHT = 400 static private
Definition at line 24 of file LevelEditor.java.
final int authoring.concretefeatures.LevelEditor.GRID_VIEW_WIDTH = 800 static private
Definition at line 25 of file LevelEditor.java.
String authoring.concretefeatures.LevelEditor.levelName private
Definition at line 28 of file LevelEditor.java.
final int authoring.concretefeatures.LevelEditor.MIN_TILE_SIZE = 40 static private
Definition at line 23 of file LevelEditor.java.
Referenced by authoring.concretefeatures.LevelEditor.getPrefTileSize().
int authoring.concretefeatures.LevelEditor.myCol private
Definition at line 32 of file LevelEditor.java.
String authoring.concretefeatures.LevelEditor.myGridType private
Definition at line 30 of file LevelEditor.java.
int authoring.concretefeatures.LevelEditor.myRows private
Definition at line 31 of file LevelEditor.java.
WorkspaceView authoring.concretefeatures.LevelEditor.myWorkspaceView private
Definition at line 27 of file LevelEditor.java.
PatchInstanceData authoring.concretefeatures.LevelEditor.patchData = new PatchInstanceData() private
Definition at line 37 of file LevelEditor.java.
PieceInstanceData authoring.concretefeatures.LevelEditor.pieceData = new PieceInstanceData() private
Definition at line 36 of file LevelEditor.java.
SuperGrid authoring.concretefeatures.LevelEditor.shapeGrid private
Definition at line 33 of file LevelEditor.java.
int authoring.concretefeatures.LevelEditor.tileSize private
Definition at line 34 of file LevelEditor.java.
Referenced by authoring.concretefeatures.LevelEditor.getPrefTileSize().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/LevelEditor.java