voogasalad_VOOGirlsGeneration: fxml_main.LevelEditor Class Reference
fxml_main.LevelEditor Class Reference
Public Member Functions
LevelEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape, PlayerData playerData)
LevelEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape, Level level)
void initEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape)
Private Member Functions
void initialize ()
void showEventsEditorWindow () throws IOException
Private Attributes
String myId
int myGridRows
int myGridCols
double myTileHeight
String myGridShape
List< Event > myEvents
GUIGrid myGrid
Consumer< Level > myOkLambda
Level myLevel
String myEditorTitle
EventsDataWrapper myData
PlayerData myPlayerData
Static Private Attributes
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
static final String CREATOR_TITLE = "Level Creator"
static final String EDITOR_TITLE = "Level Editor"
static final String LABEL_CSS = "-fx-font-size: 14pt;"
Detailed Description
Definition at line 32 of file LevelEditor.java.
Constructor & Destructor Documentation
fxml_main.LevelEditor.LevelEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape, PlayerData playerData)
Definition at line 55 of file LevelEditor.java.
References fxml_main.LevelEditor.CREATOR_TITLE, and fxml_main.LevelEditor.initEditor().
fxml_main.LevelEditor.LevelEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape, Level level)
Definition at line 68 of file LevelEditor.java.
References fxml_main.LevelEditor.EDITOR_TITLE, gamedata.gamecomponents.Level.getEvents(), gamedata.gamecomponents.Level.getGrid(), gamedata.gamecomponents.Level.getId(), authoring_environment.SuperGrid.getNumCols(), authoring_environment.SuperGrid.getNumRows(), authoring_environment.SuperGrid.getTileHeight(), and fxml_main.LevelEditor.initEditor().
Member Function Documentation
void fxml_main.LevelEditor.initEditor (Consumer< Level > okLambda, EventsDataWrapper data, String gridShape)
Definition at line 81 of file LevelEditor.java.
References fxml_main.LevelEditor.initialize().
Referenced by fxml_main.LevelEditor.LevelEditor().
void fxml_main.LevelEditor.initialize () private
Definition at line 88 of file LevelEditor.java.
References fxml_main.LevelEditor.showEventsEditorWindow().
Referenced by fxml_main.LevelEditor.initEditor().
void fxml_main.LevelEditor.showEventsEditorWindow () throws IOException private
Definition at line 169 of file LevelEditor.java.
References authoring.eventeditor.EventEditorController.loadData(), and authoring.eventeditor.EventEditorController.loadEvents().
Referenced by fxml_main.LevelEditor.initialize().
Member Data Documentation
final String fxml_main.LevelEditor.CREATOR_TITLE = "Level Creator" static private
Definition at line 35 of file LevelEditor.java.
Referenced by fxml_main.LevelEditor.LevelEditor().
final String fxml_main.LevelEditor.EDITOR_TITLE = "Level Editor" static private
Definition at line 36 of file LevelEditor.java.
Referenced by fxml_main.LevelEditor.LevelEditor().
final String fxml_main.LevelEditor.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 37 of file LevelEditor.java.
EventsDataWrapper fxml_main.LevelEditor.myData private
Definition at line 52 of file LevelEditor.java.
String fxml_main.LevelEditor.myEditorTitle private
Definition at line 50 of file LevelEditor.java.
List<Event> fxml_main.LevelEditor.myEvents private
Definition at line 44 of file LevelEditor.java.
GUIGrid fxml_main.LevelEditor.myGrid private
Definition at line 45 of file LevelEditor.java.
int fxml_main.LevelEditor.myGridCols private
Definition at line 41 of file LevelEditor.java.
int fxml_main.LevelEditor.myGridRows private
Definition at line 40 of file LevelEditor.java.
String fxml_main.LevelEditor.myGridShape private
Definition at line 43 of file LevelEditor.java.
String fxml_main.LevelEditor.myId private
Definition at line 39 of file LevelEditor.java.
Level fxml_main.LevelEditor.myLevel private
Definition at line 49 of file LevelEditor.java.
Consumer<Level> fxml_main.LevelEditor.myOkLambda private
Definition at line 47 of file LevelEditor.java.
PlayerData fxml_main.LevelEditor.myPlayerData private
Definition at line 53 of file LevelEditor.java.
double fxml_main.LevelEditor.myTileHeight private
Definition at line 42 of file LevelEditor.java.
final String fxml_main.LevelEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 33 of file LevelEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/LevelEditor.java