voogasalad_VOOGirlsGeneration: authoring.actionslogic.ActionLogicController Class Reference
authoring.actionslogic.ActionLogicController Class Reference
Public Member Functions
void initialize (URL location, ResourceBundle resources)
Map< String, Map< String, List< String > > > getActionLogic ()
void getData (ActionData actionData, PieceTypeData ptData)
Private Member Functions
void updateLogicMap ()
void updatePossibleReceivers (String selectedActor)
List< String > getReceivers (List< String > myPieceTypes, String actor)
void saveLogic ()
void loadData ()
Private Attributes
ListView< String > actionsListView
ChoiceBox< String > actorsChoiceBox
VBox myReceiversVBox
Button saveButton
Button getDataButton
List< String > myPieceTypes
List< String > myActionTypes
Map< String, Map< String, List< String > > > myLogicMap
List< CheckBox > myCBList = new ArrayList<CheckBox>()
Detailed Description
Controller for Action Logic Chart in Authoring Environment
Definition at line 24 of file ActionLogicController.java.
Member Function Documentation
Map<String, Map<String, List<String> > > authoring.actionslogic.ActionLogicController.getActionLogic ()
Returns
a map that contains actors as keys and maps that relates actions and receivers as values
Definition at line 107 of file ActionLogicController.java.
References authoring.actionslogic.ActionLogicController.myLogicMap.
void authoring.actionslogic.ActionLogicController.getData (ActionData actionData, PieceTypeData ptData)
Definition at line 111 of file ActionLogicController.java.
References authoring.data.ActionData.getActionNames(), and authoring.data.PieceTypeData.getIdSet().
Referenced by fxml_main.AuthoringController.showActionslogicChartWindow().
List<String> authoring.actionslogic.ActionLogicController.getReceivers (List< String > myPieceTypes, String actor) private
Definition at line 72 of file ActionLogicController.java.
Referenced by authoring.actionslogic.ActionLogicController.updatePossibleReceivers().
void authoring.actionslogic.ActionLogicController.initialize (URL location, ResourceBundle resources)
Definition at line 44 of file ActionLogicController.java.
References authoring.actionslogic.ActionLogicController.updatePossibleReceivers().
void authoring.actionslogic.ActionLogicController.loadData () private
Definition at line 119 of file ActionLogicController.java.
void authoring.actionslogic.ActionLogicController.saveLogic () private
Definition at line 83 of file ActionLogicController.java.
void authoring.actionslogic.ActionLogicController.updateLogicMap () private
Definition at line 53 of file ActionLogicController.java.
void authoring.actionslogic.ActionLogicController.updatePossibleReceivers (String selectedActor) private
Definition at line 61 of file ActionLogicController.java.
References authoring.actionslogic.ActionLogicController.getReceivers().
Referenced by authoring.actionslogic.ActionLogicController.initialize().
Member Data Documentation
ListView<String> authoring.actionslogic.ActionLogicController.actionsListView private
Definition at line 27 of file ActionLogicController.java.
ChoiceBox<String> authoring.actionslogic.ActionLogicController.actorsChoiceBox private
Definition at line 29 of file ActionLogicController.java.
Button authoring.actionslogic.ActionLogicController.getDataButton private
Definition at line 35 of file ActionLogicController.java.
List<String> authoring.actionslogic.ActionLogicController.myActionTypes private
Definition at line 38 of file ActionLogicController.java.
List<CheckBox> authoring.actionslogic.ActionLogicController.myCBList = new ArrayList<CheckBox>() private
Definition at line 41 of file ActionLogicController.java.
Map<String, Map<String, List<String> > > authoring.actionslogic.ActionLogicController.myLogicMap private
Initial value:
=
            new HashMap<String, Map<String, List<String>>>()
Definition at line 39 of file ActionLogicController.java.
Referenced by authoring.actionslogic.ActionLogicController.getActionLogic().
List<String> authoring.actionslogic.ActionLogicController.myPieceTypes private
Definition at line 37 of file ActionLogicController.java.
VBox authoring.actionslogic.ActionLogicController.myReceiversVBox private
Definition at line 31 of file ActionLogicController.java.
Button authoring.actionslogic.ActionLogicController.saveButton private
Definition at line 33 of file ActionLogicController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/actionslogic/ActionLogicController.java