voogasalad_VOOGirlsGeneration: authoring_environment.LibraryView Class Reference
authoring_environment.LibraryView Class Reference
Public Member Functions
LibraryView (PieceTypeData pieceData, PatchTypeData patchData)
void associateGrid (SuperGrid activeGrid)
int getUnitID ()
int getTerrainID ()
void selectUnit (Piece unit)
void selectTerrain (Patch terrain)
void addPiece (UnitEntry unit)
void addPatch (TerrainEntry terrain)
void removePiece (UnitEntry unit)
void removePatch (TerrainEntry terrain)
Protected Member Functions
void handleAction (MouseEvent event)
Private Member Functions
void setGridActionEvents ()
Private Attributes
final int HEIGHT = 300
final int WIDTH = 580
final String UNITS = "Units"
final String TERRAIN = "Terrain"
final String DELETE = "Delete"
final String EDIT = "Edit"
final String GLOBAL = "Global Commands"
final String PIECES = "Piece Templates"
final String PATCHES = "Patch Templates"
PieceTypeData myPieces
PatchTypeData myPatches
SuperGrid myGrid
Map< String, VBox > myLibraryMap
Map< String, Tab > myTabMap
SingleSelectionModel< Tab > mySelection
Piece currentUnit
Patch currentTerrain
boolean doNothing
boolean reset
boolean edit
int unitID
int terrainID
Detailed Description
Author
VOOGirls Generation
    GUI components for the library displayed on the left side of the
    game authoring environment, which contains all instantiated units
    and terrain. From here, the user can open the Unit/TerrainEditors
    to edit the units and terrain, as well as select them for
    placement on the grid.
Definition at line 38 of file LibraryView.java.
Constructor & Destructor Documentation
authoring_environment.LibraryView.LibraryView (PieceTypeData pieceData, PatchTypeData patchData)
LibraryView constructor. Initializes two tabs - one for units, one for terrain. Units and terrain are added dynamically to their respective tabs as they are created in the UnitCreator and TerrainCreator.
Definition at line 69 of file LibraryView.java.
References authoring_environment.UIspecs.allPadding.
Member Function Documentation
void authoring_environment.LibraryView.addPatch (TerrainEntry terrain)
Definition at line 236 of file LibraryView.java.
References authoring.data.PatchTypeData.add().
void authoring_environment.LibraryView.addPiece (UnitEntry unit)
Definition at line 230 of file LibraryView.java.
References authoring.data.PieceTypeData.add(), and authoring.concretefeatures.UnitEntry.getUnit().
void authoring_environment.LibraryView.associateGrid (SuperGrid activeGrid)
Definition at line 162 of file LibraryView.java.
References authoring_environment.LibraryView.setGridActionEvents().
int authoring_environment.LibraryView.getTerrainID ()
Definition at line 172 of file LibraryView.java.
References authoring_environment.LibraryView.terrainID.
int authoring_environment.LibraryView.getUnitID ()
Definition at line 167 of file LibraryView.java.
References authoring_environment.LibraryView.unitID.
void authoring_environment.LibraryView.handleAction (MouseEvent event) protected
Definition at line 196 of file LibraryView.java.
References authoring_environment.SuperGrid.findTile().
Referenced by authoring_environment.LibraryView.setGridActionEvents().
void authoring_environment.LibraryView.removePatch (TerrainEntry terrain)
Definition at line 249 of file LibraryView.java.
References authoring.data.PatchTypeData.remove().
void authoring_environment.LibraryView.removePiece (UnitEntry unit)
Definition at line 242 of file LibraryView.java.
References authoring.concretefeatures.UnitEntry.getUnit(), and authoring.data.PieceTypeData.remove().
void authoring_environment.LibraryView.selectTerrain (Patch terrain)
Definition at line 184 of file LibraryView.java.
void authoring_environment.LibraryView.selectUnit (Piece unit)
Definition at line 177 of file LibraryView.java.
void authoring_environment.LibraryView.setGridActionEvents () private
Definition at line 191 of file LibraryView.java.
References authoring_environment.LibraryView.handleAction().
Referenced by authoring_environment.LibraryView.associateGrid().
Member Data Documentation
Patch authoring_environment.LibraryView.currentTerrain private
Definition at line 56 of file LibraryView.java.
Piece authoring_environment.LibraryView.currentUnit private
Definition at line 55 of file LibraryView.java.
final String authoring_environment.LibraryView.DELETE = "Delete" private
Definition at line 44 of file LibraryView.java.
boolean authoring_environment.LibraryView.doNothing private
Definition at line 57 of file LibraryView.java.
final String authoring_environment.LibraryView.EDIT = "Edit" private
Definition at line 45 of file LibraryView.java.
boolean authoring_environment.LibraryView.edit private
Definition at line 59 of file LibraryView.java.
final String authoring_environment.LibraryView.GLOBAL = "Global Commands" private
Definition at line 46 of file LibraryView.java.
final int authoring_environment.LibraryView.HEIGHT = 300 private
Definition at line 40 of file LibraryView.java.
SuperGrid authoring_environment.LibraryView.myGrid private
Definition at line 51 of file LibraryView.java.
Map<String, VBox> authoring_environment.LibraryView.myLibraryMap private
Definition at line 52 of file LibraryView.java.
PatchTypeData authoring_environment.LibraryView.myPatches private
Definition at line 50 of file LibraryView.java.
PieceTypeData authoring_environment.LibraryView.myPieces private
Definition at line 49 of file LibraryView.java.
SingleSelectionModel<Tab> authoring_environment.LibraryView.mySelection private
Definition at line 54 of file LibraryView.java.
Map<String, Tab> authoring_environment.LibraryView.myTabMap private
Definition at line 53 of file LibraryView.java.
final String authoring_environment.LibraryView.PATCHES = "Patch Templates" private
Definition at line 48 of file LibraryView.java.
final String authoring_environment.LibraryView.PIECES = "Piece Templates" private
Definition at line 47 of file LibraryView.java.
boolean authoring_environment.LibraryView.reset private
Definition at line 58 of file LibraryView.java.
final String authoring_environment.LibraryView.TERRAIN = "Terrain" private
Definition at line 43 of file LibraryView.java.
int authoring_environment.LibraryView.terrainID private
Definition at line 61 of file LibraryView.java.
Referenced by authoring_environment.LibraryView.getTerrainID().
int authoring_environment.LibraryView.unitID private
Definition at line 60 of file LibraryView.java.
Referenced by authoring_environment.LibraryView.getUnitID().
final String authoring_environment.LibraryView.UNITS = "Units" private
Definition at line 42 of file LibraryView.java.
final int authoring_environment.LibraryView.WIDTH = 580 private
Definition at line 41 of file LibraryView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/LibraryView.java