voogasalad_VOOGirlsGeneration: gamePlayer.GameGridEffect Class Reference
gamePlayer.GameGridEffect Class Reference
Public Member Functions
GameGridEffect (ViewController vc)
void highlightActionRange ()
void highlightEffectRange (Point2D.Double loc)
void highlightCurrent (Point2D.Double loc, Piece activeP)
void greyOutPiece (Point2D.Double loc, Piece p)
void clearAllActionHighlights ()
void clearAllPieceHighlights ()
boolean isHoveringOverActionHighlight (double mouseX, double mouseY)
Static Public Attributes
static final String ACTION_RANGE_COLOR = "#FFBF00"
static final String EFFECT_RANGE_COLOR = "#DF0101"
Private Member Functions
void clearAllEffectHighlights ()
void updateActives ()
Private Attributes
ViewController myViewController
GUIGrid myGrid
Piece myActivePiece
Action myActiveAction
List< SuperTile > myHighlightedPiece
List< SuperTile > myHighlightedActions
List< SuperTile > myHighlightedEffects
Static Private Attributes
static final String DEFAULT_COLOR = "#0000FF"
static final String GREY_OUT = "#000000"
Detailed Description
Definition at line 12 of file GameGridEffect.java.
Constructor & Destructor Documentation
gamePlayer.GameGridEffect.GameGridEffect (ViewController vc)
Definition at line 27 of file GameGridEffect.java.
References gamePlayer.ViewController.getActiveAction(), gamePlayer.ViewController.getActivePiece(), and gamePlayer.ViewController.getGrid().
Member Function Documentation
void gamePlayer.GameGridEffect.clearAllActionHighlights ()
Definition at line 131 of file GameGridEffect.java.
References authoring_environment.SuperGrid.findTile().
Referenced by gamePlayer.GameGridEffect.greyOutPiece(), gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.GameGridEffect.highlightCurrent(), and gamePlayer.ApplyState.onClick().
void gamePlayer.GameGridEffect.clearAllEffectHighlights () private
Clear all effects in grid, currently only clears highlights
Parameters
grid
Definition at line 124 of file GameGridEffect.java.
References authoring_environment.SuperGrid.findTile().
Referenced by gamePlayer.GameGridEffect.greyOutPiece(), gamePlayer.GameGridEffect.highlightCurrent(), and gamePlayer.GameGridEffect.highlightEffectRange().
void gamePlayer.GameGridEffect.clearAllPieceHighlights ()
Definition at line 138 of file GameGridEffect.java.
References authoring_environment.SuperGrid.findTile().
Referenced by gamePlayer.GameGridEffect.greyOutPiece(), gamePlayer.GameGridEffect.highlightCurrent(), and gamePlayer.ApplyState.onClick().
void gamePlayer.GameGridEffect.greyOutPiece (Point2D.Double loc, Piece p)
Definition at line 110 of file GameGridEffect.java.
References gamePlayer.GameGridEffect.clearAllActionHighlights(), gamePlayer.GameGridEffect.clearAllEffectHighlights(), gamePlayer.GameGridEffect.clearAllPieceHighlights(), authoring_environment.SuperGrid.findTile(), authoring_environment.SuperTile.selectTile(), and gamePlayer.GameGridEffect.updateActives().
void gamePlayer.GameGridEffect.highlightActionRange ()
Highlight the tiles that represent the possible range of the action selected
Definition at line 42 of file GameGridEffect.java.
References gamePlayer.GameGridEffect.clearAllActionHighlights(), authoring_environment.SuperGrid.findTile(), gamedata.action.Action.getAbsoluteActionRange(), gamedata.gamecomponents.GridComponent.getLoc(), authoring_environment.SuperGrid.getNumCols(), authoring_environment.SuperGrid.getNumRows(), authoring_environment.SuperTile.selectTile(), and gamePlayer.GameGridEffect.updateActives().
Referenced by gamePlayer.ViewController.bindAction().
void gamePlayer.GameGridEffect.highlightCurrent (Point2D.Double loc, Piece activeP)
Uses GRID COORDINATE LOCATION to highlight the current location on the grid
Definition at line 97 of file GameGridEffect.java.
References gamePlayer.GameGridEffect.clearAllActionHighlights(), gamePlayer.GameGridEffect.clearAllEffectHighlights(), gamePlayer.GameGridEffect.clearAllPieceHighlights(), authoring_environment.SuperGrid.findTile(), authoring_environment.SuperTile.selectTile(), and gamePlayer.GameGridEffect.updateActives().
Referenced by gamePlayer.ViewController.highlightSelected().
void gamePlayer.GameGridEffect.highlightEffectRange (Point2D.Double loc)
Highlight the effect range of an action if to be applied at a given position Highlight the effect range of an action if to be applied at a given position
Parameters
n
red
Definition at line 74 of file GameGridEffect.java.
References gamePlayer.GameGridEffect.clearAllEffectHighlights(), authoring_environment.SuperGrid.findTile(), gamedata.action.Action.getAbsoluteEffectRange(), gamePlayer.ViewController.getActiveAction(), and authoring_environment.SuperTile.selectTile().
boolean gamePlayer.GameGridEffect.isHoveringOverActionHighlight (double mouseX, double mouseY)
Checks if the mouse movement has it hovering over an action tile Only then will it update the highlight of the effect range
Parameters
mouseX
mouseY
Returns
Definition at line 158 of file GameGridEffect.java.
References authoring_environment.SuperGrid.findClickedTile(), authoring_environment.SuperTile.getCoordinates(), and gamePlayer.ViewController.getGrid().
Referenced by gamePlayer.ApplyState.handleMouseMove().
void gamePlayer.GameGridEffect.updateActives () private
Definition at line 145 of file GameGridEffect.java.
References gamePlayer.ViewController.getActiveAction(), and gamePlayer.ViewController.getActivePiece().
Referenced by gamePlayer.GameGridEffect.greyOutPiece(), gamePlayer.GameGridEffect.highlightActionRange(), and gamePlayer.GameGridEffect.highlightCurrent().
Member Data Documentation
final String gamePlayer.GameGridEffect.ACTION_RANGE_COLOR = "#FFBF00" static
Definition at line 22 of file GameGridEffect.java.
final String gamePlayer.GameGridEffect.DEFAULT_COLOR = "#0000FF" static private
Definition at line 24 of file GameGridEffect.java.
final String gamePlayer.GameGridEffect.EFFECT_RANGE_COLOR = "#DF0101" static
Definition at line 23 of file GameGridEffect.java.
final String gamePlayer.GameGridEffect.GREY_OUT = "#000000" static private
Definition at line 25 of file GameGridEffect.java.
Action gamePlayer.GameGridEffect.myActiveAction private
Definition at line 16 of file GameGridEffect.java.
Piece gamePlayer.GameGridEffect.myActivePiece private
Definition at line 15 of file GameGridEffect.java.
GUIGrid gamePlayer.GameGridEffect.myGrid private
Definition at line 14 of file GameGridEffect.java.
List<SuperTile> gamePlayer.GameGridEffect.myHighlightedActions private
Definition at line 18 of file GameGridEffect.java.
List<SuperTile> gamePlayer.GameGridEffect.myHighlightedEffects private
Definition at line 19 of file GameGridEffect.java.
List<SuperTile> gamePlayer.GameGridEffect.myHighlightedPiece private
Definition at line 17 of file GameGridEffect.java.
ViewController gamePlayer.GameGridEffect.myViewController private
Definition at line 13 of file GameGridEffect.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamePlayer/GameGridEffect.java