voogasalad_VOOGirlsGeneration: authoring.concretefeatures.StatsIndividualEditor Class Reference
authoring.concretefeatures.StatsIndividualEditor Class Reference
Public Member Functions
StatsIndividualEditor (Stats stats)
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Static Protected Attributes
static final String DEFAULT_STAT = ""
Private Member Functions
HBox initStatsEditorBox (String name)
void createButton (VBox buttonBox, Set< String > statNames)
Private Attributes
Map< String, TextField > values
Label myStatLabel
TextField myValueField
Stats myStats
Static Private Attributes
static final int STAT_BOX_WIDTH = 100
static final int VALUE_BOX_WIDTH = 100
static final int WINDOW_HEIGHT = 400
static final int WINDOW_WIDTH = 400
static final String WINDOW_TITLE = "Stats Editor"
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Creates a pop-up for editing individual piece's stats. It has default stats (set by the piece's type) with default values. The user is able to change such default values to the values of his choice.
Author
Sandy Lee
Definition at line 29 of file StatsIndividualEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.StatsIndividualEditor.StatsIndividualEditor (Stats stats)
Constructor for an editor popup for editing stats of an individual piece on the grid.
Parameters
piece - individual piece (its stats are to be edited)
Definition at line 50 of file StatsIndividualEditor.java.
References authoring.concretefeatures.StatsIndividualEditor.initialize().
Member Function Documentation
void authoring.concretefeatures.StatsIndividualEditor.createButton (VBox buttonBox, Set< String > statNames) private
Method creates the "create" button.
Parameters
buttonBox - box that contains the "create" button
statNames - set of strings which are the names of the stats
Definition at line 114 of file StatsIndividualEditor.java.
References gamedata.stats.Stats.add().
Referenced by authoring.concretefeatures.StatsIndividualEditor.initialize().
void authoring.concretefeatures.StatsIndividualEditor.initialize () protected
Definition at line 61 of file StatsIndividualEditor.java.
References authoring.concretefeatures.StatsIndividualEditor.createButton(), gamedata.stats.Stats.getStatNames(), and authoring.concretefeatures.StatsIndividualEditor.initStatsEditorBox().
Referenced by authoring.concretefeatures.StatsIndividualEditor.StatsIndividualEditor().
HBox authoring.concretefeatures.StatsIndividualEditor.initStatsEditorBox (String name) private
Parameters
name - name of the stat
Returns
HBox - which contains label for stat name and textfield for value to be entered
Definition at line 89 of file StatsIndividualEditor.java.
References gamedata.stats.Stats.getValue().
Referenced by authoring.concretefeatures.StatsIndividualEditor.initialize().
Member Data Documentation
final String authoring.concretefeatures.StatsIndividualEditor.DEFAULT_STAT = "" static protected
Definition at line 37 of file StatsIndividualEditor.java.
Label authoring.concretefeatures.StatsIndividualEditor.myStatLabel private
Definition at line 40 of file StatsIndividualEditor.java.
Stats authoring.concretefeatures.StatsIndividualEditor.myStats private
Definition at line 42 of file StatsIndividualEditor.java.
TextField authoring.concretefeatures.StatsIndividualEditor.myValueField private
Definition at line 41 of file StatsIndividualEditor.java.
final int authoring.concretefeatures.StatsIndividualEditor.STAT_BOX_WIDTH = 100 static private
Definition at line 30 of file StatsIndividualEditor.java.
final String authoring.concretefeatures.StatsIndividualEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 35 of file StatsIndividualEditor.java.
final int authoring.concretefeatures.StatsIndividualEditor.VALUE_BOX_WIDTH = 100 static private
Definition at line 31 of file StatsIndividualEditor.java.
Map<String, TextField> authoring.concretefeatures.StatsIndividualEditor.values private
Definition at line 39 of file StatsIndividualEditor.java.
final int authoring.concretefeatures.StatsIndividualEditor.WINDOW_HEIGHT = 400 static private
Definition at line 32 of file StatsIndividualEditor.java.
final String authoring.concretefeatures.StatsIndividualEditor.WINDOW_TITLE = "Stats Editor" static private
Definition at line 34 of file StatsIndividualEditor.java.
final int authoring.concretefeatures.StatsIndividualEditor.WINDOW_WIDTH = 400 static private
Definition at line 33 of file StatsIndividualEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/StatsIndividualEditor.java