voogasalad_VOOGirlsGeneration: authoring.createedit.EventEditor Class Reference
authoring.createedit.EventEditor Class Reference
Public Member Functions
EventEditor ()
ObservableList< String > getEvents ()
Private Member Functions
void editEvent ()
void removeEvent ()
Private Attributes
ObservableList< String > events
ListView< String > eventsView
SuperEditorMenu myEditor
Static Private Attributes
static final String NAME = "Event Editor"
static final String EVENTS_LIST_NAME = "Events"
static final String EDIT_EVENT_BUTTON = "Edit Event"
static final String REMOVE_EVENT_BUTTON = "Remove Event"
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Definition at line 9 of file EventEditor.java.
Constructor & Destructor Documentation
authoring.createedit.EventEditor.EventEditor ()
Definition at line 22 of file EventEditor.java.
References authoring.createedit.EventEditor.editEvent(), authoring.createedit.SuperEditorMenu.initializeButtons(), authoring.createedit.SuperEditorMenu.initializeLibrary(), and authoring.createedit.EventEditor.removeEvent().
Member Function Documentation
void authoring.createedit.EventEditor.editEvent () private
Definition at line 38 of file EventEditor.java.
Referenced by authoring.createedit.EventEditor.EventEditor().
ObservableList<String> authoring.createedit.EventEditor.getEvents ()
Definition at line 47 of file EventEditor.java.
References authoring.createedit.EventEditor.events.
void authoring.createedit.EventEditor.removeEvent () private
Definition at line 42 of file EventEditor.java.
Referenced by authoring.createedit.EventEditor.EventEditor().
Member Data Documentation
final String authoring.createedit.EventEditor.EDIT_EVENT_BUTTON = "Edit Event" static private
Definition at line 13 of file EventEditor.java.
ObservableList<String> authoring.createedit.EventEditor.events private
Definition at line 17 of file EventEditor.java.
Referenced by authoring.createedit.EventEditor.getEvents().
final String authoring.createedit.EventEditor.EVENTS_LIST_NAME = "Events" static private
Definition at line 12 of file EventEditor.java.
ListView<String> authoring.createedit.EventEditor.eventsView private
Definition at line 18 of file EventEditor.java.
SuperEditorMenu authoring.createedit.EventEditor.myEditor private
Definition at line 20 of file EventEditor.java.
final String authoring.createedit.EventEditor.NAME = "Event Editor" static private
Definition at line 11 of file EventEditor.java.
final String authoring.createedit.EventEditor.REMOVE_EVENT_BUTTON = "Remove Event" static private
Definition at line 14 of file EventEditor.java.
final String authoring.createedit.EventEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 15 of file EventEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/createedit/EventEditor.java