voogasalad_VOOGirlsGeneration: fxml_main.GridComponentAbstCtrl< T > Class Template Reference
fxml_main.GridComponentAbstCtrl< T > Class Template Reference abstract
Protected Member Functions
GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef)
abstract void initGlobalNewBtn (Button newBtn)
abstract void initGlobalEditBtn (Button editBtn)
abstract void initGlobalDelBtn (Button delBtn)
void addEntry (T entry)
HBox makeCompleteEntryBox (T entry)
HBox initEntryControls (T entry)
abstract HBox makeEntryBox (T entry)
abstract void initEntryEditBtn (T entry, Button editBtn)
abstract void initEntryDelBtn (T entry, Button delBtn)
Protected Attributes
VBox myVBox
ScrollPane myPropertiesSPane
GUIGridReference myGridReference
Map< T, HBox > myEntryMap
Private Member Functions
void initGlobalControls ()
Detailed Description
Author
Sandy Lee, Jennie Ju
Parameters
<T>
Definition at line 19 of file GridComponentAbstCtrl.java.
Constructor & Destructor Documentation
fxml_main.GridComponentAbstCtrl< T >.GridComponentAbstCtrl (VBox vbox, ScrollPane propertiesSPane, GUIGridReference gridRef) protected
Definition at line 25 of file GridComponentAbstCtrl.java.
Member Function Documentation
void fxml_main.GridComponentAbstCtrl< T >.addEntry (T entry) protected
Definition at line 62 of file GridComponentAbstCtrl.java.
HBox fxml_main.GridComponentAbstCtrl< T >.initEntryControls (T entry) protected
Definition at line 78 of file GridComponentAbstCtrl.java.
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.makeCompleteEntryBox().
abstract void fxml_main.GridComponentAbstCtrl< T >.initEntryDelBtn (T entry, Button delBtn) abstract protected
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.initEntryControls().
abstract void fxml_main.GridComponentAbstCtrl< T >.initEntryEditBtn (T entry, Button editBtn) abstract protected
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.initEntryControls().
void fxml_main.GridComponentAbstCtrl< T >.initGlobalControls () private
Definition at line 34 of file GridComponentAbstCtrl.java.
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.GridComponentAbstCtrl().
abstract void fxml_main.GridComponentAbstCtrl< T >.initGlobalDelBtn (Button delBtn) abstract protected
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.initGlobalControls().
abstract void fxml_main.GridComponentAbstCtrl< T >.initGlobalEditBtn (Button editBtn) abstract protected
Sets the on-click actions for the Edit individual components button
Parameters
editBtn - button allowing editing of components on the grid
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.initGlobalControls().
abstract void fxml_main.GridComponentAbstCtrl< T >.initGlobalNewBtn (Button newBtn) abstract protected
Sets the on-click actions for the New component button
Parameters
newBtn - button allowing for creation of new components
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.initGlobalControls().
HBox fxml_main.GridComponentAbstCtrl< T >.makeCompleteEntryBox (T entry) protected
Definition at line 70 of file GridComponentAbstCtrl.java.
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.addEntry().
abstract HBox fxml_main.GridComponentAbstCtrl< T >.makeEntryBox (T entry) abstract protected
Referenced by fxml_main.GridComponentAbstCtrl< Patch >.makeCompleteEntryBox().
Member Data Documentation
Map<T, HBox> fxml_main.GridComponentAbstCtrl< T >.myEntryMap protected
Definition at line 23 of file GridComponentAbstCtrl.java.
GUIGridReference fxml_main.GridComponentAbstCtrl< T >.myGridReference protected
Definition at line 22 of file GridComponentAbstCtrl.java.
ScrollPane fxml_main.GridComponentAbstCtrl< T >.myPropertiesSPane protected
Definition at line 21 of file GridComponentAbstCtrl.java.
VBox fxml_main.GridComponentAbstCtrl< T >.myVBox protected
Definition at line 20 of file GridComponentAbstCtrl.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/GridComponentAbstCtrl.java