voogasalad_VOOGirlsGeneration: authoring.concretefeatures.RangeEditor Class Reference
authoring.concretefeatures.RangeEditor Class Reference
Classes
class SelectHandler
class selectRangeHandler
Public Member Functions
RangeEditor (List< Point2D.Double > range, Consumer< List< Point2D.Double >> consumer, String shape)
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Member Functions
int getPrefTileSize (int gridWidthNumber, int gridHeightNumber)
VBox makeTextField (String label)
Private Attributes
int myGridLength = RANGE_EDITOR_WIDTH - 100
int myTileSize = DEFAULT_TILE_SIZE
int myGridWidthNumber
int myGridHeightNumber
RangeGridView rangeGridView
List< Point2D.Double > myRange
Button mySelect
Consumer< List< Point2D.Double > > myConsumer
Static Private Attributes
static final int ENTER_LAYOUT_X = 300
static final int VRADIUS_LAYOUTX = 100
static final int VRADIUS_MAX_WIDTH = 120
static final int HRADIUS_MAX_WIDTH = 120
static final String VERTICAL_RADIUS = "Vertical Radius"
static final String HORIZONTAL_RADIUS = "Horizontal Radius"
static final int SELECT_BUTTON_SIZE = 50
static final String CUSTOM = "Custom(default)"
static final String RADIUS = "Radius"
static final String ALL = "All"
static final String ROW = "Row"
static final String COLUMN = "Column"
static final String NAME = "Range Editor"
static final int MIN_TILE_SIZE = 30
static final int RANGE_EDITOR_HEIGHT = 800
static final int RANGE_EDITOR_WIDTH = 600
static final int DEFAULT_TILE_SIZE = 40
static final String STYLESHEET
static final String DEFAULT_SHAPE = "SQUARE_GRID"
Detailed Description
Popup GUI element that allows the user to specify the size of the grid, selects the tiles and returns the list of relative coordination of selected tiles.
Author
Meng'en Huang, Jesse Ling, Jennie Ju
Definition at line 28 of file RangeEditor.java.
Constructor & Destructor Documentation
authoring.concretefeatures.RangeEditor.RangeEditor (List< Point2D.Double > range, Consumer< List< Point2D.Double >> consumer, String shape)
Definition at line 76 of file RangeEditor.java.
References authoring.concretefeatures.RangeEditor.initialize(), authoring.concretefeatures.RangeEditor.myConsumer, and authoring.concretefeatures.RangeEditor.myRange.
Member Function Documentation
int authoring.concretefeatures.RangeEditor.getPrefTileSize (int gridWidthNumber, int gridHeightNumber) private
Definition at line 172 of file RangeEditor.java.
References authoring.concretefeatures.RangeEditor.MIN_TILE_SIZE.
Referenced by authoring.concretefeatures.RangeEditor.initialize().
void authoring.concretefeatures.RangeEditor.initialize () protected
Definition at line 94 of file RangeEditor.java.
References authoring.concretefeatures.RangeEditor.getPrefTileSize(), authoring.concretefeatures.RangeEditor.myRange, authoring_environment.RangeGridView.returnSelectedList(), and authoring_environment.RangeGridView.update().
Referenced by authoring.concretefeatures.RangeEditor.RangeEditor().
VBox authoring.concretefeatures.RangeEditor.makeTextField (String label) private
Definition at line 244 of file RangeEditor.java.
Member Data Documentation
final String authoring.concretefeatures.RangeEditor.ALL = "All" static private
Definition at line 47 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.COLUMN = "Column" static private
Definition at line 51 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.CUSTOM = "Custom(default)" static private
Definition at line 43 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.DEFAULT_SHAPE = "SQUARE_GRID" static private
Definition at line 65 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.DEFAULT_TILE_SIZE = 40 static private
Definition at line 58 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.ENTER_LAYOUT_X = 300 static private
Definition at line 29 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.HORIZONTAL_RADIUS = "Horizontal Radius" static private
Definition at line 39 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.HRADIUS_MAX_WIDTH = 120 static private
Definition at line 35 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.MIN_TILE_SIZE = 30 static private
Definition at line 55 of file RangeEditor.java.
Referenced by authoring.concretefeatures.RangeEditor.getPrefTileSize().
Consumer<List<Point2D.Double> > authoring.concretefeatures.RangeEditor.myConsumer private
Definition at line 72 of file RangeEditor.java.
Referenced by authoring.concretefeatures.RangeEditor.SelectHandler.handle(), and authoring.concretefeatures.RangeEditor.RangeEditor().
int authoring.concretefeatures.RangeEditor.myGridHeightNumber private
Definition at line 68 of file RangeEditor.java.
int authoring.concretefeatures.RangeEditor.myGridLength = RANGE_EDITOR_WIDTH - 100 private
Definition at line 60 of file RangeEditor.java.
int authoring.concretefeatures.RangeEditor.myGridWidthNumber private
Definition at line 67 of file RangeEditor.java.
List<Point2D.Double> authoring.concretefeatures.RangeEditor.myRange private
Definition at line 70 of file RangeEditor.java.
Referenced by authoring.concretefeatures.RangeEditor.SelectHandler.handle(), authoring.concretefeatures.RangeEditor.initialize(), and authoring.concretefeatures.RangeEditor.RangeEditor().
Button authoring.concretefeatures.RangeEditor.mySelect private
Definition at line 71 of file RangeEditor.java.
int authoring.concretefeatures.RangeEditor.myTileSize = DEFAULT_TILE_SIZE private
Definition at line 61 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.NAME = "Range Editor" static private
Definition at line 53 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.RADIUS = "Radius" static private
Definition at line 45 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.RANGE_EDITOR_HEIGHT = 800 static private
Definition at line 56 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.RANGE_EDITOR_WIDTH = 600 static private
Definition at line 57 of file RangeEditor.java.
RangeGridView authoring.concretefeatures.RangeEditor.rangeGridView private
Definition at line 69 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.ROW = "Row" static private
Definition at line 49 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.SELECT_BUTTON_SIZE = 50 static private
Definition at line 41 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.STYLESHEET static private
Initial value:
=
            "/resources/stylesheets/actioncreator_layout.css"
Definition at line 62 of file RangeEditor.java.
final String authoring.concretefeatures.RangeEditor.VERTICAL_RADIUS = "Vertical Radius" static private
Definition at line 37 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.VRADIUS_LAYOUTX = 100 static private
Definition at line 31 of file RangeEditor.java.
final int authoring.concretefeatures.RangeEditor.VRADIUS_MAX_WIDTH = 120 static private
Definition at line 33 of file RangeEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/concretefeatures/RangeEditor.java