voogasalad_VOOGirlsGeneration: utilities.leapMotion.LeapUIController Class Reference
utilities.leapMotion.LeapUIController Class Reference
Public Member Functions
void start (Stage stage) throws Exception
Static Public Member Functions
static void main (String[] args)
Static Public Attributes
static final String LEAP_UI = "leapUI.fxml"
static final String MOUSE_OPTIONS = "/src/utilities/leapMotion/mouseControl"
static final String MOUSE_KEY = "mouse"
static final String CLICK_KEY = "click"
Protected Member Functions
void setUpGesture ()
void setUpDropDown ()
Private Member Functions
void mapKey (TextField tf)
void onSelect ()
void okayAction () throws IOException
Private Attributes
VBox gesturesVBox
ComboBox ClickDropDown
ComboBox MouseDropDown
BorderPane myRoot
Map< String, String > myControls
Label myCurrentLabel
Stage myStage
Detailed Description
Definition at line 35 of file LeapUIController.java.
Member Function Documentation
static void utilities.leapMotion.LeapUIController.main (String[] args) static
Definition at line 205 of file LeapUIController.java.
void utilities.leapMotion.LeapUIController.mapKey (TextField tf) private
Definition at line 121 of file LeapUIController.java.
void utilities.leapMotion.LeapUIController.okayAction () throws IOException private
Definition at line 191 of file LeapUIController.java.
References utilities.leapMotion.PropertyStorage.save().
void utilities.leapMotion.LeapUIController.onSelect () private
Definition at line 171 of file LeapUIController.java.
void utilities.leapMotion.LeapUIController.setUpDropDown () protected
to set mouse tracking of leap motion allows for dynamic UI dropdown based on the current available options
Definition at line 140 of file LeapUIController.java.
Referenced by utilities.leapMotion.LeapUIController.start().
void utilities.leapMotion.LeapUIController.setUpGesture () protected
Definition at line 82 of file LeapUIController.java.
Referenced by utilities.leapMotion.LeapUIController.start().
void utilities.leapMotion.LeapUIController.start (Stage stage) throws Exception
Definition at line 59 of file LeapUIController.java.
References utilities.leapMotion.LeapUIController.setUpDropDown(), and utilities.leapMotion.LeapUIController.setUpGesture().
Member Data Documentation
final String utilities.leapMotion.LeapUIController.CLICK_KEY = "click" static
Definition at line 40 of file LeapUIController.java.
ComboBox utilities.leapMotion.LeapUIController.ClickDropDown private
Definition at line 47 of file LeapUIController.java.
VBox utilities.leapMotion.LeapUIController.gesturesVBox private
Definition at line 44 of file LeapUIController.java.
final String utilities.leapMotion.LeapUIController.LEAP_UI = "leapUI.fxml" static
Definition at line 37 of file LeapUIController.java.
final String utilities.leapMotion.LeapUIController.MOUSE_KEY = "mouse" static
Definition at line 39 of file LeapUIController.java.
final String utilities.leapMotion.LeapUIController.MOUSE_OPTIONS = "/src/utilities/leapMotion/mouseControl" static
Definition at line 38 of file LeapUIController.java.
ComboBox utilities.leapMotion.LeapUIController.MouseDropDown private
Definition at line 49 of file LeapUIController.java.
Map<String, String> utilities.leapMotion.LeapUIController.myControls private
Definition at line 52 of file LeapUIController.java.
Label utilities.leapMotion.LeapUIController.myCurrentLabel private
Definition at line 53 of file LeapUIController.java.
BorderPane utilities.leapMotion.LeapUIController.myRoot private
Definition at line 51 of file LeapUIController.java.
Stage utilities.leapMotion.LeapUIController.myStage private
Definition at line 55 of file LeapUIController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/utilities/leapMotion/LeapUIController.java