voogasalad_VOOGirlsGeneration: authoring.eventeditor.NewConditionController Class Reference
authoring.eventeditor.NewConditionController Class Reference
Public Member Functions
void initialize (URL fxmlFileLocation, ResourceBundle resources)
void loadLambda (Consumer< Condition > okLambda)
void loadData (EventsDataWrapper data)
Private Member Functions
List< String > trimClassList (List< String > conditionsList)
void showConditionEditorPane ()
String trimClassPaths (String s)
Private Attributes
ChoiceBox< String > conditionChoiceBox
ScrollPane editorScrollPane
List< Class > conditionsList
Consumer< Condition > myDoneLambda
EventsDataWrapper myData
Detailed Description
Definition at line 20 of file NewConditionController.java.
Member Function Documentation
void authoring.eventeditor.NewConditionController.initialize (URL fxmlFileLocation, ResourceBundle resources)
Definition at line 35 of file NewConditionController.java.
References utilities.ClassGrabber.getClasses(), authoring.eventeditor.NewConditionController.showConditionEditorPane(), and authoring.eventeditor.NewConditionController.trimClassList().
void authoring.eventeditor.NewConditionController.loadData (EventsDataWrapper data)
Definition at line 101 of file NewConditionController.java.
Referenced by authoring.eventeditor.EventEditorController.showNewConditionWindow().
void authoring.eventeditor.NewConditionController.loadLambda (Consumer< Condition > okLambda)
Definition at line 97 of file NewConditionController.java.
Referenced by authoring.eventeditor.EventEditorController.showNewConditionWindow().
void authoring.eventeditor.NewConditionController.showConditionEditorPane () private
Definition at line 73 of file NewConditionController.java.
Referenced by authoring.eventeditor.NewConditionController.initialize().
List<String> authoring.eventeditor.NewConditionController.trimClassList (List< String > conditionsList) private
Definition at line 64 of file NewConditionController.java.
References authoring.eventeditor.NewConditionController.trimClassPaths().
Referenced by authoring.eventeditor.NewConditionController.initialize().
String authoring.eventeditor.NewConditionController.trimClassPaths (String s) private
Removes the classpath prefixes for each Condition name
Parameters
s
Definition at line 85 of file NewConditionController.java.
Referenced by authoring.eventeditor.NewConditionController.trimClassList().
Member Data Documentation
ChoiceBox<String> authoring.eventeditor.NewConditionController.conditionChoiceBox private
Definition at line 25 of file NewConditionController.java.
List<Class> authoring.eventeditor.NewConditionController.conditionsList private
Definition at line 29 of file NewConditionController.java.
ScrollPane authoring.eventeditor.NewConditionController.editorScrollPane private
Definition at line 27 of file NewConditionController.java.
EventsDataWrapper authoring.eventeditor.NewConditionController.myData private
Definition at line 32 of file NewConditionController.java.
Consumer<Condition> authoring.eventeditor.NewConditionController.myDoneLambda private
Definition at line 31 of file NewConditionController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/eventeditor/NewConditionController.java