voogasalad_VOOGirlsGeneration: authoring_environment.VoogaView Class Reference
authoring_environment.VoogaView Class Reference
Public Member Functions
VoogaView ()
Private Member Functions
void initializeCreator ()
Private Attributes
MenuView myMenuView
WorkspaceView myWorkspaceView
LibraryView myLibraryView
final String CREATOR_TITLE = "Creator"
final int HEIGHT = 600
final int WIDTH = 1000
final int WIDTH2 = 350
final int WINDOW_PADDING = 10
ActionData myActions = new ActionData()
PieceTypeData pieceTypeData
PatchTypeData patchTypeData
Detailed Description
The GUI contains all the parts in authoring environment. It sets the size and the position of the parts in the GUI.
Author
huangmengen
Definition at line 21 of file VoogaView.java.
Constructor & Destructor Documentation
authoring_environment.VoogaView.VoogaView ()
Associate the LibraryView with the currently selected Tab
Definition at line 35 of file VoogaView.java.
References authoring_environment.WorkspaceView.getActiveGrid(), and authoring_environment.VoogaView.initializeCreator().
Member Function Documentation
void authoring_environment.VoogaView.initializeCreator () private
Definition at line 63 of file VoogaView.java.
Referenced by authoring_environment.VoogaView.VoogaView().
Member Data Documentation
final String authoring_environment.VoogaView.CREATOR_TITLE = "Creator" private
Definition at line 26 of file VoogaView.java.
final int authoring_environment.VoogaView.HEIGHT = 600 private
Definition at line 27 of file VoogaView.java.
ActionData authoring_environment.VoogaView.myActions = new ActionData() private
Definition at line 31 of file VoogaView.java.
LibraryView authoring_environment.VoogaView.myLibraryView private
Definition at line 25 of file VoogaView.java.
MenuView authoring_environment.VoogaView.myMenuView private
Definition at line 23 of file VoogaView.java.
WorkspaceView authoring_environment.VoogaView.myWorkspaceView private
Definition at line 24 of file VoogaView.java.
PatchTypeData authoring_environment.VoogaView.patchTypeData private
Definition at line 33 of file VoogaView.java.
PieceTypeData authoring_environment.VoogaView.pieceTypeData private
Definition at line 32 of file VoogaView.java.
final int authoring_environment.VoogaView.WIDTH = 1000 private
Definition at line 28 of file VoogaView.java.
final int authoring_environment.VoogaView.WIDTH2 = 350 private
Definition at line 29 of file VoogaView.java.
final int authoring_environment.VoogaView.WINDOW_PADDING = 10 private
Definition at line 30 of file VoogaView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/VoogaView.java