voogasalad_VOOGirlsGeneration: authoring.data.GamePropertiesData Class Reference
authoring.data.GamePropertiesData Class Reference
Public Member Functions
GamePropertiesData (int numPlayers, String gridShape)
int getNumPlayers ()
String getGridShape ()
Private Attributes
int myNumPlayers
String myGridShape
Detailed Description
Definition at line 3 of file GamePropertiesData.java.
Constructor & Destructor Documentation
authoring.data.GamePropertiesData.GamePropertiesData (int numPlayers, String gridShape)
Definition at line 8 of file GamePropertiesData.java.
Member Function Documentation
String authoring.data.GamePropertiesData.getGridShape ()
Definition at line 17 of file GamePropertiesData.java.
References authoring.data.GamePropertiesData.myGridShape.
Referenced by authoring.createedit.GamePropertiesEditor.GamePropertiesEditor(), and fxml_main.AuthoringController.initData().
int authoring.data.GamePropertiesData.getNumPlayers ()
Definition at line 13 of file GamePropertiesData.java.
References authoring.data.GamePropertiesData.myNumPlayers.
Referenced by authoring.data.GameAuthoringData.createGame(), and authoring.createedit.GamePropertiesEditor.GamePropertiesEditor().
Member Data Documentation
String authoring.data.GamePropertiesData.myGridShape private
Definition at line 6 of file GamePropertiesData.java.
Referenced by authoring.data.GamePropertiesData.getGridShape().
int authoring.data.GamePropertiesData.myNumPlayers private
Definition at line 5 of file GamePropertiesData.java.
Referenced by authoring.data.GamePropertiesData.getNumPlayers().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/GamePropertiesData.java