voogasalad_VOOGirlsGeneration: utilities.Reflection Class Reference
utilities.Reflection Class Reference
Static Public Member Functions
static Object createInstance (String className) throws ReflectionException
static Object createInstance (String name, Object...args) throws ReflectionException
static Object callMethod (Object target, String name) throws ReflectionException
static Object callMethod (Object target, String name, Object...args) throws ReflectionException
static Object getFieldValue (Object target, String name) throws ReflectionException
static Class<?>[] toClasses (Object[] args)
Static Private Member Functions
static boolean typesMatch (Member function, Class<?>[] formals, Object[] actuals)
static Object[] convertArgs (Member function, Class<?>[] formals, Object[] actuals)
static boolean isInstance (Class<?> clss, Object instance)
static boolean isVarArgs (Member function)
static boolean isAssignableFrom (Class<?> formal, Class<?> arg)
Detailed Description
This class provides a variety of convenience methods for dynamically calling methods and allocating classes. This utility class simplifies some of Java's reflection API and fixes some issues.
Author
Robert C. Duvall
Definition at line 17 of file Reflection.java.
Member Function Documentation
static Object utilities.Reflection.callMethod (Object target, String name) throws ReflectionException static
Given a target object with a no argument method of the given name, call the named method on that object and return the result.
If the method's return type is void, null in returned.
Definition at line 61 of file Reflection.java.
static Object utilities.Reflection.callMethod (Object target, String name, Object... args) throws ReflectionException static
Given a target object with a method of the given name that takes the given actual parameters, call the named method on that object and return the result.
If the method's return type is void, null in returned.
Definition at line 77 of file Reflection.java.
References utilities.Reflection.convertArgs(), and utilities.Reflection.typesMatch().
static Object [] utilities.Reflection.convertArgs (Member function, Class<?>[] formals, Object[] actuals) static private
Definition at line 143 of file Reflection.java.
References utilities.Reflection.isVarArgs().
Referenced by utilities.Reflection.callMethod(), and utilities.Reflection.createInstance().
static Object utilities.Reflection.createInstance (String className) throws ReflectionException static
Given a String representing the fully qualified name of a class, returns an initialized instance of the corresponding class using default constructor. Returns null if string does not name a valid class.
Definition at line 23 of file Reflection.java.
Referenced by fxml_main.ActionEditor.initConclusionsBox().
static Object utilities.Reflection.createInstance (String name, Object... args) throws ReflectionException static
Given String representing fully qualified name of a class and the actual parameters, returns initialized instance of the corresponding class using matching constructor.
Definition at line 38 of file Reflection.java.
References utilities.Reflection.convertArgs(), and utilities.Reflection.typesMatch().
static Object utilities.Reflection.getFieldValue (Object target, String name) throws ReflectionException static
Given a target object with an instance variable with the given name, get the value of the named variable on that object and return it.
Definition at line 98 of file Reflection.java.
Referenced by utilities.Reflection.isInstance().
static boolean utilities.Reflection.isAssignableFrom (Class<?> formal, Class<?> arg) static private
Definition at line 195 of file Reflection.java.
Referenced by utilities.Reflection.isInstance().
static boolean utilities.Reflection.isInstance (Class<?> clss, Object instance) static private
Definition at line 164 of file Reflection.java.
References utilities.Reflection.getFieldValue(), and utilities.Reflection.isAssignableFrom().
Referenced by utilities.Reflection.typesMatch().
static boolean utilities.Reflection.isVarArgs (Member function) static private
Definition at line 188 of file Reflection.java.
Referenced by utilities.Reflection.convertArgs(), and utilities.Reflection.typesMatch().
static Class<?> [] utilities.Reflection.toClasses (Object[] args) static
Given an array of Objects, returns their corresponding Classes.
Definition at line 109 of file Reflection.java.
static boolean utilities.Reflection.typesMatch (Member function, Class<?>[] formals, Object[] actuals) static private
Definition at line 118 of file Reflection.java.
References utilities.Reflection.isInstance(), and utilities.Reflection.isVarArgs().
Referenced by utilities.Reflection.callMethod(), and utilities.Reflection.createInstance().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/utilities/Reflection.java