voogasalad_VOOGirlsGeneration: gamedata.events.Event Class Reference
gamedata.events.Event Class Reference
Public Member Functions
Event (String name)
Event (String name, List< Condition > conditions, List< GlobalAction > globalActions)
void runEvent (List< IHasStats > sources, GUIGrid grid)
String toString ()
List< Condition > getConditions ()
List< GlobalAction > getGlobalActions ()
Private Attributes
String myName
List< Condition > myConditions
List< GlobalAction > myGlobalActions
Detailed Description
Events are action-reaction pairs that allow users to define complex game rules. Events contain a list of Conditions and Actions. Conditions observe game state, and when all Conditions evaluate to true, the list of Actions are run. Through composition, the behavior of any Event object is highly customizable.
Conditions and Actions are implemented in code, rather than through the authoring environment ("hard-coded"). By allowing users to chain together any number of Conditions and Actions, we provide huge flexibility in determining game rules.
Events are stored within the Level, but require data from GUIGrid (lists of all Piece and Patch objects) to run. This is done by passing the method runEvent via a lambda into the GUIGrid, rather than sending all of that data out of GUIGrid.
Author
Mike Zhu
Definition at line 32 of file Event.java.
Constructor & Destructor Documentation
gamedata.events.Event.Event (String name)
Constructor for making an Event from scratch
Parameters
name = name of the Event
Definition at line 41 of file Event.java.
gamedata.events.Event.Event (String name, List< Condition > conditions, List< GlobalAction > globalActions)
Constructor for event with existing data, aka from game data unwrapping
Parameters
name = Event name
conditions = Previously added Conditions
globalActions = Previously added GlobalActions
Definition at line 59 of file Event.java.
Member Function Documentation
List<Condition> gamedata.events.Event.getConditions ()
Getters for the list of Conditions and GlobalActions. The getter is needed to pass Conditions and GlobalActions into the EventEditor GUI, in order to populate ListViews. This allows the user to see and modify the Event's Condition and GlobalAction lists.
Returns
Definition at line 103 of file Event.java.
References gamedata.events.Event.myConditions.
Referenced by tests.TestGameCreator.createNewEvent(), authoring.eventeditor.EventEditorController.showEventInEditor(), and tests.JSONTesterMain.testJSONwrite().
List<GlobalAction> gamedata.events.Event.getGlobalActions ()
Definition at line 107 of file Event.java.
References gamedata.events.Event.myGlobalActions.
Referenced by tests.TestGameCreator.createNewEvent(), authoring.eventeditor.EventEditorController.showEventInEditor(), and tests.JSONTesterMain.testJSONwrite().
void gamedata.events.Event.runEvent (List< IHasStats > sources, GUIGrid grid)
Method called by the Level during each "event running" cycle (can be at the end of a user action, end of turn, end of level, etc.).
The list of Conditions is evaluated, and if all return true, the list of Actions is run in order.
This method is passed from Level into GUIGrid using lambda functions to minimize the passing around of data collections.
Definition at line 75 of file Event.java.
String gamedata.events.Event.toString ()
Definition at line 92 of file Event.java.
References gamedata.events.Event.myName.
Member Data Documentation
List<Condition> gamedata.events.Event.myConditions private
Definition at line 34 of file Event.java.
Referenced by gamedata.events.Event.getConditions().
List<GlobalAction> gamedata.events.Event.myGlobalActions private
Definition at line 35 of file Event.java.
Referenced by gamedata.events.Event.getGlobalActions().
String gamedata.events.Event.myName private
Definition at line 33 of file Event.java.
Referenced by gamedata.events.Event.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/events/Event.java