voogasalad_VOOGirlsGeneration: authoring.data.PlayerStatData Class Reference
authoring.data.PlayerStatData Class Reference
Public Member Functions
PlayerStatData ()
Stats getStats ()
String getScoreStat ()
void setScoreStat (String stat)
List< Player > makePlayers (int numPlayers)
Private Attributes
Stats myStats
String myScoreStat
Detailed Description
Definition at line 10 of file PlayerStatData.java.
Constructor & Destructor Documentation
authoring.data.PlayerStatData.PlayerStatData ()
Definition at line 14 of file PlayerStatData.java.
Member Function Documentation
String authoring.data.PlayerStatData.getScoreStat ()
Definition at line 23 of file PlayerStatData.java.
References authoring.data.PlayerStatData.myScoreStat.
Referenced by fxml_main.PlayerStatEditor.initialize().
Stats authoring.data.PlayerStatData.getStats ()
Definition at line 19 of file PlayerStatData.java.
References authoring.data.PlayerStatData.myStats.
Referenced by fxml_main.PlayerStatEditor.initialize(), and fxml_main.PlayerStatEditor.PlayerStatEditor().
List<Player> authoring.data.PlayerStatData.makePlayers (int numPlayers)
Definition at line 31 of file PlayerStatData.java.
Referenced by authoring.data.GameAuthoringData.createGame().
void authoring.data.PlayerStatData.setScoreStat (String stat)
Definition at line 27 of file PlayerStatData.java.
Referenced by fxml_main.PlayerStatEditor.initialize().
Member Data Documentation
String authoring.data.PlayerStatData.myScoreStat private
Definition at line 12 of file PlayerStatData.java.
Referenced by authoring.data.PlayerStatData.getScoreStat().
Stats authoring.data.PlayerStatData.myStats private
Definition at line 11 of file PlayerStatData.java.
Referenced by authoring.data.PlayerStatData.getStats().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/data/PlayerStatData.java