voogasalad_VOOGirlsGeneration: authoring_environment.UIspecs Class Reference
authoring_environment.UIspecs Class Reference
Static Public Attributes
static final Insets allPadding = new Insets(5)
static final Insets fatPadding = new Insets(10)
static final Insets topRightPadding = new Insets(5, 5, 0, 0)
static final Insets leftPadding = new Insets(0, 0, 0, 5)
static final Insets rightPadding = new Insets(0, 5, 0, 0)
static final Insets fatLeftRightPadding = new Insets(5, 15, 5, 15)
static final Insets topPadding = new Insets(5, 0, 0, 0)
static final Insets bottomPadding = new Insets(0, 0, 5, 0)
static final Insets topBottomPadding = new Insets(5, 0, 5, 0)
static final Insets topBottomRightPadding = new Insets(5, 5, 5, 0)
static final Insets topBottomLeftPadding = new Insets(5, 0, 5, 5)
Detailed Description
Definition at line 5 of file UIspecs.java.
Member Data Documentation
final Insets authoring_environment.UIspecs.allPadding = new Insets(5) static
Definition at line 6 of file UIspecs.java.
Referenced by fxml_main.ActionViewer.createHBox(), fxml_main.PatchViewer.initialize(), authoring.concretefeatures.IndividualUnitEditor.initialize(), fxml_main.PieceEditor.initialize(), fxml_main.PatchTypeEditor.initialize(), fxml_main.PieceTypeEditor.initialize(), authoring.eventeditor.ConditionEditorPane.initialize(), authoring_environment.LibraryView.LibraryView(), and authoring.concretefeatures.UnitEntry.UnitEntry().
final Insets authoring_environment.UIspecs.bottomPadding = new Insets(0, 0, 5, 0) static
Definition at line 13 of file UIspecs.java.
final Insets authoring_environment.UIspecs.fatLeftRightPadding = new Insets(5, 15, 5, 15) static
Definition at line 11 of file UIspecs.java.
final Insets authoring_environment.UIspecs.fatPadding = new Insets(10) static
Definition at line 7 of file UIspecs.java.
final Insets authoring_environment.UIspecs.leftPadding = new Insets(0, 0, 0, 5) static
Definition at line 9 of file UIspecs.java.
final Insets authoring_environment.UIspecs.rightPadding = new Insets(0, 5, 0, 0) static
Definition at line 10 of file UIspecs.java.
final Insets authoring_environment.UIspecs.topBottomLeftPadding = new Insets(5, 0, 5, 5) static
Definition at line 16 of file UIspecs.java.
final Insets authoring_environment.UIspecs.topBottomPadding = new Insets(5, 0, 5, 0) static
Definition at line 14 of file UIspecs.java.
Referenced by authoring.concretefeatures.GameCreator.initializeVBoxContent().
final Insets authoring_environment.UIspecs.topBottomRightPadding = new Insets(5, 5, 5, 0) static
Definition at line 15 of file UIspecs.java.
final Insets authoring_environment.UIspecs.topPadding = new Insets(5, 0, 0, 0) static
Definition at line 12 of file UIspecs.java.
final Insets authoring_environment.UIspecs.topRightPadding = new Insets(5, 5, 0, 0) static
Definition at line 8 of file UIspecs.java.
Referenced by authoring.concretefeatures.GameCreator.initChoiceBox(), authoring.createedit.EventCreator.initialize(), fxml_main.PatchViewer.initialize(), fxml_main.PieceEditor.initialize(), fxml_main.PatchTypeEditor.initialize(), fxml_main.PieceTypeEditor.initialize(), authoring.concretefeatures.GameCreator.initLabel(), authoring.concretefeatures.IndividualUnitEditor.initNameField(), fxml_main.PieceEditor.initPlayerChoice(), authoring.concretefeatures.IndividualUnitEditor.initPlayerID(), and authoring.concretefeatures.IndividualUnitEditor.initRot().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring_environment/UIspecs.java