voogasalad_VOOGirlsGeneration: authoring.eventeditor.NewActionController Class Reference
authoring.eventeditor.NewActionController Class Reference
Public Member Functions
void initialize (URL fxmlFileLocation, ResourceBundle resources)
void loadLambda (Consumer< GlobalAction > okLambda)
void loadData (EventsDataWrapper data)
void loadState (IChangeGameState state)
Private Member Functions
void handleDoneButton ()
List< String > trimClassList (List< String > actionList)
void showActionEditorPane ()
String trimClassPaths (String s)
Private Attributes
TextField myYField
HBox myUnitActionsBox
ChoiceBox< String > myTypeChoiceBox
TextField myNextLevelField
TextField myXField
TextField myPlayerIDField
Button myDoneButton
ChoiceBox< IHasStats > myRefNameBox
HBox myStatsHBox
TotalLogicBox myTotalLogic
List< Class > actionList
Consumer< GlobalAction > myDoneLambda
EventsDataWrapper myData
IChangeGameState myState
int myPlayerID
String myStatName
int myConstant
TextField myStatString
TextField myIDField
TextField myConstantField
Detailed Description
Definition at line 37 of file NewActionController.java.
Member Function Documentation
void authoring.eventeditor.NewActionController.handleDoneButton () private
Definition at line 124 of file NewActionController.java.
References utilities.reflection.Reflection.createInstance().
void authoring.eventeditor.NewActionController.initialize (URL fxmlFileLocation, ResourceBundle resources)
Definition at line 78 of file NewActionController.java.
References utilities.ClassGrabber.getClasses(), authoring.eventeditor.NewActionController.showActionEditorPane(), and authoring.eventeditor.NewActionController.trimClassList().
void authoring.eventeditor.NewActionController.loadData (EventsDataWrapper data)
Definition at line 221 of file NewActionController.java.
References authoring.data.EventsDataWrapper.getPieceTypes().
Referenced by authoring.eventeditor.EventEditorController.showNewActionWindow().
void authoring.eventeditor.NewActionController.loadLambda (Consumer< GlobalAction > okLambda)
Definition at line 217 of file NewActionController.java.
Referenced by authoring.eventeditor.EventEditorController.showNewActionWindow().
void authoring.eventeditor.NewActionController.loadState (IChangeGameState state)
Definition at line 227 of file NewActionController.java.
Referenced by authoring.eventeditor.EventEditorController.showNewActionWindow().
void authoring.eventeditor.NewActionController.showActionEditorPane () private
Definition at line 177 of file NewActionController.java.
Referenced by authoring.eventeditor.NewActionController.initialize().
List<String> authoring.eventeditor.NewActionController.trimClassList (List< String > actionList) private
Definition at line 167 of file NewActionController.java.
References authoring.eventeditor.NewActionController.trimClassPaths().
Referenced by authoring.eventeditor.NewActionController.initialize().
String authoring.eventeditor.NewActionController.trimClassPaths (String s) private
Removes the classpath prefixes for each Condition name
Parameters
s
Definition at line 205 of file NewActionController.java.
Referenced by authoring.eventeditor.NewActionController.trimClassList().
Member Data Documentation
List<Class> authoring.eventeditor.NewActionController.actionList private
Definition at line 63 of file NewActionController.java.
int authoring.eventeditor.NewActionController.myConstant private
Definition at line 71 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myConstantField private
Definition at line 75 of file NewActionController.java.
EventsDataWrapper authoring.eventeditor.NewActionController.myData private
Definition at line 66 of file NewActionController.java.
Button authoring.eventeditor.NewActionController.myDoneButton private
Definition at line 56 of file NewActionController.java.
Consumer<GlobalAction> authoring.eventeditor.NewActionController.myDoneLambda private
Definition at line 65 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myIDField private
Definition at line 74 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myNextLevelField private
Definition at line 50 of file NewActionController.java.
int authoring.eventeditor.NewActionController.myPlayerID private
Definition at line 69 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myPlayerIDField private
Definition at line 54 of file NewActionController.java.
ChoiceBox<IHasStats> authoring.eventeditor.NewActionController.myRefNameBox private
Definition at line 58 of file NewActionController.java.
IChangeGameState authoring.eventeditor.NewActionController.myState private
Definition at line 67 of file NewActionController.java.
String authoring.eventeditor.NewActionController.myStatName private
Definition at line 70 of file NewActionController.java.
HBox authoring.eventeditor.NewActionController.myStatsHBox private
Definition at line 60 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myStatString private
Definition at line 73 of file NewActionController.java.
TotalLogicBox authoring.eventeditor.NewActionController.myTotalLogic private
Definition at line 61 of file NewActionController.java.
ChoiceBox<String> authoring.eventeditor.NewActionController.myTypeChoiceBox private
Definition at line 48 of file NewActionController.java.
HBox authoring.eventeditor.NewActionController.myUnitActionsBox private
Definition at line 44 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myXField private
Definition at line 52 of file NewActionController.java.
TextField authoring.eventeditor.NewActionController.myYField private
Definition at line 42 of file NewActionController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/authoring/eventeditor/NewActionController.java