voogasalad_VOOGirlsGeneration: fxml_main.PlayerStatEditor Class Reference
fxml_main.PlayerStatEditor Class Reference
Public Member Functions
PlayerStatEditor (PlayerStatData psd)
Protected Member Functions
void initialize ()
Protected Member Functions inherited from authoring.abstractfeatures.PopupWindow
abstract void initialize ()
Private Attributes
PlayerStatData myPlayerStatData
Stats myStats
Static Private Attributes
static final int WINDOW_HEIGHT = 400
static final int WINDOW_WIDTH = 420
static final int TEXTFIELD_WIDTH = 200
static final String STYLESHEET = "/resources/stylesheets/slategray_layout.css"
Detailed Description
Definition at line 15 of file PlayerStatEditor.java.
Constructor & Destructor Documentation
fxml_main.PlayerStatEditor.PlayerStatEditor (PlayerStatData psd)
Definition at line 24 of file PlayerStatEditor.java.
References authoring.data.PlayerStatData.getStats(), and fxml_main.PlayerStatEditor.initialize().
Member Function Documentation
void fxml_main.PlayerStatEditor.initialize () protected
Definition at line 31 of file PlayerStatEditor.java.
References gamedata.stats.Stats.contains(), authoring.data.PlayerStatData.getScoreStat(), authoring.data.PlayerStatData.getStats(), and authoring.data.PlayerStatData.setScoreStat().
Referenced by fxml_main.PlayerStatEditor.PlayerStatEditor().
Member Data Documentation
PlayerStatData fxml_main.PlayerStatEditor.myPlayerStatData private
Definition at line 21 of file PlayerStatEditor.java.
Stats fxml_main.PlayerStatEditor.myStats private
Definition at line 22 of file PlayerStatEditor.java.
final String fxml_main.PlayerStatEditor.STYLESHEET = "/resources/stylesheets/slategray_layout.css" static private
Definition at line 19 of file PlayerStatEditor.java.
final int fxml_main.PlayerStatEditor.TEXTFIELD_WIDTH = 200 static private
Definition at line 18 of file PlayerStatEditor.java.
final int fxml_main.PlayerStatEditor.WINDOW_HEIGHT = 400 static private
Definition at line 16 of file PlayerStatEditor.java.
final int fxml_main.PlayerStatEditor.WINDOW_WIDTH = 420 static private
Definition at line 17 of file PlayerStatEditor.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/PlayerStatEditor.java