voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.GridComponent Class Reference
gamedata.gamecomponents.GridComponent Class Reference abstract
Public Member Functions
GridComponent (String id, String name, String imageLocation, Point2D.Double point)
GridComponent (GridComponent clone, Point2D.Double placeHere)
String getID ()
void setName (String name)
Point2D.Double getLoc ()
void setLoc (Point2D.Double loc)
String getImageLocation ()
String getName ()
void setImageLocation (String imageLocation)
ImageView getImageView ()
String toString ()
Public Member Functions inherited from gamedata.gamecomponents.IHasStats
abstract Stats getStats ()
Protected Attributes
String myID
String myName
Point2D.Double myLoc
String myImageLocation
transient ImageView myImageView
Private Member Functions
void setImageView ()
Detailed Description
Abstract superclass for pieces and patches, which together constitute every element of a level that can be directly interacted with on a grid. This class contains methods that are accessible to both of them.
Author
Martin Tamayo
Definition at line 17 of file GridComponent.java.
Constructor & Destructor Documentation
gamedata.gamecomponents.GridComponent.GridComponent (String id, String name, String imageLocation, Point2D.Double point)
General constructor for instantiating a brand new piece or patch. Any instance variables specific to pieces or patches are dealt with in their own, separate constructors.
Parameters
id : Unique string ID for the piece or patch.
name : String name describing the piece or patch.
imageLocation : String path to image on file.
point : Point2D.Double location of piece or patch on grid.
Definition at line 36 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myLoc, and gamedata.gamecomponents.GridComponent.setImageView().
gamedata.gamecomponents.GridComponent.GridComponent (GridComponent clone, Point2D.Double placeHere)
General constructor for cloning a piece or patch. Once a piece or patch is created, one will often want to create copies of them to place on the grid. This constructor is for handling such cases.
Parameters
clone : Piece or patch class to copy over.
Definition at line 52 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myID, gamedata.gamecomponents.GridComponent.myImageLocation, gamedata.gamecomponents.GridComponent.myLoc, gamedata.gamecomponents.GridComponent.myName, and gamedata.gamecomponents.GridComponent.setImageView().
Member Function Documentation
String gamedata.gamecomponents.GridComponent.getID ()
Getter method for the unique ID of the GridComponent.
Returns
: Unique string ID for the piece or patch.
Definition at line 65 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myID.
Referenced by authoring.data.PatchTypeData.canAdd(), authoring.data.PieceTypeData.canAdd(), authoring.data.PieceInstanceData.canAdd(), authoring.data.PatchInstanceData.canAdd(), fxml_main.PatchTypeEditor.PatchTypeEditor(), fxml_main.PatchViewer.PatchViewer(), fxml_main.PieceEditor.PieceEditor(), fxml_main.PieceTypeEditor.PieceTypeEditor(), authoring.data.PatchInstanceData.replace(), and authoring.data.PieceInstanceData.replace().
String gamedata.gamecomponents.GridComponent.getImageLocation ()
Getter method for the path to the image for the GridComponent on file.
Returns
myImageLocation : String path to image on file.
Definition at line 104 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myImageLocation.
Referenced by fxml_main.PatchTypeEditor.PatchTypeEditor(), fxml_main.PatchViewer.PatchViewer(), fxml_main.PieceEditor.PieceEditor(), fxml_main.PieceTypeEditor.PieceTypeEditor(), and authoring.data.PatchInstanceData.replace().
ImageView gamedata.gamecomponents.GridComponent.getImageView ()
Getter method for the ImageView for the GridComponent for GUI display purposes.
Returns
myImageView : Image for the GridComponent.
Definition at line 134 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myImageView, and gamedata.gamecomponents.GridComponent.setImageView().
Referenced by authoring_environment.GUIGrid.addPatchAtLoc(), authoring_environment.GUIGrid.addPatchToTile(), authoring_environment.GUIGrid.addPieceAtLoc(), authoring_environment.GUIGrid.addPieceToTile(), authoring_environment.ShapeGrid.addTerrain(), authoring_environment.ShapeGrid.addUnit(), fxml_main.PatchController.makeEntryBox(), fxml_main.PieceController.makeEntryBox(), authoring_environment.GUIGrid.replacePatchType(), authoring_environment.GUIGrid.replacePieceType(), and gameengine.movement.Orientator.turn().
Point2D.Double gamedata.gamecomponents.GridComponent.getLoc ()
Getter method for the location of the GridComponent on the grid.
Returns
myLoc : Point2D.Double location of piece or patch on grid.
Implements gamedata.gamecomponents.IHasStats.
Definition at line 84 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myLoc.
Referenced by authoring.data.PatchInstanceData.add(), authoring.data.PatchInstanceData.canAdd(), authoring.data.PieceInstanceData.canAdd(), gamedata.goals.PieceOnPatchGoal.checkGameState(), gameengine.movement.Movement.doBehavior(), gamePlayer.GameGridEffect.highlightActionRange(), gamePlayer.ViewController.highlightSelected(), gamePlayer.ApplyState.onClick(), authoring_environment.GUIGrid.removePatch(), authoring_environment.GUIGrid.removePiece(), and authoring.data.PieceInstanceData.replace().
String gamedata.gamecomponents.GridComponent.getName ()
Getter method for the name of GridComponent.
Returns
myName: string name of grid component
Definition at line 113 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myName.
Referenced by fxml_main.PatchController.makeEntryBox(), fxml_main.PieceController.makeEntryBox(), fxml_main.PatchTypeEditor.PatchTypeEditor(), fxml_main.PatchViewer.PatchViewer(), fxml_main.PieceEditor.PieceEditor(), and fxml_main.PieceTypeEditor.PieceTypeEditor().
void gamedata.gamecomponents.GridComponent.setImageLocation (String imageLocation)
Setter method for the path to the image for the GridComponent on file.
Parameters
imageLocation : String path to image on file.
Definition at line 123 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.setImageView().
Referenced by authoring.data.PatchInstanceData.replace().
void gamedata.gamecomponents.GridComponent.setImageView () private
Method for creating an ImageView using the location of the image on file. This is for GUI display purposes. This method is used privately by the GridComponent constructor methods.
Parameters
imageLocation : String path to image on file.
Definition at line 146 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getImageView(), gamedata.gamecomponents.GridComponent.GridComponent(), and gamedata.gamecomponents.GridComponent.setImageLocation().
void gamedata.gamecomponents.GridComponent.setLoc (Point2D.Double loc)
Setter method for the location of the GridComponent on the grid.
Parameters
loc : Point2D.Double location of piece or patch on grid.
Definition at line 94 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myLoc.
Referenced by authoring_environment.ShapeGrid.addTerrain(), authoring_environment.ShapeGrid.addUnit(), gameengine.movement.Movement.doBehavior(), and gamePlayer.ApplyState.onClick().
void gamedata.gamecomponents.GridComponent.setName (String name)
Setter method for the name of the GirdComponent.
Parameters
name : String name describing the piece or patch.
Definition at line 74 of file GridComponent.java.
Referenced by authoring.data.PatchInstanceData.replace().
String gamedata.gamecomponents.GridComponent.toString ()
Returns the name of the GridComponent for display purposes
Implements gamedata.gamecomponents.IHasStats.
Definition at line 159 of file GridComponent.java.
References gamedata.gamecomponents.GridComponent.myName.
Referenced by gamedata.goals.PieceOnPatchGoal.checkGameState(), and authoring.data.PieceInstanceData.unitAtLoc().
Member Data Documentation
String gamedata.gamecomponents.GridComponent.myID protected
Definition at line 19 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getID(), gamedata.gamecomponents.GridComponent.GridComponent(), gamedata.gamecomponents.Patch.printString(), and gamedata.gamecomponents.Piece.printString().
String gamedata.gamecomponents.GridComponent.myImageLocation protected
Definition at line 22 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getImageLocation(), gamedata.gamecomponents.GridComponent.GridComponent(), gamedata.gamecomponents.Patch.printString(), and gamedata.gamecomponents.Piece.printString().
transient ImageView gamedata.gamecomponents.GridComponent.myImageView protected
Definition at line 23 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getImageView().
Point2D.Double gamedata.gamecomponents.GridComponent.myLoc protected
Definition at line 21 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getLoc(), gamedata.gamecomponents.GridComponent.GridComponent(), gamedata.gamecomponents.Patch.printString(), gamedata.gamecomponents.Piece.printString(), and gamedata.gamecomponents.GridComponent.setLoc().
String gamedata.gamecomponents.GridComponent.myName protected
Definition at line 20 of file GridComponent.java.
Referenced by gamedata.gamecomponents.GridComponent.getName(), gamedata.gamecomponents.Piece.getUniqueID(), gamedata.gamecomponents.GridComponent.GridComponent(), gamedata.gamecomponents.Patch.printString(), gamedata.gamecomponents.Piece.printString(), gamedata.gamecomponents.Patch.toString(), and gamedata.gamecomponents.GridComponent.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/GridComponent.java