voogasalad_VOOGirlsGeneration: fxml_main.ActionViewer Class Reference
fxml_main.ActionViewer Class Reference
Public Member Functions
ActionViewer (Action action)
HBox createHBox ()
Protected Member Functions
void initialize ()
Private Attributes
String myName
List< Point2D.Double > myEffectRange
List< Point2D.Double > myActionRange
Static Private Attributes
static final int HEIGHT = 150
static final int WIDTH = 150
static final String VIEWER_TITLE = "Action Viewer"
static final String NAME_LABEL = "Name: "
static final String ACTION_RANGE = "Action Range Coordinates: "
static final String EFFECT_RANGE = "Effect Range Coordinates: "
static final String LABEL_CSS = "-fx-font-size: 14pt;"
static final Insets MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10)
Detailed Description
Author
seungwonlee
Definition at line 18 of file ActionViewer.java.
Constructor & Destructor Documentation
fxml_main.ActionViewer.ActionViewer (Action action)
Definition at line 33 of file ActionViewer.java.
References gamedata.action.Action.getActionRange(), gamedata.action.Action.getEffectRange(), fxml_main.ActionViewer.initialize(), fxml_main.ActionViewer.myActionRange, fxml_main.ActionViewer.myEffectRange, and gamedata.action.Action.toString().
Member Function Documentation
HBox fxml_main.ActionViewer.createHBox ()
Definition at line 74 of file ActionViewer.java.
References authoring_environment.UIspecs.allPadding.
Referenced by fxml_main.ActionViewer.initialize().
void fxml_main.ActionViewer.initialize () protected
Definition at line 42 of file ActionViewer.java.
References fxml_main.ActionViewer.createHBox(), fxml_main.ActionViewer.myActionRange, and fxml_main.ActionViewer.myEffectRange.
Referenced by fxml_main.ActionViewer.ActionViewer().
Member Data Documentation
final String fxml_main.ActionViewer.ACTION_RANGE = "Action Range Coordinates: " static private
Definition at line 24 of file ActionViewer.java.
final String fxml_main.ActionViewer.EFFECT_RANGE = "Effect Range Coordinates: " static private
Definition at line 25 of file ActionViewer.java.
final int fxml_main.ActionViewer.HEIGHT = 150 static private
Definition at line 20 of file ActionViewer.java.
final String fxml_main.ActionViewer.LABEL_CSS = "-fx-font-size: 14pt;" static private
Definition at line 26 of file ActionViewer.java.
final Insets fxml_main.ActionViewer.MARGINS = new Insets(20, WIDTH / 5, 20, WIDTH / 5 - 10) static private
Definition at line 27 of file ActionViewer.java.
List<Point2D.Double> fxml_main.ActionViewer.myActionRange private
Definition at line 31 of file ActionViewer.java.
Referenced by fxml_main.ActionViewer.ActionViewer(), and fxml_main.ActionViewer.initialize().
List<Point2D.Double> fxml_main.ActionViewer.myEffectRange private
Definition at line 30 of file ActionViewer.java.
Referenced by fxml_main.ActionViewer.ActionViewer(), and fxml_main.ActionViewer.initialize().
String fxml_main.ActionViewer.myName private
Definition at line 29 of file ActionViewer.java.
final String fxml_main.ActionViewer.NAME_LABEL = "Name: " static private
Definition at line 23 of file ActionViewer.java.
final String fxml_main.ActionViewer.VIEWER_TITLE = "Action Viewer" static private
Definition at line 22 of file ActionViewer.java.
final int fxml_main.ActionViewer.WIDTH = 150 static private
Definition at line 21 of file ActionViewer.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/fxml_main/ActionViewer.java