voogasalad_VOOGirlsGeneration: gamedata.gamecomponents.Inventory Class Reference
gamedata.gamecomponents.Inventory Class Reference
Public Member Functions
Inventory ()
void addItem (Piece item)
void removeItem (Piece item)
void setInventory (List< Piece > items)
boolean isEmpty ()
List< Action > getItemActions ()
Map< String, List< String > > getStringDisplay ()
List< Piece > getAllInventory ()
Private Attributes
List< Piece > myInventory
Detailed Description
Inventory to be contained by a piece if the user chooses to add an inventory to a piece. Inventory contains a list of pieces.
Authors
Sandy Lee, Jennie Ju
Definition at line 21 of file Inventory.java.
Constructor & Destructor Documentation
gamedata.gamecomponents.Inventory.Inventory ()
Constructor for inventory, initializes an empty inventory
Definition at line 28 of file Inventory.java.
Member Function Documentation
void gamedata.gamecomponents.Inventory.addItem (Piece item)
Adds the indicated pieces to the inventory
Parameters
items - pieces to be added
Definition at line 36 of file Inventory.java.
Referenced by gamedata.gamecomponents.Piece.addToInventory().
List<Piece> gamedata.gamecomponents.Inventory.getAllInventory ()
Definition at line 94 of file Inventory.java.
References gamedata.gamecomponents.Inventory.myInventory.
Referenced by gamedata.gamecomponents.Level.garbageCollectPieces().
List<Action> gamedata.gamecomponents.Inventory.getItemActions ()
Returns the actions contained in all the items as a list of Actions
Returns
list of Actions contained in the items
Definition at line 70 of file Inventory.java.
Referenced by gamedata.gamecomponents.Piece.getActions().
Map<String,List<String> > gamedata.gamecomponents.Inventory.getStringDisplay ()
Returns a Map of Piece item name to List of Action names for displaying the inventory in the Game Player
Returns
Map<String,List<String>> with Piece item name keys and Action name values
Definition at line 84 of file Inventory.java.
Referenced by gamePlayer.ViewController.updateInventory().
boolean gamedata.gamecomponents.Inventory.isEmpty ()
Checks whether inventory is empty or not
Definition at line 61 of file Inventory.java.
void gamedata.gamecomponents.Inventory.removeItem (Piece item)
Removes the indicated pieces from the inventory
Parameters
items - pieces to be removed
Definition at line 44 of file Inventory.java.
Referenced by gamedata.gamecomponents.Level.garbageCollectPieces(), and gamedata.gamecomponents.Piece.removeFromInventory().
void gamedata.gamecomponents.Inventory.setInventory (List< Piece > items)
Set the inventory to an already filled list of pieces
Parameters
items - pieces in the inventory given as a list of pieces
Definition at line 54 of file Inventory.java.
Member Data Documentation
List<Piece> gamedata.gamecomponents.Inventory.myInventory private
Definition at line 22 of file Inventory.java.
Referenced by gamedata.gamecomponents.Inventory.getAllInventory().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/voogasalad_VOOGirlsGeneration/repository/src/gamedata/gamecomponents/Inventory.java